go.mod: Replace garyburd/redigo with gomodule/redigo
helm/helm pull request #10315
Opened 2021-11-05 15:32 UTC by mtojek

Closes: #10310

**What this PR does / why we need it**:

This PR adds a "replace" directive to the `go.mod` to replace the `garyburd/redigo` (previously 404, now archived) with `gomodule/redigo` (supported).

**Special notes for your reviewer**:

It tried to update the dependency on distribution/distribution, but this is a deep-down dependency, through [hcsshim/test](https://github.com/microsoft/hcsshim/tree/master/test).

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-11-07 09:44 UTC, yxxhero approved these changes
LGTM

2021-11-07 15:10 UTC, cndoit18 approved these changes
LGTM

2021-11-15 01:14 UTC, bacongobbler commented
Can you add a comment to remove this `replace` statement once we bump to distribution (\<insert version here\>)?

2021-11-16 15:35 UTC, mattfarina requested changes
Why is this using a replace?

This has to do with a transitive dependency. The packages that rely on it have updated. Why aren't we updating the package we rely on that relies on it?

2021-11-16 15:49 UTC, mtojek commented
Thanks for bringing up this question, @mattfarina.

As you noticed this is a transitive dependency, so we would have to update more packages:

```
➜  helm git:(fix-10310) go mod graph | grep garyburd/redigo
github.com/docker/distribution@v0.0.0-20190905152932-14b96e55d84c github.com/garyburd/redigo@v0.0.0-20150301180006-535138d7bcd7

➜  helm git:(fix-10310) go mod graph | grep github.com/docker/distribution@v0.0.0-20190905152932-14b96e55d84c
github.com/Microsoft/hcsshim/test@v0.0.0-20201218223536-d3e5debf77da github.com/docker/distribution@v0.0.0-20190905152932-14b96e55d84c

➜  helm git:(fix-10310) go mod graph | grep github.com/Microsoft/hcsshim/test@v0.0.0-20201218223536-d3e5debf77da
github.com/containerd/containerd@v1.5.0-beta.1 github.com/Microsoft/hcsshim/test@v0.0.0-20201218223536-d3e5debf77da

➜  helm git:(fix-10310) go mod graph | grep github.com/containerd/containerd@v1.5.0-beta.1
github.com/Microsoft/hcsshim@v0.8.15 github.com/containerd/containerd@v1.5.0-beta.1
github.com/Microsoft/hcsshim/test@v0.0.0-20210227013316-43a75bb4edd3 github.com/containerd/containerd@v1.5.0-beta.1
github.com/containerd/imgcrypt@v1.0.4-0.20210301171431-0ae5c75f59ba github.com/containerd/containerd@v1.5.0-beta.1
```

It will be challenging to upgrade every dependent library we encounter here.

2021-11-26 16:39 UTC, bacongobbler commented
IMO I'd rather we be good open source citizens and attempt to update downstream packages to use `gomodule/redigo` than a blanket `replace`. That way all projects relying on these transitive dependencies can take advantage of this work. Especially since `distribution/distribution` is a direct dependency of Helm's OCI experiment.

cc @jdolitsky

2022-03-11 20:37 UTC, bacongobbler commented
Closing as inactive. In any case we are not planning to merge this. Please update Helm's transitive dependencies to the new location. Thanks.

2022-03-11 20:37 UTC, closed without merging