Print downloaded chart path.
helm/helm pull request #10695
Opened 2022-02-22 07:33 UTC by danthelion

60,33,45,45,32,32,84,104,97,110,107,115,32,102,111,114,32,115,101,110,100,105,110,103,32,97,32,112,117,108,108,32,114,101,113,117,101,115,116,33,32,32,72,101,114,101,32,97,114,101,32,115,111,109,101,32,116,105,112,115,32,102,111,114,32,121,111,117,58,10,49,46,32,77,97,107,101,32,115,117,114,101,32,116,111,32,114,101,97,100,32,116,104,101,32,67,111,110,116,114,105,98,117,116,105,110,103,32,71,117,105,100,101,32,98,101,102,111,114,101,32,115,117,98,109,105,116,116,105,110,103,32,121,111,117,114,32,80,82,58,32,104,116,116,112,115,58,47,47,103,105,116,104,117,98,46,99,111,109,47,104,101,108,109,47,104,101,108,109,47,98,108,111,98,47,109,97,105,110,47,67,79,78,84,82,73,66,85,84,73,78,71,46,109,100,10,50,46,32,73,102,32,116,104,105,115,32,80,82,32,99,108,111,115,101,115,32,97,110,111,116,104,101,114,32,105,115,115,117,101,44,32,97,100,100,32,39,99,108,111,115,101,115,32,35,60,105,115,115,117,101,32,110,117,109,98,101,114,62,39,32,115,111,109,101,119,104,101,114,101,32,105,110,32,116,104,101,32,80,82,32,115,117,109,109,97,114,121,46,32,71,105,116,72,117,98,32,119,105,108,108,32,97,117,116,111,109,97,116,105,99,97,108,108,121,32,99,108,111,115,101,32,116,104,97,116,32,105,115,115,117,101,32,119,104,101,110,32,116,104,105,115,32,80,82,32,103,101,116,115,32,109,101,114,103,101,100,46,32,65,108,116,101,114,110,97,116,105,118,101,108,121,44,32,97,100,100,105,110,103,32,39,114,101,102,115,32,35,60,105,115,115,117,101,32,110,117,109,98,101,114,62,39,32,119,105,108,108,32,110,111,116,32,99,108,111,115,101,32,116,104,101,32,105,115,115,117,101,44,32,98,117,116,32,104,101,108,112,32,112,114,111,118,105,100,101,32,116,104,101,32,114,101,118,105,101,119,101,114,32,109,111,114,101,32,99,111,110,116,101,120,116,46,45,45,62,10,10,42,42,87,104,97,116,32,116,104,105,115,32,80,82,32,100,111,101,115,32,47,32,119,104,121,32,119,101,32,110,101,101,100,32,105,116,42,42,58,10,10,42,42,83,112,101,99,105,97,108,32,110,111,116,101,115,32,102,111,114,32,121,111,117,114,32,114,101,118,105,101,119,101,114,42,42,58,10,10,42,42,73,102,32,97,112,112,108,105,99,97,98,108,101,42,42,58,10,45,32,91,32,93,32,116,104,105,115,32,80,82,32,99,111,110,116,97,105,110,115,32,100,111,99,117,109,101,110,116,97,116,105,111,110,10,45,32,91,32,93,32,116,104,105,115,32,80,82,32,99,111,110,116,97,105,110,115,32,117,110,105,116,32,116,101,115,116,115,10,45,32,91,32,93,32,116,104,105,115,32,80,82,32,104,97,115,32,98,101,101,110,32,116,101,115,116,101,100,32,102,111,114,32,98,97,99,107,119,97,114,100,115,32,99,111,109,112,97,116,105,98,105,108,105,116,121,10

2022-02-26 14:37 UTC, yxxhero commented
@danthelion 
1.Please create a issue for this PR. Thanks very much.
2.fix the DCO in the ci.

2022-03-01 21:22 UTC, joejulian requested changes

2022-03-01 21:22 UTC, joejulian commented on pkg/downloader/chart_downloader.go
> +
```suggestion
```

2022-03-01 21:22 UTC, joejulian commented on pkg/downloader/chart_downloader.go
> +		fmt.Fprintf(&out, "Chart downloaded to: %s\n", destfile)
Shouldn't this use ChartLoader.Out to be consistent with the rest of the code?

```suggestion
		fmt.Fprintf(c.Out, "Chart downloaded to: %s\n", destfile)
```

2022-03-02 12:00 UTC, danthelion commented
Huh I'll guess accepting suggestions from the iOS GitHub app won't suffice, I'll fix the commita when I'm back near my computer @joejulian @yxxhero

2022-03-02 14:16 UTC, joejulian approved these changes
lgtm, but I'm not an approver

2022-03-02 14:54 UTC, bacongobbler commented
I am concerned about this being put in DownloadTo. Perhaps the calling function requested the package to be downloaded to a temporary path before performing additional operations, in which case the output path is totally useless to the user.

In general we reserve `c.Out` to be used more as a diagnosis/debugging logger than standard output IIRC.

`helm pull` is [supposed to display the output path](https://github.com/helm/helm/blob/65d8e72504652e624948f74acbba71c51ac2e342/cmd/helm/pull.go#L68-L72). Perhaps there's an underlying bug preventing that from happening? Hvae you looked closer at the existing infrastructure to confirm whether something else is going on?

2022-03-11 19:55 UTC, bacongobbler commented
ping.

2022-03-17 10:24 UTC, danthelion commented
Hmm you are right, it should print the output but it doesn't. I'll look into it! Sorry for being slow about it, hectic times.

2022-03-17 20:48 UTC, joejulian commented
Ah, sorry, I just noticed that everything else used c.Out so I thought that was the "right way".

2022-03-25 00:57 UTC, yxxhero commented
ping

2023-07-13 00:45 UTC, joejulian commented
closing this as abandoned

2023-07-13 00:45 UTC, closed without merging