overwrite flag added to az storage blob upload-batch
helm/helm pull request #10726
Opened 2022-03-05 04:40 UTC by sourikghosh

Signed-off-by: Sourik Ghosh <sourikghosh31@gmail.com>

**What this PR does / why we need it**:
adds a overwrite flag to az storage blob upload-batch to replace canary.
closes #10724

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-03-05 06:09 UTC, yxxhero commented
/lgtm
Thanks your PR.

2022-03-06 17:47 UTC, sourikghosh commented
@jdolitsky can you have a look at this

2022-03-08 18:19 UTC, jdolitsky requested changes
I was thinking about this. The new behavior actually protects from supply chain attacks.

Could you modify this to only add `--overwrite` if `[[ "${VERSION}" == "canary" ]]` ?

2022-03-08 18:36 UTC, jdolitsky commented on .circleci/deploy.sh
> +if
last thing, can we format this?
```
if [[ "${VERSION}" == "canary" ]]; then
  az storage blob upload-batch -s _dist/ -d "$AZURE_STORAGE_CONTAINER_NAME" --pattern 'helm-*' --connection-string "$AZURE_STORAGE_CONNECTION_STRING" --overwrite
else
  az storage blob upload-batch -s _dist/ -d "$AZURE_STORAGE_CONTAINER_NAME" --pattern 'helm-*' --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
if

2022-03-08 18:37 UTC, sourikghosh commented on .circleci/deploy.sh
> +if
ohhh snap,,, yeah yeah

2022-03-08 20:06 UTC, jdolitsky approved these changes

2022-03-08 20:06 UTC, jdolitsky commented
thanks @sourikghosh !

2022-03-08 20:06 UTC, merged