Adding details on the Factory interface
helm/helm pull request #10965
Opened 2022-05-16 19:52 UTC by mattfarina

This covers both the property and the minimal copy of the Factory
interface. It also notes that this interface is not covered by the
Helm backwards compatibility and why.

**What this PR does / why we need it**: There is confusion around what is covered by the Helm backwards compatibility. This helps clear it up with regard to this interface.

**Special notes for your reviewer**: N/A

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2022-09-23 10:36 UTC, hickeyma requested changes, later dismissed
Small nit

2022-09-23 10:36 UTC, hickeyma commented on pkg/kube/factory.go
> +// This interface is a minimal copy of the kubectl Factory interface containering only the functions
containering --> containing

2023-05-06 00:21 UTC, joejulian commented on pkg/kube/factory.go
> +// This interface is a minimal copy of the kubectl Factory interface containering only the functions
@hickeyma I pushed that typo fix

2023-08-28 19:13 UTC, joejulian approved these changes

2023-08-28 19:13 UTC, merged