Fix - TLS hnadshake failure for oci pull while client authentication enable.
helm/helm pull request #11034
Opened 2022-06-09 13:03 UTC by suryatech27-cloud

What this PR does / why we need it:
Fix for (https://github.com/helm/helm/issues/10597)

    Added 2-way TLS Support for oci pull for artifact repository which causes TLS handshake failure error.

Special notes for your reviewer:

    Added flag for two-way authentication (--tls-enabled) .
    For Testing this PR , Need to create a test environment . use following link to create a test environment.
    https://github.com/suryatech27-cloud/helm-oci-test-environment/blob/main/README.md

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-06-12 07:12 UTC, bacongobbler commented
Note to future reviewers: see https://github.com/helm/helm/pull/10808 for past discussion - this is a re-review of an earlier PR.

2022-06-12 07:16 UTC, bacongobbler requested changes
I will re-iterate the same ask as requested in the previous PR… we ask that pull requests come with a set of unit tests to ensure the feature works as expected. Can you please write unit tests to cover the code you’ve written. Have a look at `pkg/repo/repotest`. Thanks.

2022-07-14 07:22 UTC, lindhe commented
Before this is considered for merge, please fix the title! :)

2022-08-11 16:07 UTC, hickeyma reviewed
@suryatech27-cloud There is feedback from @bacongobbler and @lindhe. Do you mind rebasing and addressing the comments?

2025-09-28 00:24 UTC, closed without merging