Add chart name and version for output of helm list command with json/yaml
helm/helm pull request #11060
Opened 2022-06-20 14:23 UTC by yong-jie-gong

Signed-off-by: Gong Yongjie <yong-jie.gong@microfocus.com>

**What this PR does / why we need it**:
currently “helm list” merge the char name and version as single field chart. but sometimes, we need know the chart name/version one  installed release is referring  to

**Special notes for your reviewer**:

**If applicable**:
- [x ] this PR contains documentation
- [x ] this PR contains unit tests
- [ x] this PR has been tested for backwards compatibility

2022-06-25 00:09 UTC, yxxhero commented on cmd/helm/history.go
> +func getChartname(c *chart.Chart) string {
unittest

2022-06-25 00:09 UTC, yxxhero commented on cmd/helm/history.go
> +func getChartVerison(c *chart.Chart) string {
unittest

2022-08-23 11:34 UTC, hickeyma requested changes
@yong-jie-gong Do you mids opening a feature issue for this. It would be good to have details like:

- Use case(s) for this feature
- Show output before and after

2022-08-27 08:31 UTC, yong-jie-gong commented
> @yong-jie-gong Do you mids opening a feature issue for this. It would be good to have details like:
> 
> * Use case(s) for this feature
> * Show output before and after

Create feature issues for tracking
https://github.com/helm/helm/issues/11281

2022-09-17 00:02 UTC, joejulian approved these changes
Nice feature! I could have used this many times.

2022-09-17 01:35 UTC, yxxhero commented
@yong-jie-gong Show output before and after in plain.

2022-09-26 01:49 UTC, yong-jie-gong commented
> @yong-jie-gong Show output before and after in plain.
table ouput stays as before, nothing changed in case some developer use the shell command to parse the table output

2023-10-11 17:43 UTC, yonahd commented
Is there any more work needed here?

2023-10-12 02:54 UTC, yxxhero commented
@joejulian  could you merge this PR? thanks so much.

2023-10-16 20:13 UTC, mattfarina commented
This is a new feature that ends up adding to a struct. Need to do this in a minor release. Moving there.

2025-09-11 21:34 UTC, scottrigby commented
Needs rebase onto `main` — Helm 3 is not accepting new features.

2026-01-11 00:28 UTC, closed without merging