Update golangci-lint and fix linting issues
helm/helm pull request #11064
Opened 2022-06-21 10:32 UTC by devfbe

**Update golangci-lint from to latest version**:

Update golangci-lint from version 1.43.0 to the latest linter version 1.46.2.

This is the latest version of golangci-lint which finds new (small) errors in the source code. This linting issues have been fixed in this merge request, too.

Fixed linting issues:

Remove newline from error string in internal/test/test.go
and remove redundant nil / len(0) check from asMap() function
in pkg/chartutil/values.go. Guard this function by a unit test.

**Special notes for your reviewer**:
Only linting issues fixed, added unit tests for changed logic to ensure nothing breaks.

**If applicable**:
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2022-08-27 01:37 UTC, sudermanjr approved these changes
LGTM

2022-08-29 09:28 UTC, hickeyma reviewed
@devfbe Do you mind pushing again to kick off CircleCI as uncle to restart it on my side?

2022-09-23 09:44 UTC, hickeyma commented
Ping @devfbe

2025-03-13 17:15 UTC, scottrigby requested changes
@devfbe this is quite an old one, and most of this PR is no longer applicable. However, `TestAsMap()` could still be added if you want to update this PR, or if someone else wants to take this on. I'll rename the PR accordingly.

2025-03-13 17:15 UTC, scottrigby commented on pkg/chartutil/values.go
> +	if len(v) == 0 {
This code is already in main now

2025-03-13 17:15 UTC, scottrigby commented on .circleci/config.yml
> +      GOLANGCI_LINT_VERSION: "1.46.2"
We have moved from CircleCI to GitHub actions. These upgrades are now handled by dependabot (example PR https://github.com/helm/helm/pull/30535)

2025-03-13 17:15 UTC, scottrigby commented on pkg/chartutil/values_test.go
> +func TestAsMap(t *testing.T) {
One thing from this PR we do not have is a function like this to test `AsMap()`. This could still be added if you want to update this PR. The new file location is https://github.com/helm/helm/blob/main/pkg/chart/v2/util/values_test.go.

2025-03-13 17:15 UTC, scottrigby commented on internal/test/test.go
> +		return errors.Errorf("does not match golden file %s\n\nWANT:\n'%s'\n\nGOT:\n'%s'", filename, expected, actual)
this change is already in main

2026-02-01 00:35 UTC, closed without merging