perf(dep-up): do not update the same repo multiple times
helm/helm pull request #11112
Opened 2022-07-04 21:47 UTC by felipecrs

**What this PR does / why we need it**:

When you have a Chart.yaml which declares multiple charts in the same repository, Helm tries to update all of them one by one, even if they are the same repository.

This improves the performance by ensuring that we do not update the same repository multiple times without any benefit.

**Special notes for your reviewer**:

None.

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility
  I tested it manually.

2022-08-17 16:54 UTC, sudermanjr commented
/lgtm

2022-08-17 16:55 UTC, sudermanjr approved these changes
lgtm

2022-09-20 13:17 UTC, felipecrs commented
I think this is a good candidate for 3.10

2023-06-14 14:49 UTC, felipecrs commented
@mattfarina is there a chance you can look at this one? It's simple, and it saves more than 5 minutes to `helm dep up` my big umbrella chart.

2023-09-27 22:21 UTC, felipecrs commented
Just a ping... perhaps this can enter next patch release? :)

PS: I have been compiling helm manually for more than one year with this PR patched in it, with no issues. My CI/CD loops that uses such manually compiled Helm runs thousands of times by week.

2024-02-16 15:30 UTC, felipecrs commented
@mattfarina any chance you can take a look at this one?

2024-02-16 15:52 UTC, felipecrs commented
@yxxhero would you mind taking a look at this one as well? It's a simple change, and saves more than 5 minutes within my CI pipelines.

2024-07-10 21:01 UTC, felipecrs commented
Ping?

2025-02-17 16:54 UTC, felipecrs commented
This PR is rebased and can be reviewed again.

2025-02-20 17:40 UTC, godhanipayal reviewed
lgtm

2025-02-20 17:40 UTC, godhanipayal approved these changes

2025-02-20 17:41 UTC, joejulian requested changes

2025-02-20 17:43 UTC, felipecrs commented on pkg/downloader/manager.go
> +	repos = dedupeRepos(repos)
Done, thanks you!

2025-02-20 17:44 UTC, joejulian submitted a review, later dismissed

2025-02-20 17:46 UTC, felipecrs commented
@joejulian, I've fixed DCO. Please approve the workflow run again.

2025-02-20 18:28 UTC, gjenkins8 commented on pkg/downloader/manager.go
> +		r.URL = strings.TrimSuffix(r.URL, "/")
I don't think this normalization should be done here (it is updating the original repo object via the pointer).

Preferably IMHO, the chart repo's URL would be normalized when the repo is loaded.

A more hacky way, the "seen" map could be keyed by a normalized URL. But the passed `repos` not mutated.

2025-02-20 18:30 UTC, gjenkins8 requested changes
https://github.com/helm/helm/pull/11112/files#r1964139179

2025-02-20 18:47 UTC, felipecrs commented
@gjenkins8 linter complained about the variable name. Fixed now. You'll have to approve the workflow again, sorry about that.

2025-02-20 19:54 UTC, scottrigby commented
@felipecrs the test is failing https://github.com/helm/helm/actions/runs/13442473795/job/37562625432?pr=11112. Can you take a look?

2025-02-20 20:00 UTC, felipecrs commented
Oops, done, @scottrigby, thank you.

2025-02-21 01:47 UTC, gjenkins8 approved these changes

2025-02-21 22:08 UTC, gjenkins8 commented
Forgot to mention, thanks for the PR. And the patience / prompting to get it over the line.

2025-02-21 22:12 UTC, felipecrs commented
My pleasure, @gjenkins8. Thanks for spending your time reviewing it.

2025-02-22 20:47 UTC, joejulian approved these changes

2025-02-22 20:50 UTC, merged