Use own scheme rather than mutating a global shared one
helm/helm pull request #11250
Opened 2022-08-19 11:17 UTC by ash2k

**What this PR does / why we need it**:

Fixes data race caused by code in `Client`. Fixes https://github.com/helm/helm/issues/11169.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-11-14 10:10 UTC, ash2k commented
Hello?

2023-01-10 03:58 UTC, ash2k commented
Conflict resolved, ready for merge.

2023-07-19 04:23 UTC, ash2k commented
@joejulian Hi! I wonder if there is a reason this is not getting merged but getting bumped each time? It shouldn't cause any breakage, it fixes a data race. It's almost 1 year since I opened this PR.

2023-07-19 04:42 UTC, joejulian commented
I only recently became a maintainer and I've been working my way up through what I can. I only have an hour a day after work but I'm doing what I can.

2023-07-19 05:35 UTC, ash2k commented
Thank you! No pressure, just wanted to see if there is some other reason apart from lack of time.

2024-11-15 04:13 UTC, ash2k commented
Rebased to resolve a conflict. I still hope to see this merged.

2025-03-31 09:19 UTC, ash2k commented
Conflict resolved, ready for merge.

2025-07-12 01:00 UTC, ash2k commented
Conflict resolved, ready for merge. Almost 3 years now since I opened this PR.

2025-08-01 10:53 UTC, ash2k commented
@mattfarina Could you review/merge this PR please? It's been open for a while and I see the problematic code is being propagated further into the v3 packages.

p.s. Looks like https://github.com/helm/helm/pull/31078 is missing from v3 too.

2025-08-19 06:08 UTC, ash2k commented
@gjenkins8 Hi! Since you are assigned, could you give this one a review/merged please?

2025-09-11 21:35 UTC, scottrigby commented
Please rebase to `main` first; backport to `dev-v3` if Helm 3 also needs the fix.

2025-09-12 00:40 UTC, ash2k commented
@scottrigby Rebased, PTAL.

2026-01-22 04:04 UTC, ash2k commented
@scottrigby Rebased again, PTAL.

2026-04-30 03:20 UTC, ash2k commented
It's stale because it's not being reviewed. 🤷

2026-04-30 09:01 UTC, TerryHowe requested changes

2026-04-30 09:01 UTC, TerryHowe commented on pkg/kube/converter.go
> +var NativeScheme *runtime.Scheme
`NatigveScheme` is mutable here, so this doesn't really solve the issue, it just moves it. Make NativeScheme a function maybe?

2026-04-30 09:32 UTC, ash2k commented on pkg/kube/converter.go
> +var NativeScheme *runtime.Scheme
Yes. But even if it's a function, `*runtime.Scheme` is mutable. Returning a new object each time might be too expensive, not sure.

2026-05-02 01:26 UTC, ash2k commented on pkg/kube/converter.go
> +var NativeScheme *runtime.Scheme
@TerryHowe Well, actually, it does fix the data race. So, this PR is leaving things strictly better vs status quo. Any reasons not to merge it?

I can make it a function if you prefer, but that also wouldn't solve the problem of mutability. `runtime.Scheme` is mutable itself. We can make it immutable only if we prevent direct access it to (e.g. wrap it in a struct).

2026-05-02 15:41 UTC, TerryHowe commented on pkg/kube/converter.go
> +var NativeScheme *runtime.Scheme
NativeScheme is a public var so it is mutable. Am I missing something this morning?

2026-05-03 23:27 UTC, ash2k commented on pkg/kube/converter.go
> +var NativeScheme *runtime.Scheme
@TerryHowe My point was that, yes, the package-level var is mutable, but the object itself is mutable too. Even if we hide the var, the value is mutable still. And that is what was causing the data race - some other code mutated it, not the var.

Anyway, I do agree that if we hide the var, it's a bit better "defense". Done that.

2026-05-07 01:50 UTC, ash2k commented on pkg/kube/converter.go
> +	return nativeScheme
Well, that's what I'm talking about - making it a function doesn't solve this. But creating a new scheme each time is too expensive imo. I think the current approach is good enough. Also, let's not forget that this PR fixes a data race so there is no reason not to merge it. Desired behaviour can be debated and changed later, lets fix the data race first.

2026-09-06 00:37 UTC, closed without merging