add create time for helm search repo
helm/helm pull request #11326
Opened 2022-09-11 19:51 UTC by cleverhu

Signed-off-by: cleverhu <shouping.hu@daocloud.io>

**What this PR does / why we need it**:
Implement: https://github.com/helm/helm/issues/11042
add create time for helm search repo
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2023-01-20 21:35 UTC, NickFitan approved these changes
LGTM

2023-03-15 04:39 UTC, sivachandran-s commented
Hi , 

when these changes are planned to release ?

2023-03-17 00:05 UTC, joejulian commented
Unfortunately this is considered a breaking change. A lot of folks scrape the output of helm and parse the text. Adding a field, however helpful it might be, would break their automation.

It could still be added to the json and yaml outputs, but the table output would be considered breaking.

2023-03-23 03:11 UTC, adamdavis40208 commented
What monsters don't use json/yaml output for automation :P

2023-05-08 17:40 UTC, joejulian requested changes
blocked for the breaking change in the table output

2024-04-18 10:39 UTC, yzinkovets commented
Creation timestamp is really useful. 
@joejulian Maybe addition of `--with-timestamps` could manage the output of `CREATED` column?

2024-11-05 15:13 UTC, ksauzz commented
I created [another PR](https://github.com/helm/helm/pull/13421) based on this PR adding `--with-timestamps` option for backward compatibility.

2025-09-27 00:21 UTC, closed without merging