Speed up `tpl`
helm/helm pull request #11351
Opened 2022-09-16 13:41 UTC by greed42

**What this PR does / why we need it**:

This dramatically improves the performance of the `tpl` function, resolving the issues described in https://github.com/helm/helm/issues/8002. Our typical charts go from 2-3 minute renders to 1-2 seconds. A particularly pathological one went from 37 minutes to 23 seconds.

It uses a clone of the invoking Go `Template` instance, rather that re-building everything from scratch, to isolate the effects of parsing the `tpl` text from the calling context. To allow `include`s of `define`s from the `tpl` text to continue to work, it also re-defines `include` within the clone so it can close over the clone itself.

**Special notes for your reviewer**:

The only user-noticeable change should be to performance: actual chart output is unaffected by this change. All tests are unaffected.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-09-23 10:24 UTC, yxxhero commented
@greed42 good job.

2022-10-13 10:53 UTC, StephanDollberg commented
@yxxhero can this be triaged/merged/looked at?

Seems like a massive benefit for a little change.

2022-10-13 10:57 UTC, yxxhero commented
@bacongobbler @hickeyma @joejulian @scottrigby  could you have free time to review this feature? this is a good change. Thanks very much.

2022-10-13 16:50 UTC, joejulian commented
How does this differ from #8371?

2022-10-15 00:31 UTC, yxxhero commented
@joejulian main logic is the same. I think we should discuss the PR in the meeting. WDYT?

2022-10-15 00:32 UTC, joejulian commented
Sounds good

2022-10-15 00:35 UTC, yxxhero commented
@joejulian my English is not good. So looking forward to your discussion. Thanks very much.

2022-10-15 00:35 UTC, joejulian commented
Actually, no meetings the rest of October.

If one isn't any better than the other, we should just add the older one to the next minor release milestone and close the newer.

2022-10-15 00:39 UTC, yxxhero commented
@joejulian I'm not familiar with this core logic of `tpl`. So I can't pick out which is better.

2022-10-15 01:00 UTC, joejulian commented
@greed42 @diafour any comment about the difference of these two PRs?

2022-10-17 11:40 UTC, greed42 commented
#8371 permutes the existing code less, so is trivially better on that measure. It's also better for DRY-ness.

Mine also has a bug with `define` inside `tpl` that then calls `tpl` and `include`s that `define`, so #8371 is also better there.

2022-10-18 09:27 UTC, greed42 commented
Though #8371 has an infinite recursion bug with a case that involves `.Files.Get` which my approach (just not re-using the filename:string render interface) doesn't suffer. I haven't gotten it isolated yet.

2022-10-18 11:15 UTC, greed42 commented
`.Files.Get` is a possible red-herring for #8371; it's an empty string to `tpl` that's the problem, basically:

```
{{ tpl "" . }}
```

Except that PR looks to do `.New(name).Parse(tpl)` which I would expect to not suffer from that problem... except the sign you haven't done `.New(name)` is that:

```
 {{ tpl `{{ "" }` . }}
```

 also recurses and it doesn't.

2022-10-18 14:06 UTC, greed42 commented
OK I've worked out that the difference between `t.Execute()` and `t.ExecuteTemplate()` is critical to how empty behaves. The latter will let "earlier" definitions leak through, as `t.Parse()` will always grab the previous value for a given name for the named association... while the "plain" template `t.Execute()` uses will see the empty text.

I think that means it is impractical to share Execute code between `tpl` and regular manifest expansion. `tpl` needs to be a special case, like `include` is a special case.

I will see if I can get some tests for the various edge cases I've observed with my chart library regression suite, and set them up as a separate PR so that this PR does not have additions for tests that cover existing behaviour.

2022-10-18 20:45 UTC, joejulian commented
Based on that analysis, I'll add #8371 to the v3.11.0 milestone and hope that the core maintainers have time to get it reviewed and merged.

2022-10-22 00:07 UTC, joejulian commented
I believe you're saying that #11456 is the better solution now? I'm happy to switch which PR's in the milestone. I can't duplicate the issue so I have to count on you folks that see the problem to guide me here.

2022-10-24 09:46 UTC, greed42 commented
> I believe you're saying that #11456 is the better solution now? I'm happy to switch which PR's in the milestone. I can't duplicate the issue so I have to count on you folks that see the problem to guide me here.

No; #11456 is just tests for existing behaviour. It doesn't fix anything. #11351 (this one) is the fix I would now recommend.

The fault in #8371 is with this manifest or anything containing:

```
---
kind: Test
data: {{ tpl "" . }}
```

Or other define-only things like:

```
---
kind: Test
data: {{ tpl `{{define "foo"}}test{{end}}`  . }}
```

You get a stack overflow, as the empty template never becomes the template `ExecuteTemplate` sees, and so:

```
% bin/helm template test
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc0eb46a380 stack=[0xc0eb46a000, 0xc10b46a000]
fatal error: stack overflow
...
```

2023-01-03 14:22 UTC, mattfarina commented
I like the speedup. We'll need to take a very careful look at this change as there is potential to break existing charts.

2023-01-03 16:10 UTC, greed42 commented
> I like the speedup. We'll need to take a very careful look at this change as there is potential to break existing charts.

I definitely recommend getting https://github.com/helm/helm/pull/11456 merged, as then there will be tests which will show "expected" changes from this PR. And make it much easier to cover cases not already covered in that (test-only) PR.

2023-01-24 08:46 UTC, davesmits commented
I don't know how hard it would be with the infrastructure but maybe offer a preview build with this PR in it so people can help to test?

2023-03-01 10:24 UTC, g-schaeffer commented
+1 for at least a preview build. It's a mustT

2023-03-06 09:44 UTC, FlamingFlowair commented
This could drastically reduce our build time as we massively use tpl and umbrella chart to deploy an app with multiples components and micro services.

2023-04-07 08:57 UTC, fan-tad commented
is this feature still in review? Would like to have this in the next release as it would help up reduce the build time

2023-04-18 07:55 UTC, tduverge commented
I tried this change on my project with a huge chart umbrella (about 50 subcharts), it works and saves a lot of time.
We also use helm to generate yaml templates for non-kubernetes environment and this feature works as well.
This is a game changer as we were thinking of leaving helm.

2023-04-18 08:19 UTC, yxxhero commented
@joejulian @mattfarina need your help. thanks very much.

2023-04-20 06:26 UTC, xeonx commented
As mentioned above by original author @greed42, this PR and #11456 goes together.
#11456 add some tests for the `tpl` function, especially for scenario with `define` mixed together with `tpl`.

This PR changes some of those (unspecified) behaviors.
You can see the impact of this PR versus those new test cases here: https://github.com/xeonx/helm/commit/1ea011f3625f860943d627b0993392427afe5633#diff-b16f55bb6289c9df88deaedc99a45db09154ba13ee3a186b7c5636d67f5b345d

So I definitely recommend merging first #11456, then this PR will have to be updated to show the impact on the current behavior 
(mainly when there is a `define` override from within a `tpl`, of course impacting only inside `tpl` whereas in current implementation the globally defined `define` is used).

Also, for those interested I delivered an unofficial beta version of helm that include this change, so feel free to test with your charts and report any unexpected behavior.
https://github.com/xeonx/helm/releases/tag/v3.12.0-tpl-beta.1

2023-04-27 12:09 UTC, TheBritz commented
Geeking out about this, @greed42 - you're my hero! This took our 100+ umbrella chart render time from 4.5 min down to under 7 seconds.

Can I somehow send you a beer? Haha!

2023-05-06 06:19 UTC, xeonx commented
For those interested, as the milestone for this is now moved to 3.13 (September 2023), I will keep updating my fork and create releases allowing to test this change based on official latest helm release. 
https://github.com/xeonx/helm/releases/tag/v3.12.0-rc.1-fast-tpl
Feel free to ping me in the helm-dev slack for any question.

2023-05-10 07:32 UTC, xeonx commented
FYI, while testing this, I found an issue in the text/template package related to clone
https://github.com/golang/go/issues/60100
Thus until this bug is fixed (or a workaround is implemented in this PR) this PR will introduce a regression.

2023-05-10 23:35 UTC, joejulian requested changes, later dismissed
Thanks for that @xeonx. I'm going to block this on upstream https://github.com/golang/go/issues/43022.

2023-05-11 21:18 UTC, greed42 commented
> FYI, while testing this, I found an issue in the text/template package related to clone
> [golang/go#60100](https://github.com/golang/go/issues/60100)
> Thus until this bug is fixed (or a workaround is implemented in this PR) this PR will introduce a regression.

I've added a check to my test backfill PR for this case: https://github.com/helm/helm/pull/11456/commits/f235f0f28564b4391ef8b0b5f06b2d754bc13873

2023-06-22 00:20 UTC, ashleydavies commented
Just to add a voice to the chorus, this dramatically sped up Helm for us. We were using a home-grown function that avoids invoking `tpl` as much as possible by hacking at common cases (e.g. straightforward variable lookups were done without `tpl`), but it's impossible to avoid sometimes and also our chart dependencies use it very frequently 😄

For us, this took our chart that contains third-party charts from ~15 seconds per Helm operation to ~1s(!), and 

@greed42 Am I right in understanding that with your workaround, nothing is blocking this PR from being reviewed? If there's anything blocking that can be helped with some investigation and work I would be happy to try to help if I can.

2023-06-22 13:35 UTC, greed42 commented
> @greed42 Am I right in understanding that with your workaround, nothing is blocking this PR from being reviewed? If there's anything blocking that can be helped with some investigation and work I would be happy to try to help if I can.

As far as I can tell, there shouldn't be anything blocking. If we got the test backfill PR (https://github.com/helm/helm/pull/11456) merged, then any possible issues could be raised as new checks which would cause this PR to fail testing.

2023-06-22 23:05 UTC, ashleydavies commented
🥳 

@joejulian as the assignee, are you able to take a look at the associated PR and this one? It seems like the author's got them to a great place and there's a reasonable amount of demand here for what is a really significant optimisation.

I have a feeling it'll have a much bigger impact than what's obvious from the reactions to this PR - a lot of people probably just assume Helm is just slow for big charts, unless they've spent a lot of time messing with their chart to discover the issue is `tpl` invocations. It took me quite a while to get to the bottom of it (luckily we added a lot of `tpl` in one go that was obvious in a `git bisect`, but in another world we never figured it out 😄)

[Sorry to @ you, I hope it's not considered rude! Wasn't sure what the workflow is here]

2023-07-31 23:36 UTC, joejulian approved these changes
It works for me. I don't have anything that takes more than 2 seconds, anyway, so I can't see the improvement, but there's enough feedback to give me confidence that it works for others.

2023-07-31 23:55 UTC, greed42 commented
> It works for me. I don't have anything that takes more than 2 seconds, anyway, so I can't see the improvement, but there's enough feedback to give me confidence that it works for others.

Thanks. The new tests will fail after merging in main, so I've pushed a merge and the appropriate test changes to this branch.

2023-08-01 19:54 UTC, stavros-k commented
Here is some numbers from someone what has something big :)

```shell
/tmp/helm/bin/helm version   
version.BuildInfo{Version:"v3.12+unreleased", GitCommit:"b261a1b1bee93343cf9fe92335d3f1ccf3e24558", GitTreeState:"clean", GoVersion:"go1.20.6"}

time /tmp/helm/bin/helm template . > /dev/null
/tmp/helm/bin/helm template . > /dev/null  0,51s user 0,04s system 159% cpu 0,344 total
```

```shell
helm version
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}

time helm template . > /dev/null 
helm template . > /dev/null  22,30s user 0,45s system 147% cpu 15,452 total
```

2023-08-01 20:24 UTC, stavros-k approved these changes

2023-08-01 22:19 UTC, yxxhero approved these changes

2023-08-05 23:18 UTC, yxxhero commented
speed up!!!!

2023-08-23 06:29 UTC, yxxhero commented
@joejulian would you mind to talk the PR in the dev meeting?

2023-09-14 10:25 UTC, starwarsfan commented
What's the current state here? Will this be fixed with 3.13?

2023-10-03 06:31 UTC, starwarsfan commented
As 3.13.0 is released, the fix did not make it into it, right?

2023-10-06 11:49 UTC, Kuzmenko-Pavel commented
We look forward to speeding up!!!

2023-10-06 12:02 UTC, HrechykhinVlad commented
Please speed up, we need those changes. Thank you!

2023-10-06 13:04 UTC, Lokker29 commented
We really need this improvement. Please, merge it!

2023-10-06 13:12 UTC, Mixxxxerr commented
Need this asap. Merge pls

2023-10-06 15:21 UTC, DaniilOmelianenko commented
Hey! This really cool! Speed up it, please.

2023-10-09 05:28 UTC, oleksandrhrekov commented
Looks cool! Speed it up, please.

2023-10-26 08:33 UTC, FlamingFlowair commented
No news on this, is it still under review ? we're almost 3 months after the first approval.
Hope this gets merged soon

2023-11-05 12:03 UTC, Ornias1993 approved these changes
Nicely structured and documented.
Speed improvement is crucial for bigger repositories and charts.

LGTM.

2023-11-05 12:09 UTC, Ornias1993 commented
@scottrigby and @mattfarina Can we get a final review from you two as well?

It seems most issues including previous upstream blockers have been dealth with and this PR would give a significant boost to making Helm more usefull for projects with more complex requirements relying on heavy tpl usage.

2023-12-12 10:34 UTC, swythan commented
Any update on getting this merged?

2024-01-08 09:21 UTC, sabre1041 approved these changes
LGTM

2024-01-08 22:51 UTC, merged

2024-01-08 22:59 UTC, yxxhero commented
Cool.