Adding support for RISC-V arch
helm/helm pull request #11377
Opened 2022-09-23 14:02 UTC by advancedwebdeveloper

On behalf of https://github.com/helm/helm/issues/11341

CC @lazyparser @carlosedp

Signed-off-by: gghjgj <yantitarenko5@gmail.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-11-23 00:13 UTC, gjenkins8 commented
I think it might be worth joining the [weekly call](https://github.com/helm/community/blob/main/communication.md#meetings) to discuss this PR. And at least I think the circleci build needs to pass, and likely also the CI be able to produce RISC-V artifacts (current failure is a syntax error)

2022-12-17 23:19 UTC, paperstarr requested changes
easy fix. (it's my first pull request review lol)

2022-12-17 23:19 UTC, paperstarr commented on pkg/plugin/plugin_test.go
> +	else if os == "linux" && arch == "riscv64" {
fix code style breaking CI

```suggestion
	} else if os == "linux" && arch == "riscv64" {
```

2023-07-13 00:51 UTC, joejulian commented
Closing this as abandoned. If you can come back and address the change request, please reopen the PR.

2023-07-13 00:51 UTC, closed without merging