fix HTTPInstaller not handling octet-stream media types
helm/helm pull request #11389
Opened 2022-09-27 01:06 UTC by s7m4b4

closes #11272
Signed-off-by: Stephen Bell <8148044+s7m4b4@users.noreply.github.com>

**What this PR does / why we need it**:
As mentioned in #11272, Github uses "application/octet-stream" media type which `mediaTypeToExtension` does not consider, meaning any plugin installs from Github will fail when using `HTTPInstaller`. This fixes that.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-12-09 12:45 UTC, hickeyma approved these changes
@s7m4b4 Thank you for pushing this fix.

I have changed the description to say partial-fix #11272 as this fix fixes the HTTP get issue. As you mentioned in https://github.com/helm/helm/issues/11272#issuecomment-1258822058, there are more open issues when files are not in the root of the archive.

2022-12-09 12:46 UTC, hickeyma commented
Would like another maintainer to take a look also before merging.

2022-12-14 18:42 UTC, hickeyma commented
Thanks for the feedback @phil9909 and input always welcome. Lets get more input and see how we want to handle this.

2022-12-19 22:16 UTC, mattfarina requested changes
I tried this change on top of https://github.com/helm/helm/pull/11508 and it doesn't fix the issue. It also opens the door to downloading other things and trying to work on them. We shouldn't do that.

2022-12-19 22:16 UTC, mattfarina commented on pkg/plugin/installer/http_installer.go
> +	case "application/gzip", "application/x-gzip", "application/x-tgz", "application/x-gtar", "application/octet-stream":
The addition of application/octet-stream doesn't mean it's a valid file. We need to make sure the extension is valid in the case of this. Can we pass it in to this function and then check for this case that the extension is right?

2023-07-13 00:53 UTC, joejulian commented
Closing this as abandoned. If you can come back and address the change request, please reopen the PR.

2023-07-13 00:53 UTC, closed without merging