Import values override defaults
helm/helm pull request #11527
Opened 2022-11-10 08:53 UTC by pbusko

**What this PR does / why we need it**:
Address the issue https://github.com/helm/helm/issues/11518

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2022-12-08 17:52 UTC, technosophos commented
I think this is the PR that introduced the current behavior: https://github.com/helm/helm/commit/7ea4d8c7c460eae18bf74c682832acfb009445ce

2022-12-17 11:54 UTC, digitalstudium commented
I prefer current behavior. The use case is when I import default values from a library chart and then redefine some of them if needed in a parent chart.
Example which works for me today:
library chart `values.yaml`:
```
defaults:
  image:
    registry: quay.io
    name: ""
```
`values.yaml` of a chart which imports library chart:
```
image:
  name: nginx
```

Resulting `values.yaml`:
```
  image:
    registry: quay.io
    name: nginx
 ```
 
So I prefer if you change documentation, not the code. Because I want my library chart to have default values and I want to have a method to redefine some of them in parent's `values.yaml`. This is very convenient way.
Such way library chart's `values.yaml` is like a class which I can inherit and then extend or modify.

Side note: the way I import library chart is such:
```
dependencies:
  - name: base
    repository: file://../../libraries/base
    version: "*"
    import-values:
      - child: defaults
        parent: .
```

2022-12-17 11:59 UTC, digitalstudium commented
And BTW, if you merge this PR it will be breaking change. Some people already wrote charts which work with current behavior and which will not work after merging this code.

2023-07-02 12:24 UTC, hedayat commented
> And BTW, if you merge this PR it will be breaking change. Some people already wrote charts which work with current behavior and which will not work after merging this code.

And there are some people who already wrote charts which work with the old behavior, and are not currently working with the new one. And it doesn't follow the documented behavior. 

Having a very inconsistent behavior based on different versions of helm doesn't look good. Anyway, #11162 seems to be a good solution.

2024-05-16 02:24 UTC, scottrigby requested changes
We've been attempting to clarify how this should work, so that both documentation and tests for code follow. Here is the google doc WIP for documenting this: https://docs.google.com/document/d/1ZjmIc5VYzNbaJ-SQ6nT02Oo1t9ctlvomufP8ulR6q70/edit

As I understand it, @digitalstudium is correct that the current behavior is as intended. Documentation improvement in progress here: [What is the order of precedence logic?](https://docs.google.com/document/d/1ZjmIc5VYzNbaJ-SQ6nT02Oo1t9ctlvomufP8ulR6q70/edit#heading=h.brer0zqgu3qn):

> Logical specification/ordering (from [12480](https://github.com/helm/helm/pull/12480)) should be:
> 1. User specified values (e.g CLI --set, -f)
> 2. Parent chart default values
> 3. Imported values get merged from child chart(s) into parent chart’s value
> 4. Parent chart’s values get propagated to sub-chart(s), and merged with sub-chart values

Based on this, I believe the changes should be an update to the docs.

2024-05-17 18:42 UTC, hedayat commented
@scottrigby The doc is still WIP, and inconsistent (also mentioned in the comments). And the priority doesn't cover all the use cases mentioned there. Unless decisions has been made somewhere else, I think it's still not ready to be concluded from!

2024-05-31 12:07 UTC, intetinte commented
The current ordering is:
1. User specified values (e.g CLI --set, -f)
2. Parent chart default values
3. Parent chart’s values get propagated to sub-chart(s), and merged with sub-chart values
4. Imported values get merged from child chart(s) into parent chart’s value

With this pull request implemented it will instead be:
1. User specified values (e.g CLI --set, -f)
2. Imported values get merged from child chart(s) into parent chart’s value
3. Parent chart default values
4. Parent chart’s values get propagated to sub-chart(s), and merged with sub-chart values

And this doc https://docs.google.com/document/d/1ZjmIc5VYzNbaJ-SQ6nT02Oo1t9ctlvomufP8ulR6q70/edit#heading=h.brer0zqgu3qn explains another ordering (aligned in this PR https://github.com/helm/helm/pull/12590) :
1. User specified values (e.g CLI --set, -f)
2. Parent chart default values
3. Imported values get merged from child chart(s) into parent chart’s value
4. Parent chart’s values get propagated to sub-chart(s), and merged with sub-chart values

Someone need to state what the ordering should be an align to that.

2026-01-02 12:13 UTC, closed without merging