feat: pass basic auth to env-vars when running download plugins
helm/helm pull request #11878
Opened 2023-03-06 15:35 UTC by Exchizz

**What this PR does / why we need it**:
This PR passes username and password from "helm repo add --username X --password Y" to download plugins. See #11877 for motivation.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

closes #11877

I created this PR with help from @birjj

2023-04-14 10:37 UTC, Exchizz commented
Hi,

What's the status of this PR ? Currently an [issue ](https://github.com/aslafy-z/helm-git/issues/255) in helm-git is waiting for this this PR to be merged.

\Exchizz

2023-04-28 21:28 UTC, mattfarina requested changes
There is one change that, I think, needs to happen. It's due to a CVE that came to Helm a couple years ago and has to do with where the username/password are used.

2023-04-28 21:28 UTC, mattfarina commented on pkg/getter/plugingetter.go
> +	env = append(env, fmt.Sprintf("HELM_PLUGIN_PASSWORD=%s", p.opts.password))
There is one more `opt` that should be passed along for this. It is `passCredentialsAll`.

This is for security. The username and password are for the specific "thing" that's being downloaded. This could be an individual chart of an index file for a chart repo. When getting the index file, the charts could be on a different domain. Do you pass the username/password on to this other domain? If so, you could leak the credentials.

Helm stores the intent if the username/password should be passed on to other domains in this option. This is due to [CVE-2021-32690](https://github.com/helm/helm/security/advisories/GHSA-56hp-xqp3-w2jf). The details of this situation can be found there.

2023-04-29 20:32 UTC, Exchizz commented on pkg/getter/plugingetter.go
> +	env = append(env, fmt.Sprintf("HELM_PLUGIN_PASSWORD=%s", p.opts.password))
I've added HELM_PLUGIN_PASS_CREDENTIALS_ALL as env-var :)

2023-09-11 11:29 UTC, Exchizz commented
Hi @mattfarina,

I can see this PR is set to be included in 3.13.0 which is set to be released in a couple of days.
Do you think this PR will make it into the next release ? 

Thanks in advance

2024-01-05 23:47 UTC, joejulian approved these changes

2024-01-05 23:47 UTC, joejulian commented
Since @mattfarina's concern was addressed, I'm going to go ahead and merge this.

2024-01-05 23:48 UTC, merged