Bump the Go version
helm/helm pull request #11896
Opened 2023-03-09 18:33 UTC by mattfarina

**What this PR does / why we need it**:
Use a supported version of Go.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2023-03-12 12:43 UTC, TerryHowe approved these changes

2023-03-12 12:43 UTC, TerryHowe commented on .github/workflows/build-test.yml
> +          GOLANGCI_LINT_VERSION: '1.51.2'
This version works on mac! 1.50 with go 1.20 was borked.

2023-03-21 09:15 UTC, hickeyma requested changes
Looks good @mattfarina except should the `go.mod` be bumped to 1.20?

2023-03-23 13:29 UTC, scottrigby commented
@mattfarina @souleb  @sabre1041 @jdolitsky hmm Matt I see your test details in Keybase, fun change in Go 🧐 If we don't have a solution for this now I agree we should revert in the meantime, work to resolve this and then bring back into main after resolving (pun intended!). To help us with this - and for future, any objections to setting up our GitHub action on a matrix of Helm's supported Go versions, architectures, etc? https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

2023-03-23 16:27 UTC, scottrigby commented
@souleb is working on a potential fix. @mattfarina any objection to holding off on reverting for a bit? Say until Monday?

2023-03-23 17:38 UTC, mattfarina commented
@hickeyma can you please re-review? It's working now.

The large size of the change is because of the deprecation of ioutil and the linter making it an error now. The change has been around for that long.

Also, there is a mock DNS resolver because some systems have trouble with the system resolvers which are inconsistent.

2023-03-24 10:30 UTC, hickeyma approved these changes
Great work on this @mattfarina especially tracking and fixing the dns issue.

2023-03-24 12:54 UTC, merged