helm history UPDATED should print local time
helm/helm pull request #11924
Opened 2023-03-22 07:49 UTC by faucct

At the moment history ignores timezones:

```
MacBook-Pro:~ faucct$ helm history shadow-ranker --max=3
REVISION	UPDATED                 	STATUS    	CHART       	APP VERSION	DESCRIPTION                       
403     	Wed Mar 22 06:57:54 2023	deployed  	ranker-0.1.0	           	ranker-feature__java-17-ca53f05.38
404     	Wed Mar 22 11:17:56 2023	superseded	ranker-0.1.0	           	Rollback to 402                   
405     	Wed Mar 22 07:22:45 2023	deployed  	ranker-0.1.0	           	ranker-master-50fb173.138         
MacBook-Pro:~ faucct$ helm history shadow-ranker --max=3 --output=json | jq
[
  {
    "revision": 403,
    "updated": "2023-03-22T06:57:54.4714541Z",
    "status": "deployed",
    "chart": "ranker-0.1.0",
    "app_version": "",
    "description": "ranker-feature__java-17-ca53f05.38"
  },
  {
    "revision": 404,
    "updated": "2023-03-22T11:17:56.517365+04:00",
    "status": "superseded",
    "chart": "ranker-0.1.0",
    "app_version": "",
    "description": "Rollback to 402"
  },
  {
    "revision": 405,
    "updated": "2023-03-22T07:22:45.612469614Z",
    "status": "deployed",
    "chart": "ranker-0.1.0",
    "app_version": "",
    "description": "ranker-master-50fb173.138"
  }
]
```

2023-03-22 07:57 UTC, faucct commented
`status.go` also prints non-local time without a timezone, but its output is locked in tests, so they will probably break if I change that.

2023-05-09 00:30 UTC, joejulian requested changes
This would be considered a breaking change. There are many tools that are written around scraping the text output of helm commands and this could have unintended consequences on those tools.

2023-05-09 09:09 UTC, faucct commented
Can’t those tools use the formats with timezones if they need the precision? Do you suggest to close this PR?

2023-05-10 23:33 UTC, joejulian commented
> Can’t those tools use other formats, more parceable and with timezones, if they need the precision? Do you suggest to close this PR?

They _could_ but that's the thing, they don't currently and we have [very strict rules](https://github.com/helm/community/blob/main/hips/hip-0004.md) about not breaking users. A change like this would have to wait for Helm 4.

2023-08-09 06:08 UTC, joejulian commented
@faucct I'm going to go ahead and close this. Feel free to ping me if you think there is more to be done here.

2023-08-09 06:08 UTC, closed without merging