add govulncheck to CI
helm/helm pull request #12045
Opened 2023-05-02 17:30 UTC by joejulian

**What this PR does / why we need it**:
We get a lot of false-positives from users running security scanners that are incorrectly identifying upstream packages as being relevant. This would give us a reference to show that those issues are not valid.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2023-05-02 20:59 UTC, gjenkins8 commented
nice!

2023-05-02 23:40 UTC, yxxhero approved these changes

2023-05-04 17:03 UTC, gjenkins8 commented
One question -- does this introduce any blocking CI checks? One pitfall with CVE checks is blocking PRs unrelated to the existing and then discovered CVE. IMHO only PRs that introduce a CVE should be blocked. CVEs which already exist in the code should be reported (of course).

2023-05-25 16:29 UTC, mattfarina requested changes

2023-05-25 16:29 UTC, mattfarina commented on .github/workflows/build-test.yml
> +        uses: Templum/govulncheck-action@v0.10.1
Our actions are pinned to a revision. For example,

```
actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@3.5.0
```

Can you pin this one?

2024-08-06 20:38 UTC, scottrigby approved these changes
This lgtm. I havne't used govulncheck until today. Thanks @gjenkins8 for pointing it out.

Speaking of:
> One question -- does this introduce any blocking CI checks? One pitfall with CVE checks is blocking PRs unrelated to an existing, but then discovered CVE. IMHO only PRs that introduce a CVE should be blocked. CVEs which already exist in the code should be reported (of course).

@gjenkins8 we can dismiss checks if the code found is unrelated to the PR, yes?

PS @mattfarina's requested change was made (version is now pinned) https://github.com/helm/helm/pull/12045#pullrequestreview-1444273920

2024-08-08 18:16 UTC, scottrigby reviewed
Backing out of my approval for the moment because - while this seems useful to me - a bit more discussion may help. I checked in with @gjenkins8 to better understand the concern. I'll let him describe his point of view.

One additional note though, we may want to check in with the Minio folks to ask their experience. They've been using govulncheck in CI for 2 years. While infrequent, it seems from a search that this has come in handy. Here is an example comment that I think exemplifies @joejulian 's initial motivation for this PR: https://github.com/minio/minio/issues/17730#issuecomment-1652599721

2024-09-09 16:19 UTC, closed without merging