adds lint-mode flag to helm template
helm/helm pull request #12160
Opened 2023-06-22 07:27 UTC by bennsimon

**What this PR does / why we need it**:
Adds `--lint-mode` flag to helm template command. This allows one to execute helm template command successfully when required values are missing.

**Special notes for your reviewer**:
The `lint-mode` flag had already been [added](https://github.com/bennsimon/helm/commit/213f7146042f92a6d019cbf1da75c1145b1abaf2) but it remained internal. This PR will expose the flag to the user. 

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2023-09-15 06:44 UTC, bennsimon commented
Hey @joejulian, Any update on this?

2024-11-07 19:19 UTC, joejulian submitted a review, later dismissed

2024-12-02 14:11 UTC, gjenkins8 commented
> What this PR does / why we need it:
Adds --lint-mode flag to helm template command. This allows one to execute helm template command successfully when required values are missing.

For my understanding, why will this be useful? Certainly, Helm could ignore required values and render the templates. But the results are likely to be ill-formed in this case? (helm lint also renders the templates, but that just shows that gotemplate accepts them. And it discards the results)

2025-03-12 17:17 UTC, gjenkins8 requested changes
https://github.com/helm/helm/pull/12160#issuecomment-2511650431

Answering why this is useful before merging please

2025-03-15 13:08 UTC, bennsimon commented
> [#12160 (comment)](https://github.com/helm/helm/pull/12160#issuecomment-2511650431)
> 
> Answering why this is useful before merging please

Hi @gjenkins8 
I exposed the `lint-mode` feature to get rendered templates (for `pre-deployment` checks) without necessarily specifying the required variables which are only crucial during installation/update. 

Currently, I need to be able to run automated continuous integration policy review checks (using OPA rego) before helm deployments using several different  (open-source) helm charts. I do that now by running policy review checks on the rendered templates.

The required variables are usually custom to the chart, have no defaults, and can vary per environment/context/application or even when using merging helm values files with helm secrets; in this case, exposing the secrets on CI pipelines is not ideal or even that these required variables are already on the cluster  (in secret manifest) so won't be useful when running pre-deployment review. The type, nature and number of required variables are reserved to the chart author(s). 

In my use cases, I run the policy review checks by only relying on Kubernetes API manifest spec of resources e.g. `. metadata.labels`, `.spec.replicas` etc., with official spec users are certain on the variables they can review.

2025-09-11 21:55 UTC, scottrigby commented
@bennsimon Needs rebase. Note Helm 3 is not accepting new features, so this now goes into Helm 4.

2025-09-12 10:33 UTC, bennsimon commented
> @bennsimon Needs rebase. Note Helm 3 is not accepting new features, so this now goes into Helm 4.

@scottrigby This is done.

2026-01-11 00:28 UTC, closed without merging