chore: remove unuse untar option
helm/helm pull request #12202
Opened 2023-07-13 08:29 UTC by Abirdcfly

**What this PR does / why we need it**:
[`getter.options`](https://github.com/helm/helm/blob/14d363669f8cc257f0413995d42237e673422d81/pkg/getter/getter.go#L33) has parameters [`untar`](https://github.com/helm/helm/blob/14d363669f8cc257f0413995d42237e673422d81/pkg/getter/getter.go#L38) and its setting function [`WithUntar()`]( https://github.com/helm/helm/blob/14d363669f8cc257f0413995d42237e673422d81/pkg/getter/getter.go#L118C6-L118C15).
But it's not used anywhere, not even in the tests.
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2023-07-13 15:32 UTC, mattfarina requested changes
Helm follows semantic versioning. We cannot remove this until Helm v4 or the Go API will be broken.

A useful change would be to have a code comment noting that it's deprecated.

2023-07-13 16:23 UTC, Abirdcfly commented
> We cannot remove this until Helm v4 or the Go API will be broken.

But `options.untar` is an **Non-capitalized** identifier. it can not be exported and can only be accessed from within the same package, and we do not use this identifier in `options` package...

So, neither `options.untar` nor `WithUntar()` will have any effect.

2023-07-18 20:05 UTC, mattfarina commented
@Abirdcfly The issue is with `WithUntar`. That is a public method that could be used in some calling code for someone using the Helm SDK. Even if it does nothing. Removing it will break their calling code. This is part of the public Helm Go SDK API so we can't remove it until Helm v4. To remove it would violate Semantic Versioning.

2023-08-11 00:29 UTC, joejulian commented
Thanks for noticing this and making an effort, @Abirdcfly . I'm going to go ahead and close this, though, since it's not something that can be merged.

2023-08-11 00:29 UTC, closed without merging