fix: the pull command does not take effect to set the username and pa…
helm/helm pull request #12241
Opened 2023-07-20 04:56 UTC by 0xff-dev

…ssword

**What this PR does / why we need it**:
Fix:  https://github.com/helm/helm/issues/12117

The current implementation is to put the parameters of repositories.yaml after the list, which will cause the user and password to be overwritten even if we set them.
So, we put the contents of repositories.yaml at the front of the list.

**Special notes for your reviewer**:
@joejulian 

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2023-08-01 00:46 UTC, joejulian requested changes
This PR is contrary to the discussion that was had on the PR. The final outcome was expected to be a PR that would warn the user if `--pass-credentials` is used when `pass_credentials_all` is `false`.

https://github.com/helm/helm/issues/12117#issuecomment-1577945270

2023-08-01 01:20 UTC, 0xff-dev commented
Yes, the discussion said to add some warnings, so this PR should not fix that issue.

The problem with this PR is that when the user sets the username and password during pull and install, the information in the configuration is still used.

Should my PR be unlinked from that issue? And submit another PR to add the warning?

2023-08-24 06:08 UTC, joejulian commented
@0xff-dev Yes. This PR changes the behavior which goes against the guiding principal in [hip-0004](https://github.com/helm/community/blob/main/hips/hip-0004.md).

2023-08-27 02:40 UTC, 0xff-dev commented
> @0xff-dev Yes. This PR changes the behavior which goes against the guiding principal in [hip-0004](https://github.com/helm/community/blob/main/hips/hip-0004.md).

Thanks for the review, the code has been modified.

2025-08-24 06:23 UTC, closed without merging