fix: Enable release action to override helm-latest-version
helm/helm pull request #12670
Opened 2023-12-27 22:10 UTC by gjenkins8

**What this PR does / why we need it**:
Currently, Helm release action (`release.yml`) does not allow updating https://get.helm.sh/helm-latest-version , which causes `get-helm-3` script to download stale versions.

fixes: 12669

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2023-12-27 22:15 UTC, z4ce requested changes

2023-12-27 22:15 UTC, z4ce commented on .github/workflows/release.yml
> +        overwrite: 'true'
This should be in the 'with' statement

2023-12-27 22:19 UTC, z4ce approved these changes

2023-12-28 08:20 UTC, yxxhero approved these changes

2024-01-10 15:03 UTC, closed without merging