Add loongarch64 support
helm/helm pull request #12708
Opened 2024-01-12 01:31 UTC by yzewei

**What this PR does / why we need it**:
 Add loongarch64 support for helm,

**Special notes for your reviewer**:
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Use QEMU to simulate the Loongarch architecture in other architecture.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-01-12 01:32 UTC, yzewei commented
ptal

2024-06-17 09:14 UTC, NickJosevski commented
@yzewei could you rebase, as now there's merge conflicts

2024-10-15 00:30 UTC, gjenkins8 requested changes
awaiting rebase

2024-12-07 08:08 UTC, yzewei commented
> awaiting rebase

ok

2025-09-23 00:22 UTC, closed without merging