fix: fix oci tag error in helm push
helm/helm pull request #12737
Opened 2024-01-21 22:27 UTC by Rashmi-K-A

**What this PR does / why we need it**:
Closes #12728 by adding a clearer error log that says `Version tag <VERSION> need not be passed for remote"`

See local run result:
<img width="763" alt="Screenshot 2024-01-21 at 2 26 37 PM" src="https://github.com/helm/helm/assets/39820442/32f08994-9379-4099-a1b3-034260ae21b9">

**Special notes for your reviewer**:
Note for local development: The strings.SplitN(...) command works only with go version >=1.18, not sure if a backwards compatible strings.Split(...) is required instead.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-01-24 17:52 UTC, mattfarina requested changes
Thanks for the pull request. The change needs to go in a different file. Where you put it is in the routing logic and this needs to go in a more specific place.

2024-01-24 17:52 UTC, mattfarina commented on pkg/uploader/chart_uploader.go
> +	}
This check should be placed inside _ocipusher.go_. `UploadTo` has basic error handling for the URI to make sure it's valid and we have the ability to route it to a pusher. This logic is specific to OCI style things so it should go in that pusher.

2024-01-31 07:27 UTC, Rashmi-K-A commented
Sure, I will make some changes this week

2024-02-15 08:22 UTC, Rashmi-K-A commented
Moved it, didnt catch error for parsing since a bad url Parse would have been caught at the chart_uploader level. Tested it out locally and it seems to work

2024-02-27 19:43 UTC, Rashmi-K-A commented
@mattfarina this one has been open for a while, can you take a look

2025-09-23 00:22 UTC, closed without merging