Added suit tests and updated the package versions
helm/helm pull request #12910
Opened 2024-03-26 10:33 UTC by anirudh-hegde

Updated the package versions and added piece of code for test suites

2024-03-29 11:22 UTC, anirudh-hegde commented
Please somebody review my code

2024-06-07 20:01 UTC, robertsirc requested changes
So, fortio.org/assert doesn't have any dependencies and you are changing dependencies that should not need to be updated.

2024-06-07 20:26 UTC, mattfarina requested changes
The new package being added doesn't have any dependencies. So, the dependency tree should not be updated like this. Can you please back out and only make the Go dependencies update for this single change?

Or, maybe use the existing assert package with testify, unless I'm missing something.

2024-06-07 20:26 UTC, mattfarina commented on pkg/registry/client_http_test.go
> +		assert.Equal(suite.T(), 5, suite.VariableThatShouldStartAtFive)
Why is this assert package being added when testify can already do what's being used?

2025-09-23 00:22 UTC, closed without merging