Adjust name validation in pkg/chart/metadata to use filepath.IsLocal
helm/helm pull request #13049
Opened 2024-05-20 18:05 UTC by astraldawn

**What this PR does / why we need it**: Closes #12868 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-06-07 19:25 UTC, robertsirc approved these changes
LGTM: pulled the branch built it and ran all the unit test and my smoke tests worked fine. But since this handles namespace I want to ask a core maintainer if this is the correct place for it.

2024-06-10 14:43 UTC, mattfarina requested changes
`/` in the chart name is something we need to talk about. There are docs on the name at https://helm.sh/docs/chart_best_practices/conventions/#chart-names. `/` is not covered but the allowed characters are covered and it's not included. I understand the use case and what artifactory did. I added it to the agenda for this weeks developer call.

Even if this is allowed, the current PR code mishandles `.` which is not allowed.

2024-06-10 14:43 UTC, mattfarina commented on pkg/chart/metadata.go
> +	if !filepath.IsLocal(md.Name) {
The [documentation has some details on what is allowed and not allowed in a name](https://helm.sh/docs/chart_best_practices/conventions/#chart-names). For example, a `.` is not allowed in a name. But, `filepath.IsLocal` returns true when a `.` is in the name. So, it's not good to use for this kind of validation.

2024-06-13 20:12 UTC, mattfarina requested changes
I've been looking into this one. Some things I've learned...

* Running `helm create foo/bar` (i.e. a name with a `/` in it) will return an error when it tries to create a directory.
* The chart helpers created by default (and the same style help functions widely used) will generate manifest names with `/` in them which Kubernetes will reject.
* In the `charts` directory within a Chart, where archives are stored, we run into a couple problems...
  * If the chart is nested in one or more subdirectories then Helm will return an error and not use the nested chart.
  * If you have two charts with the same base name (e.g., `foo/bar` and `baz/bar`) with them both being stored in the root of the `charts` directory there will be a problem with only one of them being present.

I think this worked for artifactory because the listing in `index.yaml` was namespaced but not the name in the chart itself. Also, people are only using one chart with the same basename.

If we want to just do the name in the `index.yaml` file than we should do a custom validation function when loading that file and not affect what's in the `Chart.yaml` file. We should also document that the base names cannot be the same.

2024-06-20 10:46 UTC, astraldawn commented
> I think this worked for artifactory because the listing in index.yaml was namespaced but not the name in the chart itself. Also, people are only using one chart with the same basename. If we want to just do the name in the index.yaml file than we should do a custom validation function when loading that file and not affect what's in the Chart.yaml file.

Agree, will adjust the MR accordingly.

> Even if this is allowed, the current PR code mishandles . which is not allowed.

The convention page does not explicitly disallow dots ("should not be used"), so the docs would need an update as well.

2024-06-22 09:10 UTC, astraldawn commented
@mattfarina Based on https://helm.sh/docs/chart_best_practices/conventions/#chart-names

```
1. Chart names must be lower case letters and numbers.
2. Words may be separated with dashes (-)
3. Neither uppercase letters nor underscores can be used in chart names.
4. Dots should not be used in chart names.
```

If 4. (should) is not allowed, then chart.metadata.name validation must enforce 1. (must) and 3. (can).

This leads to multiple failures when running `make test-unit` due to chart names containing upper case letters, underscores and dots, suggesting a need to get consensus on whether best practices for naming should be enforced.

2025-09-22 00:24 UTC, closed without merging