chore: Update backward compatibility section in CONTRIBUTING.md
helm/helm pull request #13048
Opened 2024-05-20 13:18 UTC by banjoh

**What this PR does / why we need it**:

Update backward compatibility section in CONTRIBUTING.md to reflect what HIP-0004 says

Fixes: https://github.com/helm/helm/issues/13045

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-05-23 21:08 UTC, robertsirc approved these changes
LGTM: this is just text updates on why libraries in pkg/ "MUST" remain backwards compatible.

2024-05-25 13:58 UTC, scottrigby requested changes
thanks for taking this on. agree, all looks good except one accidental half sentence. just clean that up and this will be good to go 🙂

2024-05-25 13:58 UTC, scottrigby commented on CONTRIBUTING.md
> +We also remain committed to not changing publicly accessible Go library definitions inside of the `pkg/` directory of our source code in a non-backwards-compatible way. For more on
just remove trailing duplicate "for more on"

```suggestion
We also remain committed to not changing publicly accessible Go library definitions inside of the `pkg/` directory of our source code in a non-backwards-compatible way.
```

2024-05-27 14:03 UTC, banjoh commented
> thanks for taking this on. agree, all looks good except one accidental half sentence. just clean that up and this will be good to go 🙂

I've cleaned it up

2024-06-12 20:34 UTC, scottrigby approved these changes

2024-06-12 20:37 UTC, scottrigby commented
Looks good! Thanks @banjoh

2024-06-12 20:37 UTC, merged