Allow post-renderer to process hooks
helm/helm pull request #13154
Opened 2024-07-02 21:46 UTC by carloslima

closes #7891

**What this PR does / why we need it**:
Allow post-renderer to receive and process manifests with hook annotations.

**Special notes for your reviewer**:
In order to avoid dealing with YAML comments or reconciling file contents back to their filenames, this MR calls the post-renderer right after the templates are rendered and before they get split into hooks, manifests and partials lists.
This implies that the format of the data passed into (and expected back from) the post-renderer when handling hooks is different than when it is not.

 The previous behavior stays unchanged and the new behavior is behind a `--post-renderer-hooks` flag.

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

2024-07-03 19:20 UTC, robertsirc commented
Hello, this looks to be a breaking change, is there any consideration for backwards compatibility?

2024-07-04 00:20 UTC, carloslima commented
@robertsirc It may have escaped my attention. Can you elaborate on what does it break? The new behavior is behind an extra flag `--post-renderer-hooks`. Unless enabled by the flag the previous behavior should continue unchanged. Did I forget to consider a particular case?

2024-07-06 10:14 UTC, carloslima commented
@robertsirc I think you meant that I changed the `NewExec` signature. I have pushed a fix for that. Does it solve the problem you raised? Anything else I can add/change to improve the PR?

2024-08-19 15:52 UTC, rossbachp commented
Can you merge this feature, please!

2024-08-19 16:36 UTC, rossbachp commented
When is the release of Charts 2.x planned? I need the feature :)

2024-09-11 14:25 UTC, viclim commented
any chance this PR could get a review?

2024-09-11 19:24 UTC, robertsirc commented
Great PR. We are taking a deeper look at it now. One thing we have a style error if you could fix:

```bash 
golangci-lint run ./...
pkg/postrender/exec.go:41: File is not `gofmt`-ed with `-s` (gofmt)
  return NewExecHooks(binaryPath, false, args...)
make: *** [test-style] Error 1
``

2024-09-11 21:32 UTC, carloslima commented
>  we have a style error if you could fix:

Ooops. Whitespace mistake, fixed :-)

2024-10-18 07:40 UTC, carloslima commented
@robertsirc Is there anything I can do to help move this forward?

2024-11-08 10:46 UTC, spideyfusion commented
This feature would really help me in my current deployment workflows. 🙏

2024-11-12 10:58 UTC, AbyPhantom commented
I'd really love to see this implemented. Would be really helpful to me.

2024-12-17 20:04 UTC, spideyfusion approved these changes

2025-02-08 23:58 UTC, joejulian commented on pkg/postrender/postrender.go
> +	IncHooks() bool
This will break any existing 3rd party software that implements this interface, which might be ok since we're on the helm 4 path.

2025-02-12 19:38 UTC, carloslima commented on pkg/postrender/postrender.go
> +	IncHooks() bool
Would [this change](https://github.com/helm/helm/pull/13154/commits/7f3e88d038dbd5d489a907649880793e8b54887a) be appropriate to keep the interface backwards compatible?

I was going to rebase the MR but noticed that main is moving to helm v4. Should I rebase on top of dev-v3 instead?

2025-03-06 19:33 UTC, carloslima commented on pkg/postrender/postrender.go
> +	IncHooks() bool
Hi @joejulian 
Can I get a review on this MR? Anything further I can do to help move it along?

2025-03-27 16:32 UTC, joejulian commented on pkg/postrender/postrender.go
> +	IncHooks() bool
> Would [this change](https://github.com/helm/helm/pull/13154/commits/7f3e88d038dbd5d489a907649880793e8b54887a) be appropriate to keep the interface backwards compatible?
> 
> I was going to rebase the MR but noticed that main is moving to helm v4. Should I rebase on top of dev-v3 instead?

No, this is fine. I wanted to confirm with some of the other maintainers.

2025-03-27 17:16 UTC, carloslima commented on pkg/postrender/postrender.go
> +	IncHooks() bool
@joejulian Let me know what the next steps are to move this forward.

2025-04-30 09:50 UTC, benoittgt approved these changes
I've reviewed this patch several times and support this well-executed addition to meet the request. ;)

2025-04-30 15:24 UTC, gjenkins8 reviewed
Lets decide if we want a flag, then can look at the details on the implementation

2025-04-30 15:24 UTC, gjenkins8 commented on cmd/helm/flags.go
> +	cmd.Flags().Lookup(postRenderHooksFlag).NoOptDefVal = "true"
I'm wondering if we want this flag. For compatibility purposes, certainly, we would need a flag to prevent the behavior from unexpectedly changing.

But for Helm 4, we don't have that strong compatibility requirement. We do want to maintain workflow compatiblity, especially for common workflows.

I'm wondering if there is any real use case for a post renderer to not process hooks? And even if so, whether the post renderer should exclude hook manifests based on its own internal logic (it could/would not post-render manifests with the hook annotation).

If this did sound agreeable, we could simply always pass hook manifets to the post-renderer. And avoid the additional flag, which presents itself as a thing a user has to discover and understand (and to a much lesser degree of concern, the implementation complexity).

2025-04-30 15:24 UTC, gjenkins8 commented on cmd/helm/flags.go
> +	p.options.incHooks = (val != "false" && val != "0")
(but see note above on whether we should have flag at all)

2025-05-02 11:07 UTC, carloslima commented on cmd/helm/flags.go
> +	cmd.Flags().Lookup(postRenderHooksFlag).NoOptDefVal = "true"
Based on the discussions in #7891 and the fact that it's marked as a bug, it doesn't seem like excluding hooks from the post-renderer was ever intended.

I agree, it makes sense for Helm 4 to have a single, consistent post-rendering behavior, rather than supporting two modes behind a flag.

If we still want to provide backward compatibility with Helm 3, we could offer an external wrapper that processes the new Helm 4 format, removes the hooks, and pass the manifests in the legacy Helm 3 format to the legacy post renderer.

Something like this:
```
#!/usr/bin/env ruby

# Usage: helm3-adapter <legacy-post-renderer> <arg1> <arg2> ..

require 'yaml'
require 'open3'

# Transform Helm 4 output into legacy Helm 3 format
yaml_output = StringIO.new
YAML.load(STDIN.read).reject { |filename, manifest| manifest.dig(*%w(metadata annotations helm.sh/hook)) }.each do |f, c|
  yaml_output.puts "---"
  yaml_output.puts "# Source: #{f}"
  yaml_output.puts c.to_yaml.sub(/^---\n/, '')
end

# Start the external process with the provided arguments
if ARGV.length > 0
  stdout, stderr, status = Open3.capture3(*ARGV, stdin_data: yaml_output.string)
  
  # Print the output from the process
  puts stdout unless stdout.empty?
  STDERR.puts stderr unless stderr.empty?
  exit status.exitstatus
end
```
to be invoked as:
```
helm install ... --post-renderer helm3-adapter --post-renderer-args 'legacy-post-renderer' --post-renderer-args 'legacy pr arguments'
```

That reduces the complexity inside Helm while still offering a workable backwards compatible solution.

I can make the changes to remove the flag soon.

2025-05-02 11:07 UTC, carloslima commented on cmd/helm/flags.go
> +	p.options.incHooks = (val != "false" && val != "0")
Thanks for pointing this out. Yes, if we have a boolean flag it should only accept `false, False, FALSE, f, F, 0`, `true, True, TRUE, t, T, 1` :+1:

2025-05-06 18:02 UTC, carloslima commented on cmd/helm/flags.go
> +	cmd.Flags().Lookup(postRenderHooksFlag).NoOptDefVal = "true"
@gjenkins8 I've pushed the changes to drop Helm 3 compatibility. Can you review again?

2025-05-15 18:54 UTC, carloslima commented on pkg/postrender/exec.go
> +func (p *execRender) Run(renderedFiles map[string]string) (modifiedFiles map[string]string, err error) {
No strong reason. I initially thought the naming made things clearer for documentation purposes, but I don't think it actually does.

It's fixed now.

2025-05-19 16:57 UTC, gjenkins8 commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
(Apologies for the drip-fed review comments)

I don't think we can simply change the post-renderer input format like this. The canonical use-case for the post renderer is a tool which accepts a stream of yaml documents, modifies them, and emits the stream back to Helm e.g. [kustomize](https://kustomize.io/).

Explicitly, this simple stdin/stdout "pipe" + yaml doc interface is how the majority of tools out there expect to consume a yaml stream. Changing the format breaks any/all tools which expect this simple format, and would force an unexpected change on users.

We also do have an explicit goal for Helm 4 that we will be compatible with the majority of user workflows. It is a judgement call to whether e.g. passing hook yaml in post-renderer vs changing the format is "compatible with the majority of user workflows". But for this example, not passing hook yaml is fairly unexpected from a user perspective. And easy'ish for users to mitigate against, if they actually needed to (judged to be unexpected), when they upgrade to Helm 4.

But forcing probably all users to adapt post-renderer format is a significant breaking change. Certainly, e.g. yamlscript could be used to "intercept" the map, and invoke a sub-command per-document. But this is still an "unexpected" (IMHO) change for the majority of post-renderer users.

For this PR, IMHO we should (must) keep the scope: to passing hook yaml to the post-renderer only. If we want to change the post-renderer format, we would need further discussion. And make a separate change (that does account for varying user scenarios).



```
file1.yaml: |
   <content>
_helpers.tpl:
  <content>
```

2025-05-19 16:57 UTC, gjenkins8 requested changes
https://github.com/helm/helm/pull/13154/files#r2096150476

2025-05-20 21:30 UTC, carloslima commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
I understand this is a significant change and that's why I called it out clearly in the PR description, added comments in the code, and initially gated it behind a flag. 🙂

Let me try a different approach. I need a way to recover the filenames after they've been processed by the post-render step, but without relying on YAML comments, since most YAML parsers don't preserve them.

2025-05-22 17:27 UTC, gjenkins8 commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
> I understand this is a significant change and that's why I called it out clearly in the PR description, added comments in the code, and initially gated it behind a flag.

Apologies. I missed the format change originally (too much multi-tasking sorry)

2025-05-27 20:23 UTC, gjenkins8 commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
>I understand this is a significant change and that's why I called it out clearly in the PR description, added comments in the code, and initially gated it behind a flag. 🙂

Apologies, too much multi-tasking here. My review was very round-a-bout.

But I do still think a flag is not warranted -- too many tools will expect the document-based yaml stream. *As well as* being able to process hook yaml. So IMHO we are still on the right path.

> Let me try a different approach. I need a way to recover the filenames after they've been processed by the post-render step, but without relying on YAML comments, since most YAML parsers don't preserve them.

This is the behavior for non-hook Kubernetes YAML today? The post renderer will drop the filename comments.. Is it necessary for Helm to recover these?

If it is necessary, I think we can assume Kubernetes' API object type and name (the tuple of: `(GroupVersion, Kind, Namespace, Name)`) is unique. A map of this tuple to the filename, would then allow mapping back to the filename post-rendering I think. New or mutated objects that don't match, wouldn't map back to a "file". But that is expected I think.

2025-05-28 20:31 UTC, carloslima commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
I think I have a workable solution. I will publish it soon :hourglass_flowing_sand:

2025-05-29 11:11 UTC, carloslima commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
I gotta run out now. I'll fix this PR later but the changes are here: https://github.com/carloslima/helm/pull/1/files

Tests are long but the actual changes are relatively small. Can you take a look?

2025-05-29 15:47 UTC, carloslima commented on pkg/postrender/exec.go
> +	originalManifests, err := yaml.Marshal(renderedFiles)
@gjenkins8 I've updated the MR. Please check when you have time :)

2025-06-05 16:40 UTC, robertsirc commented
@gjenkins8 you are requesting changes on this PR is this still active or have your changes been met?

2025-06-08 21:37 UTC, dwalters commented
I clearly missed a lot of changes here since the original PR!   I rebased a similar change in #30778 against v3 earlier today, but it's basically the same approach that's now being taken here, and this looks fine to me.  I'd suggest this be the default behavior in helm v4.

For v3, I do prefer opting in to the new behavior via an annotation instead of having to provide a CLI flag.

2025-06-08 23:02 UTC, carloslima commented
@dwalters I've been waiting on a review for this PR for about a year now. It’s clear this isn’t a top priority :-)

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +	FilenameAnnotation = "helm-postrender-filename"
Can we make this private? Unless there is a good reason to make it public, and so part of Helm's SDK public interface, private is preferred. As that allows it to remain an implementation detail, and able to be changed in the future. If public, it becomes part of Helm's public SDK interface, and non-amendable to changes/non-backwards compatible updates in the future.

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +func AnnotateAndMerge(files map[string]string) (string, error) {
Similar to above, can we make this private(?)

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +func SplitAndDeannotate(postrendered string) (map[string]string, error) {
Similar to above, can we make this private(?)

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +		return nil, fmt.Errorf("re-parsing merged buffer: %w", err)
nit: If the post renderer produces invalid yaml, the user will get a somewhat (IMHO) confusing error like:
```
error while parsing post rendered files: re-parsing merged buffer: MalformedYAMLError: yaml: line 3: could not find expected ':'
```

(<https://go.dev/play/p/gT-Z-yLmDvQ>) 

The user does not (and should not) know what the "merged buffer" is. I think we should align this error chain message closer to what will be helpful to the user e.g. something like:
```
error while parsing post renderer output: error parsing YAML: MalformedYAMLError: yaml: line 3: could not find expected ':'
```

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +		if merged, err = AnnotateAndMerge(files); err != nil {
style nit:
```suggestion
		merged, err := AnnotateAndMerge(files)
		if err != nil {
```

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +		if files, err = SplitAndDeannotate(postRendered.String()); err != nil {
style nit:
```suggestion
		manifests, err := SplitAndDeannotate(postRendered.String())
		if err != nil {
```

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +			return hs, b, notes, fmt.Errorf("error while parsing post rendered files: %w", err)
nit: the post renderer doesn't handle "files". It streams an output:
```suggestion
			return hs, b, notes, fmt.Errorf("error while parsing post renderer output: %w", err)
```

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +	FilenameAnnotation = "helm-postrender-filename"
We should probably name this annotation more canonically. I think something like:
```
postrenderer.helm.sh/postrender-filename
```

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +func SplitAndDeannotate(postrendered string) (map[string]string, error) {
This function does two distinct things:
1. Parses the yaml string
2. Reconstructs the filename -> yaml string map

I wonder if it would be better to split these disinct things into seperate functions? In that it would be easier to test and reason about?

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +		manifestsByFilename[fname] = append(manifestsByFilename[fname], manifest)
If the post renderer contains documents with duplicate annotations, we will overwrite the previous documents here?

2025-06-14 17:57 UTC, gjenkins8 commented on pkg/action/action.go
> +func AnnotateAndMerge(files map[string]string) (string, error) {
This function does three distinct things:

1. Parses the yaml in filename -> yaml doc map into kyaml types
2. Loops each manifest in the kyaml type and adds the annotation
3. finally, writes the array of manifests into a yaml doc

I wonder if it would be better to split these distinct things into separate functions/functionality? For ease of testing and readability?

2025-06-14 17:58 UTC, gjenkins8 requested changes
https://github.com/helm/helm/pull/13154/files#r2147057212 is a bug we need to fix I think

2025-06-14 18:03 UTC, gjenkins8 commented
> For v3, I do prefer opting in to the new behavior via an annotation instead of having to provide a CLI flag.

Fwiw, for v3 is largely closed for new functionality, we have moved to bugfixes/maintenance only (short reason: we have limited time to focus on Helm 4, and back porting changes to Helm 3 is time consuming and diverts limited resources to getting changes built for Helm 4)

2025-06-15 11:42 UTC, carloslima commented on pkg/action/action.go
> +	FilenameAnnotation = "helm-postrender-filename"
Done

2025-06-15 11:42 UTC, carloslima commented on pkg/action/action.go
> +func SplitAndDeannotate(postrendered string) (map[string]string, error) {
done

2025-06-15 11:42 UTC, carloslima commented on pkg/action/action.go
> +func AnnotateAndMerge(files map[string]string) (string, error) {
done

2025-06-15 11:42 UTC, carloslima commented on pkg/action/action.go
> +		return nil, fmt.Errorf("re-parsing merged buffer: %w", err)
done

2025-06-15 11:42 UTC, carloslima commented on pkg/action/action.go
> +		if merged, err = AnnotateAndMerge(files); err != nil {
done

2025-06-15 11:43 UTC, carloslima commented on pkg/action/action.go
> +		if files, err = SplitAndDeannotate(postRendered.String()); err != nil {
done

2025-06-15 11:43 UTC, carloslima commented on pkg/action/action.go
> +			return hs, b, notes, fmt.Errorf("error while parsing post rendered files: %w", err)
done

2025-06-15 11:49 UTC, carloslima commented on pkg/action/action.go
> +		manifestsByFilename[fname] = append(manifestsByFilename[fname], manifest)
If I understood your question correctly, no, they will be combined. See test case here: https://github.com/helm/helm/pull/13154/files#diff-52b738d4936c2effb6743132c20ba5d13a6be01903130a3fe78f6a7754f8c17dR617-R650

2025-06-15 11:54 UTC, carloslima commented on pkg/action/action.go
> +func SplitAndDeannotate(postrendered string) (map[string]string, error) {
The YAML parsing is already handled by a single function call followed by an if err check. I don’t see a way to make it any simpler. If you have any suggestions that could improve readability or testability, let me know :-)

2025-06-15 11:58 UTC, carloslima commented on pkg/action/action.go
> +func AnnotateAndMerge(files map[string]string) (string, error) {
Same here: YAML parsing and dumping are already handled by a single function call followed by an `if err` check. Anything I can think of would only make it noisier. If you have a suggestion, I’d be happy to hear it :)

2025-06-15 11:59 UTC, carloslima commented on pkg/action/action.go
> +	FilenameAnnotation = "helm-postrender-filename"
done

2025-06-15 12:05 UTC, carloslima commented
> https://github.com/helm/helm/pull/13154/files#r2147057212 is a bug we need to fix I think
> 
> otherwise, most of my comments are style/refactoring type concerns. logic here I think is the way to go. thanks for the updates.

Thanks for the review. I made all the changes except for the three cases I mentioned above. They are in separate commits to make review easier, but I’ll squash them if you're happy with the changes.

2025-06-28 14:24 UTC, gjenkins8 approved these changes, later dismissed
nice, thanks for the updates. Agree https://github.com/helm/helm/pull/13154/files#r2147057212 is actually handled. 

LGTM, just nee to resolve the go.mod conflict and I can reapprove (will require one more maintainer approval)

2025-06-28 14:28 UTC, gjenkins8 commented
We should also probably document the `postrenderer.helm.sh/postrender-filename` annotation. Something along the lines like: setting this annotation in the post-renderer will cause Helm to associate that "filename" with the YAML doc. https://helm.sh/docs/topics/advanced/#post-rendering

I've added the `docs-needed` label to track.

2025-06-28 15:11 UTC, carloslima commented
> nice, thanks for the updates. Agree https://github.com/helm/helm/pull/13154/files#r2147057212 is actually handled.
> 
> LGTM, just nee to resolve the go.mod conflict and I can reapprove (will require one more maintainer approval)

Done. I've rebased it on top of latest main :)

2025-06-28 16:01 UTC, carloslima commented
> We should also probably document the `postrenderer.helm.sh/postrender-filename` annotation. Something along the lines like: setting this annotation in the post-renderer will cause Helm to associate that "filename" with the YAML doc. https://helm.sh/docs/topics/advanced/#post-rendering
> 
> I've added the `docs-needed` label to track.

Is this enough?

https://github.com/helm/helm-www/pull/1734

2025-07-03 00:41 UTC, gjenkins8 approved these changes

2025-07-10 16:30 UTC, scottrigby approved these changes
nice work 👏 Tested manually as well. LGTM

2025-07-10 16:31 UTC, merged

2025-09-10 10:40 UTC, Anany-k commented
Will this be included in a release for helm v3 ?

2025-09-10 10:46 UTC, benoittgt commented
@Anany-k I don’t think so, based on https://github.com/helm/helm/pull/13154#issuecomment-2972932742