build: set kube version via `debug.BuildInfo`
helm/helm pull request #13180
Opened 2024-07-16 05:57 UTC by branchvincent

**What this PR does / why we need it**:

This is inspired by #13174, where Homebrew built `helm` outside of the Makefile and accidentally did not set the correct ldflags for the `k8sVersion` variables (which were defaulted to `1.20` instead of `1.30`)

Instead, this uses `runtime/debug`'s [`ReadBuildInfo`](https://pkg.go.dev/runtime/debug#ReadBuildInfo) to automatically extract the correct `k8s.io/client-go` version, regardless if the Makefile was used (for example, using `go install helm.sh/helm/v3/cmd/helm@latest`). It also adds a similar fallback for the git metadata ldflags using 1.18's [`BuildSetting`](https://pkg.go.dev/runtime/debug#BuildSetting) (but respects the variables if they are already set):

```console
$ go build ./cmd/helm && ./helm version
version.BuildInfo{Version:"v3.15", GitCommit:"7af094d606aff055c1eb938775b6fd260e637158", GitTreeState:"clean", GoVersion:"go1.22.5"}
```

**Special notes for your reviewer**:

This does introduce a lot of test golden changes since tests now also run with the correct `k8s.io/client-go` version

**If applicable**:

- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-08-07 19:49 UTC, robertsirc commented
This PR is a bit in depth could you attend the developer call on Thursdays at 9:30-10:00 Pacific ([meeting details](https://github.com/helm/community/blob/master/communication.md#meetings))??

2024-09-16 16:58 UTC, gjenkins8 reviewed
Thanks for the PR. I do think this is a worthy change. TIL about https://pkg.go.dev/runtime/debug#ReadBuildInfo . Removing these ldflags and Makefile logic from Helm's certainly seems an improvement.

And in particular, Helm is often used as an SDK. And SDK users (presumably) find out the hard way they need to set these ldflags in their build system.

The only concerns I can think of are a) accuracy. I assume `debug.ReadBuildInfo()` can be accurate here. But probably just need to do some diligence to confirm, and b) performance. As long as reading this info does have some significant latency (I can't imagine it does), I can't imagine Helm wouldn't want to read this info at runtime.

2025-02-09 00:31 UTC, gjenkins8 requested changes
Git commit changes I think need more thought. If we move them to a seperate PR, can approve the Kubernetes client-go version changes

2025-02-09 00:31 UTC, gjenkins8 commented on internal/version/version.go
> +	if gitCommit != "" || gitTreeState != "" {
Can we make a seperate PR for chaning the git state please? The Kubernetes changes look good to merge for me.

Here, I think we should take `gitCommit` from `vcs.revision`. But to keep the seperate changes independant, think worth creating separate PRs.

2025-08-23 15:23 UTC, branchv commented on internal/version/version.go
> +	if gitCommit != "" || gitTreeState != "" {
No problem, backed this out

2025-09-16 20:10 UTC, gjenkins8 commented
Note: I copied and reworked this PR into: https://github.com/helm/helm/pull/31296 (which has some differences in implementation, which I think are worthwhile). Also to move this forward and simplify Helm's build.

2025-09-26 19:58 UTC, branchv commented
Thanks for pushing this forward @gjenkins8

2025-09-26 19:58 UTC, closed without merging

2025-09-26 23:47 UTC, TerryHowe commented
Whoops closed

2025-09-27 00:03 UTC, branchvincent commented
Yes this was superseded by #31296