feat(helm): add --namespace-labels flag to install and upgrade
helm/helm pull request #13200
Opened 2024-07-25 01:09 UTC by caruccio

It creates the new namespace with givem values to flag '--namespace-labels'. If not if provider, the default 'name=<namespace-name>' is used.

**What this PR does / why we need it**:

New namespaces may need to be created with a custom set of labels. This PR adds this capability.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-07-25 01:13 UTC, caruccio commented
I was just wondering if it's a good idea to also add the flag `--namespace-annotations`?

2024-08-07 19:37 UTC, robertsirc commented
You are going to need to fix your DCO. And shouldn't there be test for this change?

2024-08-07 20:11 UTC, caruccio commented
Just added my signature. Sorry for that.

I didn't included tests since `--create-namespace` also doesn't have it.

2024-09-06 19:46 UTC, robertsirc commented
I understand your stance on the tests, I am sure a maintainer can weigh in on this. My suggestion is to have both inline documentation and documentation in the docs site on what this enhancement means. If you look at `cmd/helm/upgrade.go` there is a variable called `upgradeDesc` it makes sense to add that there.

2024-10-15 00:11 UTC, gjenkins8 requested changes
I echo @robertsirc comment that we would want tests to ensure this feature remain unbroken in the future. It is unfortunate there are not tests for the `--create-namespace` currently. That is a past mistake that shouldn't be replicated.

2024-10-15 00:11 UTC, gjenkins8 commented on cmd/helm/upgrade.go
> +	f.StringToStringVarP(&namespaceLabels, "namespace-labels", "L", nil, "Labels that would be added to created namespace. Should be divided by comma. If --create-namespace is not set, this is ignored.
```suggestion
	f.StringToStringVar(&namespaceLabels, "namespace-labels", nil, "labels to add to the created namespace. Comma separated key=value pairs. Ignored if --create-namespace is not set (default 'name=<namespace-name>'")
```

I would propose no "shorthand" flag here. IMHO, shorthand flags are useful to save typing for commonly used flags. I don't think a `--namespace-labels` flag meets that criteria.

Also some suggestions for the verbiage.

2024-10-15 00:11 UTC, gjenkins8 commented on cmd/helm/install.go
> +	f.StringToStringVarP(&client.NamespaceLabels, "namespace-labels", "L", nil, "Labels that would be added to created namespace. Should be divided by comma. If --create-namespace is not set, this is ig
ditto the suggestion on `upgrade.go`

2025-09-22 00:23 UTC, closed without merging