fix: Add binary plugin url support
helm/helm pull request #13225
Opened 2024-08-01 15:34 UTC by idsulik

closes [13221](https://github.com/helm/helm/issues/13221)

**What this PR does / why we need it**:
A `tar.gz` file can have the MIME type `application/octet-stream`, so I added support for this case

**If applicable**:
- [N] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [Y] this PR contains unit tests
- [N] this PR has been tested for backwards compatibility

2024-08-21 16:42 UTC, idsulik commented on pkg/plugin/installer/installer.go
> +			if strings.HasSuffix(source, ".tar.gz") && contentType == "application/octet-stream" {
pushed the func refactoring

2024-09-06 03:40 UTC, idsulik commented
Hi @mattfarina ,

I noticed that this pull request has been pending for a while. Is there anything more needed from my side? Please let me know if there are any updates or additional changes required.

Thanks!

2024-09-16 00:23 UTC, gjenkins8 approved these changes
LGTMe. Thanks for the update. Will raise for maintainer review.

2024-10-25 19:24 UTC, robertsirc commented
Hello @idsulik thank you for your pull request. I pulled your branch down and built it. When I ran the test I got the following error:
```
=== RUN   TestIsRemoteHTTPArchive
    installer_test.go:46: Expected "http://127.0.0.1:64831/plugins/fake-plugin-0.0.1.tar.gz" to be a valid archive URL
--- FAIL: TestIsRemoteHTTPArchive (0.01s)
```

2024-10-25 20:05 UTC, idsulik commented
> Hello @idsulik thank you for your pull request. I pulled your branch down and built it. When I ran the test I got the following error:
> 
> ```
> === RUN   TestIsRemoteHTTPArchive
>     installer_test.go:46: Expected "http://127.0.0.1:64831/plugins/fake-plugin-0.0.1.tar.gz" to be a valid archive URL
> --- FAIL: TestIsRemoteHTTPArchive (0.01s)
> ```

Hi @robertsirc, I've just checked and it works:
```
=== RUN   TestIsRemoteHTTPArchive
--- PASS: TestIsRemoteHTTPArchive (0.00s)
PASS
```

2024-10-29 18:05 UTC, idsulik commented
Hello @mattfarina, just a gentle reminder about this PR created months ago. If possible, could it be reviewed before the next Helm release? I’d appreciate any feedback to help get it ready in time. Thank you!

2024-11-11 16:43 UTC, gjenkins8 commented on pkg/plugin/installer/installer_test.go
> +		t.Errorf("Expected %q to be a valid archive URL", source)
I was trying to spot why @robertsirc got an error, and I noticed:

```suggestion
		t.Errorf("Expected %q to be a valid archive URL", binarySource)
```

2024-11-11 16:47 UTC, gjenkins8 requested changes

2024-11-11 18:32 UTC, idsulik commented on pkg/plugin/installer/http_installer_test.go
> +			if strings.HasSuffix(r.URL.Path, ext) {
@gjenkins8 good catch, pushed a fix. Thank you!

2024-11-14 22:37 UTC, NickJosevski commented
@mattfarina could you please have a look at this PR and advise if the supplied tests are adequate?

2024-11-14 22:58 UTC, APErebus commented
I ran the new test locally (`go version go1.23.0 windows/amd64`) and the test pass successfully
```
=== RUN   TestIsRemoteHTTPArchive
--- PASS: TestIsRemoteHTTPArchive (0.01s)
PASS
```

2024-11-14 23:26 UTC, MissedTheMark commented
I also ran that test locally (`go version go1.23.1 darwin/arm64`) and it passed:
```
=== RUN   TestIsRemoteHTTPArchive
--- PASS: TestIsRemoteHTTPArchive (0.00s)
PASS
```

2024-11-20 10:43 UTC, banjoh approved these changes

2024-11-21 11:52 UTC, idsulik commented on pkg/plugin/installer/installer.go
> +	res, err := http.Head(url)
@banjoh I've just extracted the login into separate methods. The http.Head was implemented here https://github.com/helm/helm/pull/8752/files#diff-cd876a43f3b2cb4b6041a9cd099e0048e86fb5e722d1db608eefda164e8fefecR98

2024-12-02 13:52 UTC, gjenkins8 submitted a review, later dismissed

2024-12-13 05:08 UTC, idsulik commented
@gjenkins8 hi! Created backport PR https://github.com/helm/helm/pull/13530

2024-12-27 20:33 UTC, scottrigby commented
Do you have an example of a helm plugin tarball binary this PR works with? Or perhaps there's a different way to test this? Thanks

```console
$ ./bin/helm --debug plugin install https://github.com/databus23/helm-diff/releases/latest/download/helm-diff-macos-amd64.tgz

Error: extracting files from archive: open /Users/r6by/Library/Caches/helm/plugins/https-github.com-databus23-helm-diff-releases-latest-download-helm-diff-macos-amd64.tgz/diff/LICENSE: no such file or directory
helm.go:86: 2024-12-26 12:47:43.188275 -0500 EST m=+0.946240535 [debug] open /Users/r6by/Library/Caches/helm/plugins/https-github.com-databus23-helm-diff-releases-latest-download-helm-diff-macos-amd64.tgz/diff/LICENSE: no such file or directory
extracting files from archive
helm.sh/helm/v3/pkg/plugin/installer.(*HTTPInstaller).Install
	helm.sh/helm/v3/pkg/plugin/installer/http_installer.go:135
helm.sh/helm/v3/pkg/plugin/installer.Install
	helm.sh/helm/v3/pkg/plugin/installer/installer.go:55
main.(*pluginInstallOptions).run
	helm.sh/helm/v3/cmd/helm/plugin_install.go:78
main.newPluginInstallCmd.func3
	helm.sh/helm/v3/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
	runtime/proc.go:272
runtime.goexit
	runtime/asm_amd64.s:1700
```

Similar when loading from a file
```console
$ ./bin/helm --debug plugin install helm-diff-macos-amd64.tgz

Error: expected plugin to be a folder
helm.go:86: 2024-12-26 12:47:01.100353 -0500 EST m=+0.040190389 [debug] expected plugin to be a folder
helm.sh/helm/v3/pkg/plugin/installer.init
	<autogenerated>:1
runtime.doInit1
	runtime/proc.go:7290
runtime.doInit
	runtime/proc.go:7257
runtime.main
	runtime/proc.go:254
runtime.goexit
	runtime/asm_amd64.s:1700
```

2025-02-11 01:10 UTC, sabre1041 commented
Running into challenges testing the PR

```
helm.go:86: 2025-02-10 18:09:01.261162 -0600 CST m=+1.079038876 [debug] mkdir /Users/ablock/Library/Caches/helm/plugins/http-10.1.196.125-8080-helm-sigstore.tar.gz: file exists
extracting files from archive
helm.sh/helm/v3/pkg/plugin/installer.(*HTTPInstaller).Install
        helm.sh/helm/v3/pkg/plugin/installer/http_installer.go:135
helm.sh/helm/v3/pkg/plugin/installer.Install
        helm.sh/helm/v3/pkg/plugin/installer/installer.go:55
main.(*pluginInstallOptions).run
        helm.sh/helm/v3/cmd/helm/plugin_install.go:78
main.newPluginInstallCmd.func3
        helm.sh/helm/v3/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_arm64.s:1222
```

2025-02-11 11:11 UTC, idsulik commented
@scottrigby hi! you're passing the link to archive with the plugin's binary file, but you should pass a link to archive with helm plugin source code

2025-03-10 01:45 UTC, gjenkins8 commented
@idsulik -- can you edit the PR's summary to add an example for a plugin install this PR fixes (I'm sure I validated this a while back, but I forget)

2025-03-10 05:17 UTC, idsulik commented
@gjenkins8 I have no example, I pushed the fix half a year ago

2025-04-16 19:49 UTC, scottrigby commented
Closing this PR because the author has clarified in Slack they do not have the energy to contribute to Helm at present, but maybe will again in the future: https://kubernetes.slack.com/archives/C51E88VDG/p1744777892226199?thread_ts=1743860225.430069&cid=C51E88VDG

2025-04-16 19:49 UTC, closed without merging

2025-10-18 12:06 UTC, idsulik commented
Opened new PR with updates https://github.com/helm/helm/pull/31405