Rename formatChartname to formatChartName
helm/helm pull request #13310
Opened 2024-09-08 17:22 UTC by myeunee

Rename formatChartname to formatChartName for consistency

**What this PR does / why we need it**:
This PR renames the variable `formatChartname` to `formatChartName` to maintain naming consistency across the codebase. Consistent naming conventions improve code readability and maintainability.

**Special notes for your reviewer**:
No additional dependencies or breaking changes are introduced by this PR. This is a simple renaming for consistency.

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-09-08 23:52 UTC, yxxhero commented
@myeunee this is a beaking change. it requires users to update their chart.

2024-09-09 05:22 UTC, myeunee commented
> @myeunee this is a beaking change. it requires users to update their chart.

Sorry. I updated the description.

2024-09-09 12:58 UTC, robertsirc approved these changes
This is a private function. LGTM.

2024-09-09 15:18 UTC, myeunee commented
Hi, I see that there are three workflows awaiting approval for this PR. If possible, I would appreciate it if the approvals could be reviewed soon. Thank you so much for your time and attention! ☺️

2024-09-09 16:48 UTC, robertsirc commented
Best way to get the conversation started with your PR is to attend the developer [meeting](https://zoom.us/j/696660622) Thursday at 9:30 AM PST

2024-09-09 23:36 UTC, yxxhero commented
> @myeunee this is a beaking change. it requires users to update their chart.

oh. sorry. I miss something.

2024-09-13 19:42 UTC, mattfarina requested changes

2024-09-13 19:42 UTC, mattfarina commented on cmd/helm/history.go
> +func formatChartName(c *chart.Chart) string {
You missed occurrences of this name change. Can you please get all of them.

2024-09-30 16:24 UTC, gjenkins8 commented
Thanks @myeunee for the contrib.

https://github.com/helm/helm/pull/13349 is the fixed version of this PR (Thanks @TerryHowe). Want to close in favor of this?

2024-10-01 18:09 UTC, closed without merging

2024-10-01 18:10 UTC, mattfarina commented
Note, the PR that was merged instead of this one preserved the commit and author from the work here. It fixed the issue on top of that work.