feat: Add --log functionality for additional commands and resources
helm/helm pull request #13358
Opened 2024-10-01 07:16 UTC by cgetzen

**What this PR does / why we need it**:

- Jobs with the `"helm.sh/hook": "test"` annotation will now work with `helm test --logs`. This previously caused helm to error due to searching for a pod with the same name as the job.
- Upgrades that have Pods or Jobs that contain any annotation (e.g. `"helm.sh/hook": post-install`) can now run with `--logs` to print the logs post-upgrade.

This is important because the cause of the hook related upgrade failures is not possible to determine with the helm output, and requires investigating kubernetes job logs.

**Special notes for your reviewer**:

I'm unsure if this code is possible to unit test because it relies on the output of annotated pods. If there is an integration test framework for helm, I will add tests to that. I was able to manually test with the following helm single-file chart:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: test
        image: ubuntu
        command: ["echo",  "hello world"]
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
      - name: test
        image: ubuntu
        command: ["echo",  "I'm a test!"]
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: backwards-compatible
  annotations:
    "helm.sh/hook": test
spec:
  containers:
  - name: test
    image: ubuntu
    command: ["echo",  "I'm a test pod!"]
  restartPolicy: Never
```

**If applicable**:
- [x] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2024-10-02 14:55 UTC, robertsirc requested changes
The build-test and golinter actions are failing.

2024-10-02 14:56 UTC, robertsirc commented
Hello thank you for your PR. There are some issues with the GH actions could you please address that so we can review?

2024-10-02 18:24 UTC, cgetzen commented
Hi @robertsirc, the latest commit looks successful on my end. If there's any links to failures I can take a look!

2024-10-02 19:42 UTC, robertsirc commented
We appreciate your PR. Your account is coming up `Unverified` could you correct that?

2024-11-25 18:51 UTC, cgetzen commented
@robertsirc is there anything else that is needed to get a review? This PR does a few things, and I'd be happy to strip it down to do a single thing if that helps the review process -- I'm mostly interested in getting log output for helm upgrades.

2025-02-21 17:42 UTC, gjenkins8 requested changes

2025-10-01 00:25 UTC, closed without merging