fix(helm): No more retry if jobs failed beyond BackoffLimit
helm/helm pull request #13364
Opened 2024-10-02 10:40 UTC by dayeguilaiye

**What this PR does / why we need it**:
This PR closes #13317 
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-10-02 14:50 UTC, robertsirc requested changes

2024-10-02 14:51 UTC, robertsirc commented on pkg/kube/ready.go
> +	"github.com/pkg/errors"
Thank you for your PR. I pulled it down to review and there is one initial issue we need cleared up.

2024-10-08 04:40 UTC, kalvarahul approved these changes

2024-10-09 01:17 UTC, dayeguilaiye commented on pkg/kube/ready.go
> +	"github.com/pkg/errors"
Thanks, I fixed this next commit.

2024-10-09 08:31 UTC, dayeguilaiye commented
@robertsirc I fixed the lint problem, could you review again?

2024-10-09 19:37 UTC, robertsirc commented
Hi @dayeguilaiye i pulled this down and ran all the unit test, and a few of my smoke test. What I think we need is a unit test around this functionality. Is there a way we can add in some test coverage?

2024-10-10 02:07 UTC, dayeguilaiye commented
@robertsirc I found that there is no any test for `wait.go`, and test for `wait` may waste so much time when doing unit test so I didn't add any test. 

But I found that there are some test for `ready.go`, and I should test that `when Failed > BackoffLimit, it should return an ErrNotRetryError`, I'll add it. 

Thanks for your reviewing and advise.

2024-10-10 02:33 UTC, dayeguilaiye commented
@robertsirc I've added it as I said. Could you review again?

2024-11-01 17:09 UTC, robertsirc commented
Also you might want to look at latest I did a bit of work in writing up more unit test for coverage.

2024-11-07 02:12 UTC, TerryHowe commented on pkg/kube/wait.go
> +	if errors.Is(err, ErrNoRetryError) {
Bit of a nit, but seems like this should be above the if statement above

2024-11-07 02:12 UTC, TerryHowe commented on pkg/kube/wait.go
> +		w.log("The error is a NoRetryError, Retryable err? %t", false)
Not much value in this log to me

2024-11-07 02:12 UTC, TerryHowe commented on pkg/kube/wait.go
> +var ErrNoRetryError = errors.New("this error will stop retry")
Maybe something along the lines of "retry limit exceeded waiting on resource"

2024-11-17 06:37 UTC, gzb1128 commented
I want to fix this issue, if @dayeguilaiye is not taking progress, may I make a new PR to fix it?

2025-04-30 01:56 UTC, dayeguilaiye commented
> I want to fix this issue, if @dayeguilaiye is not taking progress, may I make a new PR to fix it?

@gzb1128  I haven't had much time to work on this PR lately. If you're interested, feel free to submit a PR to address the issue. If you confirm that you will fix it, I can close this PR for now.

2025-09-01 03:50 UTC, closed without merging