fix(lint): Extend --skip-schema-validation for lint command
helm/helm pull request #13414
Opened 2024-10-30 16:17 UTC by idsulik

closes #13413 

**What this PR does / why we need it**:
Added full support of `--skip-schema-validation` for the `lint` command

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-11-06 10:49 UTC, idsulik commented
@mattfarina hi! Could you please check the PR?

2024-11-22 14:26 UTC, Konstanktin commented
Any updates here? We urgently need this fix

2024-11-22 14:33 UTC, idsulik commented
@banjoh hi! Could you please check it?

2024-12-13 05:13 UTC, idsulik commented
Hello @mattfarina, @banjoh , just a gentle reminder about this PR created months ago. If possible, could it be reviewed before the next Helm release? I’d appreciate any feedback to help get it ready in time. Thank you!

2024-12-16 01:41 UTC, sabre1041 submitted a review, later dismissed
LGTM

2024-12-16 07:42 UTC, banjoh approved these changes
LGTM

2024-12-22 19:59 UTC, joebowbeer commented
@scottrigby finishing touch for `--skip-schema-validation`

2025-01-14 09:06 UTC, armingerten commented
Hey 👋 
Any news on this? :)

2025-01-14 09:35 UTC, idsulik commented
@armingerten hi! Unfortunately, it takes several months to review && merge changes. some of my PRs have been waiting almost a year..  
@mattfarina hi! are there any rules on how you review PR?

2025-01-15 11:14 UTC, dig-whois commented
We are also dealing with this issue, is there any plans on merging this?

2025-01-25 22:30 UTC, gjenkins8 requested changes

2025-01-25 22:30 UTC, gjenkins8 commented on pkg/lint/rules/values.go
> +		res := chartutil.ValidateAgainstSingleSchema(coalescedValues, schema)
nit:
```suggestion
		return chartutil.ValidateAgainstSingleSchema(coalescedValues, schema)
```

2025-01-25 22:30 UTC, gjenkins8 commented on pkg/lint/rules/values.go
> +func ValuesWithOverridesWithSkipSchemaValidation(linter *support.Linter, values map[string]interface{}, skipSchemaValidation bool) {
This function duplicates the lint rules in `ValuesWithOverrides`, and as such these are going to be run twice, and report issues twice to the user

That said, now we are targeting Helm 4, we don't need to maintain backward compatiblity we function signatures, and can simply add the new `skipSchemaValidation` parameter to `ValuesWithOverrides`

(this will preclude backporting this to Helm 3 in its current form)

2025-09-10 09:32 UTC, armingerten commented
#not-stale

2025-09-10 13:30 UTC, benoittgt commented
I've opened a new PR to close this one https://github.com/helm/helm/pull/31275

2025-09-10 18:52 UTC, closed without merging