Add --take-ownership flag for install and upgrade commands
helm/helm pull request #13439
Opened 2024-11-12 12:12 UTC by mayankshah1607

**What this PR does / why we need it**:

`TakeOwnership` option was added to the Install and Upgrade options in https://github.com/helm/helm/pull/13130. This PR allows setting this option on the CLI commands using a new `--take-ownership` flag

**Special notes for your reviewer**:

xref: https://github.com/helm/helm/issues/10304#issuecomment-2468532665

**If applicable**:
- [x] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-11-12 13:46 UTC, banjoh approved these changes

2024-11-13 04:58 UTC, unclok approved these changes

2024-11-19 04:31 UTC, gjenkins8 reviewed
very minor fix up of the help text please

2024-11-19 04:31 UTC, gjenkins8 commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "if set, install will ignore the check for helm annotations and take ownership of the existing resources.")
```suggestion
	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "if set, install will ignore the check for helm annotations and take ownership of the existing resources")
```

minor consistency thing pls

2024-11-19 04:31 UTC, gjenkins8 commented on cmd/helm/upgrade.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "if set, upgrade will ignore the check for helm annotations and take ownership of the existing resources.")
```suggestion
	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "if set, upgrade will ignore the check for helm annotations and take ownership of the existing resources")
```

2024-11-19 04:33 UTC, mayankshah1607 commented on cmd/helm/install.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "if set, install will ignore the check for helm annotations and take ownership of the existing resources.")
updated, thank you

2024-11-19 04:33 UTC, mayankshah1607 commented on cmd/helm/upgrade.go
> +	f.BoolVar(&client.TakeOwnership, "take-ownership", false, "if set, upgrade will ignore the check for helm annotations and take ownership of the existing resources.")
updated, thank you

2024-11-19 23:19 UTC, gjenkins8 approved these changes, later dismissed

2024-12-09 16:06 UTC, banjoh commented
@scottrigby / @joejulian are you able to take a look at this one?

2024-12-10 17:51 UTC, banjoh commented
@mayankshah1607 since this PR needs to merged into v3, can you please create a new PR to [dev-v3 branch](https://github.com/helm/helm/tree/dev-v3)?

2024-12-11 05:33 UTC, scottrigby reviewed
This PR looks good, however with manual testing this doesn't seem to be working for upgrade, only install. I'm not sure why this would be the case, since it should work according to #12876

Can someone else reproduce this?

```sh
# create example chart
helm create foo

# create matching plain template files
helm template foo foo --output-dir foo-template
<remove all helm labels>
<remove tests dir>

# install plan manifests without helm labels or metadata
kubectl apply -f foo-template/foo/templates/

# it makes sense that this wouldn't work
$ helm upgrade foo foo/ --take-ownership
Error: UPGRADE FAILED: "foo" has no deployed releases

# from this PR it seems this should work, but doesn't
$ helm upgrade --install foo foo/ --take-ownership
Error: Unable to continue with install: ServiceAccount "foo" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "foo"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

# this works
$ helm install foo foo/ --take-ownership
<expected output>
$ helm ls  
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART    	APP VERSION
foo 	default  	1       	2024-12-11 00:21:59.727628 -0500 EST	deployed	foo-0.1.0	1.16.0  
```

PS I'm also updating the description to point to the correct PR (#12876 not #13130), and adding closing keywords to related issues (#10304 and #2730).

2024-12-11 05:55 UTC, scottrigby commented
For `upgrade --install` to work, I believe we also need to add this:
```diff
diff --git a/cmd/helm/upgrade.go b/cmd/helm/upgrade.go
index 1fe793a92..75788459b 100644
--- a/cmd/helm/upgrade.go
+++ b/cmd/helm/upgrade.go
@@ -151,6 +151,7 @@ func newUpgradeCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
                                        instClient.Labels = client.Labels
                                        instClient.EnableDNS = client.EnableDNS
                                        instClient.HideSecret = client.HideSecret
+                                       instClient.TakeOwnership = client.TakeOwnership
 
                                        if isReleaseUninstalled(versions) {
                                                instClient.Replace = true
```

2024-12-11 05:59 UTC, scottrigby requested changes
For `upgrade --install` to work, we also need to add this:
```diff
diff --git a/cmd/helm/upgrade.go b/cmd/helm/upgrade.go
index 1fe793a92..75788459b 100644
--- a/cmd/helm/upgrade.go
+++ b/cmd/helm/upgrade.go
@@ -151,6 +151,7 @@ func newUpgradeCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
                                        instClient.Labels = client.Labels
                                        instClient.EnableDNS = client.EnableDNS
                                        instClient.HideSecret = client.HideSecret
+                                       instClient.TakeOwnership = client.TakeOwnership
 
                                        if isReleaseUninstalled(versions) {
                                                instClient.Replace = true
```

2024-12-11 15:27 UTC, mayankshah1607 commented
Thanks @scottrigby , I've updated the PR

2024-12-11 15:28 UTC, mayankshah1607 commented
> @mayankshah1607 since this PR needs to merged into v3, can you please create a new PR to [dev-v3 branch](https://github.com/helm/helm/tree/dev-v3) with the same changes here?

@banjoh can I just change the base of this PR? Or does it need to be created against both `main` and `dev-v3`?

2024-12-11 16:28 UTC, scottrigby approved these changes, later dismissed
lgtm! great work @mayankshah1607

We also need better test coverage for this feature, as evidenced by my finding a bug only through manual testing. I've opened a separate issue for that which someone can pick up in a separate PR: https://github.com/helm/helm/issues/13519

2024-12-11 18:09 UTC, gjenkins8 submitted a review, later dismissed

2024-12-11 20:43 UTC, scottrigby commented
A failing test now needs to be fixed

2024-12-12 15:29 UTC, banjoh commented
@mayankshah1607 have you had any luck looking into the failing test?

2024-12-12 16:28 UTC, mayankshah1607 commented
Running the tests locally, everything seems to pass. I'm not sure what the issue is, but I pushed a fix anyway.. not sure if that'll do.

2024-12-13 07:34 UTC, mayankshah1607 commented
Ok, tests are fixed. PR against `dev-v3` branch is ready: https://github.com/helm/helm/pull/13531

2024-12-13 11:51 UTC, banjoh approved these changes

2024-12-15 05:46 UTC, gjenkins8 approved these changes

2024-12-19 16:30 UTC, scottrigby approved these changes
@mayankshah1607 test fix looks good. Nice work 👏

2024-12-19 16:32 UTC, merged

2024-12-19 19:09 UTC, lucasfcnunes commented
@yxxhero take a look at this. Helmfile would greatly benefit from it.

2025-01-24 09:00 UTC, atsu85 commented
if i understand correctly, then [official documentation](https://helm.sh/docs/helm/helm_upgrade/#options) isn't currently updated with this new flag?

Seems just the feature i was looking for - very good timing regarding the release of this feature :)