Make the authorizer and registry authorizer configurable
helm/helm pull request #13480
Opened 2024-11-22 22:18 UTC by rynowak

Fixes: #12584

This change makes the authorizer and registryAuthorizer of the registry client configurable via options. This allows Go SDK users to override the authentication behavior of the client.

This PR makes both the authorizer and registryAuthorizer configurable because depending on the exact scenario that may be needed. The default registryAuthorizer only supports a specific implementation of the authorizer.

**What this PR does / why we need it**:

This PR ports #12588 to the dev-v3 branch. I'm opening this per-request after it was merged to v4/main https://github.com/helm/helm/pull/12588#issuecomment-2492867470

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-11-23 15:23 UTC, TerryHowe reviewed
At this point I think we should revisit this after oras v2 merges

2024-11-25 02:58 UTC, scottrigby commented
> At this point I think we should revisit this after oras v2 merges

This is just a backport for v3 of the PR that was already merged into main (now that it's for v4). At this point there is no significant divergence.

2024-11-25 02:59 UTC, scottrigby approved these changes
@rynowak thanks for the backport. Approving with same reasoning as #12588

2024-12-02 13:54 UTC, gjenkins8 approved these changes

2024-12-02 15:09 UTC, TerryHowe requested changes

2024-12-02 15:09 UTC, TerryHowe commented on pkg/registry/client.go
> +func ClientOptRegistryAuthorizer(registryAuthorizer *registryauth.Client) ClientOption {
No separation of concerns here since `registryauth.Client` is an ORAS object and a v1 object too.

2024-12-02 19:54 UTC, merged