Feat/1163 chart testing - WIP
helm/helm pull request #1777
Opened 2017-01-03 17:48 UTC by michelleN

2017-02-05 04:06 UTC, thomastaylor312 requested changes
Mostly small fixes here and a few questions just for clarification. I have not tested this yet, but I will do so on Monday and come back with any suggestions

2017-02-05 04:06 UTC, thomastaylor312 commented on pkg/tiller/release_server_test.go
> +    "helm.sh/hook": test
Should be `test-success` right?

2017-02-05 15:02 UTC, michelleN commented on pkg/releasetesting/test_suite.go
> +			}
That'll be in a follow up PR

2017-02-05 15:03 UTC, michelleN commented on _proto/hapi/services/tiller.proto
> +    //TODO: move this to a test release service or rename to RunReleaseTest
yep good catch

2017-02-05 15:04 UTC, michelleN commented on _proto/hapi/services/tiller.proto
> +	// TODO: change to repeated hapi.release.Release.Test results = 1; (for stream)
Not tracking TODOs anywhere. They're usually just for me. I don't push them into master but I just forgot this one.

2017-02-05 15:04 UTC, michelleN commented on cmd/helm/release_testing.go
> +Th test command runs the tests for a release.
👍

2017-02-05 15:04 UTC, michelleN commented on pkg/releasetesting/test_suite.go
> +		} //else if resourceCreated && resourceCleanExit && status == api.PodUnkown {
👍

2017-02-05 15:05 UTC, michelleN commented on pkg/releasetesting/test_suite_test.go
> +    "helm.sh/hook": test
should be test-success

2017-02-05 15:06 UTC, michelleN commented on pkg/tiller/release_server_test.go
> +    "helm.sh/hook": test
yes

2017-02-06 15:37 UTC, michelleN commented on cmd/helm/release_testing.go
> +			return prettyError(err)
This will stop if there is an error with something in the testing framework not an individual test itself.

2017-02-06 15:38 UTC, michelleN commented on pkg/releasetesting/environment.go
> +	msg := fmt.Sprintf("FAILED: %s, run `kubectl logs %s` for more info", name, name)
yea that should be simple

2017-02-07 07:53 UTC, thomastaylor312 requested changes
This is tested and everything seems to be working as intended. Just one more small request before an LGTM

2017-02-07 07:53 UTC, thomastaylor312 commented on pkg/tiller/release_server.go
> +
We might want to have some logging here and possibly in `Run`. Everything else seems to have some basic logging in there

2017-02-07 16:13 UTC, thomastaylor312 approved these changes

2017-02-08 00:09 UTC, technosophos commented
LGTM2

2017-02-08 14:28 UTC, merged