doccs(related): add KubeCon 2016 videos
helm/helm pull request #2034
Opened 2017-02-27 14:09 UTC by Ladicle

close #2023

2017-02-27 16:21 UTC, michelleN commented
hey @Ladicle - thanks for your submission. The second video link isn't really about the Helm tool. I think the title is misleading in this context. Would you mind taking that reference out and just keeping the first one. If I'm mistaken, please let me know!

2017-02-27 22:56 UTC, michelleN requested changes

2017-02-28 03:36 UTC, Ladicle commented on docs/related.md
> +- [KubeCon2016: Ancestry's Journey to Kubernetes by Paul MacKay, Ancestry.com](https://www.youtube.com/watch?v=zLn_H5jaWxQ&index=69&list=PLj6h78yzYM2PqgIGU1Qmi8nY7dqn9PCr4)
hi @michelleN, Thank you for your comment. I have searched for the word `Taking the Helm` and listed it. Certainly, I think that the second subject is not Helm tool. I'll fix it :octocat:

2017-02-28 18:12 UTC, michelleN approved these changes

2017-02-28 18:13 UTC, michelleN commented
thank you @Ladicle !

2017-02-28 18:13 UTC, merged