helm(version): set 5 seconds timeout
helm/helm pull request #2088
Opened 2017-03-09 08:11 UTC by Ladicle

close #1972

2017-03-09 21:48 UTC, fibonacci1729 requested changes

2017-03-09 21:48 UTC, fibonacci1729 commented on pkg/helm/client.go
> +	c, err := grpc.Dial(h.opts.host, grpc.WithInsecure(), grpc.WithTimeout(5))
1. From the grpc godoc: ```WithTimeout returns a DialOption that configures a timeout for dialing a ClientConn initially. This is valid if and only if WithBlock() is present.``` ...I.e. Add grpc.WithBlock() in addition to the timeout.

2. The default variant of time.Duration is Nanosecond. If "5 Seconds" is desired, then this should be ```grpc.WithTimeout(5*time.Second)```

2017-03-10 06:14 UTC, Ladicle commented on pkg/helm/client.go
> +	c, err := grpc.Dial(h.opts.host, grpc.WithInsecure(), grpc.WithTimeout(5))
Thanks your RV. I've fixed.

2017-03-11 01:45 UTC, fibonacci1729 approved these changes

2017-03-11 01:46 UTC, merged