feat(hooks): Adds weighted hooks
helm/helm pull request #2157
Opened 2017-03-21 20:41 UTC by jchauncey

closes #2136
* Adds new annotation `helm.sh/hookWeight`
* Sorts executing hooks of similar kind in ascending order
* There is no upper or lower bounds on the weights

Testing Steps:
* Create a chart with at least 2 hooks (any type will work)
* Weight each hook so that they execute in a predetermined order
* Use a combination of positive and negative numbers.
* It is also possible to not supply a weight and it will default to 0
* Watch pod status to verify that pods come up in the correct order.

2017-03-22 18:54 UTC, technosophos commented
This looks very straightforward to me. I think you said, @jchauncey, that you were fixing docs, too? Once that's done, I'll LGTM.

2017-03-23 20:32 UTC, technosophos commented
@jchauncey Can you try rebasing and then re-pushing? I think @adamreese 's change hasn't kicked in for this PR.

2017-03-23 20:34 UTC, jchauncey commented
@technosophos done

2017-04-01 19:21 UTC, thomastaylor312 commented
@jchauncey Looks like there is a static validation test failure: 'pkg/tiller/hooks.go:114:3:warning: ineffectual assignment to hw (ineffassign)'. Could you address that and repush?

2017-04-02 12:02 UTC, unguiculus commented
Existing hooks use hyphens, not camel case (e. g. `pre-install`, `post-delete`). I'd suggest to name it `hook-weight` in order to be consistent.

2017-04-03 15:27 UTC, jchauncey commented
@thomastaylor312 updated pr. waiting on CI now

2017-04-03 18:08 UTC, thomastaylor312 commented
@technosophos Is this good to go now?

2017-04-03 20:17 UTC, technosophos requested changes
Just that one small doc change, and this is ready to merge.

2017-04-03 20:17 UTC, technosophos commented on docs/charts_hooks.md
> +    "helm.sh/hookWeight": "5"
I think this needs to be changed to `hook-weight`

2017-04-03 20:33 UTC, technosophos approved these changes

2017-04-03 20:34 UTC, merged