fix(helm): manifests string parsing works for newlines in the manifests
helm/helm pull request #2190
Opened 2017-03-26 02:28 UTC by anubhavmishra

Now new line such as:
```
(blank line)
---
apiVersion: v1
kind: Pod
metadata:
  name: "keystone-tempest-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
...
```
doesn't return a whitespace while parsing through the manifests.

Trying to fix #2158

2017-03-26 17:46 UTC, seh requested changes

2017-03-26 17:46 UTC, seh commented on pkg/releaseutil/manifest.go
> +	tmp := strings.Split(bigFileTmp, sep)
- [ ] How about using [`(*regexp.Regexp).Split`](https://golang.org/pkg/regexp/#Regexp.Split) instead?  
  It looks like you want to match a YAML document separator with any amount of whitespace around it. Note that [a YAML document starting boundary marker](http://yaml.org/spec/current.html#c-document-start) must occur at the beginning of the line. Hence, I recommend the following regular expression:
```(?:^|\\s*\n)---\\s*```
That is, the boundary marker is either at the beginning of the document of occurring after a newline, but preceded by any amount of whitespace.  

  [Here's a sample using this technique in the Go playground.](https://play.golang.org/p/FsdylWkbWU)

2017-03-26 17:48 UTC, seh commented on pkg/releaseutil/manifest.go
> +	// Making sure yaml formatting doesn't matter when generating manifest from string.
- [ ] While we're here, capitalize the word "YAML":  
> Make sure that any extra whitespace in the YAML stream doesn't preclude splitting its documents.

2017-03-27 13:21 UTC, seh requested changes
I wasn't clear enough in my previous suggestion, which I intended to eliminate the need for trimming the file content explicitly.

2017-03-27 13:21 UTC, seh commented on pkg/releaseutil/manifest.go
>  	bigFileTmp := strings.TrimSpace(bigfile)
- [ ] There's no need for this call, given that the regular expression defined at line 41 already eats the space surrounding the boundary marker.

2017-03-27 13:21 UTC, seh commented on pkg/releaseutil/manifest.go
> +	sep := regexp.MustCompile("(?:^|\\s*\n)---\\s*")
- [ ] Consider declaring this as a top-level `var`.  
  Doing so avoids compiling the regular expression on every invocation, though I don't know how often this function will be called.

2017-03-27 13:21 UTC, seh commented on pkg/releaseutil/manifest.go
> +	// Making sure YAML formatting doesn't matter when generating manifest from string.
- [ ] [As suggested earlier](https://github.com/kubernetes/helm/pull/2190#discussion_r108066539), consider revising this comment, as it doesn't read properly in American English.  
  > Make sure that any extra whitespace in the YAML stream doesn't preclude splitting its documents.

2017-03-27 13:21 UTC, seh commented on pkg/releaseutil/manifest.go
> +	tmp := sep.Split(bigFileTmp, -1)
- [ ] `tmp` is an odd name here, as all of these variables are "temporary."  
  Instead, use "docs" for a sequence of YAML documents.

2017-03-28 05:48 UTC, anubhavmishra commented on pkg/releaseutil/manifest.go
>  	bigFileTmp := strings.TrimSpace(bigfile)
Sorry! That was my bad, I wasn't paying attention.

2017-03-28 05:49 UTC, anubhavmishra commented
@thomastaylor312 this doesn't fix #2158. Just helps with better parsing of YAML string.

2017-03-28 13:00 UTC, seh commented on pkg/releaseutil/manifest.go
> +var sep = regexp.MustCompile("(?:^|\\s*\n)---\\s*")
In the interest of full disclosure, I'll note that it's _possible_—though I don't think Kubernetes does so—that the YAML stream could also include a positive number of [_ending_ document boundary markers](http://yaml.org/spec/current.html#c-document-end) ("...") before the starting one ("---"). Accommodating those—including any intervening comments that would be valid—with a regular expression is impractical.

2017-03-28 13:01 UTC, seh approved these changes

2017-03-30 03:14 UTC, anubhavmishra commented
@thomastaylor312 can we merge this?

2017-03-30 03:18 UTC, thomastaylor312 commented
@anubhavmishra Sorry for the delay on this. I am a 1 man show this week, so I have been a bit backlogged. I will get to this tomorrow. Luckily, @seh already did a good review so it should be fairly simple for me

2017-03-30 04:17 UTC, anubhavmishra commented
@thomastaylor312 its all good! Just wondering what was up haha 😄

2017-03-30 14:14 UTC, seh commented on pkg/releaseutil/manifest.go
> +var sep = regexp.MustCompile("(?:^|\\s*\n)---\\s*")
I intend to add these boundary markers (both starting and ending) in a fix for #2181.

2017-04-01 18:46 UTC, thomastaylor312 reviewed
One small fix to a comment @anubhavmishra and this is ready to go

2017-04-01 18:46 UTC, thomastaylor312 commented on pkg/releaseutil/manifest.go
>  	// This is not the best way of doing things, but it's how k8s itself does it.
I am guessing that since you changed this, it no longer holds true. Can you update this comment to reflect the new code?

2017-04-03 18:10 UTC, thomastaylor312 approved these changes

2017-04-03 18:10 UTC, merged

2017-04-12 22:27 UTC, technosophos commented on pkg/releaseutil/manifest.go
> +	tmp := strings.Split(bigFileTmp, sep)
This is a good idea.