fix(tiller): adding kind to tiller client logs
helm/helm pull request #2191
Opened 2017-03-26 08:13 UTC by anubhavmishra

Closes #2162

2017-03-26 17:30 UTC, seh requested changes

2017-03-26 17:30 UTC, seh commented on pkg/kube/client.go
> +		log.Printf("Doing get for %s: '%s'", info.Mapping.GroupVersionKind.Kind, info.Name)
- [ ] Quoting the name with single quotation marks is odd.  
  Consider instead using the `%q` format verb and removing the single quotation marks.

2017-03-26 17:30 UTC, seh commented on pkg/kube/client.go
> +		log.Printf("Looks like there are no changes for %s %s", target.Mapping.GroupVersionKind.Kind, target.Name)
- [ ] At line 155 above, we quote the object name, but here we don't.  
  Make that treatment consistent. I recommend using the `%q` format verb for the object name.

2017-03-27 06:18 UTC, anubhavmishra commented on pkg/kube/client.go
> +		log.Printf("Doing get for %s: '%s'", info.Mapping.GroupVersionKind.Kind, info.Name)
I didn't add the single quotation mark I just added the object type to to the print statement.

2017-03-27 06:18 UTC, anubhavmishra commented on pkg/kube/client.go
> +		log.Printf("Looks like there are no changes for %s %s", target.Mapping.GroupVersionKind.Kind, target.Name)
Again. I haven't quoted the object earlier either :)

2017-03-27 12:35 UTC, seh commented on pkg/kube/client.go
> +		log.Printf("Doing get for %s: '%s'", info.Mapping.GroupVersionKind.Kind, info.Name)
I didn't accuse _you_ of adding it. I was just suggesting what I think would be an improvement to the same line of code that you're editing here (and below at line 393). It doesn't seem worthy of a separate PR, unless you know of many more places that would require the same quoting change.

2017-03-27 22:33 UTC, anubhavmishra commented on pkg/kube/client.go
> +		log.Printf("Doing get for %s: '%s'", info.Mapping.GroupVersionKind.Kind, info.Name)
will do.

2017-03-28 01:22 UTC, thomastaylor312 reviewed
I agree with @seh's feedback on this. Once that change is made, I can go ahead and merge this.

2017-03-28 05:41 UTC, anubhavmishra commented
@thomastaylor312 done!

2017-03-28 12:49 UTC, seh requested changes
One step forward, a half step back, but that's still progress.

2017-03-28 12:49 UTC, seh commented on pkg/kube/client.go
> +		log.Printf("Doing get for %q: %q", info.Mapping.GroupVersionKind.Kind, info.Name)
- [ ] I was only suggesting that we quote the object name, not the kind. Hence:
```Requesting %s %q via GET```

2017-03-28 12:49 UTC, seh commented on pkg/kube/client.go
> +		log.Printf("Looks like there are no changes for %q %q", target.Mapping.GroupVersionKind.Kind, target.Name)
- [ ] I was only suggesting that we quote the object name, not the kind. Hence:
```Requesting %s %q via GET```

2017-03-28 12:50 UTC, seh commented
I noticed these additional lines that could benefit from the same quoting treatment, in the interest of consistency in the logging style:

- line 189  
  Replace single quotation marks with bare kind name and double-quoted object name (via `%q`).
- line 236  
  Use double quotation marks around object name (via `%q`).
- line 242  
  Use double quotation marks around object name (via `%q`).
- line 246  
  Use double quotation marks around object name (via `%q`).
- line 261  
  Use double quotation marks around object name (via `%q`).
- line 263  
  Use double quotation marks around object name (via `%q`).
- line 281  
  Use double quotation marks around object name (via `%q`).
- line 353  
  Use double quotation marks around object name (via `%q`).

2017-03-28 23:20 UTC, anubhavmishra commented
@seh I think that should look more consistent now.

2017-03-29 01:42 UTC, thomastaylor312 approved these changes

2017-03-29 01:42 UTC, merged

2017-03-29 11:42 UTC, seh reviewed
It looks like here you used the "%d" verb—suitable for integers—for object names. Were those typos?

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +	log.Printf("Using reaper for deleting %d", info.Name)
- [ ] s/%d/%q/

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +		log.Printf("Starting delete for %d %s", info.Name, info.Mapping.GroupVersionKind.Kind)
- [ ] s/%d/%q/

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +			log.Printf("Failed to delete %d, err: %s", info.Name, err)
- [ ] s/%d/%q/

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +			log.Printf("error updating the resource %d:\n\t %v", info.Name, err)
- [ ] s/%d/%q/

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +			return fmt.Errorf("no resource with the name %d found", info.Name)
- [ ] s/%d/%q/

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +			log.Printf("Created a new %s called %d\n", kind, info.Name)
- [ ] s/%d/%q/

2017-03-29 11:42 UTC, seh commented on pkg/kube/client.go
> +				log.Printf("failed to print object type %d, object: %d :\n %v", t, o, err)
- [ ] s/type %d, object: %d/type %s, object: %q/  
  I'm not sure what the type of variable "o" is here. If it's just a name, then the "%q" verb is appropriate. If it's a struct, then maybe "%v" would be better.

2017-03-29 11:43 UTC, seh commented
Oh, I see the next commit 76ebf20aac7b7939904130a3bf61b56e22cdf904 addresses these.

2017-03-29 17:08 UTC, chancez commented
Woot, thanks! This will make things much nicer to debug.