docs(*): Add ci script to confirm docs are up to date with commits
helm/helm pull request #2245
Opened 2017-04-10 02:53 UTC by cblecker

2017-04-11 23:19 UTC, technosophos commented
This will once again edge us closer to CircleCI's memory and timeout limit. It appears to run okay in the current form... I'll leave it up to @adamreese whether we should add this and risk another round of CircleCI explosions.

2017-04-11 23:36 UTC, cblecker commented
If nothing is built, it takes 38s..
```
$ time make verify-docs 
GOBIN=/opt/gopath/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.Version=v2.3.0 -X k8s.io/helm/pkg/version.GitCommit=dfe2200d01cad3baae4337dd3300213ed682cf95 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
helm docs up to date.

real	0m38.288s
user	1m37.450s
sys	0m10.845s
```

If the `make build` step is already done, then it adds on about 2 seconds of wall-clock time:
```
$ time make build && time make verify-docs
GOBIN=/opt/gopath/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.Version=v2.3.0 -X k8s.io/helm/pkg/version.GitCommit=dfe2200d01cad3baae4337dd3300213ed682cf95 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...

real	0m36.676s
user	1m39.475s
sys	0m10.323s
GOBIN=/opt/gopath/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.Version=v2.3.0 -X k8s.io/helm/pkg/version.GitCommit=dfe2200d01cad3baae4337dd3300213ed682cf95 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
helm docs up to date.

real	0m2.058s
user	0m0.965s
sys	0m0.798s
```

I assume at the test stage of CircleCI, things are already built, so hopefully this doesn't add too much extra.

2017-04-12 05:57 UTC, adamreese requested changes
Looks great,  thanks for adding this validation!

2017-04-12 05:57 UTC, adamreese commented on scripts/ci.sh
> +  make verify-docs
Run this on a different node

2017-04-12 17:43 UTC, cblecker commented on scripts/ci.sh
> +  make verify-docs
When I tried to run this one a 2) node, it didn't run at all -- I only see a 0 and 1 nodes... that's why I added it here. But maybe I'm not doing it right? I don't have a ton of experience with CircleCI.

2017-04-12 19:19 UTC, adamreese commented on scripts/ci.sh
> +  make verify-docs
Looks like I needed to add a third node in circleci.  Give it another shot.

2017-04-12 19:29 UTC, adamreese approved these changes

2017-04-12 19:29 UTC, cblecker commented
@adamreese Changes made, and tests pass. :)

2017-04-12 19:29 UTC, adamreese commented
Awesome, Thanks!

2017-04-12 19:31 UTC, merged