feat(*): update to latest gRPC and Protobuf
helm/helm pull request #2282
Opened 2017-04-17 20:19 UTC by technosophos

Effectively, this switches us to gRPC's internal version 4. This is
compatible with protoc 3.2 and grpc-go 1.2.1.

2017-04-17 20:34 UTC, technosophos commented
We need to assess whether switching from gRPC version 3 to 4 is considered an API-breaking change. None of the proto files changed, but the generated files did. `tiller.pb.go` has a change that breaks compatibility with the older gRPC library.

2017-04-18 21:54 UTC, adamreese commented
Added the breaking label because all clients will need to be recompiled.

2017-04-25 05:50 UTC, thomastaylor312 commented
@adamreese Do you mean that a new version of the `helm` binary would not work with old Tiller versions?

2017-04-25 06:00 UTC, thomastaylor312 requested changes
One tiny little change that can be done with the rebase and this should be good to go. I tested update, rollback, install, delete, history, and status and everything worked properly

2017-04-25 06:00 UTC, thomastaylor312 commented on glide.yaml
> +  # version: df1d3ca07d2d07bba352d5b73c4313b4e2a6203e
Should this be removed?

2017-04-28 05:46 UTC, thomastaylor312 approved these changes

2017-04-28 14:10 UTC, merged