Fixes various issues related to plugin command
helm/helm pull request #2400
Opened 2017-05-05 04:46 UTC by sushilkm

- [ ] issues/2398: Added error in case requested plugin version does not exists while installing a plugin
- [ ] issues/2385: Added error in case requested plugin exists while installing a plugin
- [ ] issues/2385: Added update option to plugin command to update an existing plugin
- [ ] issues/2384: Fixed messages for plugin remove option

2017-05-06 20:29 UTC, thomastaylor312 commented
@sushilkm Would it be difficult to pull out the feature addition (the update option) into its own PR? That is a new feature and the others are bug fixes, so I think it would be better to split them out. I'll review the code, but I am going to wait to test until then

2017-05-06 20:41 UTC, thomastaylor312 reviewed
Mostly some small changes and nits here

2017-05-06 20:41 UTC, thomastaylor312 commented on cmd/helm/plugin_remove.go
> +		return errors.New("please provide plugin name to remove")
If I remember right, it is preferable to use `fmt.Errorf` instead

2017-05-06 20:41 UTC, thomastaylor312 commented on pkg/plugin/hooks.go
> +	// Update is executed after the plugin is removed.
Shouldn't this say "after the plugin is updated"?

2017-05-06 20:41 UTC, thomastaylor312 commented on pkg/plugin/installer/installer.go
> +// Update updates a plugin to $HELM_HOME.
Nit: "updates a plugin in $HELM_HOME" as opposed to "updates a plugin to $HELM_HOME"

2017-05-06 20:41 UTC, thomastaylor312 commented on pkg/plugin/installer/installer.go
> +		return errors.New("plugin does not exists")
Nit: exist instead of exists

2017-05-06 20:41 UTC, thomastaylor312 commented on pkg/plugin/installer/vcs_installer_test.go
> +	"fmt"
This should go up with the other imports and the extra space should be removed in between external imports

2017-05-06 22:52 UTC, sushilkm commented on cmd/helm/plugin_remove.go
> +		return errors.New("please provide plugin name to remove")
I think errors.New is faster fmt.Errorf, so if it is plain string, I think errors.New should be preferable, let me know if fmt.Errorf is a better option, I can replace

2017-05-06 23:01 UTC, sushilkm commented
@thomastaylor312 create a new PR for update option, https://github.com/kubernetes/helm/pull/2410
Also fixed the comments in that PR as mostly all were related to update changes 👍

2017-05-08 20:30 UTC, thomastaylor312 commented on cmd/helm/plugin_remove.go
> +		return errors.New("please provide plugin name to remove")
Ok, that makes sense. We'll stick with it

2017-05-09 03:36 UTC, thomastaylor312 requested changes
One small fix and then this should be good to go

2017-05-09 03:36 UTC, thomastaylor312 commented on cmd/helm/plugin_remove.go
> +			fmt.Fprintf(pcmd.out, "Plugin: %s not found\n", name)
Right now this will still return 0 when exiting (same with line 71). This should return `fmt.Errorf` so it errors out properly

2017-05-09 04:40 UTC, thomastaylor312 approved these changes

2017-05-09 04:40 UTC, merged