Add the status of pod when using "Helm status" command, as the issue 2138
helm/helm pull request #2421
Opened 2017-05-10 02:29 UTC by yan234280533

2017-05-10 02:56 UTC, yan234280533 commented
@thomastaylor312  Can you help me a litter, I  split the commit. But the CI is failed again, when run test-style.  Thanks billions. I don't know how to find a way to solve this problem, so I have no choice but to look for help of you.  Thanks billions.

2017-05-11 05:08 UTC, yan234280533 commented
@thomastaylor312  I did an ci test, but it failed again. We not edit any code, but it failed also. It so strange.

2017-05-11 07:33 UTC, yan234280533 commented
@thomastaylor312 I solve the problem by  run the "go fmt" and then commit the file again.

2017-05-17 13:40 UTC, yan234280533 commented
@technosophos Hi , Matt . Can you help me to review this feature ? The feature is describe in #2318 , it is to add the ability to show the status of pod. Many thanks.

2017-05-22 11:30 UTC, yan234280533 commented
@adamreese  Hi, adamreese. Can you do a review of this pull requrest for me ?  If these have some questions, I will modify it as soon as possible as you reviewed. So many thanks for you.

2017-05-31 06:33 UTC, yan234280533 commented
@adamreese  Hi,Adamreese. Can you do an review of this commit, so many thanks.

2017-06-23 02:04 UTC, yan234280533 commented
@adamreese  Hi , Adamreese. Can you do an review of this commit for me , So many thanks for you. It so sorry to trouble you.

2017-07-07 03:32 UTC, technosophos commented
I know a few of us have looked at this, yet nobody's done a full review. Can someone take a moment to do a review?

2017-08-08 02:55 UTC, thomastaylor312 requested changes
Sorry for the long delay on this. A few changes in the comments. Also, could you please write tests for the new functionality?

2017-08-08 02:55 UTC, thomastaylor312 commented on pkg/kube/client.go
> +	log.Printf("getSelectRelationPod selector: %+v", selector)
With these log statements, can you make sure to use `c.Log` (you can see examples of this throughout the other functions)

2017-08-08 02:55 UTC, thomastaylor312 commented on pkg/kube/client.go
> +func (c *Client) getSelectRelationPod(info *resource.Info, objPods map[string][]api.Pod) (map[string][]api.Pod, error) {
I think a comment for at least this function (and probably the others) would be helpful in following this new logic

2017-08-08 02:55 UTC, thomastaylor312 commented on pkg/kube/client.go
> +
Nit: There is a lot of extra whitespace in this `for` loop, removing some of it may make it cleaner

2017-08-23 15:27 UTC, yan234280533 commented
@thomastaylor312  I rewrite the PR in an new branch. I am so sorry to trouble you to help me to review the  PR's code.

2017-08-23 15:28 UTC, closed without merging