fix(*): return non-zero exit code on test failure
helm/helm pull request #2425
Opened 2017-05-10 15:23 UTC by michelleN

* resolves #2089

2017-05-10 15:25 UTC, michelleN commented
I would appreciate some manual testing on this PR. 
Also, I chose to exit cleanly when there are no tests found in the release. Is that a decision we agree with or do we feel like helm test should fail (exit non-zero) when there are no tests found in the release object?

2017-05-15 17:46 UTC, fibonacci1729 approved these changes

2017-05-15 17:46 UTC, fibonacci1729 commented on cmd/helm/helm_test.go
> +		var wg sync.WaitGroup
Optionally, you could just add ```wg.Add(len(c.responses))```.

2017-05-15 18:54 UTC, adamreese requested changes
Run a `make bootstrap protoc` to ensure correct versions for code generation

```
helm on pr/2425
❯ make protoc
...

helm on pr/2425 [!]
❯ git status
On branch pr/2425
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pkg/proto/hapi/chart/chart.pb.go
	modified:   pkg/proto/hapi/chart/config.pb.go
	modified:   pkg/proto/hapi/chart/metadata.pb.go
	modified:   pkg/proto/hapi/chart/template.pb.go
	modified:   pkg/proto/hapi/release/hook.pb.go
	modified:   pkg/proto/hapi/release/info.pb.go
	modified:   pkg/proto/hapi/release/release.pb.go
	modified:   pkg/proto/hapi/release/status.pb.go
	modified:   pkg/proto/hapi/release/test_run.pb.go
	modified:   pkg/proto/hapi/release/test_suite.pb.go
	modified:   pkg/proto/hapi/rudder/rudder.pb.go
	modified:   pkg/proto/hapi/services/tiller.pb.go
	modified:   pkg/proto/hapi/version/version.pb.go

no changes added to commit (use "git add" and/or "git commit -a")
```

2017-05-15 18:54 UTC, adamreese commented on cmd/helm/release_testing.go
> +	// message []string{}
delete me

2017-05-16 17:00 UTC, adamreese approved these changes

2017-05-17 16:58 UTC, merged