WIP Add --node-selectors and --output flags to helm init
helm/helm pull request #2557
Opened 2017-06-07 18:31 UTC by jascott1

This partially implements #2299. `--set` has been deferred due to the complexity introduced and `--output` enables similar use cases.

2017-06-07 18:51 UTC, thomastaylor312 commented on cmd/helm/installer/install.go
> +	nodeSelectors["beta.kubernetes.io/os"] = "linux"
This looks like a sensible way to do it. Have it default to linux and if the user specifies another one, it will be overwritten.

2017-06-08 04:12 UTC, thomastaylor312 commented
Waiting to label until this is out of WIP. Ping one of us @jascott1 when this is ready for review

2017-06-16 00:42 UTC, seh commented
Reviewed 2 of 4 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[cmd/helm/init.go, line 124 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiDt4U8XvkAqOQXdu6:-KmiDt4VPqGaXzk8rJzl:bdp40cl) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L124)):*
> which node tiller lands on

How about "on which node tiller lands?"

---

*[cmd/helm/init.go, line 124 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiE5wLUjoXr2S3sWA8:-KmiE5wLUjoXr2S3sWA9:bpvjjhq) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L124)):*
> node-selectors

The name implies that the flag accepts several selectors. How does one separate each selector? What's the syntax?

---

*[cmd/helm/init.go, line 125 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiFFileHTS7uouIkAV:-KmiFFimwvsa7_vFUoKU:b-8j7119) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L125)):*
> ```Go
> 
> 	f.StringVar(&i.opts.NodeSelectors, "node-selectors", "", "labels to select which node tiller lands on")
> 	f.StringVarP(&i.opts.Output, "output", "o", "", "skip installation and output tiller's manifest in specified format (json,yaml)")
> ```

Instead of using a string here for the flag, consider defining a new type that implements [`pflag.Value`](https://godoc.org/github.com/spf13/pflag#Value). Approximately:
```go
type outputFormat string

func (f outputFormat) String() string {
	return string(f)
}

func (outputFormat) Type() string {
	return "format"
}

const (
	fmtJSON outputFormat = "json"
	fmtYAML              = "yaml"
)

func (f *outputFormat) Set(s string) error {
	for _, of := range []outputFormat{fmtJSON, fmtYAML} {
		if s == string(of) {
			*f = of
			return nil
		}
	}
	return fmt.Errorf("unknown output format %q", s)
}
```
With that, you can use [`pflag.Var`](https://godoc.org/github.com/spf13/pflag#Var) instead of `pflag.StringVar`

---

*[cmd/helm/init.go, line 192 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiEcZgXOdpiqtdcn8w:-KmiEcZh_DaHhMk6YOUI:bco1vef) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L192)):*
> ```Go
> 	}
> 	if len(i.opts.Output) > 0 {
> ```

Remove blank line.

---

*[cmd/helm/init.go, line 204 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiJ8nDq8vOJpFL59OW:-KmiJ8nEiQJWCby_zMom:b-ouuh72) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L204)):*
> ```Go
> 				return err
> 			}
> 			jsons := string(jsonb)
> ```

It looks like you could avoid this conversion to a string by using `io.WriteString` with the metadata prefix followed by `(*io.Writer).Write` on `jsonb[1:]`.

---

*[cmd/helm/installer/options.go, line 76 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiKIr5wJNuOx4FG4uM:-KmiKIr5wJNuOx4FG4uN:b-wcff83) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/installer/options.go#L76)):*
> Tiller

I noticed that here we capitalize the word "Tiller," but in the flag documentation we write in lowercase as "tiller." I think it should be capitalized throughout.

---

*[cmd/helm/installer/options.go, line 79 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiKDMmb-s-XCRG3h-0:-KmiKDMnlY-0eGPMr18m:b-g81dwb) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/installer/options.go#L79)):*
> json

Capitalize the format as "JSON."

---

*[cmd/helm/installer/options.go, line 108 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiKrAdxr8mJ6QXSdeO:-KmiKrAdxr8mJ6QXSdeP:b50cpuv) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/installer/options.go#L108)):*
> ```Go
> // valuesMap returns user set values in map format
> func (opts *Options) valuesMap() (map[string]interface{}, error) {
> 	m := map[string]interface{}{}
> ```

Do we expect the map to contain the same number of entries as `opts.Values`? If so:
```go
m := make(map[string]interface{}, len(opts.Values))
```

---

*[cmd/helm/installer/options.go, line 110 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiKh2-yMLUpKujUVUx:-KmiKh2-yMLUpKujUVUy:bm205yn) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/installer/options.go#L110)):*
> ```Go
> 	m := map[string]interface{}{}
> 	for _, skv := range opts.Values {
> 		err := strvals.ParseInto(skv, m)
> ```

Instead:
```go
if err := strvals.ParseInto(skv,m); err != nil {
  return nil, err
}
```

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-16 22:23 UTC, jascott1 commented
Thanks @seh. Im still working on it and will check out your suggestions asap.

2017-06-16 22:25 UTC, jascott1 commented
All flags are functioning now including `--set` which is working with values nested under lists but it still needs tests for those.

2017-06-16 22:46 UTC, jascott1 commented
Review status: 1 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[cmd/helm/init.go, line 124 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiDt4U8XvkAqOQXdu6:-Kmn3ebdSA3R85PcaNKi:b-gppszq) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L124)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> which node tiller lands on

How about "on which node tiller lands?"
</blockquote></details>

technically I changed it to "node on which tiller is installed"

---

*[cmd/helm/init.go, line 125 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiFFileHTS7uouIkAV:-Kmn4UStG9mqeFXD2Nd2:b4v9iwx) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L125)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Instead of using a string here for the flag, consider defining a new type that implements [`pflag.Value`](https://godoc.org/github.com/spf13/pflag#Value). Approximately:
```go
type outputFormat string

func (f outputFormat) String() string {
	return string(f)
}

func (outputFormat) Type() string {
	return "format"
}

const (
	fmtJSON outputFormat = "json"
	fmtYAML              = "yaml"
)

func (f *outputFormat) Set(s string) error {
	for _, of := range []outputFormat{fmtJSON, fmtYAML} {
		if s == string(of) {
			*f = of
			return nil
		}
	}
	return fmt.Errorf("unknown output format %q", s)
}
```
With that, you can use [`pflag.Var`](https://godoc.org/github.com/spf13/pflag#Var) instead of `pflag.StringVar`
</blockquote></details>

Will check into this next commit

---

*[cmd/helm/init.go, line 204 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiJ8nDq8vOJpFL59OW:-Kmn4PxLVwPrae3bTyPb:b4v9iwx) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L204)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

It looks like you could avoid this conversion to a string by using `io.WriteString` with the metadata prefix followed by `(*io.Writer).Write` on `jsonb[1:]`.
</blockquote></details>

Will check into this next commit

---

*[cmd/helm/installer/options.go, line 76 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiKIr5wJNuOx4FG4uM:-Kmn43Alvg3rdmxdbVWO:b-6cfkzi) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/installer/options.go#L76)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> Tiller

I noticed that here we capitalize the word "Tiller," but in the flag documentation we write in lowercase as "tiller." I think it should be capitalized throughout.
</blockquote></details>

Capitalized Tiller in options.go

---

*[cmd/helm/installer/options.go, line 108 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiKrAdxr8mJ6QXSdeO:-Kmn4FULTzJ8Nwh0NE2t:b-kt812n) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/installer/options.go#L108)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Do we expect the map to contain the same number of entries as `opts.Values`? If so:
```go
m := make(map[string]interface{}, len(opts.Values))
```
</blockquote></details>

No this is dynamic

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-16 23:20 UTC, jascott1 commented
Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/helm/init.go, line 125 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiFFileHTS7uouIkAV:-KmnArSp-wS4AGkJHXQr:blc2mjt) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L125)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

Will check into this next commit
</blockquote></details>

I like it and concede its more proper but im not sure its worth it for simple string check. Are we doing this for consistency for flags of this type?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-16 23:37 UTC, jascott1 commented
Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/helm/init.go, line 204 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiJ8nDq8vOJpFL59OW:-KmnG8THcIWpyv-pDiPo:b9kcvdz) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L204)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

Will check into this next commit
</blockquote></details>

nice! looks way cooler taboot.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-17 00:01 UTC, seh commented
Reviewed 2 of 3 files at r5.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/helm/init.go, line 125 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiFFileHTS7uouIkAV:-KmnJkK1jutSMRBTjYWC:bbs30xl) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L125)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

I like it and concede its more proper but im not sure its worth it for simple string check. Are we doing this for consistency for flags of this type?
</blockquote></details>

The idea is that _cobra_ can then detect the mismatch as a flag parsing failure, and stop the program at that stage, in the same way that if you asked for an integer and got "pdq" as a command-line flag value, _cobra_ would reject that value before you ever saw it.

It gets more worth the investment when you plan to use the flag type many times. Here, we only have one use at the moment, but maybe there are other places in Helm that will allow the user to specify this same kind of output format.

---

*[cmd/helm/init.go, line 204 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiJ8nDq8vOJpFL59OW:-KmnHgPkMxf2wcBgEx5T:b7c9o7o) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L204)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

nice! looks way cooler taboot.
</blockquote></details>

It occurred to after writing last night that the original code winds up copying the JSON bytes three times: once to convert the byte vector to a string, once to concatenate the JSON string to the metadata prefix, and once more to write the combined string to the destination. We can't eliminate the last transfer, but the first two are unnecessary.

---

*[cmd/helm/init.go, line 205 at r5](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmnIqYUC3nRUTgIjJhf:-KmnIqYUC3nRUTgIjJhg:bflbd8j) ([raw file](https://github.com/kubernetes/helm/blob/1ef31019d7ee69f97d94c41bd6ebb40776560df9/cmd/helm/init.go#L205)):*
> ```Go
> 			}
> 			io.WriteString(i.out, "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",")
> 			(io.Writer).Write(i.out, jsonb[1:])
> ```

I was expecting a statement like this:
```go
_, err := i.out.Write(jsonb[1:])
return err
```

---

*[cmd/helm/installer/options.go, line 47 at r5](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmnLJQh17U-7gxKLfyn:-KmnLJQh17U-7gxKLfyo:b4r1wbm) ([raw file](https://github.com/kubernetes/helm/blob/1ef31019d7ee69f97d94c41bd6ebb40776560df9/cmd/helm/installer/options.go#L47)):*
> ```Go
> 	Namespace string
> 
> 	// ServiceAccount is the Kubernetes service account to add to Tiller
> ```

It's not your focus here, but I'll note that most of these field documentation lines are punctuated, but some are not (such as the "Output" one you added below. Consider unifying them.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-20 01:39 UTC, jascott1 commented
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/helm/init.go, line 125 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiFFileHTS7uouIkAV:-Kn27x3_eZeLN77KjP6_:benvywg) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L125)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

The idea is that _cobra_ can then detect the mismatch as a flag parsing failure, and stop the program at that stage, in the same way that if you asked for an integer and got "pdq" as a command-line flag value, _cobra_ would reject that value before you ever saw it.

It gets more worth the investment when you plan to use the flag type many times. Here, we only have one use at the moment, but maybe there are other places in Helm that will allow the user to specify this same kind of output format.
</blockquote></details>

Thanks for the explanation. I implemented your changes.

---

*[cmd/helm/init.go, line 204 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmiJ8nDq8vOJpFL59OW:-Kn28P_QRlFB2UKsM5f-:bjkxvgy) ([raw file](https://github.com/kubernetes/helm/blob/215bd6a45c0a30d2ebf24fe3e125ae157f7f5d8d/cmd/helm/init.go#L204)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

It occurred to after writing last night that the original code winds up copying the JSON bytes three times: once to convert the byte vector to a string, once to concatenate the JSON string to the metadata prefix, and once more to write the combined string to the destination. We can't eliminate the last transfer, but the first two are unnecessary.
</blockquote></details>

Please take a look at the new revision and let me know.  I also added json.Indent.

---

*[cmd/helm/init.go, line 205 at r5](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmnIqYUC3nRUTgIjJhf:-Kn28ldiScXYfM_4To9J:b-j2wkmf) ([raw file](https://github.com/kubernetes/helm/blob/1ef31019d7ee69f97d94c41bd6ebb40776560df9/cmd/helm/init.go#L205)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

I was expecting a statement like this:
```go
_, err := i.out.Write(jsonb[1:])
return err
```
</blockquote></details>

Its been refactored in a different way. Please let me know what you think.

---

*[cmd/helm/installer/options.go, line 47 at r5](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmnLJQh17U-7gxKLfyn:-Kn28uWZ_UV3LCJ8UUfA:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/1ef31019d7ee69f97d94c41bd6ebb40776560df9/cmd/helm/installer/options.go#L47)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

It's not your focus here, but I'll note that most of these field documentation lines are punctuated, but some are not (such as the "Output" one you added below. Consider unifying them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-20 18:36 UTC, seh commented on cmd/helm/installer/install.go
> +func parseNodeSelectors(labels string, m map[string]string) map[string]string {
- [ ] This function got strange with this change. It now mutates a supplied map in place, and returns that same map, though the signature can't promise that the returned map is the same as the map supplied as an argument. A caller might wonder whether he needs the return value. A caller might wonder whether his input argument is safe against mutation.  

  What if you had `parseNodeSelectors` create and return a fresh map, eliminating this confusion, and then add your "os=linux" selector into the map returned from the call in `generateDeployment`?

2017-06-20 18:49 UTC, jascott1 commented on cmd/helm/installer/install.go
> +func parseNodeSelectors(labels string, m map[string]string) map[string]string {
@seh User needs to be able to override that default selector. Are you suggesting that anything that needs to be mutated needs to be passed as a pointer?

2017-06-20 18:51 UTC, seh commented on cmd/helm/installer/install.go
> +func parseNodeSelectors(labels string, m map[string]string) map[string]string {
No, I wasn't suggesting that. If you want that function to mutate in place, then don't return a map as well. That eliminates the confusion. With that signature change, I'd consider renaming it to `parseNodeSelectorsInto`.

2017-06-20 18:55 UTC, seh commented on cmd/helm/installer/install.go
> +func parseNodeSelectors(labels string, m map[string]string) map[string]string {
By the way, [maps are (effectively) pointers](https://dave.cheney.net/tag/maps). I recalled that article too late to include it earlier.

2017-06-20 21:38 UTC, seh commented
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/helm/init.go, line 202 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn5xiFjm1N4hUdI8D2v:-Kn5xiFkk5A8MiHMShdo:btdo5dl) ([raw file](https://github.com/kubernetes/helm/blob/2cb6af64e460995bd28da0fbec290fc96f153837/cmd/helm/init.go#L202)):*
> ```Go
> 		case "json":
> 			var out bytes.Buffer
> 			jsonb, err := yaml.ToJSON([]byte(body))
> ```

Unfortunately, that conversion to `[]byte` makes a copy—unless the compiler is clever enough to prove that `yaml.ToJSON` never writes through the slice.

---

*[cmd/helm/init.go, line 206 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn5yA60reTVt5yWlJaw:-Kn5yA61ffMOlCh101Ce:b-zd8hv2) ([raw file](https://github.com/kubernetes/helm/blob/2cb6af64e460995bd28da0fbec290fc96f153837/cmd/helm/init.go#L206)):*
> ```Go
> 				return err
> 			}
> 			tm := []byte("{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",")
> ```

It would be better to use `bytes.Buffer` and [`(*bytes.Buffer).Write`](https://golang.org/pkg/bytes/#Buffer.Write) here and on the line below, then call [`(*bytes.Buffer).Bytes`](https://golang.org/pkg/bytes/#Buffer.Bytes) in the call to `json.Indent` below. You can supply the header byte vector to `bytes.NewBuffer`, though the subsequent call to `Write` is going to require reallocating the backing array and copying the initial content anyway. Best would be to size the initial array to length of "tm" plus the length of _"json" - 1_.

Here's [a Playground sample](https://play.golang.org/p/cUM5V-YchO) that shows avoiding a few lurking copies.

It's a shame that there's no `yaml.ToJSONIndent` function like [`json.MarshalIndent`](https://golang.org/pkg/encoding/json/#MarshalIndent).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-20 23:27 UTC, jascott1 commented on cmd/helm/installer/install.go
> +func parseNodeSelectors(labels string, m map[string]string) map[string]string {
I renamed and updated to not return map. Thanks for the help!

2017-06-20 23:30 UTC, jascott1 commented
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/helm/init.go, line 206 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn5yA60reTVt5yWlJaw:-Kn6pP7clFuunOEnreMu:b-icl271) ([raw file](https://github.com/kubernetes/helm/blob/2cb6af64e460995bd28da0fbec290fc96f153837/cmd/helm/init.go#L206)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

It would be better to use `bytes.Buffer` and [`(*bytes.Buffer).Write`](https://golang.org/pkg/bytes/#Buffer.Write) here and on the line below, then call [`(*bytes.Buffer).Bytes`](https://golang.org/pkg/bytes/#Buffer.Bytes) in the call to `json.Indent` below. You can supply the header byte vector to `bytes.NewBuffer`, though the subsequent call to `Write` is going to require reallocating the backing array and copying the initial content anyway. Best would be to size the initial array to length of "tm" plus the length of _"json" - 1_.

Here's [a Playground sample](https://play.golang.org/p/cUM5V-YchO) that shows avoiding a few lurking copies.

It's a shame that there's no `yaml.ToJSONIndent` function like [`json.MarshalIndent`](https://golang.org/pkg/encoding/json/#MarshalIndent).
</blockquote></details>

I altered it with your suggestions, thanks.

---

*[cmd/helm/installer/install.go, line 132 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmhclZ8q1_5g6591VYu-r6-132:-Kn6pufnzDU1XANiw6uI:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/2cb6af64e460995bd28da0fbec290fc96f153837/cmd/helm/installer/install.go#L132)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

I renamed and updated to not return map. Thanks for the help!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-21 00:11 UTC, seh commented
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/helm/init.go, line 209 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6wcuZV1V2wA9FLD-a:-Kn6wcu_814wRhCfbAzS:b-4px0do) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/cmd/helm/init.go#L209)):*
By the way, what is that first character in "jsonb" that we're skipping? The opening '{'?
If you come through here again, a comment would be nice. Consider:
> Drop the opening object delimiter ('{').

---

*[cmd/helm/installer/install.go, line 139 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6xPMat7Yg9FNFV3fH:-Kn6xPMat7Yg9FNFV3fI:bbqc2wp) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/cmd/helm/installer/install.go#L139)):*
> Invalid

Error messages [should not used capitalized first words](https://github.com/golang/go/wiki/Errors#errors) so that they can be concatenated more easily.

> Error strings should not start with a capital letter because they'll often be prefixed before printing

Also, consider using the "%q" verb to quote the offending label string.

---

*[docs/helm/helm_init.md, line 41 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6ySHny7KLNV3T_nZJ:-Kn6ySHoQoBELK5ITTPw:b-mlzusx) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/docs/helm/helm_init.md#L41)):*
> tiller

I think I noted this elsewhere, but our flags are inconsistent in capitalizing the word "tiller." Note that "--set" capitalizes it, but "--canary," "--client-only," "--net-host," "--node-selectors," "--output," "--tiller-image," "--tiller-tls," "--tiller-tls-cert," "--tiller-tls-key," "--tiller-tls-verify," and "--upgrade" do not. Oh, wait, there are more: "--host," and "--tiller-namespace."

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-21 00:29 UTC, jascott1 commented
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/helm/init.go, line 209 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6wcuZV1V2wA9FLD-a:-Kn72SXg2Hy2h3WKFH0I:b-oz8tym) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/cmd/helm/init.go#L209)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

By the way, what is that first character in "jsonb" that we're skipping? The opening '{'?
If you come through here again, a comment would be nice. Consider:
> Drop the opening object delimiter ('{').
</blockquote></details>

Good call.

---

*[cmd/helm/installer/install.go, line 139 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6xPMat7Yg9FNFV3fH:-Kn72EPLX74Pr4mQQ7Vm:b-dwk1w0) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/cmd/helm/installer/install.go#L139)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> Invalid

Error messages [should not used capitalized first words](https://github.com/golang/go/wiki/Errors#errors) so that they can be concatenated more easily.

> Error strings should not start with a capital letter because they'll often be prefixed before printing

Also, consider using the "%q" verb to quote the offending label string.
</blockquote></details>

Good stuff. Thanks!

---

*[docs/helm/helm_init.md, line 41 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6ySHny7KLNV3T_nZJ:-Kn72H6dQN9IwMUvojTh:b-a38ifw) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/docs/helm/helm_init.md#L41)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> tiller

I think I noted this elsewhere, but our flags are inconsistent in capitalizing the word "tiller." Note that "--set" capitalizes it, but "--canary," "--client-only," "--net-host," "--node-selectors," "--output," "--tiller-image," "--tiller-tls," "--tiller-tls-cert," "--tiller-tls-key," "--tiller-tls-verify," and "--upgrade" do not. Oh, wait, there are more: "--host," and "--tiller-namespace."
</blockquote></details>

I will defer that to another atomic commit for that purpose unless you think its important now.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-21 01:14 UTC, jascott1 commented
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/helm/helm_init.md, line 41 at r7](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn6ySHny7KLNV3T_nZJ:-Kn7Bjl9V3am6XC7cZ7B:bjtrwdi) ([raw file](https://github.com/kubernetes/helm/blob/c1ddde94bbe5288ad5d1309a3b33cb19d41492c1/docs/helm/helm_init.md#L41)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

I will defer that to another atomic commit for that purpose unless you think its important now.
</blockquote></details>

I started another PR for this. I noticed that "tiller" in many if not most of the other commands' usage strings are not capitalized. Im planning to gauge merit based on feedback from #2601 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-21 13:29 UTC, seh commented
Reviewed 1 of 3 files at r4, 3 of 5 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/helm/init.go, line 196 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9nhmjm5fB9GlabJPc:-Kn9nhmjm5fB9GlabJPd:b-v6ok53) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init.go#L196)):*
> ```Go
> 		var body string
> 		var err error
> 		if body, err = installer.DeploymentManifest(&i.opts); err != nil {
> ```

Consider using the alternate `deploymentManifest` function proposed below that returns `[]byte` instead of a string.

---

*[cmd/helm/init_test.go, line 323 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9lX3RZVMbWcIbBFJ9:-Kn9lX3S9X21xwSKshA0:b-9tiozs) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init_test.go#L323)):*
> expectF
This name confuses me. How about "unmarshalF" or just "unmarshal?"

---

*[cmd/helm/init_test.go, line 324 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9ldPmHL-NgNtF8W1o:-Kn9ldPmHL-NgNtF8W1p:b-dm0vro) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init_test.go#L324)):*
> expectName
This name confuses me. How about "outputFormat" or "format?"

---

*[cmd/helm/init_test.go, line 355 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9lLJ2Ly5r3xdYCIpv:-Kn9lLJ3nXmr9ycqePZK:bco1vef) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init_test.go#L355)):*
> ```Go
> 		}
> 	}
> ```

Remove blank line.

---

*[cmd/helm/installer/install.go, line 115 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9lzI6mVhvPU6SYz7Y:-Kn9lzI6mVhvPU6SYz7Z:b-dd0ui5) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install.go#L115)):*
> string(buf)
I suspect that we can't change this signature at this point because this function is exported, but if you returned a `[]byte` here instead of a string, you could save yourself two copies of the content up in `(*initCmd).run`.
Consider introducing a parallel function that returns `[]byte`, and call on it from `DeploymentManifest` to preserve backward compatibility if necessary.
```go
func deploymentManifest(opts *Options) ([]byte, error) {
obj, err := deployment(opts)
	if err != nil {
		return "", err
	}
	buf, err := yaml.Marshal(obj)
	return buf, err
}

func DeploymentManifest(opts *Options) (string, error) {
	b, err := deploymentManifest(opts)
	return string(b), err
}
```
If you're concerned that [`yaml.Marshal` can emit content even when it fails](https://github.com/go-yaml/yaml/blob/v2/yaml.go#L138-L146), you could be more conservative, at the cost of an extra interface comparison:
```go
func DeploymentManifest(opts *Options) (string, error) {
	b, err := deploymentManifest(opts)
	if err !=nil {
		return "", err
	}
	return string(b), nil
}
```

---

*[cmd/helm/installer/install_test.go, line 447 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9oG0hdAfBTVWYg8g_:-Kn9oG0hdAfBTVWYg8ga:b-43l93z) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L447)):*
> ```Go
> 		},
> 	}
> 	for _, tt := range tests {
> ```

You could use subtests here ([`*testing.T).Run`](https://golang.org/pkg/testing/#T.Run), using the "name" field from "tt" as the subtest name. Your error messages could then be more concise, though the test name gets mangled somewhat.

---

*[cmd/helm/installer/install_test.go, line 457 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9opi6e_oiwlt8G3_o:-Kn9opi6e_oiwlt8G3_p:b-fd2yfv) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L457)):*
> ```Go
> 			t.Fatalf("%s: error %q", tt.name, err)
> 		}
> 		// verify environment variable in deployment reflect the use of tls being enabled.
> ```

Since the sentence is punctuated, capitalize the first word.

---

*[cmd/helm/installer/install_test.go, line 457 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9p51Xs39V-ocb7cGS:-Kn9p51Xs39V-ocb7cGT:b-er4jpz) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L457)):*
> ```Go
> 			t.Fatalf("%s: error %q", tt.name, err)
> 		}
> 		// verify environment variable in deployment reflect the use of tls being enabled.
> ```

s/tls/TLS/

---

*[cmd/helm/installer/install_test.go, line 457 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9p6s6eGKGDrTaBs1Y:-Kn9p6s6eGKGDrTaBs1Z:b-7fygms) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L457)):*
> ```Go
> 			t.Fatalf("%s: error %q", tt.name, err)
> 		}
> 		// verify environment variable in deployment reflect the use of tls being enabled.
> ```

s/reflect/reflects/ or s/variable/variables/, depending on whether there is more than one variable.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-21 18:51 UTC, jascott1 commented
Review status: 4 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/helm/init.go, line 196 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9nhmjm5fB9GlabJPc:-KnAn94f-R1C4GXp7eUi:b-anjsws) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init.go#L196)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Consider using the alternate `deploymentManifest` function proposed below that returns `[]byte` instead of a string.
</blockquote></details>

Deferred this as noted in other comment.

---

*[cmd/helm/init_test.go, line 323 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9lX3RZVMbWcIbBFJ9:-KnAnN_yuQpWxZBpcF10:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init_test.go#L323)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> expectF
This name confuses me. How about "unmarshalF" or just "unmarshal?"
</blockquote></details>

Done.

---

*[cmd/helm/init_test.go, line 324 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9ldPmHL-NgNtF8W1o:-KnAnNu7SmrR82snMzIn:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init_test.go#L324)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> expectName
This name confuses me. How about "outputFormat" or "format?"
</blockquote></details>

Done.

---

*[cmd/helm/init_test.go, line 355 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9lLJ2Ly5r3xdYCIpv:-KnAnQRt1pwXoCvJ2ob0:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/init_test.go#L355)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Remove blank line.
</blockquote></details>

Done.

---

*[cmd/helm/installer/install.go, line 115 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9lzI6mVhvPU6SYz7Y:-KnAmb8g4VINUok6xigh:b3om4j8) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install.go#L115)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> string(buf)
I suspect that we can't change this signature at this point because this function is exported, but if you returned a `[]byte` here instead of a string, you could save yourself two copies of the content up in `(*initCmd).run`.
Consider introducing a parallel function that returns `[]byte`, and call on it from `DeploymentManifest` to preserve backward compatibility if necessary.
```go
func deploymentManifest(opts *Options) ([]byte, error) {
obj, err := deployment(opts)
	if err != nil {
		return "", err
	}
	buf, err := yaml.Marshal(obj)
	return buf, err
}

func DeploymentManifest(opts *Options) (string, error) {
	b, err := deploymentManifest(opts)
	return string(b), err
}
```
If you're concerned that [`yaml.Marshal` can emit content even when it fails](https://github.com/go-yaml/yaml/blob/v2/yaml.go#L138-L146), you could be more conservative, at the cost of an extra interface comparison:
```go
func DeploymentManifest(opts *Options) (string, error) {
	b, err := deploymentManifest(opts)
	if err !=nil {
		return "", err
	}
	return string(b), nil
}
```
</blockquote></details>

Since this only affects the one shot `init` operation at this time, I'd rather defer taking on a wrapper func until we have another use.

---

*[cmd/helm/installer/install_test.go, line 447 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9oG0hdAfBTVWYg8g_:-KnAhrYoMd_OZHkW5BgG:b-sewrv4) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L447)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

You could use subtests here ([`*testing.T).Run`](https://golang.org/pkg/testing/#T.Run), using the "name" field from "tt" as the subtest name. Your error messages could then be more concise, though the test name gets mangled somewhat.
</blockquote></details>

In this case I prefer following existing convention in the test file. 

---

*[cmd/helm/installer/install_test.go, line 457 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9p6s6eGKGDrTaBs1Y:-KnAmI0i06H04iQE2pm8:bqtyu4l) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L457)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

s/reflect/reflects/ or s/variable/variables/, depending on whether there is more than one variable.
</blockquote></details>

Removed line as it was stray from copy of existing test. Thanks for noticing it.

---

*[cmd/helm/installer/install_test.go, line 457 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9p51Xs39V-ocb7cGS:-KnAmWgSSpjIJFU7eoCf:b-6imlbg) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L457)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

s/tls/TLS/
</blockquote></details>

Removed comment.

---

*[cmd/helm/installer/install_test.go, line 457 at r8](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kn9opi6e_oiwlt8G3_o:-KnAiFqv4NKRdVo8sH8z:brtuu3v) ([raw file](https://github.com/kubernetes/helm/blob/92d3dd52c22e177dbc857876badddd1648d6da4d/cmd/helm/installer/install_test.go#L457)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Since the sentence is punctuated, capitalize the first word.
</blockquote></details>

Removed stray comment.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-06-21 19:00 UTC, seh commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.kubernetes.io/lgtm.png" height="20" width="61"/>
Thank you for your persistence. You suffered through me learning how to use Reviewable, which is quite complicated, but I think provides for good accountability through these iterative reviews.

---

Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-KnB0MeCfCckn0Vu-4ya:b-v566y)*
<!-- Sent from Reviewable.io -->

2017-06-21 19:04 UTC, jascott1 commented
@seh Thanks so much for all the insights! Its also my first time really working with Reviewable as well and so far I like it.

2017-06-24 21:15 UTC, kfox1111 commented on cmd/helm/installer/install.go
> +	nodeSelectors["beta.kubernetes.io/os"] = "linux"
Since nodeSelectors is added, can this go away now?

2017-06-24 21:15 UTC, kfox1111 commented
It tested this out. both args are working well. I think this is ready to merge if the windows hack isn't removed first.

2017-06-24 21:21 UTC, kfox1111 commented
I tried this ps to make it easier to run tiller as a static pod:

bin/helm init --net-host --output json | jq '.spec = .spec.template.spec | .kind="Pod" | .apiVersion="v1" | .spec.nodeSelector={} | .spec.volumes=[{"name":"kubeconf", "hostPath":{"path":"/etc/kubernetes/admin.conf"}}] | .spec.containers[0].volumeMounts=[{"name":"kubeconf", "mountPath":"/etc/kubernetes/admin.conf"}] | .spec.containers[0].command=["/bin/sh", "-c", "KUBECONFIG=/etc/kubernetes/admin.conf /tiller"]' > /etc/kubernetes/manifests/tiller.json

.nodeSelector had to be blanked out as the "linux" selector breaks the static pod... If that hack was removed, it woudln't be needed.

The user does need to tweak the generated file to point to a valid tiller image version. apparently KUBECONFIG support broke sometime after 2.3.0. :/ Will work on that elsewhere.

2017-06-24 21:25 UTC, kfox1111 commented
the KUBECONFIG issue raised here #2619

2017-06-26 17:53 UTC, jascott1 commented on cmd/helm/installer/install.go
> +	nodeSelectors["beta.kubernetes.io/os"] = "linux"
Im not sure about removing it. @thomastaylor312 what do you think?

2017-06-26 21:23 UTC, jascott1 commented
Waiting to get Taylor's input as he added the node selector workaround.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-KnaHGSw3nPL8bxGh4MJ:b-mgjn1j)*
<!-- Sent from Reviewable.io -->

2017-06-27 05:29 UTC, thomastaylor312 commented
@kfox1111 I am not sure if I understand why the node selector is causing a problem. Could you explain a little more?

2017-07-05 19:58 UTC, kfox1111 commented
@thomastaylor312 I'm using it as a static pod, and kubelet doesn't like a nodeSelector if its a static pod.

2017-07-06 05:03 UTC, thomastaylor312 commented
Ok, that makes sense @kfox1111. @jascott1 Let's just take out the default node selector. @technosophos would that count as breaking or do we just have to document it really well in the release?

2017-07-10 17:33 UTC, jascott1 commented
@thomastaylor312 We also have the new PR for deleting keys so we could go either way (either remove default nodeSelector or let user remove it after that PR lands).

2017-07-10 17:37 UTC, kfox1111 commented
The node selector was added as a stopgap till this ps landed. I think we should land this one without the default node selector and then users can do whatever they want to get it to land where they want.

2017-07-10 17:41 UTC, jascott1 commented
That makes sense to me. I will remove it from this PR unless others have strong feelings.

2017-07-10 18:46 UTC, thomastaylor312 commented
Nope, that sounds good to me

2017-07-11 01:20 UTC, thomastaylor312 commented
@jascott1 I am assuming now that you have removed the node selector, this is ready for @seh to look at again? Also, when you are completely ready, can you squash this down to fewer commits?

2017-07-11 13:20 UTC, seh commented
Reviewed 3 of 5 files at r10, 1 of 2 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/helm/init_test.go, line 352 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KolljfkgCy7tgiROIte:-KolljfkgCy7tgiROItf:b-vucrr3) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/init_test.go#L352)):*
> string(buf.Bytes())

That could be [`(*ByteBuffer).String`](https://golang.org/pkg/bytes/#Buffer.String) instead.

---

*[cmd/helm/installer/install.go, line 147 at r9](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmhclZ8q1_5g6591VYu-r9-147:-Kolm81kc9LXQ9GEINQV:b-wyh53w) ([raw file](https://github.com/kubernetes/helm/blob/5a0f8cca15249ff40b7c88b386f8580c4fa058f4/cmd/helm/installer/install.go#L147)):*
<details><summary><i>Previously, jascott1 (Justin Scott) wrote…</i></summary><blockquote>

Im not sure about removing it. @thomastaylor312 what do you think?
</blockquote></details>

Per [@kfox1111's comment](https://github.com/kubernetes/helm/pull/2557#issuecomment-314179365), we agreed to remove the default selector.

---

*[cmd/helm/installer/install_test.go, line 457 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KolmPsf1tSsI7QcmuSL:-KolmPsf1tSsI7QcmuSM:bun84ib) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/installer/install_test.go#L457)):*
> ```Go
> 			t.Fatalf("%s: error %q", tt.name, err)
> 		}
> 		// verify environment variable in deployment reflect the use of tls being enabled.
> ```

Capitalize "Verify," "Deployment," and "TLS."

---

*[cmd/helm/installer/install_test.go, line 492 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kolmc0zCyiaHJwLXwTl:-Kolmc1-UQxQsc48965K:b-nbuax) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/installer/install_test.go#L492)):*
> ```Go
> 		},
> 		/*
> 			// TODO test --set value nested beneath list
> ```

Do we intend to exercise this case now?
If not, remove this whole comment block and consider filing an issue requesting coming back through to address this case.

---

*[cmd/helm/installer/options.go, line 48 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KolnJtmXyOYWxT0oUYS:-KolnJtnOPWFhKsL1r3-:b-iik9tj) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/installer/options.go#L48)):*
> ```Go
> 
> 	// ServiceAccount is the Kubernetes service account to add to Tiller.
> ```

Remove blank line between the comment and the "ServiceAccount" field declaration.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-07-11 16:53 UTC, jascott1 commented
Done.

---

Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/helm/init_test.go, line 352 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KolljfkgCy7tgiROIte:-KomTiW_xE0vtxAPgGIh:bi986c3) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/init_test.go#L352)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> string(buf.Bytes())

That could be [`(*ByteBuffer).String`](https://golang.org/pkg/bytes/#Buffer.String) instead.
</blockquote></details>

Fixed. Thanks!

---

*[cmd/helm/installer/install.go, line 147 at r9](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KmhclZ8q1_5g6591VYu-r9-147:-KomTqnuxbUX7XbsTidL:b-8qnxay) ([raw file](https://github.com/kubernetes/helm/blob/5a0f8cca15249ff40b7c88b386f8580c4fa058f4/cmd/helm/installer/install.go#L147)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Per [@kfox1111's comment](https://github.com/kubernetes/helm/pull/2557#issuecomment-314179365), we agreed to remove the default selector.
</blockquote></details>

The default is gone but the mechanism to set them still exists.

---

*[cmd/helm/installer/install_test.go, line 457 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KolmPsf1tSsI7QcmuSL:-KomUVQsibL_1mWbHAck:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/installer/install_test.go#L457)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Capitalize "Verify," "Deployment," and "TLS."
</blockquote></details>

Done.

---

*[cmd/helm/installer/install_test.go, line 492 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Kolmc0zCyiaHJwLXwTl:-KomUC1wiGIKVmB0X88B:bss4a2b) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/installer/install_test.go#L492)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Do we intend to exercise this case now?
If not, remove this whole comment block and consider filing an issue requesting coming back through to address this case.
</blockquote></details>

Removed.

---

*[cmd/helm/installer/options.go, line 48 at r12](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KolnJtmXyOYWxT0oUYS:-KomUWVKG21A-5wzRfUi:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/4a1bd1ba594844f7ea6f3a5ff0798613a639943a/cmd/helm/installer/options.go#L48)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Remove blank line between the comment and the "ServiceAccount" field declaration.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-KomURnx6EfVH8cfwA4K:b-896fix)*
<!-- Sent from Reviewable.io -->

2017-07-11 17:06 UTC, seh commented
It's hard to follow how the _APIService_- and "kind sorter"-related commits wound up as part of this review.

---

Reviewed 6 of 6 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/downloader/manager.go, line 195 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomaV4MYP1juUDKhxTs:-KomaV4MYP1juUDKhxTt:b-q4ketb) ([raw file](https://github.com/kubernetes/helm/blob/79a24c76b81b9061c176431fcb8d2ac9e32401dd/pkg/downloader/manager.go#L195)):*
> ```Go
> // a conflict.
> func (m *Manager) downloadAll(deps []*chartutil.Dependency) error {
> 	repos, err := m.loadChartRepositories()
> ```

Consider bailing early if there are no dependencies present:
```go
if len(deps) == 0 {
  return nil
}
```

---

*[pkg/tiller/kind_sorter_test.go, line 122 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komanfks8WNgJ24VZZi:-KomanflmCx7WWlyyn5V:bm6h3mi) ([raw file](https://github.com/kubernetes/helm/blob/79a24c76b81b9061c176431fcb8d2ac9e32401dd/pkg/tiller/kind_sorter_test.go#L122)):*
> ```Go
> 		{
> 			name:    "w",
> 			content: "",
> ```

We delete this line in the competing #2667.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-Komb8wnXYyyKVlzazzz:bi3inoa)*
<!-- Sent from Reviewable.io -->

2017-07-11 17:34 UTC, jascott1 commented
@seh Those last reviews are not relevant anymore (to this PR) as I had forgotten to rebase again and they aren't included in this PR anymore.

2017-07-11 17:36 UTC, jascott1 commented
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/downloader/manager.go, line 195 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomaV4MYP1juUDKhxTs:-KomiGHXMhpTB9q3uY1d:b2nhjff) ([raw file](https://github.com/kubernetes/helm/blob/79a24c76b81b9061c176431fcb8d2ac9e32401dd/pkg/downloader/manager.go#L195)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Consider bailing early if there are no dependencies present:
```go
if len(deps) == 0 {
  return nil
}
```
</blockquote></details>

N/A

---

*[pkg/tiller/kind_sorter_test.go, line 122 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komanfks8WNgJ24VZZi:-KomiIQhRqgG0CZ2hDML:b2nhjff) ([raw file](https://github.com/kubernetes/helm/blob/79a24c76b81b9061c176431fcb8d2ac9e32401dd/pkg/tiller/kind_sorter_test.go#L122)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

We delete this line in the competing #2667.
</blockquote></details>

N/A

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557)*
<!-- Sent from Reviewable.io -->

2017-07-11 17:48 UTC, seh commented
I went through the files again one more time to focus on the complete set of changes, and found a few cosmetic nits. If you choose to ignore them, that's fine, as I know this one has been open for a long time.

---

Reviewed 1 of 2 files at r12, 1 of 6 files at r13.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/helm/installer/install.go, line 262 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komip8hNq5Jez_zDAo2:-Komip8hNq5Jez_zDAo3:b6z30qb) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install.go#L262)):*
> []byte(finalY)

It looks like "finalY" is already of type `[]byte` here, per the [`yaml.Marshal`](https://github.com/ghodss/yaml/blob/master/yaml.go#L15) signature.

---

*[cmd/helm/installer/install_test.go, line 424 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomjKrFMFM8Z_VORkOP:-KomjKrFMFM8Z_VORkOQ:bi8w10j) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L424)):*
> ```Go
> }
> func TestDeploymentManifest_WithNodeSelectors(t *testing.T) {
> 	//note 'beta.kubernetes.io/os": "linux"' is a default nodeSelector in helm init's deployment manifest
> ```

The comment formatting is odd here.
Consider adding an intervening space after the comment delimiter, capitalizing the first word, capitalizing "Deployment," and punctuating the sentence.

---

*[cmd/helm/installer/install_test.go, line 457 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komjjjd_ER7B0_0Iorr:-KomjjjeEPKwRMlhwSgL:b-wwnmq8) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L457)):*
> Verify environment variable

Since there can be more than one environment variable, write, "Verify that environment variables."

---

*[cmd/helm/installer/install_test.go, line 461 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komjv-P-Z66Oa9GCUmK:-Komjv-P-Z66Oa9GCUmL:bmhcftp) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L461)):*
> nodeselector

Should that be "nodeSelector?"

---

*[cmd/helm/installer/install_test.go, line 521 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komk3RFiCRpuC4hK1a-:-Komk3RFiCRpuC4hK1a0:bco1vef) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L521)):*
> ```Go
> 				t.Errorf("%s: expected value %q, got %q", tt.name, tt.expect, pv)
> 			}
> ```

Remove blank line.

---

*[cmd/helm/installer/options.go, line 76 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomkS1Xy34m9I6IWEN0:-KomkS1Xy34m9I6IWEN1:b1po4lz) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/options.go#L76)):*
> ```Go
> 	EnableHostNetwork bool
> 
> 	// NodeSelectors determine which nodes Tiller can land on
> ```

Punctuate this sentence.

---

*[cmd/helm/installer/options.go, line 79 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomkUYo3gmwWsjt73SX:-KomkUYo3gmwWsjt73SY:b1po4lz) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/options.go#L79)):*
> ```Go
> 	NodeSelectors string
> 
> 	// Output dumps the Tiller manifest in the specified format (e.g. JSON) but skips Helm/Tiller installation
> ```

Punctuate this sentence.

---

*[cmd/helm/installer/options.go, line 82 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomkVGBfzsJ_zJtA-IS:-KomkVGBfzsJ_zJtA-IT:b1po4lz) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/options.go#L82)):*
> ```Go
> 	Output OutputFormat
> 
> 	// Set merges additional values into the Tiller Deployment manifest
> ```

Punctuate this sentence.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-Komkk-lbAdtY2NTW0HL:bnh7rim)*
<!-- Sent from Reviewable.io -->

2017-07-11 18:08 UTC, jascott1 commented
I fixed them. Thanks for the excellent reviews as always!

---

Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/helm/installer/install.go, line 262 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komip8hNq5Jez_zDAo2:-Kommxw7EEO_xuxE-m8C:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install.go#L262)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> []byte(finalY)

It looks like "finalY" is already of type `[]byte` here, per the [`yaml.Marshal`](https://github.com/ghodss/yaml/blob/master/yaml.go#L15) signature.
</blockquote></details>

Done.

---

*[cmd/helm/installer/install_test.go, line 424 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomjKrFMFM8Z_VORkOP:-Komn4W44v5VHXmlYQjk:b-q3fsqi) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L424)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

The comment formatting is odd here.
Consider adding an intervening space after the comment delimiter, capitalizing the first word, capitalizing "Deployment," and punctuating the sentence.
</blockquote></details>

Removed the comment as we removed the default node selector entirely.

---

*[cmd/helm/installer/install_test.go, line 457 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komjjjd_ER7B0_0Iorr:-KomnM0w77ZcJ8b3ciK3:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L457)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> Verify environment variable

Since there can be more than one environment variable, write, "Verify that environment variables."
</blockquote></details>

Done.

---

*[cmd/helm/installer/install_test.go, line 461 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komjv-P-Z66Oa9GCUmK:-KomnSBnoOBLJQRdMQGK:b-am364n) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L461)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

> nodeselector

Should that be "nodeSelector?"
</blockquote></details>

Sure why not ;)

---

*[cmd/helm/installer/install_test.go, line 521 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-Komk3RFiCRpuC4hK1a-:-Komns4Mop8_XSUQ3Txm:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/install_test.go#L521)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Remove blank line.
</blockquote></details>

Done.

---

*[cmd/helm/installer/options.go, line 76 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomkS1Xy34m9I6IWEN0:-KomngtM7Jm0X6dUgdqN:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/options.go#L76)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Punctuate this sentence.
</blockquote></details>

Done.

---

*[cmd/helm/installer/options.go, line 79 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomkUYo3gmwWsjt73SX:-KomnjdmCBrFDLQZPkZE:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/options.go#L79)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Punctuate this sentence.
</blockquote></details>

Done.

---

*[cmd/helm/installer/options.go, line 82 at r14](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-KomkVGBfzsJ_zJtA-IS:-KomnmkaXLO_gtc0icJo:b-896fix) ([raw file](https://github.com/kubernetes/helm/blob/125062e842f9da149790e1a0c4dac5eeab5f4c61/cmd/helm/installer/options.go#L82)):*
<details><summary><i>Previously, seh (Steven E. Harris) wrote…</i></summary><blockquote>

Punctuate this sentence.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-KomoZkATFuDEo1unPCy:bczubga)*
<!-- Sent from Reviewable.io -->

2017-07-11 18:12 UTC, seh commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.kubernetes.io/lgtm.png" height="20" width="61"/>

---

Reviewed 3 of 3 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-KomqaxUE-RS-EowPljL:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-07-11 18:17 UTC, jascott1 commented
Woot!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/2557#-:-KomrfCmGw3kh-pvFxwQ:b-7yqb5t)*
<!-- Sent from Reviewable.io -->

2017-08-14 17:26 UTC, jascott1 commented
@technosophos can we get a milestone for this one?

2017-08-14 20:06 UTC, thomastaylor312 commented
@jascott1 I'm going to put this in 2.7 for now

2017-09-25 23:16 UTC, egeland commented
Would be great if the documentation for this would include an example of how to set a _node affinity_, and how to set a _toleration_. 👍

2017-10-06 01:12 UTC, thomastaylor312 commented
@jascott1 What is the status on this one? Will it be ready for 2.7?

2017-10-09 17:02 UTC, jascott1 commented
@thomastaylor312 I will rebase today and should be good to go. I will also add some examples @egeland

2017-10-10 01:08 UTC, thomastaylor312 requested changes
One super tiny constant missing a type and an optional nit then this is good to go

2017-10-10 11:46 UTC, kfox1111 commented
Had an idea for this. @jascott1 plz ping me tomorrow about it.

2017-10-10 18:05 UTC, jascott1 commented on cmd/helm/init.go
> +			const tm = `{"apiVersion":"extensions/v1beta1","kind":"Deployment",`
Thanks for catch! Fixed.

2017-10-10 18:06 UTC, jascott1 commented on cmd/helm/installer/options.go
> +	fmtYAML              = "yaml"
Not sure what I was thinking there either. Fixed.

2017-10-10 21:47 UTC, jascott1 commented
@thomastaylor312 I changed the `--set` to `--override` to not conflict with future enhancements.

2017-10-10 23:27 UTC, thomastaylor312 approved these changes

2017-10-10 23:27 UTC, thomastaylor312 commented
Approved pending CI

2017-10-10 23:30 UTC, merged