give an uniform check for release process
helm/helm pull request #2565
Opened 2017-06-10 13:34 UTC by yan234280533

give an uniform check for release process ，fixed #2538

2017-06-12 16:45 UTC, adamreese requested changes

2017-06-12 16:45 UTC, adamreese commented on pkg/tiller/release_server.go
> +func validateReleaseName(releaseName string) error {
This should return `errMissingRelease` if `releaseName == ""`

2017-06-12 16:45 UTC, adamreese commented on pkg/tiller/release_server_test.go
> +		if valid != (validateReleaseName(name) == nil) {
This test could be updated to check against specific errors
```
for name, err := range map[string]error{
  "nina pinta santa-maria": errInvalidName,
  "nina-pinta-santa-maria": nil,
  "": errMissingRelease,
  ...
```

2017-06-13 14:23 UTC, yan234280533 commented on pkg/tiller/release_server_test.go
> +		if valid != (validateReleaseName(name) == nil) {
@adamreese  Many thanks for you to review the code. I modified and fixed the code as you mentioned. Please help me to review the code, thanks a billion.

2017-06-13 23:53 UTC, adamreese approved these changes

2017-06-14 15:19 UTC, bacongobbler commented on pkg/tiller/release_server.go
> +	errInvalidName = errors.New("invalid release name")
any way we can return a more informative error as to why the release name is invalid? Something like "invalid release name. Must match regex \<insert ValidName regex here\>"

2017-06-15 02:16 UTC, yan234280533 commented on pkg/tiller/release_server.go
> +	errInvalidName = errors.New("invalid release name")
@bacongobbler  Many thanks for you review.  It a good idea, but   I worried is that it is return too long of the message.

Such as return  this error message:

errInvalidName = errors.New("invalid release name; must match  regex  ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$\  and the max length is 53 ")

2017-06-21 02:03 UTC, yan234280533 commented on pkg/tiller/release_server.go
> +	errInvalidName = errors.New("invalid release name")
@bacongobbler  I was modified the return message as which you suggested. Can you help me to review the commit again. So many thanks.

2017-06-22 16:05 UTC, technosophos commented
Thanks! Merging now.

2017-06-22 16:05 UTC, merged