Document that ingress may need service.type: NodePort
helm/helm pull request #2637
Opened 2017-06-30 05:59 UTC by IlyaSemenov

`helm create` creates a chart with the following section:

```yaml
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
```

This is quite deceitful because on Google Container Engine (one of the most popular Kubernetes provisioners) the default ingress controller does not work with service.type: ClusterIP, it requires service.type: NodePort:

<https://github.com/kubernetes/ingress/tree/master/controllers/gce>: *Remember that the GCE L7 is routing you through the NodePort service*
<https://github.com/kubernetes/kubernetes/issues/26508>: *nodeport is a requirement of the GCE Ingress controller (and cloud controllers in general)*

I think this comment should either be removed or amended correspondingly.

2017-06-30 06:21 UTC, IlyaSemenov commented
Bump for SLA.

2017-06-30 13:43 UTC, seh commented
I favor removing the comment, rather than recommending use of a _Service_ of type "NodePort," which is not necessary for other ingress controllers I've seen (those that run either in the cluster or at least have access to the cluster network). An ingress controller doesn't have to use the _Service_ cluster IP address at all; it can [track the _Endpoints_ backends and use them directly](https://github.com/kubernetes/contrib/issues/1140#issuecomment-226646458).

2017-06-30 14:59 UTC, seh requested changes

2017-06-30 14:59 UTC, seh commented on pkg/chartutil/create.go
> +  # Should be used with service.type: ClusterIP (or NodePort for certain ingress controllers).
- [ ] Remove this sentence.  
  Some ingress controllers can work with _Services_ that lack a cluster IP ("headless"), let alone them exposing a node port, so it's best to not say anything here about a particular type of _Service_ here, given that the requirements vary this much.

2017-06-30 14:59 UTC, seh commented on pkg/chartutil/create.go
> +  # Used to create Ingress record.
- [ ] Add the word "an" before "Ingress."

2017-07-02 21:56 UTC, seh approved these changes

2017-07-02 21:57 UTC, seh commented
Thank you for your contribution.

2017-07-02 21:57 UTC, merged