WIP: Adding APIService to the sort order
helm/helm pull request #2650
Opened 2017-07-06 21:23 UTC by arschles

This ensures that APIService resources are installed last and uninstalled first.

This is still a work in progress.

Fixes #2641

2017-07-06 21:48 UTC, arschles commented
@technosophos @adamreese @michelleN can one of you guys check this out and tell me if I'm on the right track?

2017-07-07 03:28 UTC, technosophos commented
@arschles Yes, this looks correct.

2017-07-07 16:05 UTC, arschles commented
@technosophos ok, I've removed the WIP from this

2017-07-07 21:12 UTC, seh requested changes
Please augment the unit test [`tiller.TestKindSorter`](https://github.com/arschles/kube-helm/blob/5ff75f84a6c2fc1cb326753aed790aa1ef82bd57/pkg/tiller/kind_sorter_test.go#L26-L167) in file _kind_sorter_test.go_ to cover the "APIService" kind as well. Note that the single-character names are assigned alphabetically in the expected installation order (at what's currently [line 150](https://github.com/arschles/kube-helm/blob/5ff75f84a6c2fc1cb326753aed790aa1ef82bd57/pkg/tiller/kind_sorter_test.go#L150)), so "APIService" would get the name "w."

2017-07-10 21:34 UTC, arschles commented
@seh thanks for pointing me in that direction - I've made the change in https://github.com/kubernetes/helm/pull/2650/commits/58a2d7b5c125871cd21b0593a792f3706516b3da

2017-07-10 23:36 UTC, seh approved these changes
Thank you for the unit test as well.

2017-07-10 23:37 UTC, merged