Add -a to helm list command
helm/helm pull request #2654
Opened 2017-07-07 09:27 UTC by mstrzele

2017-07-07 21:14 UTC, seh requested changes

2017-07-07 21:14 UTC, seh commented on cmd/helm/list.go
> +	f.BoolVar(&list.all, "all", "a", false, "show all releases, not just the ones marked DEPLOYED")
- [ ] I think you meant to use [`pflag.BoolVarP`](https://godoc.org/github.com/spf13/pflag#BoolVarP) here instead.

2017-07-08 22:43 UTC, mstrzele commented on cmd/helm/list.go
> +	f.BoolVar(&list.all, "all", "a", false, "show all releases, not just the ones marked DEPLOYED")
You're right. Thanks! 😃 Is it OK now?

2017-07-10 13:40 UTC, seh approved these changes
I agree that this change matches the behavior of the similar flag for "helm get values."

2017-07-10 13:42 UTC, merged