feat(*) add key helm.sh/hook-delete-policy to hook annotation
helm/helm pull request #2692
Opened 2017-07-17 03:34 UTC by DoctorZK

When "helm.sh/hook-delete-policy: hook-succeed" is provided in a hook's annotation, Tiller will automatically delete the hook after the hook is succeed. When "helm.sh/hook-delete-policy: hook-failed" is provided in a hook's annotation, Tiller will automatically delete the hook after the hook is failed.

Closes #1769

2017-07-21 04:41 UTC, thomastaylor312 commented
I am putting this in 2.7 for now because 2.6 is focused on stability. If that is going to be a big problem, we are open to discuss it 🙂

2017-08-08 01:49 UTC, thomastaylor312 commented
@DoctorZK Sorry for the delay on this. I'll try to get a review done later in the week and then we can merge after 2.6 gets cut

2017-08-09 01:15 UTC, DoctorZK commented
OK. Please feel free to contact me if you have any question about the pr.

2017-08-15 00:01 UTC, thomastaylor312 requested changes
One small naming change needed. Could you also add some documentation for this?

Otherwise, the functionality is all tested and good to go. I am super excited to see this feature!

2017-08-17 13:38 UTC, DoctorZK commented on pkg/tiller/hooks.go
> +				if exist {
OK， I will handle this bug in a new PR

2017-08-17 13:39 UTC, DoctorZK commented on pkg/hooks/hooks.go
> +	HookSucceed = "hook-succeed"
Excellent suggestion. I will fix this soon

2017-08-17 13:39 UTC, DoctorZK commented on pkg/tiller/hooks.go
> +// 		annotations:
Good Suggestion

2017-08-19 23:46 UTC, thomastaylor312 commented
Thank you for the fixes @DoctorZK! Can you add some documentation for the new feature? It should be good to go once we have that

2017-08-21 02:36 UTC, DoctorZK commented
Sure

2017-08-25 02:36 UTC, thomastaylor312 commented
Thank you for the docs. This is good to go!

2017-08-25 02:36 UTC, thomastaylor312 approved these changes

2017-08-25 02:36 UTC, merged

2017-08-25 05:41 UTC, redbaron commented
How can I achieve that Job is deleted either way? Successful or not, I don't want it to block further updates of a given release.

2017-08-25 07:07 UTC, DoctorZK commented
It would not block further updates since hook deletion is an asynchronous request. Also because of the asynchronous request, we can not achieve that the Job is deleted or not. What we do now is just sending the request to K8S apiserver and making sure the apiserver hase successfully recieved the request.

2017-08-25 08:18 UTC, redbaron commented
@DoctorZK, maybe I misunderstood code, but it seems that async request to delete Job will be sent if Job succeeded or fail, there is no way to specify "delete job irrespective of exit status", right?  So there can be a situation where subsequent helm release will fail due to job still present and there is no way to prepare helm chart in such way that it works for all the cases, in other ways I can't say:

```
"helm.sh/hook-delete-policy": ["hook-succeeded", "hook-failed"]
```

is this case covered somehow else?

2017-08-25 16:29 UTC, thomastaylor312 commented
@redbaron You can specify both. I tried it and it deleted it irrespective of the exit code

2017-08-25 16:30 UTC, thomastaylor312 commented
Oh, but the syntax is `"helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"`