feat(*): add k8s version to version debug cmd
helm/helm pull request #2754
Opened 2017-08-02 17:42 UTC by rbwsam

When 'helm version --debug' is run, this will print the kubernetes server
version as well as the helm client and server versions.

Closes #1398 

---

I'm wide open to feedback - I'm here to learn!

I think it would make sense to also move the tiller version code to the new `InfoService` but I didn't want to include that in this PR since it's probably a breaking change.

2017-08-02 17:44 UTC, rbwsam commented on pkg/proto/hapi/chart/chart.pb.go
> -// Code generated by protoc-gen-go. DO NOT EDIT.
I made sure I built this with libprotoc 3.2.0 but the comments are still different...

2017-08-31 18:47 UTC, technosophos commented
Sorry for being late on this one. Would it be easier to just run the query from the client directly to the Kubernetes API server instead of adding a Tiller roundtrip? (For example, see the tunnel code). Then we wouldn't have to modify the proto at all.

2017-09-01 20:48 UTC, rbwsam commented
Great point! I will make that change and update the PR.

2017-10-31 17:26 UTC, bacongobbler requested changes

2017-10-31 17:26 UTC, bacongobbler commented on cmd/helm/version.go
> +	if settings.Debug {
hey! Sorry about the long wait on the review here.

Would you mind moving this after line 106? If we're making a server-side call to check the kubernetes version, we will want to respect the `--client-only` flag.

2017-12-04 20:08 UTC, jascott1 commented
Hi @rbwsam Thanks for the PR! It looks like we are one small change away from being mergeable. Do you think you will be able to continue working on this?

2017-12-05 09:05 UTC, rbwsam commented
@jascott1 Yes I am happy to make the changes, expect them in the next 48 hours.

2017-12-28 23:37 UTC, bacongobbler approved these changes
This is a fantastic enhancement. Thanks @rbwsam!

2017-12-28 23:37 UTC, merged