CircleCI 2 config
helm/helm pull request #2838
Opened 2017-08-22 13:58 UTC by nebril

All basic test jobs are running in parallel, there could be some improvements here and there, but it works.

Not sure about deployment job, @adamreese @thomastaylor312 PTAL.

2017-08-22 19:31 UTC, thomastaylor312 commented
I'll take a look at this tonight. I'll give the deployment stuff a look too, but I am betting that @adamreese knows the most

2017-08-23 17:28 UTC, adamreese commented on .circleci/config.yml
> +          command: wget "https://storage.googleapis.com/golang/go${GOVERSION}.linux-amd64.tar.gz" -O "${HOME}/go${GOVERSION}.tar.gz" && tar -C /usr/local -xzf "${HOME}/go${GOVERSION}.tar.gz"
The installing go steps can be removed because it is running in the `golang:1.8` image

2017-08-23 17:28 UTC, adamreese commented on .circleci/config.yml
> +          name: update PATH
Can all this path munging be removed now?

2017-08-23 17:38 UTC, thomastaylor312 commented on .circleci/config.yml
> +          name: update PATH
I had to manually add the Go bin in last time I did a Circle 2 file

2017-08-23 17:52 UTC, thomastaylor312 requested changes
Some changes needed, but this looks pretty good. If you have any questions about my comments please let me know 🙂

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +      - run:
Likewise here, the go installation steps can be pulled out

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +      WORKDIR: "/root/.go_workspace/src/k8s.io/helm"
We won't need `WORKDIR` any more. We can now set the working directory with `working_directory`. See an example [here](https://github.com/thomastaylor312/helm-commandeer/blob/master/.circleci/config.yml#L4)

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +          command: mkdir -p "$(dirname ${WORKDIR})" && mv "${HOME}/project" "${WORKDIR}"
You won't need this with `working_directory` specified

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +          command: cd "${WORKDIR}" && make bootstrap
Won't need the `cd` any more with `working_directory`

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +          name: install dependencies
I would cache the dependencies after they are installed and restore the cache in future build steps (unless we end up using workflows). See the docs [here](https://circleci.com/docs/2.0/configuration-reference/#save_cache)

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +jobs:
Obviously out of scope for this PR, but I wanted to capture somewhere that we should probably use `workflows` in the future to make some of these jobs (not steps) run at the same time

2017-08-23 17:52 UTC, thomastaylor312 commented on .circleci/config.yml
> +    parallelism: 4
I am not sure if this is going to have the behavior we want. It is going to try and run each step of this job in parallel. See the docs [here](https://circleci.com/docs/2.0/parallelism-faster-jobs/) and [here](https://circleci.com/docs/2.0/configuration-reference/#build).

2017-08-23 17:53 UTC, thomastaylor312 commented on .circleci/config.yml
> +    parallelism: 4
To clarify, I worry about it trying to run the tests and `make bootstrap` at the same time. Have you run into those issues?

2017-08-24 08:37 UTC, nebril commented on .circleci/config.yml
> +          command: wget "https://storage.googleapis.com/golang/go${GOVERSION}.linux-amd64.tar.gz" -O "${HOME}/go${GOVERSION}.tar.gz" && tar -C /usr/local -xzf "${HOME}/go${GOVERSION}.tar.gz"
True.

2017-08-24 08:38 UTC, nebril commented on .circleci/config.yml
> +    parallelism: 4
Each parallel build instance has it's own container, so it should be fine.

2017-08-24 08:38 UTC, nebril commented on .circleci/config.yml
> +      WORKDIR: "/root/.go_workspace/src/k8s.io/helm"
True, will fix

2017-08-24 08:39 UTC, nebril commented on .circleci/config.yml
> +      - run:
Will do

2017-08-24 08:39 UTC, nebril commented on .circleci/config.yml
> +          command: mkdir -p "$(dirname ${WORKDIR})" && mv "${HOME}/project" "${WORKDIR}"
Will fix

2017-08-24 08:39 UTC, nebril commented on .circleci/config.yml
> +          name: install dependencies
Didn't find these docs, thanks!

2017-08-24 08:39 UTC, nebril commented on .circleci/config.yml
> +          command: cd "${WORKDIR}" && make bootstrap
kk, thanks

2017-08-24 09:51 UTC, nebril commented
@thomastaylor312 thanks for the feedback, fixes resulted in much smaller config file

2017-08-24 09:51 UTC, nebril commented on .circleci/config.yml
> +jobs:
Makes sense, we can track it in an issue after this PR is merged

2017-08-24 16:46 UTC, thomastaylor312 approved these changes
This is looking great! Thanks @nebril! I'll wait for @adamreese to sign off too because he started the review

2017-08-31 14:51 UTC, adamreese commented
Let merge after the 2.6.1 release

2017-09-05 19:32 UTC, adamreese commented
@nebril Feel free to merge this, just ping me when you do

2017-09-07 07:21 UTC, merged