Fix(helm): fix the bug of helm search --regexp
helm/helm pull request #2876
Opened 2017-08-30 14:03 UTC by rocky-nupt

helm search cannot search for upper case by --regexp, because it
lowers all the letters when build repo index.

Closes #2865

2017-08-31 18:34 UTC, technosophos commented
If I understand it, the new logic would make it so that a search for `github` would fail for a chart that had `GitHub` or `Github` or `gitHub` in the name. That was not the intention of the initial design.

I think we'd need to modify the SearchLiteral query to do a regexp with the `i` modifier to preserve backward compatibility. So `helm search github` should return results for `github`, `GitHub`, etc.

I think case sensitivity for regexp-based searches is fine, though.

2017-09-01 02:48 UTC, rocky-nupt commented
Sorry, I don't know the intention of the initial design. I have changed the PR. Now helm search doesn't have case sensitivity while helm search --regexp still has. @technosophos

2017-09-04 13:26 UTC, nebril requested changes
Looks like a good change, please revise tests as asked.

2017-09-04 13:26 UTC, nebril commented on cmd/helm/search/search_test.go
> -			query: "two",
These test cases still need to pass, please add uppercase test cases as additional cases.

2017-09-04 13:26 UTC, nebril commented on cmd/helm/search/search.go
> -	return strings.ToLower(i)
This change should be covered with unit tests (I think TestAddRepo_Sort should be altered for this).

2017-09-06 04:30 UTC, rocky-nupt commented
Thanks for your review! I have added an uppercase test and altered TestAddRepo_Sort. Is it ok? @nebril

2017-09-06 08:57 UTC, nebril approved these changes
LGTM!

2017-09-06 08:57 UTC, nebril commented on cmd/helm/search/search_test.go
> +			query: "Th[ref]*",
Looks much better, but I have to be picky here: this change in test case is unaffected by your logic changes. It's really minor, so I will approve this PR.

2017-09-28 03:27 UTC, thomastaylor312 commented
@nebril Are you going to merge this one or are you waiting on something?

2017-09-28 10:37 UTC, merged