UnmarshalChartfile never retur
helm/helm pull request #2946
Opened 2017-09-18 11:17 UTC by carlory

2017-09-18 11:24 UTC, carlory commented
/test

2017-09-18 11:24 UTC, carlory commented
/retest

2017-09-28 10:23 UTC, nebril requested changes
Hi! Can you please explain why exactly do you want this function to return nil? Empty string is perfectly valid yaml AFAIK and it seems sensible to just unmarshal it regardless of its length and return empty Metadata.

2018-01-19 19:21 UTC, bacongobbler commented
closing as stale.

2018-01-19 19:21 UTC, closed without merging