feat(helm): add --format flag to 'helm list'
helm/helm pull request #2950
Opened 2017-09-18 19:45 UTC by rbwsam

When 'helm list --format (text|json|yaml) is run, this will print the list
of releases in the specified format.

WIP #1534

2017-09-19 17:33 UTC, jascott1 commented
Hi @rbwsam, 
Thanks for the PR. We have discussed this elsewhere as `-o | --output` to be consistent with `kubectl` and also we have a prior PR that we need to reconcile with your work here. https://github.com/kubernetes/helm/pull/2836

2017-09-19 18:28 UTC, rbwsam commented
@jascott1 `-o` is already being used for `-o, --offset` in `helm list`. What flag do you suggest we use for this situation?

2017-09-19 18:35 UTC, jascott1 commented
@rbwsam Sorry I didn't realize that. I guess we can roll with your original suggestion unless someone else has another idea. The `-o` inconsistency will bug me forever :/

2017-09-28 09:15 UTC, alexey-medvedchikov commented
:+1: 
Waiting for this PR to be merged: I've implemented kubectl `go-template`-like behavior for it.

2017-11-21 19:24 UTC, mrgleeco commented
is this PR DOA? This is a killer feature..

2017-11-21 23:19 UTC, rbwsam commented
If there are any changes required so this can get merged I am happy to oblige.

2017-12-29 18:36 UTC, bacongobbler commented
Thasnks @rbwsam. We were all at KubeCon and then ran straight into the holidays. I'm finally coming out of holiday mode. I'll take a look at this now. Thanks for your patience!

2017-12-29 18:40 UTC, bacongobbler requested changes

2017-12-29 18:40 UTC, bacongobbler commented on cmd/helm/list.go
> +	case "short":
can you add this to the list of supported output formats in the docstring?

2017-12-29 18:40 UTC, bacongobbler commented on cmd/helm/list.go
> +	fmt.Fprint(l.out, formatted)
have you tested this change with the text and short output formats? Looks fine, but just want to make sure that this has been tested.

2017-12-29 18:40 UTC, bacongobbler commented on cmd/helm/list_test.go
> +		},
can we add a "short" list format test as well?

2018-01-19 19:24 UTC, bacongobbler commented
ping, looks like this PR needs a rebase as well as the above comments. We're cutting v2.8.0 next week so if you'd like to get this PR in, now's a good time to fix it up :)

2018-02-06 16:11 UTC, mattfarina commented
@rbwsam I'd like to get this into Helm 2.9. I'm happy to support you in cleaning it up or in taking over the work myself.

2018-02-28 12:35 UTC, michelleN commented
ping @rbwsam - We'd love to see this go through. Any luck on addressing those comments above?

2018-02-28 15:21 UTC, alexey-medvedchikov commented
Have some work made upon this PR so will make another PR with lunapark and stuff if original poster won't appear in nerest time :)

2018-04-18 19:29 UTC, seaneagan commented
Since there wasn't much activity here of late and we have been looking forward to this functionality I went ahead and took a shot at this in #3923.

@rbwsam

2018-07-18 15:12 UTC, mindw commented
/remove-lifecycle stale

2018-07-18 21:34 UTC, au-phiware commented
Can this be closed now, since #3923?

2018-07-18 21:49 UTC, bacongobbler commented
yes, thank you @au-phiware for pointing that out. :)

2018-07-18 21:49 UTC, closed without merging