fix(helm): Set template context inside tpl function to outer function.
helm/helm pull request #3061
Opened 2017-10-24 22:22 UTC by eicnix

docs(helm): Added documentation about tpl function

Fix for https://github.com/kubernetes/helm/issues/3054

The Template Name of BasePath of the outer template which calls the tpl function will now be set during the execution of the tpl function.

2017-10-26 16:07 UTC, mparry commented
Hi - I was looking at this problem locally a bit today, out of curiosity. The issue seemed to me to be where it is injecting `.Template` into the values during the `render()` call:

```
vals := tpls[file].vals
vals["Template"] = map[string]interface{}{"Name": file, "BasePath": tpls[file].basePath}
```

The `vals` structure here is the real global values, and so the real `.Values.Template` gets overwritten as soon as `tpl` is called. Wouldn't it be better to just avoid this injection altogether when `render()` is called by `tpl`, rather than making the dummy template in `tpl` pretend that it is the real top level one?

For example:

```
if _, ok := vals["Template"]; !ok {
	vals["Template"] = map[string]interface{}{"Name": file, "BasePath": tpls[file].basePath}
}
```

(Or else perhaps an explicit parameter to `render()`.)

2017-10-26 18:39 UTC, eicnix commented
I get your point and it should be decided if running `tpl` should be treated as a sub rendering processes or an independent rendering process. Based on this decision the template variable should either point to the outer template or to a `tpl` template.

2017-11-01 23:53 UTC, bacongobbler requested changes
can we also add unit tests here to ensure this won't break again? Thanks!

2017-11-01 23:53 UTC, bacongobbler commented on pkg/engine/engine.go
> +		println(vals.Table)
this needs to be removed

2017-11-01 23:54 UTC, bacongobbler commented
also looks like we need a rebase. Thanks!

2017-12-03 16:43 UTC, eicnix commented
Hi @bacongobbler,

I made the changes you requested:
* removed debug statement
* changed existing unit test to include this specific behaviour
* rebased branch

2017-12-03 17:05 UTC, eicnix commented on pkg/engine/engine.go
> +		println(vals.Table)
Debug statement removed

2017-12-28 23:12 UTC, bacongobbler approved these changes

2017-12-28 23:12 UTC, merged