WIP: support output-dir when running 'helm template'
helm/helm pull request #3144
Opened 2017-11-15 08:49 UTC by rajatjindal

Its a work in progress right now.

if --output-dir provided, helm template will create the files instead of printing on stdout.

while doing so, the directory structure of the output files will be same as directory structure of input template files.

2017-11-15 09:23 UTC, rajatjindal commented
@technosophos can you please review.

2017-11-15 18:53 UTC, rajatjindal commented
cc'ing @bacongobbler also - didn't realize he pinged on helm-users suggesting to open PR with helm project

2017-11-15 19:02 UTC, bacongobbler commented
Thanks! We'll take a look at this eventually. We've got a lot on our plates at this time, but we'll come back around when we're doing another round of reviews.

2017-11-15 20:46 UTC, rajatjindal commented
sure, thank you

2017-11-21 18:27 UTC, technosophos requested changes
This is looking great. I left a few comments to remove `panic`. For the most part, our coding convention is to avoid panic unless something really, really bad happens. So just returning `error` objects is preferable in most cases.

Otherwise, this looks great.

2017-11-21 18:27 UTC, technosophos commented on cmd/helm/template.go
> +func writeToFile(outputDir string, name string, data string) {
Can we have this return an `error` and not `panic` when the create/write fails?

2017-11-21 18:27 UTC, technosophos commented on cmd/helm/template.go
> +			panic(fmt.Sprintf("output-dir '%s' does not exist", t.outputDir))
This should return an error like the `fmt.Errorf()` call a few lines above.

2017-11-21 18:27 UTC, technosophos commented on cmd/helm/template.go
> +func ensureDirectoryForFile(file string) {
Again, just returning an error instead of panicing is our preference.

2017-11-21 19:09 UTC, technosophos approved these changes
Updated PR LGTM! Thanks for making the changes.

2017-11-21 19:10 UTC, merged