fix(helm): Init not creating local-index symlink on Windows
helm/helm pull request #3233
Opened 2017-12-05 16:15 UTC by pietromenna

os.Symlink required additional permissions on Windows, and init is not currently identifying the failed creation.

Related to #2071

2017-12-05 17:00 UTC, bacongobbler requested changes
Left a comment on Slack about how we should approach this with conditional build tags: https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

2017-12-13 18:41 UTC, bacongobbler requested changes

2017-12-13 18:41 UTC, bacongobbler commented on cmd/helm/init_unix.go
> +// +build darwin dragonfly freebsd linux nacl netbsd openbsd solaris
you can change this to `// +build !windows` to simplify this.

2017-12-13 18:41 UTC, bacongobbler commented on cmd/helm/init_windows.go
> +/*
You'll need to add a build tag here e.g. `// +build windows`

2017-12-13 22:40 UTC, pietromenna commented
Hi @bacongobbler .

I incorporated the changes as you suggested.

2017-12-13 22:42 UTC, bacongobbler approved these changes

2017-12-29 18:33 UTC, bacongobbler commented
The CI failure was something we fixed 2 weeks ago and isn't relevant to this PR. Merging!

2017-12-29 18:33 UTC, merged