Added support for export-values in requirements
helm/helm pull request #3243
Opened 2017-12-09 18:19 UTC by withnale

See issue #3242 

There is a need for an `export-values` method when working with requirements.

The attached PR approaches this by mimicking the `import-values` functionality but in the other direction - allowing you to specify the tree in the parent chart you wish to export into the values of the child chart.It also allows you to _ringfence_ settings to a duplicate (aliased) subchart, as can be seen in the example below:

```
dependencies:
      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        tags:
          - front-end
          - subchart1
        export-values:
          - child: release
            parent: release.old

      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        export-values:
          - child: release
            parent: release.new
        alias: subchart1a
```
Obviously, this simple use case can be achieved through other methods - it's when there are many requirements using a mix & match of various parent values that this change become effective.

2017-12-29 18:01 UTC, bacongobbler commented
Would you mind writing some documentation on this feature? I don't quite understand the 5 W's for this PR so a little context for users trying to use this new feature would be very helpful. Thank you!

2018-01-05 23:25 UTC, jascott1 commented on pkg/chartutil/requirements.go
> +	// import values from each dependency if specified in import-values
import should be export in comment

2018-01-05 23:25 UTC, jascott1 commented on pkg/chartutil/requirements_test.go
>  func verifyRequirementsImportValues(t *testing.T, c *chart.Chart, v *chart.Config, e map[string]string) {
Can you add separate test for export values that exercises 3 levels of nesting?

2018-01-05 23:27 UTC, jascott1 requested changes
Should we consider merging some of the import and export code? Perhaps we can just pass in a func that gets executed in the reqs loop.

2018-04-23 09:38 UTC, rawkode commented
Hi @withnale,

Hopefully you can pick this back up and I need exactly this :grinning: 

@bacongobbler I think a solid use-case here is using generic charts for multiple deployments.

I have a service-oriented application and I want the ability to deploy everything at once. This means I have a `web` Chart that can deploy any image with a service and ingress, provided I specify the TLS secret and DNS names.

I was looking at this syntax, but the syntax above would work just as well:

```yaml
dependencies:
 -  name: web
    version: 1.0.0
    repository: "https://example.com/charts"
    values: website1.com.yaml
 -  name: web
    version: 1.0.0
    repository: "https://example.com/charts"
    values: website2.com.yaml
```

2018-06-22 10:53 UTC, closed without merging

2018-06-22 11:51 UTC, rawkode commented
@bacongobbler @withnale I believe this functionality is very useful for a few use-cases. I'm happy to pick this up if there's confidence that it will be merged?

2018-10-25 10:47 UTC, withnale commented
@bacongobbler - it's been a long time and I kinda thought this had been merged, but now I actually need it again!

If I update the PR is it likely to be merged in?

2020-01-27 08:59 UTC, withnale commented
/reopen