WIP: Tiller logs streaming
helm/helm pull request #3263
Opened 2017-12-15 12:25 UTC by damour

This is proof-of-concept streaming tiller logs using grpc server streaming RPC.
Alternative to https://github.com/kubernetes/helm/pull/2342

Example outputs for command
helm install stable/redis --dry-run

Helm (upstream) + Tiller (upstream) - ok, with logs
performing install for 
NAME:   guilded-eel

Helm (upstream) + Tiller 1.7 - ok, without logs
NAME:   bald-goat

Helm 1.7 + Tiller (upstream) - ok, without logs
NAME:   virtuous-wolverine

So, backward compatibility don't breaking.

Maybe I missed something. Please take a look, is this the proper solution.

2017-12-15 17:26 UTC, bacongobbler commented
There are a few backwards incompatible changes here in the RPC protocol which would block this from being merged in its current state. Any way we can implement the log streaming as a separate API?

2017-12-15 18:01 UTC, damour commented
Thanks for your prompt response! Sorry for stupid question (I don't have experience with grpc). According to docs adding new fields don't breaking BC, old clients ignore them. Can you please provide example what exactly broken?

2017-12-22 16:33 UTC, bacongobbler requested changes

2017-12-22 16:33 UTC, bacongobbler commented on _proto/hapi/services/tiller.proto
> +	rpc InstallRelease(InstallReleaseRequest) returns (stream InstallReleaseResponse) {
returning a streamed response instead of a regular response is what will break existing clients.

2017-12-22 16:33 UTC, bacongobbler commented on _proto/hapi/services/tiller.proto
> +	oneof response {
this also significantly changes the response. Clients will now need to handle whether the incoming response is either a log item or an actual release object.

2017-12-22 16:33 UTC, bacongobbler commented on pkg/helm/client.go
> +	for {
I rest my case. :)

2018-01-05 20:25 UTC, damour commented
@bacongobbler I write a small example for checking backwards compatibility(added oneof and response type changed to stream).
Everything works fine (at least with golang lib). Old client ignores new fields and works with stream response without code changing.
Please [take a look](https://github.com/damour/grpc-demo).
Demo video:
[![video](https://img.youtube.com/vi/hfUGLy2kSs0/0.jpg)](https://www.youtube.com/watch?v=hfUGLy2kSs0)

2018-03-11 00:39 UTC, johngmyers commented
I would like the option for the client to demux the log files, writing them in a directory so they can be published as build artifacts. So if `LogItem` could have a separate field with a log filename instead of embedding that data in the message where it can't be unambiguously extracted, that would be better.

2019-09-30 18:28 UTC, bacongobbler commented
Closing this PR due to inactivity. If someone is interested in pushing this along the finish line, please write a PR against Helm 3. As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Thanks!

2019-09-30 18:28 UTC, closed without merging