fix(helm):  Display debug release info when upgrade failed because of timeout
helm/helm pull request #3438
Opened 2018-02-01 21:32 UTC by splisson

When an upgrade fails because of a timeout waiting for it to be ready, in debug mode, output the release content.

Closes #3020

2018-05-10 21:40 UTC, thomastaylor312 approved these changes
This looks good to me. Sorry for the really long delay, this somehow slipped through the cracks in my notifications.

2018-05-10 21:40 UTC, thomastaylor312 commented
@bacongobbler Before I merge, do you think this is something we could bring into the next bug fix release?

2018-05-10 21:48 UTC, splisson commented
No problem. Thanks for your work maintaining helm

Sébastien

> On May 10, 2018, at 14:40, Taylor Thomas <notifications@github.com> wrote:
> 
> @thomastaylor312 approved this pull request.
> 
> This looks good to me. Sorry for the really long delay, this somehow slipped through the cracks in my notifications.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-05-10 22:01 UTC, thomastaylor312 requested changes
@splisson Hey, sorry to reset my review on this, but can you add this same logic to the `install` and `rollback` commands? It works great in `upgrade`, but it should have parity across the other commands as well

2018-05-10 23:48 UTC, thomastaylor312 commented on cmd/helm/install.go
> +	if (resp == nil || resp.Release == nil) && i.wait {
Should this be wrapped with `settings.Debug`?

2018-05-10 23:54 UTC, thomastaylor312 commented on cmd/helm/install.go
> +	if (resp == nil || resp.Release == nil) && i.wait {
Actually, I looked some more into this. I think it should be `i.printRelease` which is where it prints debug

2018-05-10 23:58 UTC, thomastaylor312 commented
Ok @splisson, now that I have my head on straight and am not trying to do multiple things at once, it looks like `rollback` never printed anything before and I thought it did. Also, the install needs to use `i.printRelease`, which isn't intuitive I know. So I would remove the change to rollback and make a slight adjustment to the `install` logic and then this is good to go. 

I apologize for all of the confusion, 100% my fault.

2018-05-11 00:12 UTC, splisson commented
The existing trace for sure install did not have it before 

Sébastien

> On May 10, 2018, at 16:48, Taylor Thomas <notifications@github.com> wrote:
> 
> @thomastaylor312 commented on this pull request.
> 
> In cmd/helm/install.go:
> 
> > @@ -264,23 +264,33 @@ func (i *installCmd) run() error {
>  		helm.InstallDisableHooks(i.disableHooks),
>  		helm.InstallTimeout(i.timeout),
>  		helm.InstallWait(i.wait))
> -	if err != nil {
> -		return prettyError(err)
> +
> +	// If there is an error while waiting, make a call without waiting to get the release content
> +	if (resp == nil || resp.Release == nil) && i.wait {
> Should this be wrapped with settings.Debug?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-05-11 16:14 UTC, thomastaylor312 commented
Yeah, in `install` you shouldn't need the `if settings.Debug` block, just the call to `printRelease` should be switched to `i.printRelease`

2018-05-14 18:06 UTC, thomastaylor312 commented
@bacongobbler Yeah, this has evolved since my original comment when I mentioned you 🙂

2018-06-08 15:42 UTC, bacongobbler commented
ping

2018-06-08 17:33 UTC, splisson commented
I added the change in install.go , Rebased and resolved conflicts. The test that is failing now is looking for a file I don't see in master on main repository neither

2018-06-08 20:55 UTC, splisson commented
Looks ok now

2018-06-11 23:52 UTC, bacongobbler commented
hmm, looks like the rebase went bad actually. Could you please fix this PR? Thanks so much!

2018-06-11 23:53 UTC, bacongobbler requested changes
needs a clean rebase

2018-06-12 01:55 UTC, splisson commented
the rebase included 200+ previous commits that happened between the time I did my last commit and now. Isn't that expected ?

2018-06-12 02:35 UTC, splisson commented
I'll prepare a fresh PR from a new branch

2018-06-12 02:44 UTC, splisson commented
Closing. Replaced by PR https://github.com/kubernetes/helm/pull/4207

2018-06-12 02:44 UTC, closed without merging

2018-06-13 04:51 UTC, splisson commented
@bacongobbler I submitted a new PR #4207