update docs to demonstrate best practices in regards to named templates
helm/helm pull request #3510
Opened 2018-02-14 21:23 UTC by mueedc

This PR modified named template documentation:

- update helper examples to demonstrate namespace best practices

- highlight that templates names are global at the top of the documentation

address #3487

2018-02-14 21:46 UTC, jascott1 commented
Hi @mueedc 

This is looking great! I notice that you have moved the helper naming explanation closer to the top (thanks). Can we simply and reword the second occurrence of that same text? Perhaps leading with something like "As noted above, **template names are global...** etc"

2018-02-14 21:59 UTC, mueedc commented
Oh yeah absolutely. Gotta be DRY with our code and docs

2018-02-15 11:33 UTC, unguiculus requested changes

2018-02-15 11:33 UTC, unguiculus commented on docs/chart_template_guide/named_templates.md
> +One popular naming convention is to prefix each defined template with the name of the chart: `{{ define "mychart.labels" }}` or `{{ define "mychart_labels" }}`. By using the specific chart name as a
Please use `{{ define "mychart.labels" }}` only. This is also what `helm create` does and what we expect as best practice in the charts repo.

2018-02-15 11:33 UTC, unguiculus commented on docs/chart_template_guide/named_templates.md
> +{{- define "mychart_labels" }}
Use `{{- define "mychart.labels" }}` everywhere. See above.

2018-02-16 18:41 UTC, jascott1 requested changes
Looking great! Can you rebase/squash this into one commit? Then we should be good.

2018-02-16 19:22 UTC, closed without merging