update docs to demonstrate best practices in regards to named templates
helm/helm pull request #3524
Opened 2018-02-16 19:29 UTC by mueedc

This PR modified named template documentation:

update helper examples to demonstrate namespace best practices

highlight that templates names are global at the top of the documentation

address #3487
(opened a new PR in reference to #3510, I was not sure if I rebase/squashed correctly and did not want to mess with anything)

2018-02-16 19:30 UTC, mueedc commented
@jascott1 @unguiculus I'd love any resources you could recommend on how to properly git rebase/squash commits

2018-02-16 20:25 UTC, jascott1 approved these changes

2018-02-16 20:30 UTC, jascott1 commented
@mueedc Rebase is worth understanding and the git-scm book covers this and more here [here](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History). If you want to learn git from the ground up I have found this to be helpful https://learngitbranching.js.org/

2018-02-16 20:32 UTC, jascott1 commented
BTW Since this is a large commit we will need another core to agree and merge.

cc @bacongobbler @SlickNik

2018-02-16 20:37 UTC, mueedc commented
I have a base understanding of git but a refresher is never a bad idea. Thanks so much!

2018-02-16 20:44 UTC, bacongobbler commented
looks like the indentation for the templates were accidentally changed from 2 spaces to 1 space during the rebase. Is there any way you could revert that back? :)

Also cc'ing @unguiculus in case he wants to give it a once-over one more time to make sure all his comments were addressed. :)

2018-02-16 21:14 UTC, jascott1 commented
Thanks @bacongobbler!

2018-02-16 22:41 UTC, mueedc commented
I fixed the spacing issue, and I believe I rebase/squashed the commits down to 1. Hope I did that correctly

2018-02-16 23:39 UTC, jascott1 requested changes
Please fix the indentations. All YAML should use 2 spaces of indentation for each level of nested keys.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + myvalue: "Hello World"
Needs another space as does following 3 lines.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + name: running-panda-configmap
Fix spacing for this section too.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + myvalue: "Hello World"
Fix spacing for this section.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + name: moldy-jaguar-configmap
Fix spacing.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + name: plinking-anaco-configmap
Fix spacing.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + name: measly-whippet-configmap
Fix spacing.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + name: edgy-mole-configmap
Fix spacing.

2018-02-16 23:39 UTC, jascott1 commented on docs/chart_template_guide/named_templates.md
> + name: {{ .Release.Name }}-configmap
Fix spacing.

2018-02-16 23:49 UTC, jascott1 commented
@mueedc You are looking for `git rebase -i master` on your branch. Then you change all your commits but the first from `pick` to `squash` and save (deleting the extra commit messages on the subsequent screens). Finally you push to your repo with a `--force`. Hope that helps.

2018-02-17 00:08 UTC, mueedc commented
@jascott1 thanks for that. I think I got the hang of rebasing now and I believe everything should be good for the merge. @unguiculus this should address your comments as well.

2018-02-17 00:43 UTC, jascott1 approved these changes

2018-02-17 00:44 UTC, jascott1 commented
@unguiculus I think its good 2 go but will wait for your review. Thanks!

2018-02-17 09:06 UTC, unguiculus commented
/lgtm

2018-02-20 20:02 UTC, mueedc commented
Thanks for all the pointers along the way @jascott1. This has been an immensely helpful learning experience!

2018-02-20 22:32 UTC, merged

2018-02-20 22:34 UTC, jascott1 commented
@mueedc Glad I could help. Thanks for the contribution!