test(e2e): initial framework
helm/helm pull request #3636
Opened 2018-03-08 19:21 UTC by adamreese

See https://github.com/kubernetes/helm/pull/2846

2018-03-13 03:17 UTC, thomastaylor312 commented
@adamreese Is there any manual validation that should be done on this? Based on what I can see, the tests running in circle should just cover it. I'll be going over all of the files tomorrow for a full review

2018-03-16 04:25 UTC, adamreese commented
@thomastaylor312 Don't worry about a full review on this.  I am going to play with `minikube --vm-driver=none` to see how that could simplify the setup.

2018-03-28 01:32 UTC, michelleN commented
Hey this is pretty dope. I see we're building our own kubernetes cluster here to text against. Would it possible or even a good idea to add an option to test again the current kubernetes cluster I have running in minikube instead?

2018-04-02 20:41 UTC, thomastaylor312 requested changes
Few small discussion points. The only big thing is that this will need to be rebased against the latest changes with k8s 1.10

2018-04-02 20:41 UTC, thomastaylor312 commented on Makefile
> +	go test -v ./e2e --cluster-url http://localhost:8080 --helm-bin ../bin/helm
The cluster URL should probably use variables (set with this default value) so you can override them if testing against another cluster of your choice

2018-04-02 20:41 UTC, thomastaylor312 commented on e2e/e2e_suite_test.go
> +Copyright 2017 The Kubernetes Authors All rights reserved.
Nit: Copyright should be 2018. Same goes for a bunch of the other files

2018-04-02 20:41 UTC, thomastaylor312 commented on glide.yaml
> +  version: 1.9.3
This will need to be rebased against master with 1.10 support

2018-07-02 06:18 UTC, adamreese commented
Lets abort this and revisit for helm v3.

/close

2018-07-02 06:18 UTC, closed without merging