migrated from glide to dep
helm/helm pull request #3642
Opened 2018-03-09 03:43 UTC by robbert229

In this pull request I have migrated from glide to dep.

2018-03-10 00:33 UTC, thomastaylor312 requested changes
One small change and then I'll approve. Thanks for taking this on!

2018-03-10 00:33 UTC, thomastaylor312 commented on Gopkg.toml
> +# Gopkg.toml example
Can you remove this example comment section?

2018-03-10 00:34 UTC, thomastaylor312 commented
@bacongobbler You may want to take a look at this since you were helping out with the first pass. @mattfarina I think it would be good for you to look at it too because you are an expert at this stuff

2018-03-10 00:49 UTC, robbert229 commented
I will remove the examples once i get home!

2018-03-10 01:17 UTC, robbert229 commented
@thomastaylor312 the examples have been removed.

2018-03-10 01:20 UTC, bacongobbler commented
Thanks! I'll take a look at this next week. We'll need to take a *really* close look with this one. :)

2018-03-16 04:40 UTC, adamreese requested changes

2018-03-16 04:40 UTC, adamreese commented on glide.yaml
> -  # Pin version of mergo that is compatible with both sprig and Kubernetes
This is important! This will need to be pinned in Gopkg.toml mergo

2018-03-16 04:40 UTC, adamreese commented on glide.yaml
> -# pin version of golang.org/x/sys that is compatible with golang.org/x/crypto
Need to validate if this is still an issue

2018-04-12 08:34 UTC, mrueg commented
It would be great to see this in, since go-1.10 and glide cause this issue for me when trying to build helm from source: https://github.com/Masterminds/glide/issues/975

2018-04-23 16:48 UTC, rajatjindal commented
@robbert229 can you please update the PR with requested changes?

2018-04-23 20:05 UTC, bacongobbler commented
in case anyone wants to pick this up on the Helm 2 side, here's the Helm 3 PR: https://github.com/kubernetes/helm/pull/3945

2019-02-27 18:49 UTC, bacongobbler commented
closing due to inactivity. We've already implemented this for Helm 3. Thanks!

2019-02-27 18:49 UTC, closed without merging