add support for output format in json or yaml
helm/helm pull request #3652
Opened 2018-03-10 00:57 UTC by rajatjindal

It would be nice to be able to have history command print output in json or yaml format that can be consumed by other tools.

the PR add support for yaml and json formats and keeps existing behavior as default.

2018-03-10 01:05 UTC, rajatjindal commented
sample output here: https://gist.github.com/rajatjindal/9bdb83db13cd2995484d4e9f3bb510e4

2018-03-10 01:13 UTC, bacongobbler commented
would you mind running `make docs`?

> helm docs are out of date. Please run "make docs"

2018-03-10 01:47 UTC, rajatjindal commented
@bacongobbler updated now. sorry missed it somehow earlier.

2018-03-12 20:22 UTC, rajatjindal commented
@bacongobbler can you please review the changes

2018-03-14 16:46 UTC, rajatjindal commented
@bacongobbler gentle reminder to review the changes

2018-03-14 17:08 UTC, bacongobbler requested changes
one minor doc change, but the rest looks good to me!

2018-03-14 17:08 UTC, bacongobbler commented on cmd/helm/history.go
> +	f.StringVarP(&his.outputFormat, "output", "o", "table", "prints the output in the specified format ('json' or 'yaml' or defaults to 'table')")
can we change the docstring to "prints the output in the specified format (json|table|yaml)"? cobra will automatically display the default value, so it's kinda redundant:

```
><> ./bin/helm help history | grep -- --output
  -o, --output string        prints the output in the specified format ('json' or 'yaml' or defaults to 'table') (default "table")
```

2018-03-14 21:05 UTC, rajatjindal commented
thanks for the review @bacongobbler I've updated the doc as recommended

2018-03-14 21:09 UTC, bacongobbler approved these changes

2018-03-14 21:09 UTC, bacongobbler commented
needs one extra sign-off from another maintainer since it's a larger PR :)

2018-03-14 23:24 UTC, rajatjindal commented
thanks @bacongobbler 

pinging @thomastaylor312 @technosophos  may be one of them can find sometime to approve this PR as well.

between our team just did an internal demo using helm/kubernetes and everyone was like wow !!. 

thanks for the great work.

2018-03-15 00:30 UTC, thomastaylor312 commented
@rajatjindal I'll do another review tomorrow!

2018-03-16 05:42 UTC, rajatjindal commented
gentle reminder @thomastaylor312

2018-03-19 00:03 UTC, rajatjindal commented
gentle reminder @thomastaylor312

2018-03-20 02:20 UTC, thomastaylor312 approved these changes
So sorry for the delay! The last part of my week was crazy. This is good to go for merge @bacongobbler. Thanks again for adding this @rajatjindal and I appreciate the patience (and reminders)

2018-03-20 03:02 UTC, merged