Fix link in plugins page that results in a 404
helm/helm pull request #3711
Opened 2018-03-19 12:14 UTC by DeploymentKing

Clicking the link will work when viewing docs in GitHub but when viewing via https://docs.helm.sh I get a 404. I have explicitly applied the full address which is the same format used in the README.md e.g. [Quick Start Guide](https://docs.helm.sh/using_helm/#quickstart-guide)

2018-03-19 12:19 UTC, DeploymentKing commented
I'm not entirely sure how the build failed with this update. The logs don't seem to help as `FAIL: TestInvalidYaml (0.01s)` seems unrelated to a document change?

2018-03-19 12:45 UTC, DeploymentKing commented
test this please

2018-03-19 12:46 UTC, DeploymentKing commented
retest this please

2018-03-20 18:45 UTC, jascott1 requested changes

2018-03-20 18:45 UTC, jascott1 commented on docs/plugins.md
> +Existing plugins can be found on [related](https://docs.helm.sh/related/#helm-plugins) section or by searching [Github](https://github.com/search?q=topic%3Ahelm-plugin&type=Repositories).
Even though docs.helm.sh rewrites the URL incorrectly, lets use the proper fragment format without the last slash `https://docs.helm.sh/related#helm-plugins`

2018-03-20 18:46 UTC, jascott1 commented on docs/plugins.md
> +Existing plugins can be found on [related](https://docs.helm.sh/related/#helm-plugins) section or by searching [Github](https://github.com/search?q=topic%3Ahelm-plugin&type=Repositories).
Also can you squash this into one commit? Thanks!

2018-03-21 20:30 UTC, DeploymentKing commented
@jascott1 dodgy trailing slash removed and commits squashed...thank you

2018-12-19 00:05 UTC, jascott1 approved these changes

2018-12-19 00:12 UTC, jascott1 commented
Hi @deploymentking 

Thank you for helping to make Helm better. My apologies for such a long delay.  We need to satisfy the DCO requirement before we can merge your PR. Would you be able to rebase with the `Signed-off-by: name <email>` added to the commit message?

2019-01-29 23:50 UTC, bacongobbler commented
The link works since we moved to netlify so I'm going to close this one out. Thanks!

2019-01-29 23:50 UTC, closed without merging