Fix "no kind registered for version" when executing hooks
helm/helm pull request #3736
Opened 2018-03-22 13:25 UTC by sczizzo

This PR addresses an issue waiting on certain resources instantiated by hooks.

I ran into this while creating a Helm chart for the [Kubernetes Metrics Server](https://github.com/kubernetes-incubator/metrics-server)

It's trivial to reproduce by creating a Helm chart with a template for an APIService resource with the appropriate annotations for a `pre-install` hook:
```
# /path/to/helm/charts/metrics-server/templates/apiService.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
spec:
  service:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

When I try to install the Helm Chart with the above APIService, I run into an error, and the release is never created:
```
$ helm upgrade --install --namespace kube-system metrics-server /path/to/helm/charts/metrics-server
Release "metrics-server" does not exist. Installing it now.
Error: unable to decode "": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
```

The corresponding logs for Tiller provide a little more information:
```
[tiller] 2018/03/22 12:21:15 getting history for release metrics-server
[storage] 2018/03/22 12:21:15 getting release history for "metrics-server"
[tiller] 2018/03/22 12:21:15 preparing install for metrics-server
[storage] 2018/03/22 12:21:15 getting release history for "metrics-server"
[tiller] 2018/03/22 12:21:15 rendering metrics-server chart using values
[tiller] 2018/03/22 12:21:16 performing install for metrics-server
[tiller] 2018/03/22 12:21:16 executing 1 pre-install hooks for metrics-server
[kube] 2018/03/22 12:21:16 building resources from manifest
[kube] 2018/03/22 12:21:16 creating 1 resource(s)
[tiller] 2018/03/22 12:21:16 warning: Release metrics-server pre-install metrics-server/templates/apiService.yaml could not complete: unable to decode "": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
[tiller] 2018/03/22 12:21:16 deleting pre-install hook v1beta1.metrics.k8s.io for release metrics-server due to "hook-failed" policy
[kube] 2018/03/22 12:21:16 Starting delete for "v1beta1.metrics.k8s.io" APIService
[tiller] 2018/03/22 12:21:16 failed install perform step: unable to decode "": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
```

(For what it's worth, if I omit the `helm.sh/hook` annotation, the APIService resource is created without issue. It's only during the `pre-install` hook that this is an issue.)

For reference, here are my Helm and Kubernetes versions:
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:50:44Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

2018-03-22 15:07 UTC, bacongobbler approved these changes
LGTM but I'd love to have someone else more familiar with pkg/Kube to take a look at this :)

2018-04-04 09:54 UTC, clement-buchart commented
Fixes https://github.com/kubernetes/helm/issues/3396

2018-04-12 12:16 UTC, sczizzo commented
After some additional investigation, I'm a even more satisfied that `Unstructured` is appropriate:
- `Build` creates an ["internal" builder](https://godoc.org/k8s.io/kubernetes/pkg/kubectl/resource#Builder.Internal)
- `BuildUnstructured` creates an ["unstructured" builder](https://godoc.org/k8s.io/kubernetes/pkg/kubectl/resource#Builder.Unstructured)

The documentation appears to prefer the unstructured builder in most cases:

> Use Unstructured if you are reading an object and performing a POST or PUT.

> Use this mode [Unstructured] in preference to Internal unless you are working with Go types directly.

We're not modifying the resource objects here, simply using them to instantiate a watch, so the unstructured variant would seem appropriate.

2018-04-30 17:07 UTC, sczizzo commented
@bacongobbler apologies for pinging you directly, but I was hoping you might be able to recommend another reviewer with enough familiarity to more confidently review this change.

2018-06-20 21:01 UTC, dcovello commented
Does anyone have any update on a timeline for this? 

I just recently ran into this while trying to create a SealedSecret Resource as apart of a pre-install hook. Im thinking for now I'm just going to create a separate secondary chart that updates this resource and gets deployed before my main chart as a workaround.

2018-07-03 20:57 UTC, adamreese commented
Can you test if this works with the example chart at https://github.com/kubernetes/helm/tree/master/docs/examples/nginx

2018-07-31 17:11 UTC, bacongobbler commented
ping

2018-07-31 17:17 UTC, sczizzo commented
Sorry, I've been on vacation the past few weeks, but after trying out a build of this and attempting to deploy the example nginx chart it seems this change does introduce a regression: it seems in the case of Job resources the full, structured API object is required as currently written.

2018-07-31 17:33 UTC, bacongobbler requested changes
no worries! I'm gonna mark this as unacceptable to merge for the time being given the regression this would introduce, but let us know if things change. Thanks!

2018-08-02 17:52 UTC, sczizzo commented
Just going to go ahead and close this. Unfortunately, I just don't have time to dig into this. I encourage anyone coming to this PR to refer to Issue #3396 for future developments

2018-08-02 17:52 UTC, closed without merging