Add chart name check to lint
helm/helm pull request #3773
Opened 2018-03-27 19:41 UTC by axdotl

I run into an issue with a chart which contained a dot in the name. Thought it would be nice to get this reported when performing a lint.

2018-04-03 21:56 UTC, thomastaylor312 commented
@mattfarina Can you or one of the chart maintainers sign off on this one? Looks good from a code perspective, just wanted to make sure it fit in with the current chart testing pipeline

2018-04-18 03:24 UTC, michelleN approved these changes
This looks good to me. We should probably also file an issue that updates the documentation around chart names to specify that chart names cannot contain dots `.`

Thanks @axdotl

2018-04-18 03:26 UTC, michelleN commented
ping @mattfarina @prydonius @unguiculus

2018-07-17 08:59 UTC, axdotl commented
/remove-lifecycle stale

2018-07-17 15:06 UTC, bacongobbler reviewed
Would it be okay if you could write a test for `validateChartNameFormat`? Thanks!

2018-07-18 15:34 UTC, bacongobbler requested changes

2018-07-18 15:34 UTC, bacongobbler commented on pkg/lint/rules/chartfile_test.go
> +	badNameChartFilePath     = filepath.Join(badNameChartDir, "Chart.yaml")
I think you intended the variable to be named `badChartNameFilePath` instead. It doesn't look like `badNameChartFilePath` is used anywhere in this file. Line 45 is `badChartNameFilePath`

2018-07-18 15:36 UTC, bacongobbler commented
test failure: https://circleci.com/gh/kubernetes/helm/6048

2018-07-19 07:43 UTC, axdotl commented
@bacongobbler Hope it's fine now :)

2019-01-10 16:18 UTC, bacongobbler approved these changes

2019-01-10 16:19 UTC, bacongobbler commented
looks good! Now we just need to rebase this PR and to sign-off on the commits to comply with the DCO signoff then we can merge. ThanksQ

2019-01-10 16:52 UTC, axdotl commented
@bacongobbler Rebase done. Next to that I squashed the commits and signed-off. Please check.

2019-01-10 16:53 UTC, bacongobbler commented
looks great now. Thanks! Now we'll just have to wait for CI to pass then we can merge.

2019-01-10 16:57 UTC, axdotl commented
Do you've an idea for the broken build?

2019-01-10 16:59 UTC, bacongobbler commented
Haven't the foggiest; this is the first time seeing that failure. Assuming AppVeyor passes we should be fine since that error is unrelated; the test stage passed fine so that can be ignored.

2019-01-10 17:05 UTC, merged