added warning and set default image for unreleased versions of helm for #3770
helm/helm pull request #3781
Opened 2018-03-28 21:07 UTC by RyanHartje

I setup something in cmd/helm/installer/options.go to use the canary image in the event that the BuildMetaData for helm was "unreleased" and that UseCanary wasn't set, and the tiller-image flag wasn't used.

I separately repeated this logic in cmd/helm/init.go for the sake of keeping warnings and other output together.

2018-03-28 21:07 UTC, RyanHartje commented
This should resolve #3770

2018-04-11 21:10 UTC, bacongobbler requested changes

2018-04-11 21:10 UTC, bacongobbler commented on cmd/helm/init.go
> +	if version.BuildMetadata == "unreleased" && !i.opts.UseCanary && len(i.opts.ImageSpec) == 0 {
This should probably check if the client has requested for `--client-only` as well, as that would affect some of the branch logic here. For example, a user running `helm init --client-only` won't need the `--canary-image` flag, so the warning should not be displayed.

2018-04-12 16:55 UTC, RyanHartje commented
Thanks! I overlooked that.

2018-04-26 08:28 UTC, jstoja commented
Hey @bacongobbler after the last changes of @RyanHartje , it should be okay, what do you think?

2018-05-14 13:18 UTC, mattjmcnaughton commented
Thanks for working on this @RyanHartje  ! This has bitten me a couple of times, so I'm happy to see it getting fixed :)

2019-02-01 16:44 UTC, bacongobbler approved these changes

2019-02-01 16:45 UTC, bacongobbler commented
This PR was submitted prior to the DCO switch, so I'm merging this as @ryanhartje has signed off on the CLA. Thanks for the PR!

2019-02-01 16:45 UTC, merged