Update rbac.md
helm/helm pull request #3794
Opened 2018-03-29 15:44 UTC by AdamDang

In the main text and paragraph title, "Tiller" and "tiller" are both used.
It's better use same format.

2018-04-03 21:46 UTC, thomastaylor312 requested changes
@AdamDang Thanks for fixing this! We really appreciate it when people fix up docs. Just a few quick changes for capitalizing Helm as well while you are in here fixing this 🙂

2018-04-03 21:46 UTC, thomastaylor312 commented on docs/rbac.md
> +When running a helm client in a pod, in order for the helm client to talk to a Tiller instance, it will need certain privileges to be granted. Specifically, the helm client will need to be able to cr
While we are fixing capitalization, can you capitalize "Helm" where it occurs in this sentence?

2018-04-03 21:46 UTC, thomastaylor312 commented on docs/rbac.md
> +In this example, we will assume Tiller is running in a namespace called `tiller-world` and that the helm client is running in a namespace called `helm-world`. By default, Tiller is running in the `ku
Capitalize Helm here as well

2018-04-03 23:11 UTC, AdamDang commented
@thomastaylor312 Thanks for your kind attention.  Capitalizing Helm is done.

2018-04-05 17:14 UTC, thomastaylor312 approved these changes
Thank you for the changes!

2018-04-05 17:15 UTC, merged