Update helm template -x to support children chart manifests in more cases
helm/helm pull request #3877
Opened 2018-04-11 21:49 UTC by chancez

The previous code validated the manifests exist within the file system,
which only works when a chart is unpacked, meaning children charts
stored as tgz's in the parent chart's `charts/` directory don't exist as
individual files in the filesystem, causing validation to file.

Instead, we validate against the paths within the chart itself rather
than the filesystem, handling both chart.tgz's and charts that are
unpacked as directories in the chart/ directory.

2018-04-11 22:06 UTC, chancez commented
I took some liberties in refactoring/ordering the code since it was terribly difficult to understand before, as there was little comments and variable names weren't very descriptive/discernible.

2018-04-11 22:40 UTC, thomastaylor312 requested changes
@chancez Just one concern about how to handle non-existent paths. I tested out the code and if I give a bogus path, it returns 0 with no rendered manifests instead of an error. So it looks like something isn't catching things properly

2018-04-11 22:40 UTC, bacongobbler commented
Perhaps some unit tests to cover these scenarios would be a good next approach :)

2018-04-11 22:42 UTC, chancez commented
Oh..hm I had made some changes right before opening my PR that may have removed the error handling I did have. Let me revisit that.

2018-04-11 23:31 UTC, chancez commented
@bacongobbler @thomastaylor312 I added some tests, and realized they actually still worked on master, then recalled my case was specifically with subcharts that are .tgzs, so I updated some of the testdata to support testing this use-case, and added a test that uses a subchart stored in a .tgz.

2018-04-11 23:51 UTC, chancez commented
Also found another issue in how the tests were using subtests, so I fixed that. I also realized there were no tests that handle error cases, so I added a test that validates an error is thrown when passing a non-existent template to `-x`.

2018-04-12 01:03 UTC, thomastaylor312 approved these changes

2018-04-12 01:03 UTC, thomastaylor312 commented on pkg/chartutil/testdata/mariner/templates/placeholder.tpl
> +Goodbye {{.Values.name | default "world"}}
💯

2018-04-12 01:03 UTC, thomastaylor312 commented
@chancez Thanks for adding (and fixing) the unit tests on this!

2018-04-12 01:04 UTC, thomastaylor312 commented
Waiting on second review now that this is a size large

2018-04-12 07:17 UTC, SlickNik approved these changes
Reviewed this and did a quick smoke test as well. Thanks for the fix @chancez! LGTM 👍

2018-04-12 07:18 UTC, merged