helm test - show log of test pod
helm/helm pull request #3907
Opened 2018-04-17 08:22 UTC by GaoLiping

fix(helm): add log of test pod to 'helm test'

When 'helm test' finishes, this will print the log of the test pods

Closes #1957

2018-04-17 08:42 UTC, sorenmat commented on pkg/kube/client.go
> +//GetPodLogs print the log of a pod to standard output
Doesn't it just return the log?

2018-04-17 08:42 UTC, sorenmat commented on pkg/kube/client.go
> +func (c *Client) GetPodLogs(namespace string, reader io.Reader, timeout time.Duration) (string, error) {
doesn't seem like the timeout parameter is used

2018-04-17 08:42 UTC, sorenmat commented on pkg/releasetesting/environment.go
> +	return log, err
I personally like to explicitly return nil to indicate that there were no error

2018-04-17 08:42 UTC, sorenmat commented on pkg/releasetesting/test_suite.go
> +			fmt.Println("testing pod created ")
remove this perhaps?

2018-05-18 14:29 UTC, frankh commented
Hi, I didn't realise you already had a PR for this,

I've made one which does a similar thing, https://github.com/kubernetes/helm/pull/4081

The main differences are: It adds a flag `--logs` for showing the logs, and it streams the logs in realtime instead of printing them all at once

I would appreciate your input and which approach you think works best

2018-08-09 15:05 UTC, michelleN requested changes
Hey @GaoLiping! Thanks for contributing. It looks like this pull request was made against the `release-2.8` branch. Would you mind making this pull request against `master`? Right now, I can't test it manually because there are merge conflicts against master. I'm happy to pair and help you on that if you need. 

@frankh - Thanks for touching base here to coordinate on similar functionality. It looks like you closed the `--logs` flag PR to focus on `--paralllel`. I think the streaming functionality is what folks have been asking for as well which is what makes sense to me as well.

I think doing a `--logs` or `--verbose` flag makes sense. If we put this functionality behind a flag called `--dump-logs` then we can have both play nice but still keep the simplified output we have already.

Let me know what ya'll think @GaoLiping @frankh

2019-01-10 16:02 UTC, michelleN commented
@GaoLiping are you still interested in contributing this feature?

2019-08-06 16:26 UTC, jeff-knurek commented
I didn't see this PR till I already finished most of the work to do similar, but as it's been ignored for some time, maybe someone can have a look at https://github.com/helm/helm/pull/6167

my take is that `--verbose` would be the option that would stream logs in realtime (like what was started in https://github.com/helm/helm/pull/4081) whereas `--logs` is suitable for getting a dump of the logs at the end. and i suppose that either option will be satisfactory till Helm 3 changes are available https://github.com/helm/helm/issues/6020

2019-09-30 19:18 UTC, bacongobbler commented
Closing this PR due to inactivity. If someone is interested in pushing this along the finish line, please write a PR against Helm 3. As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Thanks!

2019-09-30 19:18 UTC, closed without merging