lets avoid failing if the outdir already exists
helm/helm pull request #3908
Opened 2018-04-17 10:41 UTC by jstrachan

rather than assuming the `outdir` exists and then failing if it doesn't, lets check if it doesn't exist first

2018-04-18 02:18 UTC, michelleN approved these changes

2018-05-13 00:44 UTC, rajatjindal commented
may be use https://golang.org/pkg/os/#MkdirAll

MkdirAll creates a directory named path, along with any necessary parents, and returns nil, or else returns an error. The permission bits perm (before umask) are used for all directories that MkdirAll creates. **If path is already a directory, MkdirAll does nothing and returns nil.**

2019-01-29 23:27 UTC, bacongobbler requested changes
So sorry for the late response.

This PR will silently fail when `os.Stat` triggers an error other than the directory not existing (for example, file permission issues, partition read errors, etc). I'm okay with the general idea behind this but if we're checking `os.Stat` and find an error we should bubble that up to the user.

What do you think about checking for the presence of an error other than `os.IsNotExist(err)` and returning that error?

I'd rather not call `os.MkdirAll` as it'll recursively create all directories that do not exist which may or may not be intended behaviour. We should just create a directory one level deep.

2019-09-30 20:23 UTC, bacongobbler commented
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

2019-09-30 20:23 UTC, closed without merging