feat(helm): add --with-subcharts option for "helm inspect values"
helm/helm pull request #3955
Opened 2018-04-24 13:17 UTC by AndreasBieber

Running helm inspect values [CHART] outputs the contents of a chart's values.yaml verbatim. This is often used to determine which configuration options a chart exposes. However, it does not provide the contents of values.yaml files of potential subcharts bundled in the charts subdirectory. The new command-line option --with-subcharts causes Helm to merge the values.yaml files of a chart and all its subcharts and output the result.

Closes #3926

2018-05-07 08:06 UTC, AndreasBieber commented
/check-cla

2018-05-07 08:26 UTC, AndreasBieber commented
Signing CLA is done

2018-05-07 08:28 UTC, AndreasBieber commented
/check-cla

2018-05-07 08:35 UTC, AndreasBieber commented
@k8s-bot /check-cla

2018-05-07 08:52 UTC, AndreasBieber commented
/check-cla

2018-05-07 08:55 UTC, AndreasBieber commented
@k8s-ci-robot check-cla

2018-05-07 09:13 UTC, AndreasBieber commented
Signing CLA done

2018-05-08 05:44 UTC, AndreasBieber commented
Signing CLA done

2018-06-04 08:41 UTC, bastianeicher commented
Hi guys,
just wanted to check-in to see it anything is missing for this to be merged.
Regards
Bastian

2018-07-03 11:31 UTC, irajdeep commented
Hi guys.
Can this be merged looks , it's a super useful feature

2019-01-21 10:49 UTC, freach commented
What's the status here, this is a very useful feature.

2019-01-22 09:17 UTC, carpenterbees commented
Also waiting for this feature to be merged.

2019-01-22 10:07 UTC, dennisosimon commented
this would be really helpful!

2019-09-30 20:36 UTC, bacongobbler requested changes
Hey @AndreasBieber, just letting you know that as per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. If you want to get this in for the next release, please let us know and we can work with you to get this in. If not, we'll have to close this and continue this effort over in Helm 3.

I was very confused after reading the expected testdata output. I was having a hard time looking at the testdata output, ensuring that the values are displayed as expeected. Values with names like `chart-globals-inspect-values-with-subcharts-subchart1-subsubchart` is very verbose and a little hard to understand. Is there a simpler naming convention you can come up with here to make the code a little simpler to understand?

Thanks!

2019-09-30 20:36 UTC, bacongobbler commented on cmd/helm/inspect_test.go
> +	insp.run()
no error checking?

2019-10-03 17:20 UTC, bacongobbler commented
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed for Helm 3. Thanks!

2019-10-03 17:20 UTC, closed without merging