Change GetVersion() timeout
helm/helm pull request #4127
Opened 2018-05-27 15:40 UTC by koooge

Hi there. Waiting time of `$ helm version`response from server is too long(300 sec). I think 5sec is better same as NewClient()

2018-05-30 13:26 UTC, mattjmcnaughton approved these changes
I'm not a maintainer but LGTM modulo my one comment :)

2018-06-11 23:27 UTC, bacongobbler requested changes
With this change, the timeout to connect to tiller is now hard-coded at 5 seconds and users cannot change this *at all* via `--tiller-connection-timeout`. I don't think that is the right approach we want to take.

2018-06-11 23:37 UTC, bacongobbler commented
```
><> time ./bin/helm --tiller-connection-timeout=1 version
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"1b17b643fb278c9bb02ffc43de2501b0ddaca4a8", GitTreeState:"clean"}
Error: cannot connect to Tiller

real    0m5.068s
user    0m0.064s
sys     0m0.031s
```

2018-06-12 02:00 UTC, koooge commented
I just want to get version (only client) and don't want to type long option.
In addition, `helm version` seems to be become to wait **30 sec** if tiller is not running on latest master. 😩 
I try to consider another approach about this issue.

```
$ time ./bin/helm version
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"be6eee18cb0f6d04cee8556fc758cccc052b1e8a", GitTreeState:"clean"}
Error: cannot connect to Tiller

real	0m35.112s
user	0m0.063s
sys	0m0.023s
```

2018-06-12 02:21 UTC, bacongobbler commented
If you just want the client version you can use the --client-only option :)

2019-01-29 23:11 UTC, closed without merging