fix(pkg/kube): make internal cache miss not an error
helm/helm pull request #4146
Opened 2018-05-31 03:55 UTC by jaredallard

This fixes #1193 by not making an internal cache miss an error, and instead making it a warning. It will default to the original object, if one exists, instead. This should fix at least one scenario of when helm loses track of the real state of the a config.

This could have issues since it uses the existing object in place of the cached one. Let me know if there are better ways of handling this, since my comment on the issue didn't have anything I decided to propose my fix but am open to any better way of fixing this!

Thanks! :sparkles:

2018-06-09 19:33 UTC, jaredallard commented
@bacongobbler, or anyone else. We've hit #1193 multiple times in our great kubernetes migration journey so far, patching the deployment to use my code fix has solved every single one! Would be awesome if we had some insight on this!

2018-06-11 22:31 UTC, bacongobbler commented
hey @jaredallard, could you please write up a unit test to cover this failure scenario? That way we can prevent this from occurring in the future. We have been putting more focus on unit tests to allow us to catch regressions earlier in the release process. Thanks so much for taking a shot at fixing this!

2018-06-11 22:32 UTC, bacongobbler commented
cc @adamreese, does this look like something we should port to `dev-v3`?

2018-06-14 15:12 UTC, jaredallard commented
@bacongobbler sure, but it might be a bit until I can get around to it

2018-06-14 18:25 UTC, adamreese requested changes

2018-06-14 18:44 UTC, jaredallard commented on pkg/kube/client.go
> +			originalInfo.Object = info.Object
I see what you're saying, but I don't believe this is true. From my experience the issue is that there is no object for that in the state, thus when it fails to find it, we pull the existing object from the kubernetes cluster which is then put into the state later on. There isn't anything to patch when it never existed in the first place.

2018-06-14 19:37 UTC, bacongobbler commented on pkg/kube/client.go
> +			originalInfo.Object = info.Object
I reported my findings between master, this PR, and @adamreese's PR here: https://github.com/kubernetes/helm/pull/4223#issuecomment-397413568

2018-06-14 19:42 UTC, jaredallard commented on pkg/kube/client.go
> +			originalInfo.Object = info.Object
Interesting, well I hope this PR (which obviously has limitations) at least did a good job (as it seems it did) of showing how big of an issue this issue is. Thanks :)

2018-06-14 19:48 UTC, bacongobbler commented
No problem @jaredallard. Because of my findings I don't think we're going to accept this PR as it currently stands, but thank you so much for looking into this!

2018-06-14 19:48 UTC, closed without merging

2018-06-15 19:36 UTC, jwickens commented
I agree this is a big issue. Part of the helm (and k8s) promise is that we declare what we want and we get it. `helm upgrade --install` (+ `--force` ! ) not working because of apparently minor runtime issues really reduces the confidence here. Especially when the fix is to delete the release....

 Ive been following this issue for several months. Thanks to @bacongobbler and @jaredallard for working on it, I just wanted to emphasise how important these issues are. I know its not easy. Will continue to watch with anticipation...

2018-07-24 17:35 UTC, robermorales commented
How can we use this build so we can avoid #1193 ?

Any ideas or schedule that will make this eventually get accepted?