fix(release_server): fix how we merge values
helm/helm pull request #4364
Opened 2018-07-19 20:01 UTC by michelleN

resolves #4337
Merging maps inside of strings gets a bit tricky. When two
strings consisting of "{}" were being added together, this resulted in
"{}\n{}" instead of "{}" which is what we wanted. This led to YAML
parsing errors and showed up when the `--reuse-values` flag was used
when no overrides via `--set` were provided during install and/or
upgrade.

2018-07-19 20:02 UTC, michelleN commented
Working on a test for this so it's a wip.

2018-07-20 15:23 UTC, michelleN commented
ready for review

2018-07-23 19:53 UTC, technosophos commented
Hey licenseybot... plz rerun.

2018-07-31 16:13 UTC, bacongobbler requested changes
two small comments, otherwise LGTM!

2018-07-31 16:13 UTC, bacongobbler commented on pkg/tiller/release_update_test.go
> +	fmt.Println("Running Install release with no overrides")
would you mind removing this?

2018-07-31 16:13 UTC, bacongobbler commented on pkg/tiller/release_update_test.go
> +	fmt.Println("Running Update release with no override and reuse-values")
would you mind removing this?

2018-08-01 18:31 UTC, bacongobbler commented
tossing into 2.10 to fix a regression

2018-08-01 19:31 UTC, michelleN commented
yea thanks let me fix those real quick

2018-08-01 19:36 UTC, michelleN commented
@bacongobbler - ready for another look whenever you're ready

2018-08-01 19:38 UTC, bacongobbler approved these changes

2018-08-01 19:38 UTC, bacongobbler commented
LGTM; merge whenever 🎉

2018-08-02 17:09 UTC, technosophos commented on pkg/tiller/release_server.go
> +		//req.Values.Raw = current.Config.Raw + "\n" + req.Values.Raw
Can we remove the commented line?

2018-08-07 21:13 UTC, merged