Dashes are not allowed in the name
helm/helm pull request #4379
Opened 2018-07-24 15:47 UTC by nashasha1

Since now helm does not support dashes in the name. See #2192. We should correct the doc.

2018-07-24 16:15 UTC, bacongobbler requested changes

2018-07-24 16:15 UTC, bacongobbler commented on docs/chart_best_practices/conventions.md
> +aws-cluster-autoscaler #incorrect do not use dashes in the name
can we remove the `#correct` comments and this line altogether, only showing what examples are good to use?

2018-07-25 01:51 UTC, bacongobbler approved these changes

2018-07-25 01:51 UTC, merged

2018-07-25 18:49 UTC, sstarcher commented
The example right below this still uses dashes `nginx-lego`.

Also how are we suppose to name things now `nginxlego` .  Are we running names together in a large blob?

2018-07-30 17:02 UTC, bacongobbler commented
I'm making a PR to soften the documentation a little in this PR. We definitely still suggest that dashes are acceptable and work, but users should be aware of the limitations of dashes as variable names in Go templates.

2018-07-30 17:06 UTC, sstarcher commented
@bacongobbler I'll close #4383 

could you ping me on your new PR just so I know how it's worded :)

2018-08-20 09:08 UTC, ksemaev commented
This so awful. What shoul be used in chart names, if no usual symbols and even capital letters are alouded to be used with templates? Real life experience shows that quite often chart names consists of several words, how do you suggest to refactor it?

2018-08-20 14:28 UTC, sstarcher commented
@ksemaev looks like the current recommendation is to keep using `-`, but to deal with the difficulty of accessing `-` named charts using index.

2018-08-20 14:53 UTC, bacongobbler commented
Yep, also see #4400 for the current verbiage. The idea here is to make users aware of the limitations around using dashes in the name using text/template, but not completely shut it out.