Avoid importing k8s.io/kubernetes from pkg/helm
helm/helm pull request #4499
Opened 2018-08-21 09:17 UTC by databus23

When writing a helm client (e.g. a helm plugin) that talks to tiller importing k8s.io/helm/pkg/helm to get the grpc client is key.
This pkg should not have a dependency to the k8s.io/kubernetes to avoid pulling in a lot of code that is only used within tiller and blow up binary sizes.

Seems like this happen accidentally within the 2.10 development process.

We had something like this happen accidentally before: #2685

2018-08-29 16:53 UTC, novas0x2a commented
Hm, copying error strings around seems somewhat risky. Perhaps a better fix would be to move the error wrappers to their own package that didn't import the rest of kube? You can leave an alias behind to avoid breaking working code.

2018-09-01 00:14 UTC, bacongobbler commented
I agree with @novas0x2a's assertion; I don't like the thought of duplicating code to get around a library issue. I sympathize and understand the use case but duplicating code (and maintenance) doesn't sit well with me.

2018-09-03 06:51 UTC, databus23 commented
@bacongobbler Sure. I updated the branch as requested.

2018-09-04 15:39 UTC, bacongobbler requested changes

2018-09-04 15:39 UTC, bacongobbler commented on pkg/storage/driver/driver.go
> -	ErrReleaseNotFound = func(release string) error { return fmt.Errorf("release: %q not found", release) }
can we do a `ErrReleaseNotFound = storageerrors.ErrReleaseNotFound`? That way we won't break other users relying on this API.

```
diff --git a/pkg/storage/driver/driver.go b/pkg/storage/driver/driver.go
index 7ad28770..017468d6 100644
--- a/pkg/storage/driver/driver.go
+++ b/pkg/storage/driver/driver.go
@@ -17,9 +17,20 @@ limitations under the License.
 package driver // import "k8s.io/helm/pkg/storage/driver"

 import (
+       storageerrors "k8s.io/helm/pkg/storage/errors"
+
        rspb "k8s.io/helm/pkg/proto/hapi/release"
 )

+var (
+       // ErrReleaseNotFound has been deprecated; please use storageerrors.ErrReleaseNotFound instead.
+       ErrReleaseNotFound = storageerrors.ErrReleaseNotFound
+       // ErrReleaseExists has been deprecated; please use storageerrors.ErrReleaseExists instead.
+       ErrReleaseExists = storageerrors.ErrReleaseExists
+       // ErrInvalidKey has been deprecated; please use storageerrors.ErrInvalidKey instead.
+       ErrInvalidKey = storageerrors.ErrInvalidKey
+)
+
 // Creator is the interface that wraps the Create method.
 //
 // Create stores the release or returns ErrReleaseExists
```

2018-09-04 15:40 UTC, bacongobbler commented
Thanks @databus23! One last change and it looks good to go.

2018-09-04 17:36 UTC, databus23 commented
@bacongobbler done

2018-09-04 18:19 UTC, bacongobbler approved these changes
thanks!

2018-09-04 18:19 UTC, merged