Install tiller as well if it exists
helm/helm pull request #4648
Opened 2018-09-16 05:08 UTC by yuya-takeyama

## What I Did

I modified `scripts/get` to install `tiller` as well if it exists in a version of release binary.

### When tiller exists

```
$ HELM_INSTALL_DIR=/tmp/helm ./scripts/get --version v2.11.0-rc.1
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.11.0-rc.1-darwin-amd64.tar.gz
Preparing to install helm and tiller into /tmp/helm
helm installed into /tmp/helm/helm
tiller installed into /tmp/helm/tiller
Run 'helm init' to configure helm.
```

### When tiller does not exist

```
$ HELM_INSTALL_DIR=/tmp/helm ./scripts/get --version v2.9.1
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.9.1-darwin-amd64.tar.gz
Preparing to install helm and tiller into /tmp/helm
helm installed into /tmp/helm/helm
warn: tiller is not included in this version of binary release
Run 'helm init' to configure helm.
```

## Background

Since release candidates of v2.11.0, the binary releases got to include `tiller` in it.

* The issue proposed to include `tiller`
  * https://github.com/helm/helm/issues/1690
* The PR fixed the issue
  * https://github.com/helm/helm/pull/4443

2018-09-16 05:09 UTC, yuya-takeyama commented on scripts/get
> -  echo "$PROJECT_NAME installed into $HELM_INSTALL_DIR/$PROJECT_NAME"
I moved this message just after `runAsRoot cp "$HELM_TMP_BIN" "$HELM_INSTALL_DIR"` in `installFile()` function.

2018-09-17 16:49 UTC, bacongobbler commented
would you mind rebasing now that https://github.com/helm/helm/pull/4653 has been merged? Thanks!

2018-09-17 16:57 UTC, yuya-takeyama commented
@bacongobbler 
Thanks, rebased!

2018-09-17 21:13 UTC, bacongobbler requested changes
One message renaming, then this looks good to ship!

2018-09-17 21:13 UTC, bacongobbler commented on scripts/get
> +    echo "warn: $TILLER_NAME is not included in this version of binary release"
Can we remove the `warn:` part of the message? If it's a warning, there should probably be some action item for the user, but we're just merely informing them that this release doesn't have tiller available.

I'd change the message to read `info: $TILLER_NAME binary was not found in this release; skipping $TILLER_NAME installation`

2018-09-17 21:25 UTC, bacongobbler approved these changes
nice. Thanks!

2018-09-17 21:42 UTC, bacongobbler commented
Manually tested and works with both newer and older releases.

```
><> ./get.sh --version v2.11.0-rc.3
Helm v2.11.0-rc.3 is available. Changing from version v2.10.0.
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.11.0-rc.3-darwin-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
helm installed into /usr/local/bin/helm
tiller installed into /usr/local/bin/tiller
Run 'helm init' to configure helm.
```

```
><> ./get.sh --version v2.9.1
Helm v2.9.1 is available. Changing from version v2.11.0-rc.3.
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.9.1-darwin-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
helm installed into /usr/local/bin/helm
info: tiller binary was not found in this release; skipping tiller installation
Run 'helm init' to configure helm.
```

2018-09-17 21:43 UTC, bacongobbler commented
kicked off a new job on Circle since the service has been a little flaky this afternoon.

2018-09-17 21:52 UTC, merged