Update using_helm.md
helm/helm pull request #4690
Opened 2018-09-24 16:36 UTC by pmcanseco

In docs/using_helm.md, it says on line 214 that you can pass in a YAML formatted file, but the example commands following that sentence create JSON code but names the file with a .yml extension. For clarity, I propose saying that it will accept JSON or YAML but clarify in the code that for the example we're making a JSON file.

2018-11-01 15:18 UTC, mattfarina commented
@pmcanseco Thanks for the contribution. On [Helm we use a DCO](https://www.helm.sh/blog/helm-dco/index.html). Could you please provide signoff on your commit. Directions are on the checks tab of the PR.

2018-11-02 06:13 UTC, pmcanseco commented
> @pmcanseco Thanks for the contribution. On [Helm we use a DCO](https://www.helm.sh/blog/helm-dco/index.html). Could you please provide signoff on your commit. Directions are on the checks tab of the PR.

done!

2018-11-07 00:14 UTC, bacongobbler commented
`-f` only accepts YAML as input so the docs are wrong in this case. Can we instead make the output of the `echo` properly-formed YAML? https://github.com/helm/helm/blob/1801fa0074a0207f4d5724667858b53d52c486f8/cmd/helm/install.go#L197

2018-12-05 21:36 UTC, bacongobbler commented
ping

2019-01-29 23:05 UTC, bacongobbler commented
It looks like the DCO check failed again. Would you mind amending your last commit and sign off on it? Thanks again.

2019-01-30 04:11 UTC, pmcanseco commented
I've amended my commit and it seems to be good now. Thanks for your patience.

2019-01-30 04:20 UTC, bacongobbler requested changes
One last change. Sorry!

2019-01-30 04:20 UTC, bacongobbler commented on docs/using_helm.md
> +You can then override any of these settings in a JSON or YAML formatted file,
"JSON or" should be removed based on previous feedback (-f doesn't handle JSON files)

2019-01-30 04:45 UTC, pmcanseco commented
Woops, fixed!

2019-01-30 05:03 UTC, bacongobbler approved these changes

2019-01-30 05:03 UTC, bacongobbler commented
Thanks!

2019-01-30 05:03 UTC, merged