Empty helm.sh/resource-policy annotation should not keep the resource
helm/helm pull request #4715
Opened 2018-09-28 17:07 UTC by sebastien-prudhomme

Fix  #4713

2018-10-11 23:43 UTC, technosophos commented
NO NOT MERGE unless core maintainers reach agreement in #4713 that this is allowed. Superficially, it appears that this could result in data loss on existing implementations.

2018-10-11 23:54 UTC, adamreese requested changes
see note above

2018-10-13 17:45 UTC, sebastien-prudhomme commented
@technosophos @adamreese I just add a new commit to not break compatibility and to improve the documentation on the current situation. I hope it will be accepted.

2018-11-07 00:34 UTC, bacongobbler requested changes

2018-11-07 00:34 UTC, bacongobbler commented on pkg/tiller/resource_policy.go
> +			toDelete = append(toDelete, m)
I still don't think this should be accepted. The logic right in master is

1. Does the annotation `helm.sh/resource-policy` exist in the template? If yes, keep
2. Else, delete

Annotations can be added and removed from a template at any point AFAIK so why do we need to change the logic to accept `helm.sh/resource-policy: keep` to mean "delete me"? Is there some documentation somewhere or some example I can find to see why this is an issue?

2018-12-05 21:35 UTC, bacongobbler commented
Given the amount of maintainers that have reviewed this PR and have rejected the change as well as how stale it's been sitting in the PR queue I'm going to close this for now. If you come up with an alternative PR (like the solution discussed in #4713), we'd be more than happy to take a look. Thanks!

2018-12-05 21:35 UTC, closed without merging