(feat)helm: Allow dynamic dependency override (#2205)
helm/helm pull request #4764
Opened 2018-10-12 07:01 UTC by FX-HAO

Add the --requirements flag to install and upgrade commands, which overrides dependencies.

2018-11-06 23:59 UTC, bacongobbler commented
Would you mind writing some usage documentation under `docs/`? For example, it might be useful to demonstrate how this feature can be best utilized as well as some example use cases under the [Using Helm](https://github.com/helm/helm/blob/master/docs/using_helm.md) section of the guide. Thanks!

2018-11-06 23:59 UTC, bacongobbler requested changes
awaiting docs before approval

2018-11-07 03:39 UTC, FX-HAO commented
@bacongobbler Added docs

2018-11-07 04:51 UTC, bacongobbler commented
I was kind of expecting something with a little more substance. Can you explain *why* someone would want to use this feature in the documentation rather than how to use it? :)

2018-11-07 04:53 UTC, bacongobbler commented
For example, https://github.com/helm/helm/blob/master/docs/using_helm.md#customizing-the-chart-before-installing is a great example of how and why you'd want to use the `--values` flag. If I'm reading the docs I'd like to know and when the `--requirements` flag may be useful.

2018-11-08 04:35 UTC, FX-HAO commented
@bacongobbler I have addressed your comments. Please let me know if anything else to be done.

2018-12-06 02:06 UTC, FX-HAO commented on cmd/helm/install.go
> +		chartRequested.Dependencies = nil
You can just make a copy of chart's `requirements.yaml` file and update the part that you want to change. With this way you can remove any dependency if `tags` or `condition` fields are absent.

2019-09-30 21:16 UTC, bacongobbler commented
As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Because this PR will require a large amount of backwards compatibility testing ([and some cleanup](https://github.com/helm/helm/pull/4764/files#diff-259fe82e12a866f01123927480c7851b)), I'm going to close this as something we will not be able to get to in time for the 2.15 release.

If someone is interested in following up, please re-target a PR against the Helm 3 branch (currently the `dev-v3` branch, but it may soon become the `master` branch).

In the future, I'd also ask if you could please write more documentation on the use cases this PR is attempting to address (the "why"). The documentation in this PR describes how the feature works, but it does not describe why a user should use this flag, or how it can be used (like as you described in [this comment](https://github.com/helm/helm/pull/4764#discussion_r239306562)).

Thanks.

2019-09-30 21:16 UTC, closed without merging