doc(helm): remove Tiller reference from the docs
helm/helm pull request #4788
Opened 2018-10-16 22:22 UTC by hickeyma

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>

2018-10-17 18:13 UTC, adamreese requested changes
@hickeyma Thanks for this!  Just a few notes.

2018-10-17 18:13 UTC, adamreese commented on docs/chart_template_guide/builtin_objects.md
> -  - `Capabilities.helmVersion` provides a way to look up the Tiller version. It has the following values: `SemVer`, `GitCommit`, and `GitTreeState`.
This line is still valid. s/Tiller/Helm/

2018-10-17 18:13 UTC, adamreese commented on docs/architecture.md
> +that library uses REST+JSON. Information in ConfigMaps located inside of Kubernetes.
```suggestion
that library uses REST+JSON. Information in Secrets located inside of Kubernetes.
```

2018-10-17 18:13 UTC, adamreese commented on docs/chart_best_practices/conventions.md
> -## Restricting Tiller by Version
This section is still valid. s/Tiller/Helm/

2018-10-17 18:13 UTC, adamreese commented on docs/charts.md
> +The install order of Kubernetes types is given by the enumeration InstallOrder in ***TBD***
you can use the v3 branch url https://github.com/helm/helm/blob/dev-v3/pkg/tiller/kind_sorter.go#L26

2018-10-17 18:13 UTC, adamreese commented on docs/charts.md
> -  (`{{.Capabilities.HelmVersion}}`, and the supported Kubernetes API versions
Keep `{{.Capabilities.HelmVersion}}`

2018-10-17 18:13 UTC, adamreese commented on docs/install.md
> +of the Helm and [install it locally](https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get).
```suggestion
of Helm and [install it locally](https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get).
```

2018-10-18 17:30 UTC, adamreese approved these changes

2018-10-18 17:30 UTC, merged

2018-10-18 21:12 UTC, hickeyma commented
Thanks for merging @adamreese