Securing tiller via running it locally.
helm/helm pull request #4869
Opened 2018-11-01 14:11 UTC by jolson490

Resolves #4852

2018-11-07 05:21 UTC, bacongobbler requested changes
looks great! Just one small change and it's good to go.

2018-11-07 12:44 UTC, jolson490 commented on docs/securing_installation.md
> +2. Configure Tiller to not have an unauthenticated endpoint
no probelm - done.

2018-11-07 15:17 UTC, mattfarina commented
@jolson490 It appears you missed the signoff on one of the two commits. A quick fix set of commands can be found on the checks tab at https://github.com/helm/helm/pull/4869/checks.

2018-11-19 18:01 UTC, bacongobbler approved these changes

2018-11-19 18:01 UTC, bacongobbler commented
thanks!

2018-11-19 18:01 UTC, merged