fix(helm): fix 'helm dep up' to check lock digest
helm/helm pull request #4918
Opened 2018-11-14 02:14 UTC by trthomps

When `helm dependency update` is run helm will now correctly check the
digest of the old and new lock file dependencies instead of the digest
of `requirements.yaml` when choosing whether or not to write
`requirements.lock` to disk.

Closes #4011

Signed-off-by: Travis Thompson <travis.r.thompson@gmail.com>

2018-11-19 19:56 UTC, bacongobbler commented
just re-jiggered the tests to make sure this isn't a flake. AppVeyor is expected to fail until #4136 is merged.

2018-11-19 19:59 UTC, bacongobbler requested changes
would you mind writing a unit test to cover this? Thanks!

2018-11-20 01:42 UTC, trthomps commented
@bacongobbler thanks for the review.  I started down the path of trying to test `Update()` but it was proving to need too many test fixtures to make that work.  So I refactored my change out into a function and test that instead.  Let me know if that's OK for this PR.

2018-11-20 19:22 UTC, bacongobbler commented
looks like the tests failed on CircleCI. They seem like legitimate test failures. Would you mind taking a look into that?

2018-11-28 18:02 UTC, bacongobbler commented
Ping. Would you also mind rebasing to ensure that the windows tests work? #4897

2018-12-04 06:38 UTC, trthomps commented
Sorry, got busy with other work and the holidays.  Will pick this up again tomorrow.

2019-09-30 21:40 UTC, bacongobbler commented
closing as a duplicate of https://github.com/helm/helm/pull/5874. Thanks!

2019-09-30 21:40 UTC, closed without merging