Fix incorrect flow example and improve operator documentation
helm/helm pull request #4919
Opened 2018-11-14 07:56 UTC by consolewitch

The syntax demonstrated in the present documentation is incorrect

values.yaml
```
stringVar: "foo"
boolVar: true
#unsetVar: "unset"
setVar: "set"
```
templates/test.yaml
```
{{ if (.Values.setVar) and eq .Values.setVar "set" }}
#infixing 'and', this should be included 
{{- end}}
 
{{- if (.Values.setVar) and false }}
#infixing 'and', this should NOT be included
{{- end}}
 
{{- if and .Values.setVar (eq .Values.setVar "set") }}
#prefixing 'and', this should be included
{{- end}}
 
{{- if and .Values.setVar (eq .Values.setVar "garbage") }}
#prefixing 'and', this should NOT be included
{{- end}}
```

results:
``` 
$ helm template ./test                                                                                                                                                                     
---
#infixing 'and', this should be included
#infixing 'and', this should NOT be included
#prefixing 'and', this should be included
```

Signed-off-by: Alex <login@sneaksneak.org>

2018-11-14 09:54 UTC, bacongobbler requested changes
looks great! just two comments about the comments in the examples and it looks good to go.

2018-11-14 09:54 UTC, bacongobbler commented on docs/chart_template_guide/functions_and_pipelines.md
> +    #Include this when the variable .Values.fooString exists and is set to "foo"
Can we move this up a line above the if statement and use gotpl comments? e.g.

```
{{/* include this when the variable .Values.fooString exists and is set to "foo" */}}
{{ if and .Values.fooString (eq .Values.fooString "foo") }}
    {{ ... }}
{{ end }}
```

2018-11-14 09:54 UTC, bacongobbler commented on docs/chart_template_guide/functions_and_pipelines.md
> +    #do not include this because unset variables evaluate to false and .Values.setVariable was negated with the not function.
same here

2018-11-14 17:45 UTC, consolewitch commented
PTAL

2018-11-28 18:03 UTC, bacongobbler commented
Would you mind rebasing to fix up the tests? #4897

2018-11-28 18:03 UTC, bacongobbler approved these changes

2018-11-28 18:04 UTC, bacongobbler commented
Will merge once rebased

2018-12-05 18:10 UTC, bacongobbler commented
ping

2018-12-13 22:58 UTC, consolewitch commented
was out of the country - Will rebase this weekend.

2019-01-07 06:45 UTC, consolewitch commented
Sorry that took so long

2019-02-01 16:18 UTC, bacongobbler approved these changes

2019-02-01 16:18 UTC, merged