Typo fixed: utilitites -> utilities
helm/helm pull request #4992
Opened 2018-12-02 11:57 UTC by JoeWrightss

Fixs typo in line 28.

2018-12-02 16:15 UTC, bacongobbler approved these changes

2018-12-02 16:16 UTC, bacongobbler requested changes
Looks like some extra commits snuck in here. Mind removing them and rebase against master?

2018-12-05 18:57 UTC, bacongobbler commented
ping

2018-12-07 08:33 UTC, closed without merging

2018-12-07 08:40 UTC, JoeWrightss commented
Thank you for your reminding, but it's seems that I can't find this tree anymore.