Improve language describing deletion of hooks
helm/helm pull request #5065
Opened 2018-12-15 01:56 UTC by henrynash

The existing language was somewhat confusing and grammatically poor.

Closes #5035

Signed-off-by: Henry Nash <henry.nash@uk.ibm.com>

2019-02-01 16:13 UTC, bacongobbler requested changes

2019-02-01 16:13 UTC, bacongobbler commented on docs/charts_hooks.md
> +If it is prefereed to actually delete the hook after each use (rather than have to handle it on a subsequent use, as shown above), then this can be achived using a delete policy of `"helm.sh/hook-del
typo: preferred

2019-02-05 15:36 UTC, henrynash commented on docs/charts_hooks.md
> +If it is prefereed to actually delete the hook after each use (rather than have to handle it on a subsequent use, as shown above), then this can be achived using a delete policy of `"helm.sh/hook-del
agreed. fixed

2019-02-05 16:24 UTC, bacongobbler approved these changes

2019-02-05 16:24 UTC, merged