WIP: add disk storage method
helm/helm pull request #5233
Opened 2019-01-30 09:58 UTC by sorenmat

**What this PR does / why we need it**:
There are issues with the configmap and secrets storage when releases
are becoming larger than 1mb, since Kubernetes (etcd) doesn't support
entries larger than that.
This tries to solve that problem by adding a new storage type disk.
This will store the release to the local disk, in order to keep it
persistent.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-02-01 23:26 UTC, bacongobbler requested changes

2019-02-04 09:10 UTC, sorenmat commented on docs/storage-disk.md
> +The solution is to do a manually deploy of tiller with a volume mount.
I'm not sure what to recommend, to be honest :)
I think there is a valid use-case for both options. The downside of running tiller locally is that only you have the configuration of the cluster. Where doing the hard coded approach will let you share the configuration, but give you the headache of doing and maintaining the manually configuration.
I was looking into see if it were possible to do via the --override options, but that didn't work :(

2019-02-04 09:11 UTC, sorenmat commented on pkg/storage/driver/.gitignore
> +releases
The test creates some test files, that are annoying when you have to do a commit :(

2019-03-18 13:07 UTC, sorenmat commented
@bacongobbler do you have any more feedback / comments for this one?

2019-10-03 14:59 UTC, bridgetkromhout commented
Hi, @sorenmat! As per [the September 26th, 2019 announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. As this feature affects the storage subsystem and given the complexity and short timeline at this point, we don't think we can get it into Helm 2. However, thank you for working on it, and hopefully you will want to bring it over to Helm 3!

2019-10-03 15:06 UTC, closed without merging