Refer to ChartMuseum in Helm Documentation
helm/helm pull request #5277
Opened 2019-02-07 08:13 UTC by SlickNik

Update the Helm documentation to add a reference to ChartMuseum under
the Chart Repositories section.

Closes #5208

Signed-off-by: Nikhil Manchanda <SlickNik@gmail.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-02-07 10:52 UTC, hickeyma requested changes

2019-02-07 10:52 UTC, hickeyma commented on docs/charts.md
> +### Chart Museum
Would it read better to be incorporated into the Chart Repositories section rather than in a subsection below it?

2019-02-07 10:52 UTC, hickeyma commented on docs/charts.md
> +backends. It works as a valid Helm Chart Repository, and also provides an API
Just wondering as you have mentioned that it is HELM repo already?
"It works as a valid Helm Chart Repository, and also provides an API for uploading charts." --> "It supports a REST API for chart repository management."

2019-02-08 16:53 UTC, bacongobbler commented
Hey @SlickNik, I'm going to close this in favour of #5282 since that PR talks about ChartMuseum in the "Chart Repositories" section of the docs. Thank you so much for the PR though! We really appreciate the effort you put into this. Thanks!

2019-02-08 16:53 UTC, closed without merging

2019-02-08 17:54 UTC, SlickNik commented
Works for me. Thanks for following through with this @bacongobbler, @jdolitsky!