Adding github workflow for contributing to helm
helm/helm pull request #5346
Opened 2019-02-22 08:24 UTC by truongnh1992

Describe detail step-by-step of using github to contribute to
helm project.

Co-Authored-By: Dao Cong Tien tiendc@vn.fujitsu.com
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

2019-02-22 13:58 UTC, mattfarina reviewed
Thanks for your interest in our contributions process. This type of content should be in the `CONTRIBUTING.md` file. That is the standard file name GitHub expects. Some of this is already in that file. Would you mind trying to make the improvements there.

2019-02-22 16:07 UTC, truongnh1992 commented
> Thanks for your interest in our contributions process. This type of content should be in the `CONTRIBUTING.md` file. That is the standard file name GitHub expects. Some of this is already in that file. Would you mind trying to make the improvements there.

I've just resolved your comment, the content of `CONTRIBUTING.md` has been updated.

2019-02-23 00:00 UTC, bacongobbler requested changes

2019-02-23 00:00 UTC, bacongobbler commented on CONTRIBUTING.md
> +$ git commit -s
Woudl you mind using the long form here? `git commit --signoff` is more memorable for first-timers in general.

2019-02-23 00:01 UTC, bacongobbler commented
Why were the file permissions on CONTRIBUTING.md changed from 644 to 755?

2019-02-23 16:09 UTC, truongnh1992 commented
> Why were the file permissions on CONTRIBUTING.md changed from 100644 to 100755?

Thank you for your review. I've already resolved all of your changes request.

2019-02-26 08:22 UTC, truongnh1992 commented
@mattfarina could you help me to review this change, please.

2019-04-25 16:47 UTC, michelleN approved these changes

2019-04-25 16:48 UTC, mattfarina approved these changes

2019-04-25 16:48 UTC, merged

2019-04-25 16:49 UTC, mattfarina commented
@truongnh1992 Thanks for the PR. We discussed it in the Helm Dev Call. It was a useful conversation.

2019-04-26 01:58 UTC, truongnh1992 commented
> 
> 
> @truongnh1992 Thanks for the PR. We discussed it in the Helm Dev Call. It was a useful conversation.

You're welcome. I'm willing to contribute to opensource project. By the way, how can I become a member of helm org on Github?

2019-04-30 13:58 UTC, mattfarina commented
@truongnh1992 You can contribute without being a member of the Helm org on GitHub. The members of the org are those who have been or currently are maintaining a project that is part of Helm.