Update deprecated URL for Helm's chart format in kubernetes.io
helm/helm pull request #5354
Opened 2019-02-25 04:41 UTC by longkb

Currently, the URL to **Chart format** in **kubernetes.io** is out of date.
This commit aims to update this URL to the working one in Helm's github that
user are able to access.

Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

**What this PR does / why we need it**:
Update deprecated URL
**Special notes for your reviewer**:
Just minor commit
**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-02-25 05:49 UTC, bacongobbler requested changes
Would you mind changing this to https://helm.sh/docs/developing_charts/#the-chart-yaml-file instead?

2019-02-25 06:09 UTC, longkb commented
> 
> 
> Would you mind changing this to https://helm.sh/docs/developing_charts/#the-chart-yaml-file instead?

Yeah! Thanks to your reviewing. I have push a change as your recommendation :)

2019-02-28 15:58 UTC, hickeyma approved these changes
LGTM, thanks

2019-02-28 16:27 UTC, bacongobbler approved these changes

2019-02-28 16:34 UTC, bacongobbler requested changes
I somehow missed that this was a change to one of the protobuf files. Because of this, you'll need to run `make protoc` to re-generate the resulting protobuf files [here](https://github.com/helm/helm/blob/33589472cf02d8d10e96e06085d95791c0611a75/pkg/proto/hapi/chart/metadata.pb.go#L74). Let me know if you have further questions.

2019-02-28 16:53 UTC, hickeyma commented
As I did. Good catch @bacongobbler .

2019-10-02 17:27 UTC, bacongobbler commented
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

2019-10-02 17:27 UTC, closed without merging