Preserve file permissions from tarball during plugin install
helm/helm pull request #5428
Opened 2019-03-10 23:27 UTC by walkafwalka

**What this PR does / why we need it**:

This PR fixes an issue where the files extracted from a tarball during plugin install do not have their permissions preserved. This is an issue because the binary for the plugin and the install hook are not set as executable, so they cannot be run which results in a permissions denied error when attempting to install a plugin via its tarball.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-03-10 23:47 UTC, walkafwalka commented
Attempted force push because the appveyor build failed due to what looks like networking issues. It happened again, so I am just going to leave it for a maintainer.

2019-03-14 15:21 UTC, hickeyma reviewed
@walkafwalka Can you provide an example of a plugin in tarball format?

2019-03-14 16:23 UTC, bacongobbler commented
^ would you mind writing a test for this in http_installer_test.go?

https://github.com/helm/helm/blob/master/pkg/plugin/installer/http_installer_test.go

2019-04-03 00:56 UTC, walkafwalka commented
It is not clear to me why the executable bit is not working for the _other_ group.
```
--- FAIL: TestExtract (0.00s)
    .../go/src/k8s.io/helm/pkg/plugin/installer/http_installer_test.go:279: Expected /tmp/helm-home-157712175/repository/cache/plugins/plugin-key/README.md to have 0666 mode it but has 775
```

2019-04-03 12:56 UTC, hickeyma commented
Seem like the `umask` is set which then restricts the file permission being set.

Add code similar to the following before [creating the tarball](https://github.com/helm/helm/blob/master/pkg/plugin/installer/http_installer_test.go#L216):
```console
 //reset the umask before setting file modes
 syscall.Umask(0000)```

2019-04-03 12:57 UTC, hickeyma requested changes
Seem like the `umask` is set which then restricts the file permission being set.

Add code similar to the following before [creating the tarball](https://github.com/helm/helm/blob/master/pkg/plugin/installer/http_installer_test.go#L216):
```console
 //reset the umask before setting file modes
 syscall.Umask(0000)
```

2019-04-03 15:16 UTC, walkafwalka commented
Thanks! That did it.

2019-04-08 09:10 UTC, hickeyma reviewed
@walkafwalka Would it be possible to provide an example plugin tarball which could be added to `pkg/plugin/testdata`? A test case could then be added to `pkg/plugin/installer/local_installer_test.go`  to test it. It think it would be beneficial to have this test case.

2019-04-08 09:26 UTC, hickeyma approved these changes

2019-04-26 09:10 UTC, hickeyma requested changes
Waiting on example tarball.

2019-04-30 15:27 UTC, walkafwalka commented
@hickeyma I will try to get to this soon. I have been swamped these past couple of weeks.

2019-04-30 15:33 UTC, hickeyma commented
@walkafwalka Not a bother.

2019-09-30 22:27 UTC, bacongobbler commented
ping

2019-10-03 18:21 UTC, bacongobbler approved these changes

2019-10-03 18:21 UTC, merged