Obtain release info from api.github.com
helm/helm pull request #5479
Opened 2019-03-20 08:02 UTC by rodrigc

Using the API is more stable than parsing HTML from the github.com web site.

Closes #5477

Signed-off-by: Craig Rodrigues <craig@portworx.com>

**What this PR does / why we need it**:

The get script is currently broken because it parses the GitHub release web site's HTML, and the format of the web site has changed.

2019-03-20 08:11 UTC, rodrigc commented
@bacongobbler the rate limiting rules are here: https://developer.github.com/v3/#rate-limiting

```
For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.
```

2019-03-20 10:04 UTC, bacongobbler requested changes
Thank you for the PR.

Because of the 60 requests per hour rate limit on unauthenticated requests, It is not okay to rely on api.github.com for general consumption. There are organizations that share an origin IP and will hit that rate limit often and frequently.

If you'd like to make this a separate script, that would be a welcome change.

2019-03-20 10:10 UTC, bacongobbler commented
Additionally, it'd be nice if the separate script handled injecting API keys into the API requests such that users could make authenticated requests to the API, gaining access to a much more reasonable rate limit of 5000 requests per hour.

2019-03-22 16:20 UTC, bacongobbler commented
closing in favour of https://github.com/helm/helm/pull/5491.

2019-03-22 16:20 UTC, closed without merging