feat(helm) add 'get version' to get the chart version
helm/helm pull request #5496
Opened 2019-03-21 15:30 UTC by jeff-knurek

Signed-off-by: Jeff Knurek <j.knurek@travelaudience.com>

**What this PR does / why we need it**:
Adding an option to `helm get` to obtain the chart version of the release that was installed. 

All other locations the chart version is listed, it gets appended to the chart name, whereas this provides just the version of the chart itself _(and therefor can be used in other helm commands that take `--version`)_

**If applicable**:
- [ ] this PR contains documentation _(I think the relevant docs are auto-generated)_
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility _(all new functionality, so not relevant)_

2019-03-21 16:11 UTC, bacongobbler commented
I think this would be better suited as a `--output` flag for `helm list`, as the chart metadata is intended to be displayed as part of `helm list`.


For example, if you were to introduce a Go template output format to `helm list`, you could accomplish the same functionality with

```
$ helm list my-release-name --format="{{ .Version }}"
```

That way we avoid the need for introducing commands for things like `helm get home`, `helm get description`, and `helm get maintainers`, for example.

2019-03-21 16:30 UTC, jeff-knurek commented
ok, that seems reasonable - but I don't have the slightest clue how to handle using a Go template to select the output

as in, I see where the `type listRelease struct` is currently used to show the output, but....???

also, there's a `.Version` that gets the revision, and a `.Version` that gets the metadata chart version, so what structure would the go template take??

2019-03-21 16:34 UTC, jeff-knurek commented
maybe the best compromise is to change this PR to be `helm get metadata --fields Version my-release-name` and then implement the different options in the metadata struct?

2019-03-21 17:01 UTC, bacongobbler commented
Have a look at the `helm version --template` flag; that should get you going.

2019-03-25 13:25 UTC, jeff-knurek commented
@bacongobbler I had a look into how the `--template` works, and then looked into adding it to `helm list`, however I feel that `helm list` is the wrong place to add this, so I added it to `helm get` directly which I think is definitely better than the original PR 

If you want, I can close this PR and open another PR of just this change

2019-05-02 13:04 UTC, hickeyma requested changes

2019-05-02 13:04 UTC, hickeyma commented on docs/helm/helm_get_version.md
> +## helm get version
This file is not needed and should be removed. All docs in docs/helm are generated file from the text specified in the helm command definition.  Ref: https://helm.sh/docs/developers/#man-pages

2019-05-02 13:10 UTC, hickeyma requested changes
@jeff-knurek Thanks for working on this.

I have tested it and it makes sense to be part of `helm get` because you want to get the chart version for a release.

Tested as follows:
```console
$ helm ls
NAME     	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
chrt-5586	2       	Wed May  1 17:23:18 2019	DEPLOYED	chrt-5586-0.1.0	1.0        	default  

$ helm get chrt-5586 --template="{{ .Release.Name }}" 
chrt-5586

$ helm get chrt-5586 --template="{{ .Release.Chart.Metadata.Version }}" 
0.1.0
```

Can you remove `docs/helm/helm_get_version.md` as it is not required.

2019-05-03 07:34 UTC, jeff-knurek commented
ok, file removed and I updated the title/description of the PR

2019-05-03 09:55 UTC, hickeyma approved these changes
LGTM, thanks for this.

2019-05-03 09:59 UTC, merged