feat(ci): push release assets to Azure and GCS
helm/helm pull request #5715
Opened 2019-05-10 14:53 UTC by bacongobbler

This PR installs the Azure CLI and pushes release assets to Azure, making Helm 2 releases available at https://get.helm.sh.

related to #5663 

This PR differs from #5694 because Helm 2 relies on `golang:1.12.5`, which runs as root so no use of `sudo` is required.

2019-05-20 17:33 UTC, jdolitsky approved these changes

2019-06-04 16:55 UTC, hickeyma requested changes
Looks good @bacongobbler. One small thing [release notes](https://github.com/helm/helm/blob/master/docs/release_checklist.md#8-write-the-release-notes) need updating in release checklist.

2019-06-04 17:13 UTC, bacongobbler commented
Thanks! Fixed those up. I also found that `make fetch-dist` still pointed at GCS so I fixed that up as well.

Once the Helm 2.14.0 release assets are available on get.helm.sh, this should be good to merge. I'll give it a quick manual test to make sure.

2019-06-04 17:42 UTC, bacongobbler commented
Also applied to https://github.com/helm/helm/pull/5841 to this PR.

2019-06-04 20:07 UTC, mattfarina approved these changes

2019-06-04 20:12 UTC, merged