support --output-dir option for helm3 template
helm/helm pull request #5762
Opened 2019-05-20 09:19 UTC by torstenwalter

**What this PR does / why we need it**:

helm 2 has an option to write the executed templates to files in output-dir instead of stdout.
This PR adds the same to helm3.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-05-20 17:16 UTC, jdolitsky approved these changes
LGTM

2019-05-28 13:52 UTC, hickeyma requested changes
@torstenwalter Thanks for submitting the PR. I have added some comments for change.
I think it would also be helpful if you could add a test case.

2019-05-28 13:52 UTC, hickeyma commented on pkg/action/install.go
> +		if outputDir == "" {
Should it be checked here for a blank template? This was similar to how it was checked in v2:
```console
if whitespaceRegex.MatchString(m.Content) {
        continue
}
```

2019-05-28 13:52 UTC, hickeyma commented on pkg/action/install.go
> +			err = writeToFile("build", m.Name, m.Content)
:s/"build"/outputDir

2019-05-28 15:28 UTC, torstenwalter commented
@hickeyma Thanks for your feedback. The suggested changes have been incorporated.

2019-05-28 17:07 UTC, hickeyma commented
@torstenwalter Would it be possible to add a unit test as mentioned in https://github.com/helm/helm/pull/5762#pullrequestreview-242671847 ?

2019-05-28 18:32 UTC, torstenwalter commented
@hickeyma Do have anything I can use as example? Haven't found any unit test in helm 2 for this.

2019-06-03 11:12 UTC, torstenwalter commented
@hickeyma While writing the test I fugured out that the check for empty manifests had no effect. They are never empty.

That's already implemented in
https://github.com/helm/helm/blob/dev-v3/pkg/releaseutil/manifest.go#L49-L51 and in https://github.com/helm/helm/blob/dev-v3/pkg/releaseutil/manifest_sorter.go#L88-L90

2019-06-03 11:14 UTC, torstenwalter commented
If you want I can also rebase and squash my changes on `dev-v3` branch.

2019-06-04 13:29 UTC, hickeyma approved these changes
LGTM, thanks for all your effort.

2019-06-04 13:29 UTC, merged