Add hpa to sorting order (port to v3)
helm/helm pull request #6047
Opened 2019-07-19 15:43 UTC by Constantin07

**What this PR does / why we need it**:

This is port of #6039 to v3

2019-07-19 15:49 UTC, hickeyma commented on pkg/releaseutil/kind_sorter_test.go
> +		{"uninstall", UninstallOrder, "wvmutsrrqponlkji2hgf1edcba!"},
wvmutsrrqponlkji2hgf1edcba! --> wvmutsxrqponlkji2hgf1edcba!

2019-07-19 15:50 UTC, bacongobbler commented
Would you mind fixing the failing tests?

> pkg/releaseutil/kind_sorter_test.go:132:11: undefined: util

2019-07-19 15:51 UTC, hickeyma requested changes
@Constantin07 Thanks for the PR. Small issue with the test.

2019-07-20 07:18 UTC, Constantin07 commented on pkg/releaseutil/kind_sorter_test.go
> +		{"uninstall", UninstallOrder, "wvmutsrrqponlkji2hgf1edcba!"},
Apologies, my bad.

2019-07-20 07:18 UTC, Constantin07 commented
Corrected now.

2019-07-22 09:40 UTC, hickeyma approved these changes
@Constantin07 LGTM, thanks

2019-07-22 09:41 UTC, merged