Fix a parsing issue with command line arguments
helm/helm pull request #6076
Opened 2019-07-24 21:44 UTC by ian-howell

Prior to now, helm has been silently ignoring any errors while parsing
the root Persistent flags. This causes an issue when a global flag comes
later on the command line than a localized flag for a subcommand, in
which the value for that global flag is never set. The solution is to
simply tell the Persistent flagset to ignore any unknown flags, since a
later command will process it

**What this PR does / why we need it**:
Closes #6073 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-07-25 15:09 UTC, mattfarina approved these changes

2019-07-25 15:37 UTC, bacongobbler approved these changes
Nice. Let me give this a quick spin right now before merging.

2019-07-25 15:47 UTC, bacongobbler requested changes
Found a case where this causes a panic. Can you please look into this?

```
><> ./bin/helm version --help
panic: pflag: help requested

goroutine 1 [running]:
main.newRootCmd(0xc0005aa540, 0x1b1b000, 0xc0000d2008, 0xc0000be160, 0x2, 0x2, 0x0)
        /home/bacongobbler/code/go/src/helm.sh/helm/cmd/helm/root.go:125 +0xf6d
main.main()
        /home/bacongobbler/code/go/src/helm.sh/helm/cmd/helm/helm.go:70 +0xa6
```

2019-07-25 16:02 UTC, ian-howell commented
@bacongobbler So with a quick glance, it's the error checking that causes the panic, and this happens regardless of whether `flags.ParseErrorsWhitelist.UnknownFlags` is set or not, meaning that `flags.Parse(args)` is returning an error any time the `--help` flag is passed.

So effectively, when a user runs `helm --help` on the current dev-v3, Parse ignores the `--help` flag, returns an error (which helm ignores), and helm proceeds as though the flag weren't passed. So `helm --help` is an equivalent call to just plain old `helm` right now.

I'm going to do a bit more digging, I imagine there's a value that needs to be set for `cobra.Command`s that fixes this.

2019-07-25 16:34 UTC, ian-howell commented
This change to the error handling fixes the help issue:
```
	if err := flags.Parse(args); err != nil {
		if err != pflag.ErrHelp {
			panic(err)
		}
	}
```

This still has the issue of panicking when an unknown flag is passed to helm, e.g. `helm --not-a-real-flag` will panic.

However after some digging through the `pflags` code, I've realized that any errors that occur during that call *should* be ignored, because if they are actually errors that we care about, they'll be caught later when the `cmd` is executed. I'll make the changes to reflect this.

2019-08-07 11:11 UTC, hickeyma commented
Tested as follows:

```console
$ helm version --help

Show the version for Helm.

This will print a representation the version of Helm.
The output will look something like this:

version.BuildInfo{Version:"v2.0.0", GitCommit:"ff52399e51bb880526e9cd0ed8386f6433b74da1", GitTreeState:"clean"}

- Version is the semantic version of the release.
- GitCommit is the SHA for the commit that this version was built from.
- GitTreeState is "clean" if there are no local code changes when this binary was
  built, and "dirty" if the binary was built from locally modified code.

Usage:
  helm version [flags]

Flags:
  -h, --help              help for version
      --short             print the version number
      --template string   template for version string format

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --debug                            enable verbose output
      --kube-context string              name of the kubeconfig context to use
      --kubeconfig string                path to the kubeconfig file
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --logtostderr                      log to standard error instead of files (default false)
  -n, --namespace string                 namespace scope for this request
      --skip-headers                     If true, avoid header prefixes in the log messages
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

$ helm create chrt-6076-3
Creating chrt-6076-3

$ helm --kubeconfig=/home/usr1/.kube/config.bak list
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          
chrt-6076 	default  	2       	2019-08-07 11:29:42.113884198 +0100 IST	deployed	chrt-6076-0.1.0
my-release	default  	2       	2019-08-07 10:36:39.30576271 +0100 IST 	deployed	mysql-1.3.0    

$ helm upgrade chrt-6076-3 chrt-6076-3/ -i --kubeconfig=/home/usr1/.kube/config.bak
Release "chrt-6076-3" does not exist. Installing it now.

$ helm --kubeconfig=/home/usr1/.kube/config.bak list
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076  	default  	2       	2019-08-07 11:29:42.113884198 +0100 IST	deployed	chrt-6076-0.1.0  
chrt-6076-3	default  	1       	2019-08-07 11:52:46.106000622 +0100 IST	deployed	chrt-6076-3-0.1.0
my-release 	default  	2       	2019-08-07 10:36:39.30576271 +0100 IST 	deployed	mysql-1.3.0      

$ helm list
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076-2	test     	2       	2019-08-07 11:36:37.480422228 +0100 IST	deployed	chrt-6076-2-0.1.0

$ helm upgrade chrt-6076-3 chrt-6076-3/ -i
Release "chrt-6076-3" does not exist. Installing it now.

$ helm list
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076-2	test     	2       	2019-08-07 11:36:37.480422228 +0100 IST	deployed	chrt-6076-2-0.1.0
chrt-6076-3	test     	1       	2019-08-07 11:53:23.774788741 +0100 IST	deployed	chrt-6076-3-0.1.0

$ helm upgrade chrt-6076-3 chrt-6076-3/
Release "chrt-6076-3" has been upgraded. Happy Helming!
NAME: chrt-6076-3
LAST DEPLOYED: 2019-08-07 11:54:50.055253005 +0100 IST
NAMESPACE: test
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=chrt-6076-3,release=chrt-6076-3" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm list
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076-2	test     	2       	2019-08-07 11:36:37.480422228 +0100 IST	deployed	chrt-6076-2-0.1.0
chrt-6076-3	test     	2       	2019-08-07 11:54:50.055253005 +0100 IST	deployed	chrt-6076-3-0.1.0

$ helm upgrade chrt-6076-3 chrt-6076-3/ --kubeconfig=/home/usr1/.kube/config.bak
Release "chrt-6076-3" has been upgraded. Happy Helming!
NAME: chrt-6076-3
LAST DEPLOYED: 2019-08-07 11:55:26.406447086 +0100 IST
NAMESPACE: default
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=chrt-6076-3,release=chrt-6076-3" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm --kubeconfig=/home/usr1/.kube/config.bak list
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076  	default  	2       	2019-08-07 11:29:42.113884198 +0100 IST	deployed	chrt-6076-0.1.0  
chrt-6076-3	default  	2       	2019-08-07 11:55:26.406447086 +0100 IST	deployed	chrt-6076-3-0.1.0
my-release 	default  	2       	2019-08-07 10:36:39.30576271 +0100 IST 	deployed	mysql-1.3.0
```

2019-08-07 11:12 UTC, hickeyma approved these changes
LGTM, thanks @ian-howell.

2019-08-07 11:12 UTC, merged