Updated upgrade to give more verbose output
helm/helm pull request #6202
Opened 2019-08-11 10:12 UTC by waveywaves

Similar to the install command

**What this PR does / why we need it**:
wrt https://github.com/helm/helm/issues/6172

2019-08-11 10:19 UTC, waveywaves commented
cc @hickeyma Can you review this ? 
This is the output the command gives now.
```
➜  helm3test helm upgrade -i trafickd-2 kubernetes-charts/traefik
Release "trafickd-2" does not exist. Installing it now.
NAME: trafickd-2
LAST DEPLOYED: 2019-08-11 15:48:36.555732669 +0530 IST m=+1.741079837
NAMESPACE: default
STATUS: deployed

NOTES:
1. Get Traefik's load balancer IP/hostname:

     NOTE: It may take a few minutes for this to become available.

     You can watch the status by running:

         $ kubectl get svc trafickd-2-traefik --namespace default -w

     Once 'EXTERNAL-IP' is no longer '<pending>':

         $ kubectl describe svc trafickd-2-traefik --namespace default | grep Ingress | awk '{print $3}'

2. Configure DNS records corresponding to Kubernetes ingress resources to point to the load balancer IP/hostname found in step 1      
```

2019-08-12 13:09 UTC, waveywaves commented
/assign @hickeyma

2019-08-12 14:58 UTC, bacongobbler commented
Dupe of #6200.

2019-08-12 14:58 UTC, bacongobbler commented
Dupe of #6200.

2019-08-12 14:59 UTC, bacongobbler commented
Actually, this looks to be the correct behaviour. The output should not be hidden behind the --debug flag.

2019-08-12 14:59 UTC, bacongobbler requested changes

2019-08-12 14:59 UTC, bacongobbler commented on cmd/helm/upgrade.go
> +
Can you remove this newline?

2019-08-12 16:17 UTC, waveywaves commented on cmd/helm/upgrade.go
> +
Updated. Removed the newline.

2019-08-12 16:20 UTC, bacongobbler approved these changes

2019-08-12 16:25 UTC, waveywaves commented
@bacongobbler Thanks for checking this out !

2019-08-12 16:38 UTC, merged