Fix wrongly displayed markdown #6230
helm/helm pull request #6231
Opened 2019-08-15 08:31 UTC by edbighead

Signed-off-by: Eduard Laur <mr.edlaur@gmail.com>

**What this PR does / why we need it**:
fix toml markdown displayed in Github (#6230)

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-08-15 16:14 UTC, mattfarina requested changes
Thank you for the pull request. These are supposed to be toml files so that should not change. What's wrong is the use of strings in the toml. They should be surrounded by quotes. You can read about toml and strings at https://github.com/toml-lang/toml#string. Would you be willing to fix the toml?

2019-08-15 18:21 UTC, edbighead commented
Sure

2019-08-16 06:41 UTC, edbighead commented
@mattfarina Done

2019-10-02 17:36 UTC, bacongobbler approved these changes

2019-10-03 18:48 UTC, merged