do not exit if stable repo miss
helm/helm pull request #6258
Opened 2019-08-21 03:07 UTC by daixiang0

Signed-off-by: Xiang Dai <764524258@qq.com>

**What this PR does / why we need it**:
Fix #6005

2019-08-21 15:28 UTC, thomastaylor312 requested changes
I don't think this solves the problem as described in #6005. With this change if I have a dependency on a repository called `foo` and `foo` doesn't exist in my repos, this will not error out like it should. I would suggest adding a section that checks if it is a URL and then add that to the dependency maps

2019-08-22 03:14 UTC, daixiang0 commented
@thomastaylor312 please review again.

2019-08-26 02:42 UTC, daixiang0 commented
@thomastaylor312 any update?

2019-08-27 02:00 UTC, daixiang0 commented
@thomastaylor312 never mind, happy to wait for review:)

2019-08-27 16:05 UTC, thomastaylor312 requested changes
When I was testing this, I got the following error when trying to update:
```
Error: no cached repo found. (try 'helm repo update'). open /Users/taylor/.helm/repository/cache/-index.yaml: no such file or directory
```

I believe this is due to the fact that there is no repo name when there is a URL, and so it is pointing to a non-existent cache file. It will need to bypass this when there is no name and fetch the chart directly

2019-08-28 05:57 UTC, daixiang0 commented
@thomastaylor312 hi, i tried to bypass this, but i am confused that when i run `make build` then check version, its version is ok, but the output still old not my code, is there anything i miss?

2019-09-04 01:51 UTC, daixiang0 commented
@thomastaylor312 hi, mind have a look?

2019-09-04 15:45 UTC, thomastaylor312 commented
@daixiang0 Sorry! I must have misread your comment. Are you ready for me to take a look at this or are you having problems getting it to build?

2019-09-05 02:24 UTC, daixiang0 commented
@thomastaylor312 yep, i met problems when build since what i build do not expected what i code. Do not find detail docs about it, please help me.

2019-09-05 20:29 UTC, thomastaylor312 commented
I pulled down your branch and was able to run `make bootstrap build` just fine. If things don't seem to be building, you can always do `rm -rf bin/` and then re-run a `make build` to make sure you don't have anything stale around

2019-09-06 02:04 UTC, daixiang0 commented
@thomastaylor312 i am really confused, after build, check version that client commit is correct, but what i code do not work, and try to add something in debug while not work too.
```
git checkout fix-stable
rm -rf bin
make build
cd /path/to/test
/path/to/bin/helm version <== git commit is correct
/path/to/bin/helm dependency update --debug <=== no custom debug info
```

2019-09-06 16:01 UTC, thomastaylor312 commented
Assuming you are trying to print some debug logic that you added, it is most likely because you aren't hitting that branch of logic because of some edge case you are running into. I'd need to see exactly what you had added to the code for debugging to be sure though

2019-09-09 02:52 UTC, daixiang0 commented
@thomastaylor312 i get the key: i should clone to  `k8s.io/helm` not `github.com/helm`.
I want to add docs about build stuff, which place do you think is good for PR?

2019-09-09 03:15 UTC, karuppiah7890 commented
@daixoang0 adding to this, you could also add docs for helm v3 (dev-v3) branch, for which code has to be present at $GOPATH/src/helm.sh/helm

2019-09-10 02:14 UTC, daixiang0 commented
@thomastaylor312 please review

2019-09-17 11:34 UTC, daixiang0 commented
@thomastaylor312 mind have a look?

2019-09-18 13:11 UTC, woodcockjosh commented
@thomastaylor312 I have tested @daixiang0 branch. I run `helm dep up` I still get this message `Error: no repository definition for https://helm.elastic.co, https://helm.elastic.co. Please add them via 'helm repo add'` In its current state I don't see how this fixes #6005 but am very interested in helping if any help is needed.

2019-09-18 13:16 UTC, woodcockjosh commented
@thomastaylor312 I just checked @daixiang0 branch. This appears to be working.

2019-09-18 13:25 UTC, woodcockjosh commented
relates to #6454

2019-09-19 18:41 UTC, thomastaylor312 approved these changes
This is looking good! Thanks for all the hard work!

2019-09-19 18:41 UTC, thomastaylor312 commented on pkg/resolver/resolver.go
> +		cacheRepoName := repoNames[d.Name]
Nit: The if statement could be simplified to
```suggestion
		cacheRepoName, ok := repoNames[d.Name]
		if !ok && d.Repository != "" {
```

2019-09-19 18:41 UTC, thomastaylor312 commented
@woodcockjosh Thanks for taking a look at this and validating

2019-09-19 18:43 UTC, thomastaylor312 commented on pkg/resolver/resolver.go
> +		cacheRepoName := repoNames[d.Name]
Since this is just a minor, non-blocking nit. I am going to merge

2019-09-19 18:43 UTC, merged