feat(cmd/helm): remove need for helm init command
helm/helm pull request #6272
Opened 2019-08-23 06:43 UTC by adamreese

* allow repository config via cli
* make `helm repo add` create repo config file if it does not exist
* squash a ton of bugs
* remove init command

2019-08-24 00:35 UTC, thomastaylor312 requested changes
Just a few questions and some non-blocking nits

2019-08-24 00:35 UTC, thomastaylor312 commented on pkg/repo/chartrepo.go
> +	fname := filepath.Join(r.CachePath, r.Config.Name+"-index.yaml")
Should this be some functionality inside of `helmpath` or is this just a one off?

2019-08-24 03:29 UTC, adamreese commented on cmd/helm/repo_add.go
> +	if err := yaml.Unmarshal(b, &f); err != nil {
Because we want to handle the case of no file existing.

2019-08-26 17:18 UTC, thomastaylor312 approved these changes
LGTM

2019-08-26 17:26 UTC, merged