(fix/issue-6267) Fixed interface type casting in parser.go
helm/helm pull request #6289
Opened 2019-08-27 00:50 UTC by waveywaves

**What this PR does / why we need it**:
wrt #6267 

**Special notes for your reviewer**:
Seems that when multiple --set values are provided, it is not able to handle it correctly.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-08-27 00:59 UTC, waveywaves commented
cc @technosophos

2019-08-27 01:30 UTC, karuppiah7890 commented
A unit test for this would be great 😄

2019-08-27 01:31 UTC, karuppiah7890 commented
I'm not sure how to write the failing test though. May be first gracefully handle the error and show it. Then write a failing test for it and then make sure error doesn't come

2019-08-27 01:40 UTC, karuppiah7890 commented
While doing type assertion, we could check if the assertion is correct using the second return value, and if it's not, we can handle it gracefully instead of having runtime panic https://golang.org/ref/spec#Type_assertions

2019-09-04 14:27 UTC, mattfarina requested changes
I followed the directions on 6116 to create the chart and passing in values via `--set` did not cause any issues. But, accessing those values in a template caused a stack overflow.

2019-09-04 14:29 UTC, waveywaves commented
@mattfarina Can you share a screen shot if possible ?

2019-10-07 21:22 UTC, hickeyma reviewed
@waveywaves Think I might have the issue that @mattfarina is referring to in https://github.com/helm/helm/pull/6289#pullrequestreview-283657367. I use the values file as per #6116 and then do the following:

```console
$ cat chrt-6116/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  params: {{ index (index .Values.dashboards.clustersmonitoringjson.select 0 0).params 0 }}
  type: {{ (index .Values.dashboards.clustersmonitoringjson.select  0 0).type }}

$ helm template chrt-6116/
---
# Source: chrt-6116/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-configmap
data:
  myvalue: "Hello World"
  params: status
  type: field

$ helm template chrt-6116/ --set dashboards.clustersmonitoringjson.select[0][0].params[0]=status --set dashboards.clustersmonitoringjson.select[0][0].type=field
Error: template: chrt-6116/templates/configmap.yaml:7:77: executing "chrt-6116/templates/configmap.yaml" at <0>: can't evaluate field params in type []interface {}
```

2019-10-09 07:06 UTC, waveywaves commented
@hickeyma I will update this fix accordingly and test what you are doing there as well.

2019-10-17 22:44 UTC, bacongobbler commented
ping. Where are we on this PR? Is there something blocking you from moving forward that we can help with?

2019-10-19 18:24 UTC, waveywaves commented
@bacongobbler I am working on this right now. Updating it.

2019-10-21 19:27 UTC, closed without merging

2019-10-21 19:41 UTC, bacongobbler commented
Apologies for the automatic closure. We just switched the `dev-v3` branch to `master`, and the old `master` branch is now `dev-v2`. Feel free to re-open a new PR with this change. Thanks again and sorry for the hassle!