feat(pkg/kube): add openapi validation for k8s objects
helm/helm pull request #6599
Opened 2019-10-07 22:16 UTC by adamreese

Add back OpenAPI validation for kubernetes objects.

Fixes: #6382

2019-10-07 22:30 UTC, bacongobbler approved these changes

2019-10-07 22:30 UTC, bacongobbler commented
Seems fairly straightforward. LGTM!

2019-10-08 10:53 UTC, hickeyma requested changes
@adamreese Thanks for this. Looks good but could you take a  look at the order in builder?

2019-10-08 10:53 UTC, hickeyma commented on pkg/kube/client.go
> +		Schema(schema).
Should `Schema` be before `Stream` as per https://github.com/helm/helm/pull/5576 ?

2019-10-09 15:15 UTC, hickeyma approved these changes
LGTM, thanks @adamreese

2019-10-09 16:23 UTC, merged