Modified the scope of Kubeconfig so it could be set outside an env va…
helm/helm pull request #6660
Opened 2019-10-13 15:57 UTC by aaronmell

**What this PR does / why we need it**:
After trying to start the terraform provider again, I realized that I had no way to set the kube config now, one of the CR requests modified the scope of the variable. I change the scope of the config back to its original state and renamed the conflicting function to something more descriptive. 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2019-10-13 16:00 UTC, aaronmell commented
@thomastaylor312 Can I get a CR please?

2019-10-14 15:56 UTC, thomastaylor312 requested changes
Just a few small changes and it should be good to go

2019-10-14 15:56 UTC, thomastaylor312 commented on pkg/cli/environment.go
> +func (s *EnvSettings) RestClientGetter() genericclioptions.RESTClientGetter {
This should be `RESTClientGetter`

2019-10-14 15:56 UTC, thomastaylor312 commented on pkg/cli/environment.go
> +	//kubeConfig string
Can you please remove the commented line?

2019-10-14 18:13 UTC, thomastaylor312 approved these changes

2019-10-14 18:14 UTC, thomastaylor312 commented
Good to go pending rebase!

2019-10-14 19:04 UTC, aaronmell commented
Rebase completed

2019-10-14 19:07 UTC, thomastaylor312 commented
Thanks for fixing this @aaronmell!

2019-10-14 19:07 UTC, merged