Allow namespace to be set by programs consuming helm.
helm/helm pull request #6798
Opened 2019-10-27 04:26 UTC by aaronmell

Signed-off-by: Aaron Mell <amell@lumindigital.com>
When consuming the helm client, there is no way to correctly set the namespace except via an env variable, and that doesn't work with terraform possibly running the client concurrently in multiple namespaces. 

I'm not sure if you want to expose Namespace. If thats the case, maybe a SetNamespace function?

2019-10-27 15:55 UTC, bacongobbler approved these changes

2019-10-27 15:56 UTC, bacongobbler commented
Would you mind writing a unit test to cover this?

2019-10-27 22:03 UTC, aaronmell commented
Sure, were you thinking a test to verify that the namespace is correct? or something else?

2019-10-28 17:05 UTC, thomastaylor312 commented
Labeled as breaking because it is changing a publicly exported function signature

2019-10-28 17:34 UTC, aaronmell commented
@bacongobbler @thomastaylor312 I reworked my change to reduce the scope, I think its a better way to fix it than changing the Namespace scope.

2019-10-28 17:56 UTC, thomastaylor312 requested changes
This does look much cleaner. Just one thing to remove

2019-10-28 17:56 UTC, thomastaylor312 commented on cmd/helm/helm.go
> +	// var namespace string
I assume this commented code doesn't need to be here?

2019-10-28 18:07 UTC, thomastaylor312 approved these changes
I'll let @bacongobbler give this one more look because he started review

2019-10-28 18:14 UTC, bacongobbler approved these changes

2019-10-28 18:58 UTC, merged