ref(pkg/action): split test of filterList
helm/helm pull request #6875
Opened 2019-11-03 14:07 UTC by jabielecki

The existing unit test doesn't cover the most important functionality
of `filterList()`. Split to cover it. Separately test the specific
namespace-related behavior.

Remove the dead variable `anotherOldOne`.

Summon @karuppiah7890

Signed-off-by: Jakub Bielecki <jakub.bielecki@codilime.com>

2019-11-03 14:19 UTC, karuppiah7890 commented
Thanks for this 😄 Just one thing, I felt the name of the function `TestFilterList_Namespace` might not do justice for people who come later and check it out. May be a single function with two `t.Run`s with a string defining what's being tested might help. Just a thought

LGTM 👍  Still, core maintainers vote only counts and they will check it out and merge 😄

2019-11-05 21:21 UTC, bacongobbler commented
marking as a code refactor to look at after Helm 3 has been released. Just letting you know it'll be a while before we come back to take a look at this proposal. Thanks!

2019-12-10 20:13 UTC, jabielecki commented
@bacongobbler Is there a problem with merging this? It's non-breaking, doesn't even touch anything besides a test.

2019-12-10 21:59 UTC, bacongobbler commented
Would you mind rebasing on top of master? Looks like some stray commits got mixed in here. Thanks!

2019-12-11 14:01 UTC, hickeyma requested changes
Thanks for this PR @jabielecki. I like the cleanup of the tests. I would however like it left in the one function `TestFilterList` for easier maintenance (as @karuppiah7890 mentioned). You can use test `Run` capability. See here for an example: https://github.com/helm/helm/blob/master/pkg/action/lint_test.go#L92

2019-12-11 18:49 UTC, jabielecki commented
Rebased. Refactored. Ready for merge. @bacongobbler

2019-12-11 18:50 UTC, jabielecki commented
> You can use test `Run` capability.
Done @hickeyma

2019-12-12 11:41 UTC, hickeyma approved these changes
LGTM, thanks @jabielecki

2019-12-12 11:41 UTC, merged

2019-12-17 17:48 UTC, technosophos commented
picked into release-3.0