print gvk information on existing resource conflict
helm/helm pull request #6904
Opened 2019-11-07 15:34 UTC by bakito

This PR adds additional information to resource conflict error messages.
We were facing some issues due to API version changes and had difficulties on finding the reason of the conflict.
Adding group and version helps a lot, since the id's of resources are compared with all this data.

Signed-off-by: Marc Brugger <github@bakito.ch>

2019-12-09 14:52 UTC, cdrage commented
@bakito Trying to replicate the issue, mind providing some steps @bakito ?

2019-12-09 16:19 UTC, bakito commented
We die an upgrade of our OpenShift cluster, where the api of some resources got converted from api version alpha to beta.
Since the Helm chart war installed with the api version alpha, we could not do an upgrade of the chart, because the version of the resource in the manifest (alpha) of the old chart did not match the version of the current resource (beta).

The error message that is changed in this PR only shows kind and name of the resource, but not the version.

I've spent hours on finding the problem, since  helm could not upgrade the chart.

This was also why i wrote this helm plugin to patch the chart to be able to do an upgrade after api version change. https://github.com/bakito/helm-patch

2020-01-08 17:33 UTC, bacongobbler requested changes

2020-01-08 17:33 UTC, bacongobbler commented on pkg/action/validate.go
> +		return fmt.Errorf("existing resource conflict: namespace: %s, name: %s, existing: [gvk: %s, ] / new: [gvk: %s]", info.Namespace, info.Name, existing.GetObjectKind().GroupVersionKind(), info.Mapping
can you fix the error output? looks like some extra characters were added in here.

should be:

```
"existing resource conflict: namespace: %s, name: %s, existing_kind: %s, new_kind: %s",
```

2020-01-08 17:54 UTC, bacongobbler approved these changes

2020-01-08 17:54 UTC, merged

2020-01-08 17:54 UTC, bacongobbler commented
thanks!