Fix secure installation link in helm init
helm/helm pull request #6912
Opened 2019-11-08 15:14 UTC by orlangure

I noticed that the link that appears after `helm init` is incorrect: apparently docs moved to another location. This PR fixes the link to the correct one.

2019-11-08 15:42 UTC, bacongobbler commented
Hi @orlangure, please re-open this PR against the `dev-v2` branch instead. Thanks!

2019-11-08 15:42 UTC, bacongobbler commented
(re-opening as I forgot base branches can be changed now via https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request)

2019-11-08 15:43 UTC, bacongobbler commented
would you mind rebasing this?

2019-11-09 10:06 UTC, orlangure commented
@bacongobbler all should be good now, is there anything else I need to do?

2019-12-10 18:33 UTC, hickeyma requested changes
@orlangure v2 docs link has changed.

2019-12-10 18:33 UTC, hickeyma commented on cmd/helm/init.go
> +					"For more information on securing your installation see: https://helm.sh/docs/securing_installation/")
v2 docs have now moved. Link is now: https://v2.helm.sh/docs/securing_installation/

2020-01-08 17:36 UTC, bacongobbler commented
ping ^

2020-01-09 10:53 UTC, hickeyma approved these changes
LGTM, thanks for fixing the link @orlangure

2020-01-09 10:53 UTC, merged