WIP: ref(client): add overwrite option
helm/helm pull request #6987
Opened 2019-11-16 23:19 UTC by jkroepke

See: https://github.com/helm/helm/issues/6980

Adds a parameter called `--overwrite` which enable the helm v2 upgrade behaviour. 

Sometimes a manifest is modified by an operator. In this cases helm should not overwrite the changes. Since this is very rarely i decide to add an optional parameter to `helm upgrade`. If overwrite is enabled, the old CreateTwoWayMergePatch like in helm 2 is used.

I used the code from https://github.com/helm/helm/pull/6124

This is my first-time contribution to this problem. Let me know if I miss something. Thanks

2019-11-17 03:10 UTC, bacongobbler commented
@hickeyma and I talked about maintaining multiple different merge patch strategies a while back to allow users to determine the patch strategy they desire, so this makes sense from a design point of view.

What do you think about renaming the flag to `--merge-strategy two-way`? That way we can default to the current merge strategy (`three-way`), and potentially enable alternative merge patch strategies as they become useful (like Kubernetes' experimental server-side apply logic).

2019-11-17 10:03 UTC, jkroepke commented
@bacongobbler 

This was my first intention. Then I choose `--overwrite` since this is more understandable without read the docs then `--merge-strategy`. But I'm also fine with the `--merge-strategy` option but this needs more documentation.

`kubectl apply` has also a parameter `overwrite` but it could be have a different meaning, e.g. the overwrite option at the three-way patch strategy.

2019-11-17 16:01 UTC, bacongobbler commented
Yes. It has different semantics. It overwrites objects when there's a merge conflict

2019-11-18 20:36 UTC, jkroepke commented
@bacongobbler Do you want to discuss it in your weekly if exists? Didn't know the next steps here.

2019-11-18 21:38 UTC, bacongobbler commented
the next two weeks' meetings are cancelled due to KubeCon NA, so if you can hold off until then, that would be a good place to discuss next steps. You could also ask other maintainers to weigh in on this topic in the #helm-dev channel on Kubernetes' slack channel. :)

2019-11-27 20:32 UTC, jkroepke commented
I would like to see this in helm 3.1 but I don't want to push or force someone.

It would be great to get some feedback.

2020-06-04 14:33 UTC, jdolitsky requested changes

2020-06-04 14:33 UTC, jdolitsky commented on pkg/kube/client.go
> +func (c *Client) Update(original, target ResourceList, force bool, overwrite bool) (*Result, error) {
I think we will want to find a way to do this without modifying the method signature

2020-07-07 17:18 UTC, bacongobbler commented
It's unclear to me whether this case is covered already by `--force`. `--force` forgoes the 3-way merge patch and performs a PUT operation on the manifest. As far as I understand, `--overwrite` is just re implementing the same use case but in a different way.

Have you had a chance to look at the `--merge-strategy` idea proposed earlier? It's been 8 months since we last discussed this so it might not be readily available in my mind.

It's also worth asking whether there is there still a use case for this 8 months later.

2020-07-07 19:38 UTC, closed without merging

2020-07-07 19:40 UTC, jkroepke commented
> It's also worth asking whether there is there still a use case for this 8 months later.

I meantime we found an other a solution to resolve our problem.