docs(install): clarify the --replace flag
helm/helm pull request #7089
Opened 2019-11-27 10:12 UTC by remcohaszing

The description of the `--replace` flag was unclear, as it can’t be used to replace active releases.

I thought this was a bug, but the current behaviour works as expected according to some discussions in #6122.

Signed-off-by: Remco Haszing <remcohaszing@gmail.com>

2019-11-27 16:58 UTC, hickeyma requested changes
@remcohaszing Thanks for pushing this clarification. I have a suggestion on the text.

2019-11-27 16:58 UTC, hickeyma commented on cmd/helm/install.go
> +	f.BoolVar(&client.Replace, "replace", false, "re-use the given name, even if that name is already used by a deleted release with history kept. This is unsafe in production")
I think it might read better as follows: "re-use the given name, only if that name is a deleted release which remains in the history." ?

2019-11-27 19:58 UTC, towolf commented
For real, we were not using `helm install` before, due to tiller, and now want to "adopt" the existing k8s resources when they come wrapped in a helm 3 release.

So, why does `helm install --replace` not overwrite the existing resources, when they are found in the cluster? Why is that the expected behaviour? @bacongobbler

2019-11-28 09:35 UTC, hickeyma reviewed
@remcohaszing Do you mind signing the dco: https://helm.sh/blog/helm-dco/#what-if-i-forget-to-sign-off-on-a-commit

2019-11-28 09:42 UTC, remcohaszing commented
> @remcohaszing Do you mind signing the dco: https://helm.sh/blog/helm-dco/#what-if-i-forget-to-sign-off-on-a-commit

Oops, amended :sweat_smile:

2019-11-28 10:01 UTC, hickeyma approved these changes
LGTM, thanks @remcohaszing

2019-11-28 10:01 UTC, hickeyma commented
Going to hold off on merging as waiting ion response to question asked in https://github.com/helm/helm/pull/7089#issuecomment-559231798

2019-11-28 10:07 UTC, towolf commented
> Going to hold off on merging as waiting on response to question asked in #7089 (comment)

Thanks, I'd really love to know why it's refusing to replace the resources.

I think `install --replace` or maybe `install --replace --force` should say "these names are mine now, going to replace them".

2019-11-28 10:10 UTC, remcohaszing commented
I also need the feature mentioned in https://github.com/helm/helm/pull/7089#issuecomment-559231798. This is why I ran into this in the first place.

I created #7103 as a feature request to support this.

2019-11-28 12:01 UTC, hickeyma commented
@towolf Going to merge as this PR related to updating the help doc to the current implementation. Do you mind re-asking your question from https://github.com/helm/helm/pull/7089#issuecomment-559231798 in #7103 ?

2019-11-28 12:01 UTC, merged