fix "Chart.lock is out of sync with Chart.yaml"
helm/helm pull request #7119
Opened 2019-11-30 06:35 UTC by zwwhdls

fixed #7101

I have found that downloadAll() might overwrite version in Chart.lock.

It's because this function will download a specific version of chart to dir "charts/" and then the specific version will overwrite the version in Chart.lock.

My solution is recalculate lock digest after downloadAll().

2019-11-30 07:52 UTC, bacongobbler commented
Hi! Can you write a test to confirm this behaviour? Thanks!

2019-11-30 12:53 UTC, zwwhdls commented
@bacongobbler Hi, I added a test case for this issue.

2019-12-02 16:27 UTC, hickeyma requested changes
Looking good @zwwhdls. Small nit before merge.

2019-12-02 16:27 UTC, hickeyma commented on pkg/downloader/manager_test.go
> +func TestUpdate_BeforeBuild(t *testing.T) {
Rename as `TestUpdateBeforeBuild` to follow test name continuity

2019-12-03 02:31 UTC, zwwhdls commented
@hickeyma Hi, I have renamed the testcase already.

2019-12-04 14:25 UTC, hickeyma approved these changes
LGTM, thanks @zwwhdls

2019-12-04 14:25 UTC, merged