[v2]stop with an error immediately if a file or directory with that name already exists
helm/helm pull request #7188
Opened 2019-12-08 07:13 UTC by zwwhdls

fix https://github.com/helm/helm/issues/7182

same as https://github.com/helm/helm/pull/7187

Signed-off-by: zwwhdls <zwwhdls@hotmail.com>

2019-12-08 07:16 UTC, karuppiah7890 requested changes

2019-12-08 07:16 UTC, karuppiah7890 commented on cmd/helm/fetch.go
> +			return fmt.Errorf("ailed to untar: a file or directory with the name %s already exists", ud)
a small typo `failed`

2019-12-08 08:02 UTC, zwwhdls commented on cmd/helm/fetch.go
> +			return fmt.Errorf("ailed to untar: a file or directory with the name %s already exists", ud)
🤣fixed.

2019-12-10 18:26 UTC, technosophos approved these changes
This might be seen as "breaking backward compatibility", but I would argue that it is a bug fix. We shouldn't let the user partially overwrite a chart because it will lead to really hard to debug problems.

Fix LGTM

2019-12-10 18:36 UTC, karuppiah7890 commented
I just wanted to add this - could we check for the error message in the test? To be sure that it's the expected error message. And also have separate tests for file and directory, both with same name as chat being extracted/untarred

2019-12-12 13:41 UTC, hickeyma requested changes
We should check on the clashing directory in the message as per review for Helm 3 https://github.com/helm/helm/pull/7187#pullrequestreview-330454226. Lets hold on this PR until v3 is merged first.

2020-01-23 14:30 UTC, hickeyma approved these changes
LGTM, thanks for porting this @zwwhdls

2020-01-23 14:31 UTC, merged