fix(kube): Port use of watcher with retries to wait for resources
helm/helm pull request #7217
Opened 2019-12-12 11:20 UTC by hickeyma

Port of Helm 2 PR #6014 to Helm 3

2019-12-12 11:27 UTC, hickeyma commented
@novoxudonoser  if you get a chance, can you test this fix and see if it resolves your issue in #7210?

2019-12-12 13:22 UTC, novoxudonoser commented
@hickeyma I don`t know much about helm code base, but will this pr add periodical TCP "heartbeats" (looks like maybe) ?

2019-12-12 14:00 UTC, hickeyma commented
@novoxudonoser I was thinking you could fetch the pr, do a build and try it out. If you not sure about doing this, you can wait till the pr is delivered and put in a release to check.

2019-12-12 14:01 UTC, novoxudonoser commented
@hickeyma I am on my way to test it (but I need some time to build helm from source) just wanted to find out my idea about what this pr is actually fixing.

2019-12-12 14:10 UTC, hickeyma commented
@novoxudonoser Context on the issue described in https://github.com/helm/helm/issues/2918#issuecomment-515020383 and in the issue thread.

2019-12-12 14:14 UTC, novoxudonoser commented
@hickeyma thanks for the direct point, I was locking to this comment previously, I just wanted to prove that `NewListWatchFromClient` will fix the load balancer timeout issue (Again I am not quite familiar with helm and kubectl code base).

2019-12-12 14:21 UTC, novoxudonoser commented
@hickeyma @thomastaylor312 just tested this pr, yes it fixes the issue :tada:. @hickeyma Big thank you for your operative pr.

2019-12-12 15:05 UTC, novoxudonoser commented
@hickeyma seems not fixed, just retested it now, 5min is timeout for tcp connection on Nginx load balancer and the error spawned just after 5 min, and its error text is different. So seems there is some problem with pr.
```
~/nixpkgs/result/bin/helm upgrade --install myname . --timeout 3000s -n myname
Release "myname" does not exist. Installing it now.



Error: no objects visited

test_timeout_hook on  master at ☸️  myclaster () took 5m 11s 855ms 
```

2019-12-13 17:00 UTC, thomastaylor312 requested changes

2019-12-13 17:19 UTC, hickeyma commented on pkg/kube/client.go
> +	lw := cachetools.NewListWatchFromClient(info.Client, info.Mapping.Resource.Resource, info.Namespace, fields.Everything())
Thanks for feedback @thomastaylor312. I will push new commit when I get a chance.

2019-12-16 11:24 UTC, hickeyma commented on pkg/kube/client.go
> +	lw := cachetools.NewListWatchFromClient(info.Client, info.Mapping.Resource.Resource, info.Namespace, fields.Everything())
Done

2019-12-16 11:25 UTC, hickeyma commented
@thomastaylor312 Thanks for the feedback. Updated and ready for review again.

2019-12-17 17:28 UTC, technosophos approved these changes

2019-12-17 17:32 UTC, thomastaylor312 approved these changes
LGTM. @novoxudonoser this PR is ok to go in as is because it is a missing port from Helm 2. However, it it is not solving the problem, let's see what else we can figure out

2019-12-17 17:41 UTC, merged

2019-12-17 17:54 UTC, technosophos commented
Picked into release-3.0