try fix last deployed release
helm/helm pull request #7238
Opened 2019-12-16 12:39 UTC by jason-liew

Signed-off-by: Jason Liew <jason_liew@163.com>

2019-12-16 12:40 UTC, jason-liew commented
[#6850 comment](https://github.com/helm/helm/issues/6850#issuecomment-566032294)

2019-12-17 20:43 UTC, bacongobbler commented
Hi @jason-liew. Would you mind writing a unit test to cover the case you are trying to fix? That would be much appreciated. Have a look at [storage_test.go](https://github.com/helm/helm/blob/master/pkg/storage/storage_test.go) for ideas. Thanks!

2019-12-17 20:43 UTC, bacongobbler requested changes
needs unit tests to confirm whether this fixes the issue proposed

2019-12-19 06:47 UTC, jason-liew commented on pkg/storage/storage.go
> +	relutil.SortByRevision(ls)
usually the order is correct without sort. may be some storage driver need sort.

2019-12-19 06:49 UTC, jason-liew commented
Hi, @bacongobbler unit test updated. Thanks.

2020-02-07 11:02 UTC, jason-liew commented
some similar pr has been merged

2020-02-07 11:02 UTC, closed without merging