WIP(proposal): Post render hooks for Helm
helm/helm pull request #7259
Opened 2019-12-17 21:10 UTC by thomastaylor312

This adds post-rendering hooks for Helm. See the proposal issue for full details

2020-01-28 13:16 UTC, thomastaylor312 commented
Here is the associated docs PR for this new feature: https://github.com/helm/helm-www/pull/479

2020-01-28 15:16 UTC, mattfarina requested changes
Musing for a moment, this works differently than the downloader getter hook. I'd like to have a consistent pattern to this sort of thing so we can replicate it again. I like this pattern and work here.

In the getter a scheme is registered and the right plugin file to call is looked up from the registration. This also enables plugins to have [platform specific commands](https://helm.sh/docs/topics/plugins/#building-plugins). I'm thinking of Windows here (something the whole CNCF community has not tended to handle well)

Should we make the plugin interaction follow a similar scheme?

2020-01-29 09:51 UTC, thomastaylor312 commented on pkg/postrender/exec.go
> +		_, err := os.Stat(filepath.Join(pluginDir, binaryPath))
Let me take a look and see if I could do that. I honestly thought there is always a _single_ plugin directory.

2020-01-29 09:52 UTC, thomastaylor312 commented on pkg/postrender/exec.go
> +		_, err := os.Stat(filepath.Join(pluginDir, binaryPath))
Let me take a look and see if I could do that. I honestly thought there is always a single plugin directory.

2020-01-29 09:55 UTC, thomastaylor312 commented
@mattfarina I am not sure I am following what you are are saying here. Is the blocking change on the single comment around handling a list of directories and the comment for the review just a general musing? Or are you saying that if the post-renderer is coming from a plugin directory to have this handle it differently?

2020-01-29 10:10 UTC, thomastaylor312 commented on pkg/postrender/exec.go
> +		_, err := os.Stat(filepath.Join(pluginDir, binaryPath))
Ok, support (and a test) added

2020-01-31 17:27 UTC, technosophos commented
What @mattfarina is suggesting is that you follow the plugin pattern used to extend downloads. Right now, a plugin can declare that it handles a protocol (e.g. `foo://`). When a download request is received, it will check whether any plugins handle that protocol. If so, it will load the plugin, execute it, and pipe the data back into Helm.

I think that the suggestion is to use the plugin pattern for post-render hooks for a few reasons:

- It provides a clear path for multi-platform binaries
- It follows an existing precedent
- It uses the hook system defined in `pkg/plugins`

I believe we chatted about this a long time ago. In my mind, the main way in which this differs from downloaders and other plugins is that essentially what this PR is trying to do is emulate something like `helm-template | $RENDER | helm install` (with where install takes the output of the plugin and directly installs it). `$RENDER`, here, can be any command, and is passed in on the CLI as a flag.

My understanding is that the purpose of this design is to make it super easy for an operator to do one-off shell commands that pipe data through some other existing tool _ad hoc_, not every single time. (Downloaders, in contrast, are automatically loaded and executed whenever necessary -- and the user can be blissfully unaware that this is even happening)

Because I think that the explicit execution of a particular program is the desired "best case", I think the PR is good as it stands. It might be worth considering integrating this into the plugin system in the future, though.

2020-02-03 12:05 UTC, hickeyma approved these changes
LGTM, thanks @thomastaylor312. I think this will be valuable capability for infra folks.

2020-02-04 16:22 UTC, mattfarina commented
@technosophos um...

> My understanding is that the purpose of this design is to make it super easy for an operator to do one-off shell commands that pipe data through some other existing tool ad hoc, not every single time.

So, if two people go to upgrade the same application one does it with the script and the other doesn't you can end up with differences.

If the one off case is the expectation than we shouldn't link it into the plugin system at all. If the plugin system is used it should be intentional. If the use case is one-off shall command not regularly used than there is no need for plugins.

I expect this to be abused.

2020-02-04 18:22 UTC, technosophos commented
@mattfarina yeah, essentially that is what we are enabling: An opportunity for a chart user to take the output of Helm, pipe it through something like Kustomize, and then install it with Helm. And we do think we want that to be the decision of the individual operator.

I imagine that it could be abused by people doing things like embedding other template languages in their charts. But (a) that can be done today, and (b) I don't think we're in the business of preventing people from making poor life choices.

My argument for including this feature is that it gives a happy path to people who want to use external patch managers like Kustomize. They can still take advantage of the rest of Helm's tooling instead of having to choose whether they want to patch their YAML or whether they want Helm-based installation management.

2020-02-07 17:34 UTC, bacongobbler approved these changes
LGTM! Nicely written, and thank you for the tests.

2020-02-07 17:35 UTC, mattfarina approved these changes
lgtm. I look forward to iterations on this to continue to make this more useful.

2020-02-07 17:55 UTC, merged