Fix a bug in Delete() in storage/driver/cfgmaps.go
helm/helm pull request #7367
Opened 2020-01-09 10:23 UTC by tiendc

Signed-off-by: Dao Cong Tien <tiendc@vn.fujitsu.com>

2020-01-21 19:48 UTC, adamreese requested changes
See comments in #7348

2020-01-30 17:06 UTC, bacongobbler commented
ping

2020-01-31 08:10 UTC, tiendc commented
> ping
Please see my comment in #7348

2020-03-13 18:35 UTC, adamreese approved these changes

2020-03-13 18:36 UTC, merged