fix(sympath): remove log statement
helm/helm pull request #7523
Opened 2020-02-04 21:23 UTC by griffin

This log line is printed if you have a system link in your chart dir. We have some tooling that sandboxs chart packaging with symlinks, leading to this being printed frequently on engineer's machines. The message isn't clear and is confusing if it is an error or not. Symlinks seem to be supported in helm, so there is no reason to print this debugging message.

Signed-off-by: Griffin Dunn <griffin.dunn@datadoghq.com>

2020-02-04 21:34 UTC, bacongobbler commented
Hi @griffin. To give some background context on this change, it was introduced as part of a CVE during the Helm security audit. More information can be found here: https://helm.sh/blog/2019-10-30-helm-symlink-security-notice/

Based on the feedback provided to us by the security team, this warning message should not be removed. Perhaps a better resolution to this may be to work on https://github.com/helm/helm/issues/6844, which then users could strip this log line by using `helm package --log-level error`.

What do you think?

2020-03-06 13:16 UTC, griffin commented
@bacongobbler Updated the description, I think this is a solid middleground.

2020-03-10 15:39 UTC, mattfarina requested changes
Reporting on symlinks is for security. The alternative is that everyone needs to opt-in to the use of symlinks when present. That would mean detecting symlinks and then performing user interaction or a flag at runtime.

Someone could use a symlink for nefarious purposes while could end up being a vulnerability.

We can't hide the current symlink messages behind debug messages because security.

2020-05-02 19:12 UTC, closed without merging

2022-06-10 13:44 UTC, rubensayshi commented
@bacongobbler @mattfarina 

how about some way to set a whitelist of paths that are accepted to be a symlink within the chart?

it will require adding that to the chart config file and then passing it down into the `Walk`.  
do you think that's too much to deal with this for the few people (like me and @griffin) who are making use of symlinks in their charts?

I'd be willing to put in the work if you at least think that such a change would have chance of being accepted.