fixed missing bullet
helm/helm pull request #7554
Opened 2020-02-07 18:54 UTC by technosophos

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

2020-02-07 18:55 UTC, bacongobbler approved these changes

2020-02-07 19:13 UTC, marckhouzam commented
LGTM.  Thanks for fixing my mistake.

2020-02-09 15:10 UTC, hickeyma requested changes

2020-02-09 15:10 UTC, hickeyma commented on ADOPTERS.md
>  # Organizations Using Helm
@technosophos Can the list be sorted in alphabetical order as mentioned in the doc?

2020-02-20 18:34 UTC, bacongobbler approved these changes
let's merge as-is for now as it addresses the immediate issue. I will follow up and address @hickeyma's comment in a follow-up.

2020-02-20 18:35 UTC, merged