fix: add new static linter and fix issues it found
helm/helm pull request #7655
Opened 2020-02-21 21:01 UTC by technosophos

This PR adds a new static analyzer to the testing target.

In the course of adding, the analyzer found two cases where code was incorrect. While neither case imposes any risk, I have fixed them both.

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

2020-02-28 20:39 UTC, jdolitsky requested changes
@technosophos looks like things are failing in circle - maybe related to the version of linter or versions being used?

2020-03-02 22:49 UTC, technosophos commented
Okay, updated for the new checks done by the new static analyzer. Weeee!

2020-03-03 23:32 UTC, jdolitsky approved these changes

2020-03-04 00:25 UTC, adamreese approved these changes

2020-03-04 00:28 UTC, merged