Add unit test for pkg/chart/chart.go
helm/helm pull request #7814
Opened 2020-03-25 14:01 UTC by hs0210

Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

2020-03-26 03:13 UTC, jdolitsky approved these changes

2020-03-26 11:05 UTC, hickeyma requested changes
Thanks for push the test @hs0210. Got some suggestions on improving the test to include other properties of the metadata.

2020-03-26 11:05 UTC, hickeyma commented on pkg/chart/chart_test.go
> +func TestName(t *testing.T) {
Should this be renamed TestMetadata? Then the test would check the rest of the properties of metadata.
I am not sure of the value of just checking the name only.

2020-03-26 12:41 UTC, hs0210 commented
PTAL

2020-03-31 15:08 UTC, hickeyma requested changes
Thanks for update @hs0210. Small nit to fix.

2020-03-31 15:08 UTC, hickeyma commented on pkg/chart/chart_test.go
> +			APIVersion: "1.0.0",
Can you set the `APIVersion` to v2?

2020-04-01 01:31 UTC, hs0210 commented
PTAL

2020-04-01 07:17 UTC, hickeyma requested changes
Small nit still on the `APIVersion`.

2020-04-01 07:17 UTC, hickeyma commented on pkg/chart/chart_test.go
> +			APIVersion: "2.0.0",
Do you mind setting it as follows: `APIVersion: "v2"`? It is to signify the chart v2 format

2020-04-01 08:14 UTC, hs0210 commented
I've changed it. PTAL, Thanks.

2020-04-01 08:26 UTC, hickeyma approved these changes
LGTM, thanks @hs0210

2020-04-01 08:26 UTC, merged