WIP: Post Render args example
helm/helm pull request #7850
Opened 2020-04-01 07:15 UTC by acaire

Proof of concept to fix #7849

2020-05-21 18:18 UTC, technosophos commented
What is the status of this? It has been marked WIP for almost two months with no activity. Is the intention to carry this on to completion?

2020-05-21 18:50 UTC, acaire commented
It was as complete as it needed to be when submitted for the related issue which I waited almost two months for an answer on, so yes the intention is to complete it

2020-05-21 19:06 UTC, technosophos commented
When it is marked WIP (Work In Progress), we do not put it in the review queue. I will remove the label and modify the title.

Please respect the fact that there are few of us and many, many issues/PRs. We work as fast as we can, but it is quite simply more work than we can handle.

2020-05-21 20:24 UTC, acaire commented
I only got a response 7 days ago, and I haven’t had a chance to implement what has been requested, so for all intents and purposes this PR is still WIP.  I have no qualms about the timeliness of this process, but I’d appreciate if you were less curt.

2020-05-21 20:34 UTC, technosophos requested changes
The `,` character is a legal character in paths. So, for example, I can have an executable named `foo,bar.sh`. The current PR breaks with names like this:

```
$ helm install --dry-run redis stable/redis --post-renderer ./foo,bar.sh,prod,redis 
Error: invalid argument "./foo,bar.sh,prod,redis" for "--post-renderer" flag: unable to find binary at ./foo: exec: "./foo": stat ./foo: no such file or directory
```

Also, unit tests will be required for final acceptance.

2020-05-21 20:41 UTC, acaire commented
A different implementation was requested as visible in the linked issue, so comma splitting won’t be necessary. Thanks for the review, I’ll let you know when it’s ready to review.

2020-06-29 09:04 UTC, acaire commented
Unfortunately I no longer have the requirement or bandwidth to implement this, closing in favour of [improved helmfile support](https://github.com/roboll/helmfile/pull/1172)

2020-06-29 09:04 UTC, closed without merging