Fix read file for 'helm lint -f some-file'
helm/helm pull request #7995
Opened 2020-04-25 07:12 UTC by lou-lan

See #7985, the description for 'helm lint -f some-file'  seems wrong, and this PR is going to fix this.

2020-04-27 20:50 UTC, technosophos approved these changes
I do not believe it is correct behavior to trap a parse error and then attempt to open the result as a file handle. Please explain why proper behavior would be to try to open the file when the file name was unparsable.

Also, there is no test.

2020-04-27 20:50 UTC, technosophos requested changes
Meant to click "request changes"

2020-04-28 15:36 UTC, lou-lan commented
> I do not believe it is correct behavior to trap a parse error and then attempt to open the result as a file handle. Please explain why proper behavior would be to try to open the file when the file name was unparsable.
> 
> Also, there is no test.


If `helm lint -f` specifies a local file, such as `values.yaml`, calling `url.Parse` parsing will get an error, `u` is a nil pointer. calling `p.ByScheme(u.Scheme)` will panic.
https://github.com/helm/helm/blob/2139e82c68e160a713cf19eb3ac55e91aef21cde/pkg/cli/values/options.go#L107-L121

2020-04-28 16:19 UTC, lou-lan commented
First, check whether `filePath` equals `-`, then check if it's a network file, in other cases, we should regard it as a local path.

2020-04-28 16:24 UTC, bacongobbler commented
Can you provide a test case? Perhaps that would better explain the justification for this change. I'm still not understanding why a URL parse error should result in an attempt to open the file.

2020-04-28 18:00 UTC, lou-lan commented
I added the test case, and I'm not sure if that solves it better, or want a better way to get schmea.

2020-05-01 21:46 UTC, technosophos commented
I am not suggesting that the error should panic. I am suggesting that on error, you should not just blindly ignore the error and attempt to read the file. That is a dangerous behavior. The best behavior is probably to just return the error. A second object would be to Stat the file and see if it exists, and then create an appropriate URL object.

Consider this code:

```
package main

import (
	"fmt"
	"net/url"
)

func main() {

	urls := []string{
		"/var/run/foo",
		"file:///var/run",
		"http://example.com/foo/bar",
	
	}
	for _, u := range urls {
		p, err := url.Parse(u)
		if err != nil {
			fmt.Printf("failed parse: %s\n", err)
		} else {
			fmt.Printf("Scheme of %q is %s\n", u, p.Scheme)
		}
	}
}
```

Note that even the regular file path correctly parses.

We use the URL parser for two things:

1. To sanity check the data that is passed in
2. To allow plugins to override protocol handlers

Your patch circumvents the regular scheme handling code, attempting a raw read on the file system after the URL parser has indicated that there was an error parsing the path. That's not what we intended to do.

Returning an error is fine here. Perhaps, though, there are cases where a character is illegal in a URL, but legal on the local filesystem. If you really want to run a secondary validation, you can os.Stat instead of reading... but please don't just do a raw file read and return. That's not how the code is supposed to work.

The test looks fine, but note that it passes even without your patch. What is the case that you believe your patch is fixing?

2020-05-03 18:03 UTC, lou-lan commented
> I am not suggesting that the error should panic. I am suggesting that on error, you should not just blindly ignore the error and attempt to read the file. That is a dangerous behavior. The best behavior is probably to just return the error. A second object would be to Stat the file and see if it exists, and then create an appropriate URL object.
> 
> Consider this code:
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"net/url"
> )
> 
> func main() {
> 
> 	urls := []string{
> 		"/var/run/foo",
> 		"file:///var/run",
> 		"http://example.com/foo/bar",
> 	
> 	}
> 	for _, u := range urls {
> 		p, err := url.Parse(u)
> 		if err != nil {
> 			fmt.Printf("failed parse: %s\n", err)
> 		} else {
> 			fmt.Printf("Scheme of %q is %s\n", u, p.Scheme)
> 		}
> 	}
> }
> ```
> 
> Note that even the regular file path correctly parses.
> 
> We use the URL parser for two things:
> 
> 1. To sanity check the data that is passed in
> 2. To allow plugins to override protocol handlers
> 
> Your patch circumvents the regular scheme handling code, attempting a raw read on the file system after the URL parser has indicated that there was an error parsing the path. That's not what we intended to do.
> 
> Returning an error is fine here. Perhaps, though, there are cases where a character is illegal in a URL, but legal on the local filesystem. If you really want to run a secondary validation, you can os.Stat instead of reading... but please don't just do a raw file read and return. That's not how the code is supposed to work.
> 
> The test looks fine, but note that it passes even without your patch. What is the case that you believe your patch is fixing?

Thank you for your patience in viewing the code, it was my carelessness. I have updated the code, please check again.

2020-05-13 21:53 UTC, jdolitsky requested changes

2020-05-13 21:53 UTC, jdolitsky commented on cmd/demo/main.go
> +package demo
Can we delete this file?

2020-05-14 02:28 UTC, lou-lan commented on cmd/demo/main.go
> +package demo
Thanks, I deleted it.

2025-09-28 00:25 UTC, closed without merging