Remove hasAllRepos function
helm/helm pull request #8028
Opened 2020-04-29 11:06 UTC by kristinnardal2

refs #7710 

**What this PR does / why we need it**:

Helm doesn't download from local cache so it's redundant to check
whether they exist in local cache before downloading. This leads to bugs
where `helm dep build` doesn't work when it should.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

Signed-off-by: Kristinn Björgvin Árdal <kristinnardalsecondary@gmail.com>

2020-05-04 20:29 UTC, technosophos commented
At one point, it was required that all repositories had to be locally pulled before a dependency could be correctly managed. I think this removes one area where that behavior was enforced. I need to take a closer look at the code to see if it is indeed globally optional now (in which case we can merge this PR as-is), or whether there is still a case where this is required.

I suspect that when we added the OCI registry support, we removed the last of the hard dependencies on a local cached copy. But again -- I will verify. It just may take me a while.

2020-05-13 23:12 UTC, technosophos commented
So far, this issue has helped us turn up a longstanding bug in `helm dep update`. It may be the case that `helm dep update` should require a valid local repo just like `helm dep build` does. Ironically, `helm dep build` may not need the local repo if the lock file is present.

2020-05-13 23:31 UTC, technosophos requested changes
Marking this as blocked until #8118 is resolved. Currently, there are no changes necessary to this PR, but if it is merged, it will make #8118 worse by introducing the same problem in `helm dep build` when a lockfile is present.

2020-05-14 08:40 UTC, hickeyma commented
@technosophos FYI Issue #8036 . It is relevant to the investigations that you are doing.

2025-09-28 00:25 UTC, closed without merging