[WIP] Configuration settings
helm/helm pull request #8032
Opened 2020-04-30 01:26 UTC by lucperkins

Fixes #8030

2020-04-30 17:22 UTC, bacongobbler requested changes
added two comments with regards to Helm's commitment to backwards compatibility. Would you mind addressing those comments as well as anywhere else you might see an issue?

2020-04-30 17:22 UTC, bacongobbler commented on pkg/cli/settings.go
> -type EnvSettings struct {
by changing the name, we are breaking backwards compatibility. To ensure other programs do not fail to compile after upgrading helm, Go has a feature called [type aliasing](https://golang.org/doc/go1.9#language).

```
type EnvSettings = Settings
```

This allows users to use either type, and it allows us to maintain backwards compatibility.

2020-04-30 21:58 UTC, mattfarina requested changes
The biggest issue with this change is that it breaks the public Go API for those who consume Helm. That means we'd need to increment to Helm v4 to release a change like this.

Can we do something in an additive manner instead?

2020-04-30 21:58 UTC, mattfarina commented on pkg/cli/settings.go
> +func (s *Settings) GetNamespace() string {
In Go it's considered bad form to use `GetNamespace` as a function name. Instead, it should be `Namespace`. This comes from https://golang.org/doc/effective_go.html#Getters (in the Go documentation) and there are linting tools that remind us not to name things that way.

This is a Go convention that's a little different from other languages.

2020-05-19 20:54 UTC, lucperkins commented
So, I think in general I'm going to give this some more thought. I do think that the Go client could use some revamping, but I absolutely do not want to break any API contracts. I'm gonna close this for now and re-open when I have something more substantial and target it for v4.

2020-05-19 20:54 UTC, closed without merging