feat: lint info on template spacing failure
helm/helm pull request #8043
Opened 2020-05-02 00:21 UTC by technosophos

**What this PR does / why we need it**:

This adds a feature (per #5763) to emit an info message when a template does not follow the recommended guidelines for whitespace in chart directives.

IMPORTANT: This will emit INFO messages where previously no INFO messages were displayed. I _think_ that we should emit warnings, but I am not sure if adding a new WARN level linter is a breaking change.

**Special notes for your reviewer**:

I'm not great at regular expressions. The best I could do here is create two regexps, where one checks the opening sequence and another checks the closing sequence. (Remember, templates can span multiple lines, AND multiple templates can appear on the same line.) If anyone wants to take a shot at better regular expressions, that would be cool.

The ones here should never give a false positive, but there may be possible cases where a formatting error could slide by. (The only example I can think of is `{{ foo -  }}`, but I don't think that is actually the same as `{{ foo -}}`)

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

Closes #5763

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

2020-05-02 00:21 UTC, technosophos commented
Example output:

```
==> Linting issue5763
[INFO] Chart.yaml: icon is recommended
[INFO] templates/configmap.yaml: whitespace required between template markers and body:
bad start: {{.Values.world}}
	{{.Values.world

bad end: {{.Values.world}}

1 chart(s) linted, 0 chart(s) failed
```

2020-05-07 15:45 UTC, mattfarina commented
This is interesting because it's a style Helm is imposing that is not required as part of the underlying engine provide by Go's test/template package. In fact, the Go documentation has cases with the missing spaces.

@technosophos What is the reason we have docs saying to have the added space? I think I'm missing the history on this.

2020-05-12 20:31 UTC, technosophos commented
@mattfarina This is the reference: https://helm.sh/docs/chart_best_practices/templates/

The recommendation originally came from the Go post when they added `{{-`, though the main champions of this have been the chart maintainers, not us.

For my part, I don't particularly care. I'm not really one of the best practices maintainers. If you would like to push for a change there, that's fine. But it does seem sensible that the best practices be recommended by the linter. Thus the request for this change.

Anymore, I'm not really sure what the point of the linter is. Is it to recommend best practices or try to catch errors? Because most of the lints are not errors _per se_, but just stylistic things. However, the chart repo tools have a lot more lints that aren't present here. After working on lints for a month, and having people complain about just about everything, I am not all that convinced that the linter adds much true value if people are just gonna argue to death that "the linter is too chatty" "I don't want the linter to warn me about X" "this should be an error, not a warning, because I don't like it" etc.

The original point of the linter was to enforce best practices in charts. Do we care about that or not? Because it feels an awful lot like what people want the linter to do is tell them their chart is fine according to their own personal standards for what they want to be fine.

2020-05-13 22:00 UTC, jdolitsky requested changes

2020-05-13 22:00 UTC, jdolitsky commented on pkg/lint/rules/template.go
> +	if matches := badTplStart.FindAllString(template, 10); matches != nil {
should this be -1 vs. 10?

2020-05-23 12:57 UTC, asears commented
@technosophos I really appreciate you working on linting for Helm over last few months.  Linting code helps myself and members of our team understand what the guidance for "good practices" are, or at least standard practices.  I question some of these "best" practices, but people with much more Go, Sprig, moustache, and handlebars templating experience have paved the dirt path for me which I should probably follow?

The linter should catch some errors locally, before they are checked into source control.  This should be in a code editor tool such as VSCode as squiggly underlines and warnings with numeric identifiers.  The linter should be protecting branches from any errors during PRs.  

The linter should show guidance on why the error or warning was raised, provide links for additional resources, and allow for ignoring the check and moving on.   It's great if the linter does some of the work of --dry-run, catching issues before things are run.  It should allow us to "break the build" when we need to.  Hopefully it promotes quality through the templates, though it isn't a substitute for tests.

For code and templating tools that don't have compile-time checks, I think it's invaluable to have a good linting tool to shave the fluff out, get rid of the dirt & most common syntax and "compile-time check" errors.  

I think other tools or extensions of the linter should auto-prettify the code for you, because in the end I don't care about whitespace and neither does compiled code.  Maybe there's a base set of linting rules, and the linter allows for extensions to run afterwards with the chart community's rules?  Maybe something scans the stable and incubating repos for patterns and best practices?  

What happens when the linter is run on stable and incubating charts?  Is there a report we could look at for this?  Should the charts be rated based on quality of the lint results?

The linter should let me filter out spurious or most common warnings, because if they're the most common then perhaps they're not important at all?  If there's pedantic discussions around what's an error and what's a warning, let the implementing team or community figure that out as part of the lint configuration?  Linter shouldn't care and rules evolve.

A valuable component of a linter or its associated helper workflows are that they can auto-fix and refactor some of these most common problems for us, for things like above whitespace issue and other trivial issues.  Otherwise you end up "yak shaving" all day...

Another valuable part of a linter is the ability to provide the breadcrumbs to "yak shave" to your hearts content, and have meaningful discussions with the community to better understand the tool.  I like the approach pylint team does with this.  They don't know why some arcane warning came up.  They look for explanations from the community.

http://pylint-messages.wikidot.com/explanation-needed

I spent a bit of time with two of the warnings below.  Chart name changed.

I ran this:

```dos
helm lint mychart --strict --debug --set fullnameOverride=strict,nameOverride=strict
```

I get this.

```shell
[INFO] Chart.yaml: icon is recommended
```

I have a private helm chart and don't want to call a public URL for the chart icon.  I need a code and lint ignore file which can ignore this for me, or add the code to the ignore file for me.  

1. What # is this info recommendation or reference breadcrumb?  
1. How do I ignore this info warning?

The error is a little better than nil warning but I still need to dig.

```shell
[ERROR] templates/: template: mychart/templates/service.yaml:8:18: executing "mychart /templates/service.yaml" at <.Values.service.type>: map has no entry for key "service"
```

I'm just picking up on the templating language and need to trace where this is missing.  My chart still works fine even with this error, so why is it an error.  

1. What # is this error or reference breadcrumb?
2. What are common fixes for this error?
3. Where do I put this entry?  In service.yaml?  In the tpl file? The deployment.yaml? values? Where was it expecting the value? 

Spent some time yesterday trying to understand why a Helm chart release wasn't recreating the pod for me, until I read that we either have to hack in some random number to change the definition, or figure out the strategy for pod replacement and identify where to place this in the definition.  By this time it is much too late, my Helm chart deployed without errors or warnings in the build and release pipelines and the code is already in an environment with a stale pod.  

I went through Github issues and StackOverflow to try and figure this recreation pod issue out. Tried to --force Helm to do what it wasn't intended to do.  Talked with a colleague who had same issue, and lets the KEDA autoscaler deal with it.  I don't think this should be the way of the Helm chart developer.

Could a linter warning about this issue have helped?  Maybe I'm missing a strategy?  Or perhaps further guidance that Helm doesn't manage pods, Kubernetes does?

I linted this issue post and got these warnings.  Are we really using 80-column terminal windows still?  This Git issues window is much smaller, is this rule still valid?

```markdownlintinginagitissuesucks
8043.md:1:81 MD013/line-length Line length [Expected: 80; Actual: 418]
8043.md:1 MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "@technosophos I really appreci..."]
8043.md:3:81 MD013/line-length Line length [Expected: 80; Actual: 275]
8043.md:5:81 MD013/line-length Line length [Expected: 80; Actual: 413]
8043.md:7:81 MD013/line-length Line length [Expected: 80; Actual: 218]
8043.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 390]
8043.md:11:81 MD013/line-length Line length [Expected: 80; Actual: 180]
8043.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 147]
8043.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 262]
8043.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 343]
8043.md:19:1 MD034/no-bare-urls Bare URL used [Context: "http://pylint-messages.wikidot..."]
8043.md:35:81 MD013/line-length Line length [Expected: 80; Actual: 194]
8043.md:43:81 MD013/line-length Line length [Expected: 80; Actual: 172]
8043.md:46:81 MD013/line-length Line length [Expected: 80; Actual: 161]
8043.md:50:119 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
8043.md:50:81 MD013/line-length Line length [Expected: 80; Actual: 119]
8043.md:52:81 MD013/line-length Line length [Expected: 80; Actual: 475]
8043.md:54:81 MD013/line-length Line length [Expected: 80; Actual: 309]
8043.md:56:81 MD013/line-length Line length [Expected: 80; Actual: 160]
8043.md:58:81 MD013/line-length Line length [Expected: 80; Actual: 170]
8043.md:58:170 MD047/single-trailing-newline Files should end with a single newline character
``` 

Anyway, just wanted to say that what you are doing @technosophos and team is important and please continue to sweat the small stuff in the linter and improve on Helm workflow.

2025-04-18 19:48 UTC, closed without merging