ref(cmd): prevent klogs flags from polluting the help text
helm/helm pull request #8067
Opened 2020-05-06 20:47 UTC by adamreese

Remove klog flags from help text.  No change to behavior.

```
...
Flags:
      --debug                      enable verbose output
  -h, --help                       help for helm
      --kube-apiserver string      the address and the port for the Kubernetes API server
      --kube-context string        name of the kubeconfig context to use
      --kube-token string          bearer token used for authentication
      --kubeconfig string          path to the kubeconfig file
  -n, --namespace string           namespace scope for this request
      --registry-config string     path to the registry config file (default "/Users/areese/.config/helm/registry.json")
      --repository-cache string    path to the file containing cached repository indexes (default "/Users/areese/.cache/helm/repository")
      --repository-config string   path to the file containing repository names and URLs (default "/Users/areese/.config/helm/repositories.yaml")
```

2020-05-06 20:48 UTC, adamreese commented
Flags before change...

```
Flags:
      --add-dir-header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --debug                            enable verbose output
  -h, --help                             help for helm
      --kube-apiserver string            the address and the port for the Kubernetes API server
      --kube-context string              name of the kubeconfig context to use
      --kube-token string                bearer token used for authentication
      --kubeconfig string                path to the kubeconfig file
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
  -n, --namespace string                 namespace scope for this request
      --registry-config string           path to the registry config file (default "/Users/areese/.config/helm/registry.json")
      --repository-cache string          path to the file containing cached repository indexes (default "/Users/areese/.cache/helm/repository")
      --repository-config string         path to the file containing repository names and URLs (default "/Users/areese/.config/helm/repositories.yaml")
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

2020-05-06 20:49 UTC, adamreese commented
I am not sure where these flags should be documented.  They are only used for deeeeep debugging of interactions with the kube apiserver.  I'm not sure if they are useful outside of Helm development.

2020-05-06 20:53 UTC, bacongobbler commented
I've been recommending `-v 10` when debugging connection timeouts to determine what requests are timing out, and where. Not sure about the rest though.

2020-05-06 20:58 UTC, adamreese commented
I think it's miss leading because it's not helm specific verbosity.  I could try to change the help text on `-v` to something kube specific.

2020-05-06 21:00 UTC, adamreese commented
@bacongobbler Also the flag still works, it is only omitted from `helm help`

2020-05-06 21:29 UTC, technosophos commented
Yeah, I sometimes see users misunderstanding the `-v` flag, assuming they are seeing Helm debug info when they are just seeing Klog info.

![klooooog](https://user-images.githubusercontent.com/89193/81230232-5583bd80-8fae-11ea-8a78-2a163a3f356a.jpg)

2020-05-06 21:32 UTC, technosophos commented
We could add a help message for `-v` if we really wanted to. I mean, adding just that one might make sense. Most of the flags are just useless for all but dev usage. And they clutter the help text with confusing out-of-context information (like `vmodule`, whose text makes no sense if you don't know klog).

2020-05-06 23:52 UTC, marckhouzam commented
Nice initiative! The extra flags are wildly annoying in the help text.

In fact, if they are not really meant to be used by helm users, what do you think if I try to remove them from the suggested shell auto-completions?

2020-05-07 15:39 UTC, mattfarina commented
I like the idea of removing them as long as they are documented somewhere. That way we can get to them when needed (like when debugging in dev). Is there a place we can document them at?

2020-05-12 23:01 UTC, technosophos approved these changes

2020-05-12 23:06 UTC, bacongobbler commented
> I like the idea of removing them as long as they are documented somewhere.

Would the documentation under the [troubleshooting section](https://helm.sh/docs/faq/#troubleshooting) suffice?

2020-05-13 22:02 UTC, jdolitsky approved these changes
lgtm, should merge once there are docs

2020-05-16 01:21 UTC, marckhouzam commented
The global flags have now been removed (mistakenly, I believe) by PR #7917.
There is #8095 to show them through the use of a new `helm options` command.

If we have the klogs flags, I like the idea of `helm options`, but if we hide the klogs flags, I'm leaning towards showing the global flags in the regular help.

We need to sort out what to do between these three PRs.

2020-07-07 15:52 UTC, bacongobbler commented
throwing this on 3.4.0 for further discussion.

2020-07-21 17:55 UTC, jdolitsky commented
Both the issues Mark mentioned are closed/merged. Where do we stand w this?

2020-07-28 18:48 UTC, paulczar commented
It would be nice to see this merged, the behavior of these flags is't clear from the help info, as it is by reading the help I would be left assuming that I should be seeing logs in stderr by default for any helm commands.

2020-07-29 07:22 UTC, hickeyma requested changes
@adamreese Thanks, this is a nice tidy up. Just 2 things to do:
- Rebase and resolve the conflict
- Open a doc PR to cover the hidden args in troubleshoot section

Then it should be good to go.

2020-09-28 08:57 UTC, hickeyma approved these changes
LGTM, thanks @adamreese

2020-09-28 17:35 UTC, merged

2021-01-11 21:09 UTC, sraillard commented
I clearly disagree with removing the document from the command line help.
Good luck to find it in the troubleshooting section of the website... I didn't...
It would be better to provide an "advanced help" flag to display all these debug flags.