Add unit test for pkg/lint/rules/deprecations.go
helm/helm pull request #8096
Opened 2020-05-12 03:02 UTC by hs0210

Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-05-12 09:24 UTC, hickeyma requested changes
Thanks for pushing the PR @hs0210. I am all for tests but I am unsure what this test adds. Can you explain what this test provides that is not covered by `TestValidateNoDeprecations`?

2020-05-12 09:59 UTC, hs0210 commented
Thanks for your review @hickeyma . Though the fmt.Sprintf() has been tested, the whole logic is worth a test. And the coverage is improved.

2020-05-13 22:15 UTC, jdolitsky approved these changes

2020-05-21 20:45 UTC, technosophos requested changes

2020-05-21 20:45 UTC, technosophos commented on pkg/lint/rules/deprecations_test.go
> +func TestError(t *testing.T) {
This name is ambiguous and should be replaced by something like `TestDeprecatedAPIError`

2020-05-22 04:14 UTC, hs0210 commented
@technosophos PTAL.

2020-06-24 06:41 UTC, closed without merging