fix(repo): Repo cache setting not recognized
helm/helm pull request #8158
Opened 2020-05-18 18:21 UTC by hickeyma

Fix `repo add` and `repo update` to use the repository cache set with the `--repository-cache` flag

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
Signed-off-by: Trond Hindenes <trond@hindenes.com>

Supersedes #7166 

Fixes #7141

**What this PR does / why we need it**:
`--repository-cache` flag not current being recognized with commands:
- `helm repo add`
- `helm repo update`

**Special notes for your reviewer**:

Test before the change and it should add nothing to the new cache directory ` /tmp/cache`. Test with PR and it should work as follows:

```
$ ls -lrt /tmp/cache
total 0

$ helm repo add astronomer http://helm.astronomer.io --repository-cache /tmp/cache
"astronomer" has been added to your repositories

$ ls -lrt /tmp/cache
total 712
-rw-r--r-- 1 root root 721299 May 18 18:16 astronomer-index.yaml
-rw-r--r-- 1 root root     97 May 18 18:16 astronomer-charts.txt

$ helm repo update --repository-cache /tmp/cache
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "astronomer" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

$ ls -lrt /tmp/cache
total 8936
-rw-r--r-- 1 root root  721299 May 18 18:17 astronomer-index.yaml
-rw-r--r-- 1 root root      97 May 18 18:17 astronomer-charts.txt
-rw-r--r-- 1 root root 8415351 May 18 18:17 stable-index.yaml
-rw-r--r-- 1 root root    3370 May 18 18:17 stable-charts.txt
```

**If applicable**:
- [x] this PR contains unit tests

2020-05-18 18:28 UTC, hickeyma commented
@trondhindenes Can you take a look and see if it fixes your issue?

2020-05-18 21:09 UTC, adamreese requested changes
Your unit tests pass without the change.  I'm not sure it's testing what you want

2020-05-18 23:58 UTC, marckhouzam commented
> Your unit tests pass without the change. I'm not sure it's testing what you want

@hickeyma be aware that the original test of the superceded PR was also passing without the change. In case you copied it verbatim.

2020-05-19 15:49 UTC, hickeyma commented
@adamreese Thanks for noticing the unit test issue.

@marckhouzam You are right about copying it. I then meant to update it as you had noticed the issue previously in #7166 but unfortunately pushed before finishing it off.

I have updated the unit test now and it fails without the change from the PR.

2020-05-19 22:25 UTC, adamreese approved these changes

2020-05-19 23:58 UTC, marckhouzam approved these changes

2020-05-20 09:14 UTC, hickeyma commented
Thanks for the reviews @adamreese @marckhouzam

2020-05-20 09:15 UTC, merged