Fix crashing `helm chart list` with large list
helm/helm pull request #8220
Opened 2020-05-28 18:55 UTC by pmengelbert

**What this PR does / why we need it**:
With a large list of charts, `helm chart list` will crash with the
following message:

```
$ helm chart list --debug
Error: open
/home/me/.cache/helm/registry/cache/blobs/sha256/109971e44d63f7fd11fff60d19db41c2429a136943be2e3f8fd3e4c165156536:
too many open files
helm.go:75: [debug] open
/home/me/.cache/helm/registry/cache/blobs/sha256/109971e44d63f7fd11fff60d19db41c2429a136943be2e3f8fd3e4c165156536:
too many open files
```

Closes #8219

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-05-28 19:00 UTC, bacongobbler requested changes
Can you please write a unit test to confirm this fixes the original issue? Thanks.

2020-05-29 15:13 UTC, pmengelbert commented
@bacongobbler I spent some time writing a unit test to prove this out, but could not get around the fact that writing the number of charts needed to crash upon `helm chart list` took about a half-hour. A tar.gz of the cache is 112MiB, so between checking in a large tarball and a very long-running unit test, neither seems particularly responsible.

To help reproduce the issue, I hosted the tarball of the registry cache that causes me problems. Try the following:
```
curl -O https://engelbucket.s3.us-east-2.amazonaws.com/too-many-charts.tar.gz
tar zxvf too-many-charts.tar.gz -C "${HOME}/.cache/helm/registry"
helm chart list
```

While I agree it's important to prove out that a fix resolves an issue, it's also true that we should be closing open files whenever we are done with them, so I see no harm in including this PR in a future release.

2020-06-19 13:59 UTC, mattfarina commented
@pmengelbert have you considered programmatically creating the test charts instead of checking them in?

@bacongobbler Do you have any other ideas on fixing this that will work in our CI? This obvious small change should go in either way, IMHO.

2020-06-23 14:53 UTC, pmengelbert commented
@bacongobbler  @mattfarina Unfortunately, programmatically created the test charts took about 30 minutes, which is definitely overkill for a unit test. Agree that it's pretty obvious for inclusion

2020-06-23 15:05 UTC, bacongobbler approved these changes
let's just get this in. Thanks.

2020-06-23 15:05 UTC, merged