Add Warning when installing or upgrading a deprecated chart
helm/helm pull request #8262
Opened 2020-06-07 00:35 UTC by stantonxu

**What this PR does / why we need it**:
Close #3724 

Add warning when installing or upgrading a deprecated chart, for release-2.16

**Special notes for your reviewer**:

Signed-off-by: Stanton Xu <xjiefeng@gmail.com>

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-06-08 05:53 UTC, hickeyma requested changes
@stantonxu Do you mind adding a unit test for install and upgrade?

2020-06-08 06:01 UTC, stantonxu commented
@hickeyma , could you please share some instructions about how to add a unit test for install and upgrade?

2020-06-08 06:08 UTC, hickeyma commented
@stantonxu have a look at test added to #6889 and tests in upgrade for pattern to add it there.

2020-06-08 06:19 UTC, stantonxu commented
@hickeyma Thanks. Will look into it soon.

2020-06-09 10:00 UTC, FabianKramm commented
just a quick note: this will destroy the output of helm install / upgrade if the flag `--output` is specified

2020-06-09 11:12 UTC, liuming-dev commented
> @hickeyma @stantonxu just a quick note: this will destroy the output of helm install / upgrade if the flag `--output json/yaml` is specified (same problem as well for v3)

The output will be as the following，and I do not think this will be a problem.

```
$ helm install helm-chart helm-chart-sample --debug -o json|jq
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /Users/apple/.kube/helm-chart-sample

client.go:108: [debug] creating 1 resource(s)
{
  "name": "helm-chart",
  "info": {
    "first_deployed": "2020-06-09T19:05:02.240651+08:00",
    "last_deployed": "2020-06-09T19:05:02.240651+08:00",
    "deleted": "",
    "description": "Install complete",
    "status": "deployed"
  },
...
```

2020-06-09 13:51 UTC, bacongobbler requested changes

2020-06-09 13:51 UTC, bacongobbler commented on cmd/helm/upgrade.go
> +		fmt.Fprintln(os.Stdout, "WARNING: This chart is deprecated")
Same here on using stderr

2020-06-09 13:51 UTC, bacongobbler commented on cmd/helm/install.go
> +		fmt.Fprintln(os.Stdout, "WARNING: This chart is deprecated")
This should be on stderr, not stdout. That way the error message is not part of the output when it’s piped to another program.

2020-06-09 14:57 UTC, bacongobbler commented
@liuming-dev https://en.wikipedia.org/wiki/Standard_streams

2020-06-09 16:47 UTC, FabianKramm commented
@bacongobbler as commented in #8273, can we also add this to v3 that currently prints this warning on os.Stdout?

2020-06-09 17:56 UTC, bacongobbler commented
I just realized this is targeted against the `release-2.16` branch. Please re-target this PR against the `dev-v2` branch. Thanks.

2020-06-09 18:46 UTC, bacongobbler commented
https://github.com/helm/helm/pull/8277 fixes the regression for Helm 3.

2020-06-14 07:41 UTC, stantonxu commented
Created PR #8310, for targeting dev-v2. Closing this one.

2020-06-14 07:41 UTC, closed without merging