test: improve repo_update test fatal message
helm/helm pull request #8416
Opened 2020-07-08 11:09 UTC by lemonli

Signed-off-by: lemonli <liwenjun0323@gmail.com>

**What this PR does / why we need it**:
`TestUpdateCustomCacheCmd` in `cmd/helm/repo_update_test.go` download index file from `https://kubernetes-charts.storage.googleapis.com` to cache dir.
I got ```--- FAIL: TestUpdateCustomCacheCmd (76.01s)
repo_update_test.go:70: error finding created index file in custom cache: &os.PathError{Op:"stat", Path:"/var/folders/1m/pst1v4fd2t320wn5hx78vrdw6kv787/T/helm433448320/updcustomcache/charts-index.yaml", Err:0x2}`
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-07-08 11:15 UTC, lemonli commented
/assign hickeyma

2020-07-16 07:23 UTC, lemonli commented
thx, @hickeyma @mattfarina

2020-07-16 11:55 UTC, hickeyma reviewed
Thanks for pushing the PR @lemonli. I would have thought if there is an issue like resolving URL then it would have failed during the repo update command in https://github.com/helm/helm/blob/master/cmd/helm/repo_update_test.go#L66? I am therefore not sure that the output would be of use here.

2020-07-17 03:00 UTC, lemonli commented
> Thanks for pushing the PR @lemonli. I would have thought if there is an issue like resolving URL then it would have failed during the repo update command in https://github.com/helm/helm/blob/master/cmd/helm/repo_update_test.go#L66? I am therefore not sure that the output would be of use here.

It is not failed when call https://github.com/helm/helm/blob/master/cmd/helm/repo_update.go#L80 and then https://github.com/helm/helm/blob/master/cmd/helm/repo_update.go#L84 write error msg into `out io.Writer`

2020-07-17 08:32 UTC, hickeyma commented
@lemonli Sure, I realised that later but didn't get to respond.

I am unsure about adding it here as these are units tests and not sure of the overall value. Maybe other @helm/all-maintainers might have an opinion on this.

2020-09-10 14:49 UTC, jdolitsky approved these changes
I think that if this helps debug an issue, its no harm to merge since its just in unit tests

2020-09-23 15:57 UTC, bacongobbler requested changes
I don't think the output needs to be displayed to fix this issue. You need to adjust the format output so that the error message is displayed instead of its type. In other words, change `%#v` to `%v` and you should see the error message.

2020-09-24 06:54 UTC, lemonli commented
> I don't think the output needs to be displayed to fix this issue. You need to adjust the format output so that the error message is displayed instead of its type. In other words, change `%#v` to `%v` and you should see the error message. There's no need to display the command output.

https://github.com/helm/helm/blob/master/cmd/helm/repo_update.go#L93 write error msg into `out io.Writer`

The origin message is
`
--- FAIL: TestUpdateCustomCacheCmd (76.44s)
    repo_update_test.go:70: error finding created index file in custom cache: &os.PathError{Op:"stat", Path:"/var/folders/1m/pst1v4fd2t320wn5hx78vrdw6kv787/T/helm380963295/updcustomcache/charts-index.yaml", Err:0x2}
`

In my commit, it is
`
--- FAIL: TestUpdateCustomCacheCmd (76.44s)
    repo_update_test.go:70: error finding created index file in custom cache: &os.PathError{Op:"stat", Path:"/var/folders/1m/pst1v4fd2t320wn5hx78vrdw6kv787/T/helm380963295/updcustomcache/charts-index.yaml", Err:0x2}
        got: Hang tight while we grab the latest from your chart repositories...
        ...Unable to get an update from the "charts" chart repository (https://kubernetes-charts.storage.googleapis.com):
        	Get "https://kubernetes-charts.storage.googleapis.com/index.yaml": dial tcp 34.64.4.16:443: connect: operation timed out
        Update Complete. ⎈ Happy Helming!⎈
`

2020-10-21 15:34 UTC, bacongobbler commented
Closing as something we do not plan to merge. We only require the error message to debug the test failure; not the full CLI output.

As mentioned previously, changing `%#v` to `%v` in the formatter would display the error message. I will address this in another PR.

2020-10-21 15:34 UTC, closed without merging

2020-10-21 15:38 UTC, bacongobbler commented
opened #8929 to address this issue.