Added support to pass values to sub-charts via `map.yaml`
helm/helm pull request #8580
Opened 2020-08-11 07:13 UTC by jorgecarleitao

**What this PR does / why we need it**: See #8576 for the long explanation.

This PR allows developers to declare a `map.yaml` file on their chart, which can be used to map values in `values.yaml` to derived values that are used in templating, including sub-charts. This allows developers to write e.g.

```
apiVersion: v1
description: Chart with map and subcharts
name: chart-with-map
version: 0.0.1
dependencies:
  - name: backend
    version: 0.0.1
  - name: frontend
    version: 0.0.1
```

```
# values.yaml
domain: example.com
```

```
# map.yaml
backend:
  uri: {{ printf "https://api.%s" .Values.domain }}

frontend:
  uri: {{ printf "https://app.%s" .Values.domain }}

other_uri: {{ printf "https://blabla.%s" .Values.domain }}
```

thereby not having to expose `backend: uri`, `frontend: uri` in `values.yaml` (for the subchart), nor ask chart users to have to pass the same value in multiple keys for consistency (or use global names that lead to naming collisions).

I.e. it allows subcharts to be populated with derived (or `map`ed) values without exposing these values to `values.yaml` (the public interface of the chart).

This solves a long standing issue of being very painful to pass values to subcharts that derive values in `values.yaml` (more details in #8576).

**Special notes for your reviewer**: This PR is not complete yet: this is part of the proposal, and is intended to demonstrate how the proposal is implemented in practice. There are at least three issues to address, two documented as `# todo`, plus   associated documentation.

To run the example,

```
make build
./bin/helm install test --debug --dry-run cmd/helm/testdata/testcharts/chart-with-map/
```

which leads to the manifest

```
---
# Source: chart-with-map/charts/subchart/templates/test1.yaml
apiVersion: v1
kind: Pod
metadata:
    name: "aaa"
    labels:
        derived: aa-a
        default: aa
---
# Source: chart-with-map/templates/test1.yaml
apiVersion: v1
kind: Pod
metadata:
    name: "aaa"
    labels:
        derived: a-a
        public1: a
```

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2020-08-29 04:04 UTC, TBBle commented
As a note, by doing this work in `recAllTpls`, `import-values` won't be able to see the data from _map.yaml_ as `chartutil.ProcessDependencies` calls `processImportValues` much earlier in the flow.

2020-09-15 21:28 UTC, bacongobbler commented
Hi @jorgecarleitao. We're asking new proposals to first write up a Helm Improvement Proposal, also known as a HIP. This gives the maintainers an opportunity to consider the design of the proposal and iron out any design kinks before a reference implementation is provided. This saves both you and us time in the long run.

Please have a read through https://github.com/helm/community/blob/master/hips/hip-0001.md and let me know if you have any questions.

2020-09-15 21:28 UTC, bacongobbler requested changes
Hi @jorgecarleitao. We're asking new proposals to first write up a Helm Improvement Proposal, also known as a HIP. This gives the maintainers an opportunity to consider the design of the proposal and iron out any design kinks before a reference implementation is provided. This saves both you and us time in the long run.

Please have a read through https://github.com/helm/community/blob/master/hips/hip-0001.md and let me know if you have any questions.

2021-09-02 17:17 UTC, m-yosefpor commented
any progress on this?

2021-09-07 11:53 UTC, bacongobbler commented
No further progress has been made since chnages were requested 12 months ago. Closing as stale.

2021-09-07 11:53 UTC, closed without merging

2022-03-14 21:53 UTC, agates4 commented
@jorgecarleitao please don't give up. :)

2023-04-18 20:00 UTC, treksler commented
Expecting anyone who is capable and willing to write code (for free) to write an HIP document instead is nuts. Like 100% nuts. If you have a problem where people are writing code that seems like it is coming out of left field, then you have lost touch with your user base, not the other way around.