Wait: turn the debug logs into stdout print
helm/helm pull request #8582
Opened 2020-08-11 15:27 UTC by desaintmartin

**What this PR does / why we need it**:

if `--wait` flag for helm `install/upgrade` is specified, Helm will log to standard output (`stdout`) the wait informations.

Before: it was logged only with `--debug` flag to `stderr`.

Solve https://github.com/helm/helm/issues/7760

**Example output:**

using a sample `values.yaml` containing:
```yaml
persistence:
    enabled: false
replication:
    enabled: false
    slaveReplicas: 3
```

```bash
bin/helm upgrade --install test stable/postgresql --wait --values values.yaml
Release "test" does not exist. Installing it now.
WARNING: This chart is deprecated
beginning wait for 6 resources with timeout of 5m0s
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 1 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods have been scheduled
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
StatefulSet is not ready: default/test-postgresql-slave. 2 out of 3 expected pods are ready
NAME: test
LAST DEPLOYED: Tue Aug 11 17:21:25 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
[Here go the traditional postgresql deployment notes]
```

**Special notes for your reviewer**:

Note that this is a purely naive implementation to be used as a starting point, and I would be happy to change it in order to have a more unified way of logging (Since there are several ways of doing it in Helm: giving `out` as parameter and using `fmt.Fprintf`, using `fmt.Fprintf` with `os.Stdout`, using `log.Output`, ...) or at least that follows existing conventions. In fact, it would be nice to use `log` everywhere without short file name and make its format configurable.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-08-18 15:47 UTC, mattfarina commented
If someone has a complicated chart and uses the `--wait` flag this would add a lot to the output. Should the extra output be hidden behind a flag?

2020-08-18 15:53 UTC, desaintmartin commented
The log would not be that huge since helm only outputs "XX is not ready" for a single object a a time (i.e in the case it is waiting for 2 Statefulset, it will arbitrarily stick for one of the two until it is ready, and print status of the second only if it is not ready).

In the given example, see how it did NOT print about "default/test-postgresql" StatefulSet.

2020-09-15 21:25 UTC, bacongobbler requested changes

2020-09-15 21:25 UTC, bacongobbler commented on pkg/kube/wait.go
> +	fmt.Fprintf(os.Stdout, fmt.Sprintf("%s\n", format), v...)
informational messages should be displayed on `os.Stderr` so that it can be stripped from the output.

2020-09-25 22:03 UTC, adrienjt commented
Why stdout? stderr is the right stream. The issue that this PR is trying to solve (#7760) is that there's no feedback at all when `--wait` is used without `--debug`. And `--debug` isn't the right feedback. A few spinners would do the trick. I'd love to have a UX similar to `kind create cluster`. See screenshots below:

![Screenshot from 2020-09-25 14-57-56](https://user-images.githubusercontent.com/13746446/94319658-03810b80-ff40-11ea-94e3-444011f84dda.png)

![Screenshot from 2020-09-25 14-58-10](https://user-images.githubusercontent.com/13746446/94319661-07149280-ff40-11ea-9830-e69495796547.png)

![Screenshot from 2020-09-25 15-01-09](https://user-images.githubusercontent.com/13746446/94319666-0976ec80-ff40-11ea-936c-c490ad81878b.png)

2020-10-21 15:29 UTC, bacongobbler commented
closing as this does not solve the original issue in the way it was proposed. This PR has been stale for over 2 months with no activity after reviews.

Please re-open when you have addressed the comments given above. Thanks.

2020-10-21 15:29 UTC, closed without merging

2025-09-28 10:28 UTC, benoittgt commented
I see that [some people](https://github.com/helm/helm/issues/7760#issuecomment-3338143024) are still requesting something to log on `--wait`. I will add a point at the next dev meeting to see if we want to do something about it.