fix: limit the usage of chartutil.Values to avoid conversion bugs
helm/helm pull request #8677
Opened 2020-09-01 04:10 UTC by aure-olli

This is the 1st PR splitted from #6876

**What this PR does / why we need it**:

Golang allows implicit conversion between `map[string]interface{}` and `chartutil.Values`, but not when converted to `interface{}` first. The usage of `chartutil.Values` as values of a root `chartutil.Values` leads to various bugs, only avoided by the usage of `.AsMap` and some random checks. This was previously believed to be the consequence of `nil` values.

This PR finally gets rid of those random bugs by limitating the usage of `chartutil.Values` and preventing its conversion to `iterface{}`.

- All functions now return `map[string]interface{}`. Implicit conversion to `chartutil.Values` makes those changes quite transparent, and avoid accidentally turning `chartutil.Values` to `interface{}`.
- All creations of a `chartutil.Values{...}` have been replaced by a `map[string]interface{}{...}`.
- In general, `chartutil.Values` are only used in one of those 2 cases:
  - when `chartutil.Values` methods are used (often as argument of a function, implicitly converted on function call)
  - when `chartutil.Values` represents the root value for templates (as in `chart.Values` expressions)
- `chartutil.Values.AsMap` has been removed to discorage the usage of `chartutil.Values` (implicit conversion works anyway).
- Tries to convert `interface{}` to `chartutil.Values` have also been removed to avoid hiding bad usages of `chartutil.Values`.

Signed-off-by: Aurélien Lambert <aure@olli-ai.com>

**Special notes for your reviewer**:

We should wait for the next PRs to merge this one, I may include few additional changes in the future (but it should globally stay the same)

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2020-09-04 16:06 UTC, bacongobbler requested changes
This PR introduces a number of breaking changes to the API. For that reason, we cannot accept this PR in its current form. Please address those concerns over backwards compatibility.

Please also write a unit test that demonstrates the issue. That way we have something to reference as we test this PR and discuss the design changes made to the package. Thank you.

2020-09-04 16:06 UTC, bacongobbler commented on pkg/chartutil/coalesce.go
> +func CoalesceValues(chrt *chart.Chart, vals map[string]interface{}) (map[string]interface{}, error) {
As this is a public-facing function signature, this cannot be changed until Helm 4.

2020-09-04 16:06 UTC, bacongobbler commented on pkg/chartutil/values.go
> +func (v Values) Table(name string) (map[string]interface{}, error) {
As this is a public-facing function, this cannot be changed until Helm 4.

2020-09-04 16:06 UTC, bacongobbler commented on pkg/chartutil/values.go
> -func (v Values) AsMap() map[string]interface{} {
Functions cannot be removed, as third parties may rely on this functionality. Instead, a note that this function is deprecated and will be removed in Helm 4 is preferred.

2020-09-04 16:06 UTC, bacongobbler commented on pkg/chartutil/values.go
> +func ReadValues(data []byte) (vals map[string]interface{}, err error) {
See above.

2020-09-04 16:06 UTC, bacongobbler commented on pkg/chartutil/values.go
> +func ReadValuesFile(filename string) (map[string]interface{}, error) {
See above.

2020-09-04 16:06 UTC, bacongobbler commented on pkg/chartutil/values.go
> +func ToRenderValues(chrt *chart.Chart, chrtVals map[string]interface{}, options ReleaseOptions, caps *Capabilities) (map[string]interface{}, error) {
See above.

2020-09-07 08:28 UTC, aure-olli commented
I tried use deprecation mechanism instead, it can work with this commit. clearly won't with the next ones, as we change the global mechanism of parsing values.

If we consider that any public function can be used by an external library, and must be preserved identical, there is no way we can change the way values are treated, as most of the used functions are public.

So maybe for a helm 4

2020-09-15 20:49 UTC, bacongobbler commented
Okay. Let's hold off until Helm 4 is underway before considering this PR.

In the future, I'd also ask that you provide some unit tests to cover this case. I only saw changes in the unit tests to change a variable's type, but there weren't any tests to confirm whether this PR actually fixed a "conversion bug", so we have no way to tell whether this actually fixes anything.

Thank you for your submission. Closing.

2020-09-15 20:49 UTC, closed without merging