fix: rollback to release revision containing resource with `helm.sh/resource-policy=keep` anntation
helm/helm pull request #8683
Opened 2020-09-02 03:35 UTC by liuming-dev

When rollback to a previous release revision that contains a resource having the
annotation `helm.sh/resource-policy=keep`, while the current release revision dosen't
have this resource, rollback option will give `Error: no XXX with the name "XXX" found`
error message. A case was reported in #8228.

We should not care about weather the resource with annotaion `helm.sh/resource-policy=keep`
exists in the current release revison or not.

fix #8228

Signed-off-by: Liu Ming <hit_oak_tree@126.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-09-15 20:36 UTC, bacongobbler requested changes
Hi @liuming-dev. Once again, I must ask that you provide either a test case to test these bug fixes, or provide an example when the code cannot be easily tested. I wasted a few hours trying to come up with a  test case to test your PR, which is why it took so long to review. Please be respectful of other's time.

Regardless, the proposed PR seems like a workaround to the core issue here. Helm cannot recognize the presence of the first resource being present in the cluster. The error report mentions the following message:

```
no ConfigMap with the name "config-common-223ee6a5d95cc68fd4af39af3b059b595f54222acf4d47ab0b53134ce89c2cfe" found
```

Which is untrue. The resource DOES exist in the cluster. It's because the annotation was removed from the object in the upgrade, preventing the kube client from finding the original.

I think there's a deeper issue here that needs to be resolved. This is not as simple to fix at first glance.

2020-09-15 20:36 UTC, bacongobbler commented on pkg/kube/client.go
> +		// Figure out weather this resource in the target release revision has
typo: whether

2020-09-16 04:52 UTC, liuming-dev commented
Hi @bacongobbler , thanks for reminder, I will improve in the next PR if I could.

As for this PR, it's not easily to make a test case, but I provide some typical examples here, all examples have passed, but some details need to be discussed, see the following:

- case 1: 
  1. revision 1:  manifest contains resource ConfigMap `cfg-0` with annotation `helm.sh/resource-policy: keep`
  2. revision 2: ConfigMap `cfg-0` was removed from manifest
  `cfg-0` was not managed by Helm and was removed from manifest, `cfg-0` existed in kubernetes
  3. revision 3: rollback to revision 1
  **without this PR**: rollback failed with `Error: no ConfigMap with the name "cfg-0" found` returned
  **with this PR**: rollback successfully, `cfg-0` was kept as revision 1
- case 2:
  1. revision 1:  manifest contains resource ConfigMap `cfg-0` with annotation `helm.sh/resource-policy: keep`
  2. revision 2: annotation `helm.sh/resource-policy: keep` of ConfigMap `cfg-0` was removed from manifest
  **without this PR**: `cfg-0` was still managed by Helm, annotation `helm.sh/resource-policy: keep` of ConfigMap `cfg-0` was removed both in release manifest and kubernetes object (***Is this expected?***)
  **with this PR**: `cfg-0` was not managed by Helm, annotation `helm.sh/resource-policy: keep` of ConfigMap `cfg-0` was removed from manifest, `cfg-0` in kubernets was kept as revision 1
  3. revision 3: rollback to revision 1
  rollback successfully, `cfg-0` was kept as revision 1
- case 3:
  1. revision 1:  manifest contains resource ConfigMap `cfg-0` WITHOUT annotation `helm.sh/resource-policy: keep`
  2. revision 2: ConfigMap `cfg-0` add annotation `helm.sh/resource-policy: keep` in manifest
  3. revision 3: rollback to revision 1
  **without this PR**: `cfg-0` was still managed by Helm, annotation `helm.sh/resource-policy: keep` of ConfigMap `cfg-0` was removed from both release manifest and kubernetes object (***Should we respect keep policy first then rollback option?***)
  **with this PR**: `cfg-0` was not managed by Helm, `cfg-0` in release manifest is like revision 1, `cfg-0` in kubernets was kept as revision 2

2020-09-16 04:54 UTC, liuming-dev commented on pkg/kube/client.go
> +		// Figure out weather this resource in the target release revision has
fixed

2020-09-16 16:59 UTC, bacongobbler commented
> 2\. `cfg-0` was still managed by Helm, annotation `helm.sh/resource-policy: keep` of ConfigMap `cfg-0` was removed both in release manifest and kubernetes object (_**Is this expected?**_)

Yes. That is expected behaviour.

2020-09-16 17:01 UTC, bacongobbler commented
Thank you for providing both the test cases you tested as well as the behaviour. Based on the test results provided here, not only does this introduce new code regressions, but it also does not solve the underlying issue as I explained earlier. It only circumvents the issue.

Because of this, I'm going ahead and closing this.

2020-09-16 17:01 UTC, closed without merging