include labels in History action
helm/helm pull request #8745
Opened 2020-09-16 21:10 UTC by billyshambrook

**What this PR does / why we need it**:

We are creating a Helm plugin which is making use of the new label feature introduced in this [change](https://github.com/helm/helm/commit/273d0364be30e3bbaa73041dceea2a338f666abe#diff-a4bb7547df65a394a7f784976d2d7bebR101) but have found that the labels aren't populated in the Releases returned from the History action.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-09-16 21:21 UTC, jdolitsky approved these changes
LGTM. Simple, straightforward

2020-09-23 15:33 UTC, bacongobbler commented
Can you please write a unit test to cover this case?>

2020-10-21 15:22 UTC, bacongobbler commented
ping.

2020-10-21 15:23 UTC, bacongobbler requested changes
needs tests before it can be merge.

2020-12-01 23:31 UTC, billyshambrook commented
Hey @bacongobbler sorry for the radio silence - have added tests, let me know if they are ok or if I need to add anything else!

2024-01-10 15:01 UTC, closed without merging