fix: allow serverInfo field on index files
helm/helm pull request #8762
Opened 2020-09-17 21:58 UTC by bacongobbler

A recent change merged into Helm fixes a number of security issues related to parsing malformed index files. Unfortunately, it also broke the ability for users to load index files from chartmuseum, which adds a "server info" field to add additional metadata.

This commit adds that field so that index files from chartmuseum can be validated. Since Helm does not use this field for anything, the information is discarded and unused.

closes #8761.

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

2020-09-17 23:00 UTC, jdolitsky approved these changes

2020-09-18 08:39 UTC, hickeyma approved these changes
LGTM, thanks @bacongobbler. Tested manually and it works as expected.

2020-09-18 08:54 UTC, jkroepke commented
@bacongobbler @hickeyma 

Since 2.16.11 is affected, will this fix applied to helm v2, too?

2020-09-18 09:08 UTC, hickeyma commented
@jkroepke Good call. I will push a backport PR for Helm 2 shortly

2020-09-18 10:43 UTC, hickeyma commented
#8764 pushed for Helm 2 backport.

2020-09-18 12:14 UTC, antonsmelyanskiy commented
Please allow fields with any names, we have the following on azure container registry:
 error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"

2020-09-18 12:19 UTC, Nitive commented
Can you please clarify, which security implications having additional fields have?

2020-09-18 12:46 UTC, hickeyma requested changes
@bacongobbler ACR seems to have an additional field "acrMetadata".

2020-09-18 13:29 UTC, mattfarina commented
@Nitive I'll try to clarify. This isn't about additional fields. It's about parser options. To mitigate security issues listed in the advisories we needed to change how YAML parsing works. A side effect of that is all of the fields must be known. To mitigate the issues while allowing any fields would have required writing our own YAML parser, IIRC.

2020-09-18 16:08 UTC, mattfarina commented
@jkroepke there is a backport of this to v2 and we plan to cut a v2 release with the fix.

2020-09-18 16:40 UTC, hickeyma approved these changes

2020-09-18 16:43 UTC, merged