Implement `helm pull` for OCI registries
helm/helm pull request #8843
Opened 2020-10-02 23:55 UTC by pmengelbert

* New `helm pull` does not depend on registry cache
* Pull OCI-stored chart with `helm pull oci://<registryURL> --version <tag>`
* Implement `helm dep update` for oci dependencies, in this format:
```
dependencies
  - name: ocichart
    version: 0.1.0
    repository: "oci://localhost:3000/myregistry"
# equivalent to "oci://localhost:3000/myregistry/ocichart:0.1.0
```
* New unit tests for `helm pull` and `helm dep update`

Signed-off-by: Peter Engelbert <pmengelbert@gmail.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2020-10-05 14:02 UTC, jdolitsky requested changes

2020-10-05 14:02 UTC, jdolitsky commented on pkg/repo/repotest/server.go
> +	"golang.org/x/crypto/bcrypt"
this import should be up w/ the others

2020-10-05 14:02 UTC, jdolitsky commented on pkg/repo/repotest/server.go
> +}
should import and use `github.com/phayes/freeport` (which is already in go mod)

2020-10-05 16:06 UTC, pmengelbert commented on pkg/downloader/manager.go
> +		return url, username, password, err
The linter run by `make test` didn't like the naked return

2020-10-05 17:08 UTC, pmengelbert commented on internal/resolver/resolver.go
> +			vs, ok = repoIndex.Entries[d.Name]
`vs` is looped over later, on line 140.

2020-10-05 17:15 UTC, pmengelbert commented on internal/resolver/resolver.go
> +		var vs repo.ChartVersions
yep, line 140

2020-10-05 20:02 UTC, bacongobbler commented
Hi @pmengelbert and @jdolitsky. Have you reached out to @phroggyy on this discussion topic? Based on [his last comment](https://github.com/helm/helm/pull/7613#issuecomment-654686203) it did appear that he was still interested in pursuing this effort. I'm curious why another competing PR is being proposed here instead of working together with @phroggyy.

2020-10-05 21:44 UTC, jdolitsky commented
No ill intentions here - just trying to move things forward based on the new proposal. (Let it be known that I had approved those changes back in February)

I've reached out to Leo in Slack. and will wait for response. We're happy to drop this PR if that one is updated to reflect the proposal.

2020-10-05 22:22 UTC, jdolitsky approved these changes

2020-10-06 02:28 UTC, jdolitsky commented on cmd/helm/pull.go
> +			}
^

2020-10-06 02:28 UTC, jdolitsky commented on pkg/action/pull.go
> +	OCI         bool
^

2020-10-06 02:29 UTC, jdolitsky requested changes
Please see comment regarding the `OCI` boolean, should not be needed

2020-10-06 04:10 UTC, phoenix-bjoern commented
If this feature is removed again from roadmap for the next release because of „new considerations“ I am going nuts. We are waiting for progress on the OCI support for almost a year and „new options“ simply show that people are tired of waiting. 
Please make your choice and move on. There are more things to solve like recursive dependencies but without some progress we get really stuck here. 
Thanks.

2020-10-06 04:21 UTC, phroggyy commented
@bacongobbler to clear up on my end: I have no issues with this going forward. I did not see your link to the HIP in my PR until I read Josh's message today, and so even without checking the code, I'd assume this is a lot closer to done based on that spec. As I said to Josh in DM, if any effort should "go to waste" it should be the older, more faulty one, imho.

2020-10-06 05:15 UTC, phroggyy commented
@phoenix-bjoern I'd consider this a massive step forwards! Sure, it's frustrating that it's been open for so long, but let's keep in mind that there was no spec for this back in #7613. Then a spec (HIP) was written, and now there's a compliant implementation – this to me seems like a massive step forwards and I would believe brings us a lot closer to getting this feature in!

2020-10-06 07:30 UTC, phoenix-bjoern commented
@phroggyy thanks for comment and all your efforts. Any implementation is fine for us as long as it means we do not have to wait another 3 months till OCI dependencies are supported in a GA version.

2020-10-06 15:58 UTC, bacongobbler commented
@phoenix-bjoern while I understand the frustration, I want to make things clear... I was asking to make sure that @phroggyy was okay with this PR. Since he's put in the most time into this, we want to make sure that credit to the original author is due. If he's okay with @pmengelbert moving this forward (as he's done so), then that's fine with me. It's important to us to make sure that the original author is given credit when they put in the work.

Even after this PR is merged, it is highly unlikely this feature will be marked as stable. If you read the proposed HIP 6 at https://github.com/helm/community/pull/136, we still need the OCI to approve the OCI Artifacts proposal until we can mark this as a stable feature.  Please refer to Section 7: "Experimental until clear messaging from OCI" for more information.

If I were to assume a timeline, I wouldn't be expecting this to be marked as a stable feature until Helm 4.

Hope that clears things up.

2020-10-08 15:32 UTC, jdolitsky approved these changes

2020-10-16 14:09 UTC, phoenix-bjoern commented
@bacongobbler the OCI feature is marked as experimental, clear. The OCI dependency issue, which I've created in #6593, has celebrated already it's first birthday ;-)
We now have two(!) working solutions. If everyone favors this implementation, could you at least agree to add this issue to the milestone list for 3.4.0? @phroggyy 's implementation in #7613 was planed for 3.2, 3.3 and 3.4, where it has been removed lately. So I just kindly ask, also for other folks who voted for this feature already in my initial issue, for some progress in this OCI functionality in order to be usable without additional workarounds/commands. Thank you.

2020-10-16 14:21 UTC, bacongobbler commented
We've been focused on the Helm 2 deprecation, which happens in less than a month's time from now. Any Helm 3 work has been put on the side-burner for the time being while we support those folks still migrating to Helm 3. Thanks for your patience.

2020-10-28 19:37 UTC, jdolitsky commented
FYI - The HIP related to this change has been accepted. Please see https://github.com/helm/community/blob/master/hips/hip-0006.md

2020-11-17 14:11 UTC, WyriHaximus approved these changes
Tested this out locally and it worked fine, aside from a file deletion error after the first time installing a chart.

One question though. Will this support semver versions ranges such as `^1.2` in the future? So we don't have to update the version we want by hand

2020-11-17 15:17 UTC, jdolitsky commented
@WyriHaximus can you expand on "file deletion error after the first time installing a chart" ? The support for version ranges might be supported in the future if we are able to query the registry for available versions (tag listing).

2020-11-17 18:22 UTC, WyriHaximus commented
> @WyriHaximus can you expand on "file deletion error after the first time installing a chart" ? 

@jdolitsky the exact error is:
```
Error: unable to move current charts to tmp dir: link error: cannot rename charts to tmpcharts: rename charts tmpcharts: file exists
```

> The support for version ranges might be supported in the future if we are able to query the registry for available versions (tag listing).

Was expecting as such, don't know OCI well enough to know if this is build in. But from a user perspective this would be very welcome and put it at the same level of use as the old skool `index.yaml` based repositories.

2020-11-18 15:44 UTC, jdolitsky commented
The "tmpcharts" piece seems unrelated: https://github.com/helm/helm/blob/af2d3021f491838c0a8a396d5c6fdaa172732bd2/pkg/downloader/manager.go#L247

Unsure if this is an existing bug or specific to this change

2020-11-18 15:46 UTC, jdolitsky commented
Seems people have had this issue in the past @WyriHaximus https://github.com/helm/helm/issues?q=is%3Aissue+cannot+rename+charts+to+tmpcharts+is%3Aclosed

2020-11-19 12:51 UTC, WyriHaximus commented
@jdolitsky Looks like I had some naming crossed inside the OCI repository. But name made sure that the chart name is be found under `oci://repository.host.name` as `oci://repository.host.name/helm-oci-test` and a tag as `oci://repository.host.name/helm-oci-test:0.5.0`.

Getting this error now:
```
Error: unable to move local charts to charts dir: link error: cannot rename tmpcharts/helm-oci-test to charts/helm-oci-test: rename tmpcharts/helm-oci-test charts/helm-oci-test: file exists
```

When running this command:
```
~/Projects/Helm/helm/bin/helm dependency update
```

Now this happens as long as the `charts/helm-oci-test` directory exists. When I remove `charts/helm-oci-test` but leave `charts` present the error becomes:

```
Error: unable to move current charts to tmp dir: link error: cannot rename charts to tmpcharts: rename charts tmpcharts: file exists
```

Not sure how helm does this internally but it seems to expect that he `charts` directory is removed before putting the just pulled versions in place. Not sure if it's related to this change, but going to test this now on a chart that uses the chartmuseum way of helm charts available to see if it also happens there.

2020-11-19 12:57 UTC, WyriHaximus commented
> but going to test this now on a chart that uses the chartmuseum way of helm charts available to see if it also happens there.

@jdolitsky Ok just tested this and there is no issue with the helm I build from this PR using charts from a chartmuseum kind of repository

2020-12-01 11:21 UTC, cobexer commented
There is an important loss of functionality here compared to old repositories:
`oci://localhost:3000/myregistry` may be a valid OCI registry in a CI/Test system, but production may want to store it's helm charts in something like: `oci://registry.prod.example.com/myregistry` - while our customer may want to store our Helm Charts in their own internal OCI registry...

This syntax needs a way of saying "in the same repository/registry as the parent chart" or "in any of the configured repositories/registries"

Am I missing something?

2020-12-01 14:51 UTC, jdolitsky commented
@cobexer - you're asking for symbolic key (such as `@myrepo`), which is dynamic depending on environment?

In any case - I don't believe this PR does not prevent that feature being added in the future.

If you want, please make PR to modify this document: https://github.com/helm/community/blob/master/hips/hip-0006.md

2020-12-07 12:39 UTC, darren-bell-nanthealth commented
Hi. Is there a potential release date for this feature? I'm hoping to use it for a DR scenario. Thanks

2020-12-14 16:16 UTC, jdolitsky approved these changes

2020-12-14 17:19 UTC, mattfarina requested changes
When I tried to run `helm dep up` (my local chart has a dependency on a chart in an OCI repo) more than once I got the following error if the chart already existed in the target location...

```
Error: unable to move local charts to charts dir: link error: cannot rename tmpcharts/test-chart to charts/test-chart: rename tmpcharts/test-chart charts/test-chart: file exists
```

Shouldn't it remove the old version and replace it with the new version?

I also noticed that `oci://` works even when the OCI experiment isn't enabled for dependencies in the `Chart.yaml` file. Is this intentional?

I've not completed my whole review but I wanted to pass on the couple issues and question I had right away.

2020-12-18 22:32 UTC, pmengelbert commented on pkg/getter/getter_test.go
> +	if len(all) != 4 {
> I've not completed my whole review but I wanted to pass on the couple issues and question I had right away.

@mattfarina Thanks so much for the review. I just pushed a commit that fixes the bug you pointed out and gives the proper error message in `getter_test.go`. Let me know what you think of the changes, and I look forward to the rest of your review!

2021-01-05 20:21 UTC, mattfarina commented on internal/experimental/registry/client.go
> +func (c *Client) PullChart(ref *Reference) (*bytes.Buffer, error) {
Note to reviewers... this function is internal and part of the experiment. It's ok to change it.

2021-01-05 20:39 UTC, technosophos approved these changes
This looks to me like a clear step forward on the experimental OCI front. I am good with merging/shipping this iteration.

2021-01-05 20:43 UTC, pmengelbert commented
@mattfarina would you do us a favor and mark the requested changes as resolved? Once that's taken care of we can finally get this merged! Really happy to see this moving forward

2021-01-05 20:44 UTC, technosophos commented
@pmengelbert we're actually both working on it right now

2021-01-05 21:08 UTC, mattfarina approved these changes

2021-01-05 21:09 UTC, merged