monior optimization.
helm/helm pull request #8979
Opened 2020-11-04 02:52 UTC by hustclf

**What this PR does / why we need it**:

1. fix  wrong crd path in comment
2. minor code optimization: deploy get  `CRDObjects()` when really needed.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-11-05 23:07 UTC, bacongobbler requested changes
Hi @hustclf. We ask that contributors please first open a ticket explaining the issue they are experiencing as well as a way to reproduce the issue in a test environment. A PR with the title "minor optimization" with no information or test fixtures makes it incredibly difficult to determine what is being fixed or why you decided to rewrite certain parts of the codebase.

It also helps to write up a test case to ensure that

1. there is a bug in the current version of Helm,
2. the code introduced fixes that bug, and
3. future iterations do not introduce a regression that would re-introduce the original bug you were trying to fix.

With the information provided here, I am not confident enough to determine what this attempts to fix, whether it is an appropriate fix for the problem, and whether these set of changes will break some pre-existing assumptions that could break backwards compatibility. 

Because of those concerns, I am strongly against merging this PR in its current state until the above conditions are met.

Please also refer to [our contributing guidelines](https://github.com/helm/helm/blob/master/CONTRIBUTING.md) for further information on the processes described above. Thank you.

2020-11-06 02:47 UTC, hustclf commented
Thanks for your detailed feedback.  I updated title of pr and git commit info.

This pr is a code refactor,  and do not has any effect on unit tests and docs. I look through the contributing guidelines, but can not find a suitable issue type for code refactor.

Does I miss something, or current state is ok for pr?

2020-11-06 02:51 UTC, bacongobbler commented
You will need to provide unit tests or a test case to prove out what you're attempting to fix, at the very least.

2020-11-16 17:36 UTC, bacongobbler commented
Hi @hustclf. Just checking in to see whether you'll have the time to address my earlier comments. Thanks!

2021-01-21 06:55 UTC, hustclf commented
@bacongobbler  Sorry for late reply,  I have no idea how to write a test case for it,  any advice for me ? thanks !

2025-09-28 00:25 UTC, closed without merging