fix: Fixed bug - The flags --cert-file/--key-file where ignored when …
helm/helm pull request #9070
Opened 2020-11-29 08:36 UTC by dinumathai

Fixed bug - The flags --cert-file/--key-file where ignored when --insecure-skip-tls-verify flag is set

**What this PR does / why we need it**:
The below command was failing 
helm upgrade --install my-chart https://localhost:8080/charts/test-0.1.0.tgz --insecure-skip-tls-verify --cert-file tls/client.crt --key-file tls/client.key
When the --insecure-skip-tls-verify flag is set flags --cert-file/--key-file where ignored

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-12-02 16:27 UTC, bacongobbler requested changes
thanks for the PR @dinumathai.

Generally speaking when changes are being made to the code, we ask for unit tests to cover and test for any code regressions. It ensures regressions like this are not introduced in the future.

Can you please add some tests here? Have a look at pkg/getter/httpgetter_test.go for inspiration.

2020-12-04 10:08 UTC, dinumathai commented
> thanks for the PR @dinumathai.
> 
> Generally speaking when changes are being made to the code, we ask for unit tests to cover and test for any code regressions. It ensures regressions like this are not introduced in the future.
> 
> Can you please add some tests here? Have a look at pkg/getter/httpgetter_test.go for inspiration.

Updated the unit test

2020-12-11 06:11 UTC, dinumathai commented
> thanks for the PR @dinumathai.
> 
> Generally speaking when changes are being made to the code, we ask for unit tests to cover and test for any code regressions. It ensures regressions like this are not introduced in the future.
> 
> Can you please add some tests here? Have a look at pkg/getter/httpgetter_test.go for inspiration.

Updated the unit test

2020-12-15 14:22 UTC, mattfarina approved these changes

2020-12-17 20:49 UTC, technosophos approved these changes

2020-12-17 20:49 UTC, merged