Avoid overwriting the content of the template file
helm/helm pull request #9097
Opened 2020-12-07 10:22 UTC by wawa0210

**What this PR does / why we need it**:
fix #9061
When helm template is used on a template file with multiple resources in it of which some have a helm.sh/hook annotation, then only the hook annotated resources will render if --output-dir is used.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2020-12-07 10:29 UTC, wawa0210 commented
I am not very clear about the reason why `fileWritten` was added, please @mattfarina help me to confirm

2021-01-21 10:29 UTC, wawa0210 commented
@bacongobbler 

Can you help, take some time to help reivew this pr? Looking forward to your comments

2021-01-25 18:40 UTC, bacongobbler requested changes
Please write unit tests to ensure the code works as intended. Thanks.

2021-02-08 20:00 UTC, bacongobbler commented
Please stop asking for another review. I reviewed this code 2 weeks ago and gave you feedback.

> Please write unit tests to ensure the code works as intended. Thanks.

Please write unit tests before asking me to re-review your code.

2021-02-22 07:14 UTC, wawa0210 commented
> Please write unit tests before asking me to re-review your code.

Sorry, I clicked the review button last time without a clear description. The unit test here is a bit difficult, I would like to ask. The current scenario will only happen when `--output-dir` is used. This flag will write the results to the specified directory. How should this test be better written?


https://github.com/helm/helm/blob/85794cfc6eb7216c987f544ceb871c94dbec6a7f/cmd/helm/template.go#L73

Resources that do not contain the `Hooks` type have been rendered successfully at this time, so when we deal with the `hooks` logic later, we only need append

2021-02-23 16:20 UTC, bacongobbler commented
In #9061, an issue occurs "when `helm template` is used on a template with multiple resources of which some have a `helm.sh/hook` annotation".

 This PR intends to fix that.

To verify this PR fixes that issue, write a test where `helm template` receives a file with multiple resources containing a hook annotation, and verify that all resources render with the `--output-dir` flag set.

Have a look at [`TestInstall`](https://github.com/helm/helm/blob/85794cfc6eb7216c987f544ceb871c94dbec6a7f/cmd/helm/install_test.go#L24) for examples.

2021-03-01 02:44 UTC, wawa0210 commented
> Have a look at [`TestInstall`](https://github.com/helm/helm/blob/85794cfc6eb7216c987f544ceb871c94dbec6a7f/cmd/helm/install_test.go#L24) for examples.

The current situation is a little different from these examples. These examples compare the standard output with the contents of the corresponding file. `--output-dir` will print the standard output to a file, and then compare the two files. The current test does not seem to This kind of scene

2022-03-11 20:40 UTC, bacongobbler commented
closing as inactive.

2022-03-11 20:40 UTC, closed without merging