WIP: Provide an alternative for --set and/or --set-string to take a value literally
helm/helm pull request #9182
Opened 2021-01-02 09:38 UTC by pscheid92

Currently, just an experiment/spike.\
Going to fill PR with more meaningful information and rebase/reword commits later.

This – hopefully – resolves #4030.

Signed-off-by: Patrick Scheid <p.scheid92@gmail.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-01-25 17:58 UTC, bacongobbler commented
Thanks you for taking this on!

I see that CircleCI is failing and has been in a "work-in-progress" state for 3 weeks. What's the status here?

Thanks!

2021-01-25 18:06 UTC, pscheid92 commented
Hello, unfortunately I had a lot going on in the last weeks and had problems finding time to work on it.\
Currently, things are smoothing down, and I hope I can continue working on this soon.

2021-03-23 03:49 UTC, buckner commented
Hi - is there any traction on this? --set-literal would be immensely helpful to have.

2021-03-23 06:36 UTC, pscheid92 commented
Hello @bacongobbler I just want to make sure I haven't missed something. Is there any next step I have to take to bring this forward?

2021-04-28 11:01 UTC, Chainsaw-does-brr commented
@bacongobbler , the commas gather their pitchforks:
,,,,,,,,,,,,,,,, , , , ,,  , , ,, ,,,,,,,,, , , ,, , ,, , ,,,,,,,,,,, ,, , , , , ,, , ,,,,,,,,,,,,
, ,, , ,,,,,,,,,,,,, ,, , , ,,,,,,,,,, , , ,,,,,, ,,,, ,,  , , ,, ,,,,,,,,, , , ,, , ,, , ,,,,, ,
We need to exclude them from parsing immediately!

2021-12-27 18:26 UTC, lsowen commented
Looks like this would also address https://github.com/helm/helm/issues/5618

2022-01-26 19:52 UTC, LukeIGS approved these changes
Unit tests pass locally, seems to adhere the code styles set forth by the project to the best of what i can tell.

2022-02-08 18:04 UTC, f1tzpatrick commented
Hello @marckhouzam or @mattfarina, when you have a chance, would you please review this PR? The functionality described in #4030 would be nice to have and this looks like it should add it.

2022-02-10 13:35 UTC, bacongobbler approved these changes

2022-02-10 13:36 UTC, bacongobbler commented
Needs another maintainer’s approval as per our contributing policy. Thanks for the contribution.

2022-03-11 03:09 UTC, Alceatraz commented
--set-literal, That gone *literal* save the world 
```bash
# Say good bye to those nightmare
--set SPRING_PROFILE='elk\,foo-prod\,bar-prod\,foobar-prod'
--set FOO_BAR='\{\"foo\":\"bar\"\}'
```

2022-03-21 05:22 UTC, Alceatraz commented
Will this RP merge in 3.9.x?

2022-03-25 17:32 UTC, zarko-a commented
Any chance this will get merged soon? 

We encountered the same issue and this would help us immensely.

2022-03-25 18:00 UTC, bacongobbler commented
I've added it to the 3.9 milestone, which is scheduled for May 2022.

2022-09-23 10:38 UTC, hickeyma commented
@pscheid92 Did you mind rebasing?

2022-09-23 11:54 UTC, pscheid92 commented
Hey @hickeyma I rebased my changes on top of the current upstream main branch (and resolved minor merge conflicts).

But it looks like something is wrong with the CircleCI Pipeline 🤔 
> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

2022-10-18 18:56 UTC, pscheid92 commented
Hey @hickeyma @bacongobbler. Can I do something to help here? It still seems like the CircleCI Pipeline is somehow broken 🤔

2022-10-27 13:58 UTC, rogaha commented
any updates?

2023-01-03 14:07 UTC, mattfarina commented
I just fixed the merge conflict which is triggering  CI

2023-01-06 11:05 UTC, hickeyma requested changes
Thank you for pushing the PR @pscheid92 and your perservence. It is looking good except for a check on the levels as specified inline. It would be worth also adding an unit test similar to `TestParseSetNestedLevels` in TestParseSetNestedLevels

2023-01-06 11:05 UTC, hickeyma commented on pkg/strvals/literal_parser.go
> +
There is a potential stack overflow if the nested levels are not checked. Do you mind adding a check for the key similar what is done in `parser.go`: https://github.com/helm/helm/blob/main/pkg/strvals/parser.go#L267-L288

2023-01-06 13:51 UTC, pscheid92 commented on pkg/strvals/literal_parser.go
> +
Hey @hickeyma, I just pushed a version with stack overflow protection. And also included a unit test for it.

2023-01-06 13:52 UTC, pscheid92 commented
Thank you very much @hickeyma. I just pushed a version with stack overflow protection and the requested test case. Good catch!

2023-01-10 12:21 UTC, hickeyma commented on pkg/strvals/literal_parser.go
> +
Great, thanks

2023-01-10 12:27 UTC, hickeyma approved these changes
I tested this manually and it fixes passing strings like `Passw\Ord!`.  I used `--set-literal passwd="Passw\\Ord\!"` flag and it output `Passw\Ord!`.

Nice feature, thanks @pscheid92

2023-01-10 17:55 UTC, hickeyma commented
@mattfarina Are you happy for this to be merged?

2023-01-12 00:10 UTC, Alceatraz commented
Finily

2023-04-28 18:39 UTC, mattfarina approved these changes

2023-04-28 18:39 UTC, merged