Allow configuring install order of Custom Resources
helm/helm pull request #9534
Opened 2021-03-24 17:07 UTC by NiklasWagner

**What this PR does / why we need it**:

By default Helm installs Kubernetes Kinds that doesn't exist in the internal [kube_sorter.go](https://github.com/helm/helm/blob/d55c53df4e394fb62b0514a09c57bce235dd7877/pkg/releaseutil/kind_sorter.go#L31-L66) at the very end of a helm installation. This causes some serious issues with Custom Resources that need to be deployed before specific other resources.

This PR introduces a new Annotation called `helm.sh/install-before`. With this annotation user can specify in which order this Custom Resource is actually installed. For example `helm.sh/install-before="Deployment,Service"` means that this Resource will be installed **before** the Deployment resource as well as **before** the Service resource.

Here is a example resource with this Annotation:

```yaml
# Source: generic-service/templates/securitygrouppolicy.yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: niklas-debug
  labels:
    helm.sh/chart: generic-service-0.5.0
    app.kubernetes.io/name: niklas-debug
    app.kubernetes.io/instance: niklas-debug
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/install-before: "Deployment,Statefulset,DaemonSet"
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: niklas-debug
      app.kubernetes.io/instance: niklas-debug
  securityGroups:
    groupIds:
      - sg-xyz
```
In this case Helm with this PR would make sure that this SecurityGroupPolicy Resource is installed **before** any Deployment, Statefulset and DaemonSet Kinds. As well as Uninstalled **after** any Deployment, Statefulset and DaemonSet Kinds

Fixes:
* #8439 
* #8291
* #7072
* #6851
* #5916
* #5642
* #8448

**Special notes for your reviewer**: I'm not a Golang developer, in fact this was the first time I wrote Golang code. So please feel free and improve stuff that doesn't look right.

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2021-05-25 07:06 UTC, kustodian commented
This would be a very good and elegant addition to Helm. Any updates about this PR?

2021-08-26 14:53 UTC, bacongobbler requested changes

2022-01-10 20:48 UTC, jimbali commented
Would love to see this feature. We had an issue today where a DeploymentConfig in OpenShift was installed slightly before an ImageStream, causing it to try and look up the image in docker.io instead of recognising that it actually referenced the ImageStream. But I do agree that this should be configured at the chart level rather than per-resource.

2023-01-10 11:16 UTC, pawellegowski89 commented on pkg/releaseutil/manifest_sorter.go
> +func SortManifests(files map[string]string, apis chartutil.VersionSet, uninstall bool) ([]*release.Hook, []Manifest, error) {
Please fix this, we waiting for this PR

2025-04-11 21:08 UTC, scottrigby commented
See "H4HIP: Helm Sequencing Proposal" https://github.com/helm/community/pull/373

2025-12-26 00:24 UTC, closed without merging