feat(helm): optionally hide validation warnings
helm/helm pull request #9604
Opened 2021-04-14 22:29 UTC by rcousineau-xandr

Closes #9407

**What this PR does / why we need it**:

when doing the following commands:
* `helm repo add`
* `helm repo update`
* `helm search repo`

the new flag `--hide-validation-warnings` will suppress the message
"skipping loading invalid entry for chart"

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation - https://github.com/helm/helm-www/pull/1069
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-04-14 23:11 UTC, bacongobbler requested changes
We cannot accept changes to public function signatures in Helm 3. To be specific, the changes to `LoadIndexFile` and `DownloadIndexFile` break backwards compatibility. Because of that we cannot accept these changes as-is.

https://github.com/helm/helm/blob/main/CONTRIBUTING.md#semantic-versioning

2021-04-14 23:16 UTC, rcousineau-xandr commented
@bacongobbler any ideas for a different way to deal with this?

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/repo/index.go#L339

I could maybe create a copy of `LoadIndexFile` called `LoadIndexFileNoValidate` or something?

2021-04-14 23:30 UTC, bacongobbler commented
That log message was explicitly added to bubble up a security issue. We will not be accepting PRs to bypass or otherwise ignore the error message entirely. I explained why in https://github.com/helm/helm/issues/9342#issuecomment-775269042.

2021-04-14 23:38 UTC, rcousineau-xandr commented
> The resolution is simple

Unfortunately we can't just *simply* remove all of these packages (nearly ~3k for our repo).

I understand not wanting to completely eliminate the message, and I'm just trying to discuss a backwards-compatible approach to optionally suppressing it.

Proposal: if `--hide-validation-warnings` is passed, `LoadIndexFileNoValidate` is called instead of `LoadIndexFile`. 

No existing interface changes, so it's backwards-compatible.

2021-04-14 23:42 UTC, rcousineau-xandr commented
> security issue

I think it's worth mentioning that we're not talking about suppressing validation of charts that we're publishing from this point forward. We have charts in this repository that were created with helm 2.x and were valid at the time.

2021-05-27 01:26 UTC, nathschmidt commented
@bacongobbler Now that @rcousineau-xandr has ensured these changes are backwards compatible, could you revisit this PR? The verbosity of this logging is causing pretty significant issues for me - particularly when it comes to reading otherwise very small logs.

I'd also like to echo the comments of @rcousineau-xandr - removing all of the offending charts is not an option, in all or many cases. These charts were valid when published and in many cases are still being used with Helm 2.

2021-05-27 02:07 UTC, bacongobbler commented
Since we cannot determine that there is any difference between what are considered “safe” and “unsafe” versions, disabling the warnings means you are now vulnerable to malicious attackers injecting malicious version numbers into any chart repository index. To do so would revert back to Helm’s prior behaviour, and the reason why the auditors raised this issue in the first place.

Because of that, we cannot accept this “feature”.

2021-05-27 02:11 UTC, rcousineau-xandr commented
@bacongobbler can you please take a look at my alternative approach: #9611 -- if we could condense the multitude of errors into a summary (instead of hiding it altogether) that would help immensely.

2025-08-27 09:10 UTC, pierluigilenoci commented
Still an interesting feature

2025-08-27 12:29 UTC, benoittgt commented
I think it might make sense to close this one regardless of https://github.com/helm/helm/pull/9604#issuecomment-849260843, and instead focus our efforts on https://github.com/helm/helm/pull/9611.

2025-12-04 09:02 UTC, pierluigilenoci commented
/nostale

2026-04-04 00:33 UTC, closed without merging