Add hint to missing dependency message
helm/helm pull request #9794
Opened 2021-06-11 10:03 UTC by j6s

**What this PR does / why we need it**:

This PR adds a hint on how to resolve the situation to the 'missing dependency' error message.
Since switching to a shared library, this is the single biggest cause for confusion for developers in my team which could be solved by adding the  _"You may need to run `helm dependency build` to fetch missing dependencies."_ message at the end.

**Special notes for your reviewer**:

n/a

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-06-17 15:08 UTC, cndoit18 reviewed
PRs must be linked to an existing issue. If none exists, may you please open one explaining the issue and expected outcome?
Please also write tests to test and verify this PR fixes your issue. Thanks.

2021-06-17 15:19 UTC, j6s commented
I have created #9823 for this PR. The PR also includes an update to the test-case for this error message.

2021-06-17 15:20 UTC, bacongobbler commented
With a few exceptions, we try to avoid avoid referring to Helm CLI commands in `pkg/action`. This is because `pkg/action` can be used by other programs as a library, so asking the user to run `helm repo update` may be completely irrelevant.

Can you please look into alternative ways to provide this hint to the user? One way might be to capture the error from `pkg/action` in `cmd/helm`, then add the appropriate context around the error message.

Hope this helps.

2021-06-17 15:20 UTC, bacongobbler requested changes
cannot use CLI error messages in `pkg/action`

2021-11-26 16:48 UTC, bacongobbler approved these changes
thank you!

2021-11-26 16:48 UTC, merged