Add --directory/-d options to `helm create`
helm/helm pull request #9847
Opened 2021-06-23 10:03 UTC by quantumsheep

**What this PR does / why we need it**:
I wanted to overwrite the default destination directory using `helm create`, noticed we can't do that so I added the feature.

This PR adds a new option to `helm create`: `--directory` (shorthand `-d`). Here's an example:
```bash
$ helm create coolapp -d coolapp-helm
Creating coolapp

$ ls ./coolapp-helm
Chart.yaml  charts      templates   values.yaml
```

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2021-08-19 03:12 UTC, technosophos commented
I hate to be a stickler for things like this, but a feature PR must be linked to an issue that describes the feature.

2021-08-22 21:05 UTC, quantumsheep commented
@technosophos no worries :) Here you go: #10048.

2021-08-23 15:54 UTC, bacongobbler requested changes
Looks good! just need to fix a breaking change in the API's behaviour before we can merge.

2021-08-23 15:54 UTC, bacongobbler commented on cmd/helm/create.go
> +		destination = o.name
Don't we want the destination to be `filepath.Dir(o.name)`? That would match the old behaviour.

2021-08-23 15:54 UTC, bacongobbler commented on pkg/chartutil/create.go
> +	parentPath := filepath.Dir(cdir)
By doing this, you change the current behaviour of `Create()`, which is a [publicly available API endpoint](https://pkg.go.dev/helm.sh/helm/v3@v3.6.3/pkg/chartutil#Create). Changing its internal behaviour will silently break users consuming the public API.

Notice how you had to change every invocation of `chartutil.Create` in the tests in order to match its new calling signature.

In other words, if I previously expected

```
chartutil.Create("/foo")
```

To create a new chart in directory `/foo`, then the same should hold true until Helm 4.

2021-08-23 15:56 UTC, bacongobbler commented
I had to double check with `helm lint` and `helm package` to see if this convention was valid, but after the removal of the "chart name must match the directory name" constraint in Helm 3 this appears to work.

```
bacongobbler@ultralisk /tmp ><> helm create coolapp
Creating coolapp
bacongobbler@ultralisk /tmp ><> mv coolapp coolapp-helm
bacongobbler@ultralisk /tmp ><> helm lint ./coolapp-helm
==> Linting ./coolapp-helm
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
bacongobbler@ultralisk /tmp ><> helm package ./coolapp-helm
Successfully packaged chart and saved it to: /tmp/coolapp-0.1.0.tgz
```

2021-08-23 15:58 UTC, bacongobbler commented
Note that `helm create` accepts a path as an argument.

From the help text:

> 'helm create' takes a path for an argument. If directories in the given path
do not exist, Helm will attempt to create them as it goes. If the given
destination exists and there are files in that directory, conflicting files
will be overwritten, but other files will be left alone.

Please make sure you accommodate this in your tests. Thanks!

2022-03-23 09:11 UTC, closed without merging