fix: refactor downloadAll
helm/helm pull request #9889
Opened 2021-06-29 19:37 UTC by bacongobbler

This refactor cleans up downloadAll's validation, download, and save logic:

1. A temporary directory is created, and removed after all references to
   the struct have been dropped via `defer`
2. Any local dependencies in the `charts` directory are kept intact and validated
3. Charts that have been updated are moved to the `charts` directory

This refactor has a number of improvements, including:

- tmpCharts is removed after execution
- no remote charts are downloaded to destPath: they are all pulled into tmpPath, validated, then moved to destPath
- lots of code cleanup/improvements, like the `if` block checking whether the `charts` directory was actually not a directory. In some cases it could be checking a `nil` object, causing a runtime panic.
- the cyclomatic complexity of the code was simplified
- extra (and in some cases, dangerous) calls to `os.RemoveAll` have been refactored, cleaning the code and preventing certain failure cases.

A test has been provided to demonstrate the tmpCharts removal issue has been fixed. I also left a comment that further improvements can be made to this piece of code should someone feel the need to make improvements there.

closes #5567
closes #8846 
closes #9680

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

2021-06-29 20:03 UTC, jdolitsky commented
@bacongobbler - checked the failing tests. I believe I experienced the same "no such file or directory" w/ the OCI changes... May need to make a change similar to https://github.com/helm/helm/pull/9782/files#diff-a689ad99783d272ab2c91f3372579ffa3e0e96a64ead1b2872e05ba8e86d953b. Just a hunch

2021-06-29 20:35 UTC, bacongobbler commented
Good call. Thanks! I'll look into that.

2021-06-30 18:02 UTC, bacongobbler commented
Hmm... I think the issue was due to a simple bug in my code. I think I caught it and it should work as expected now.

2021-06-30 18:05 UTC, bacongobbler commented
I'm going to change some of the behaviour around `safeDeleteDep`. It looks like there can be a case where a fail to "safely" delete a dependency can cause data loss. That doesn't seem optimal. Code should remain the same, but updates should be more atomic as a result.

2021-07-07 21:52 UTC, jdolitsky approved these changes

2021-07-07 22:20 UTC, bacongobbler commented
I think I failed to account for one last use case, which is when a "local" dependency (one where the "repository" field in your dependencies is empty) is packaged as a tarball instead of a directory. I've seen some use cases utilizing that.

2021-07-07 23:08 UTC, bacongobbler commented
> That may call for some deeper introspection of the chart dependency tree than I was hoping for, but /shrug

done

2021-07-07 23:21 UTC, bacongobbler commented
As it turns out, local dependencies cannot be anything other than directories according to https://github.com/helm/helm/blob/21251378b432fb629cb1a49af3892e20c1ec9624/pkg/downloader/manager.go#L277, so I just added some extra safeguards in case we decide to change that assumption. :)

2021-07-26 10:26 UTC, hickeyma requested changes
@bacongobbler Do you mind rebasing to resolve the conflict? I will finish me review then.

2021-08-19 14:56 UTC, bacongobbler commented
rebased and squashed.

2021-08-19 20:51 UTC, technosophos approved these changes

2021-08-19 21:13 UTC, merged