fix(install): add flag
helm/helm pull request #9918
Opened 2021-07-07 10:10 UTC by cndoit18

Signed-off-by: cndoit18 <cndoit18@outlook.com>

**What this PR does / why we need it**:

fixes: #9915 

**Special notes for your reviewer**:

2021-07-09 05:49 UTC, yxxhero commented
@cndoit18 from the issue, it  conditionally enable/disable child charts. example: 
```yaml
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    version: The version of the chart ("1.2.3")
    repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
```
I think you should decide whether to load chart's crds by **condition** filed. do you think of?

2021-07-09 05:51 UTC, cndoit18 commented
> @cndoit18 from the issue, it conditionally enable/disable child charts. example:
> 
> ```yaml
> dependencies: # A list of the chart requirements (optional)
>   - name: The name of the chart (nginx)
>     version: The version of the chart ("1.2.3")
>     repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
>     condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
> ```
> 
> I think you should decide whether to load chart's crds by **condition** filed. do you think of?

Very good, I gave missed this part. I'll rethink it.

2021-09-01 05:39 UTC, yxxhero requested changes

2021-09-01 05:39 UTC, yxxhero commented on pkg/action/action_test.go
> +func loadChart(t *testing.T, path string) *chart.Chart {
this is a utils func, why has testing.T arg? you can return (*chart.Chart, error), WDYT?

2021-09-25 10:40 UTC, yxxhero approved these changes
LGTM
@bacongobbler what do  you think of?

2021-09-27 10:58 UTC, hickeyma approved these changes
LGTM, thanks @cndoit18 for the fix. I cannot think of any way we can test this with CRDs, so unit test is not required.

This requires another core maintainer to merge.

2021-11-26 16:47 UTC, bacongobbler approved these changes

2021-11-26 16:47 UTC, merged