Use jsonmergepatch.CreateThreeWayJSONMergePatch for unstructured objects
helm/helm pull request #9938
Opened 2021-07-13 08:45 UTC by wxdao

**What this PR does / why we need it**:

closes #9937

Use jsonmergepatch.CreateThreeWayJSONMergePatch to create three way merge patch for unstructured objects like kubectl apply does.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-07-14 05:16 UTC, cndoit18 approved these changes
LGTM

2021-07-15 16:45 UTC, mattfarina requested changes
This needs to sit behind an opt-in flag. See https://github.com/helm/helm/issues/9937#issuecomment-880853027 for some more detail.

2021-07-16 06:58 UTC, wxdao commented
@mattfarina

Since `kube.Client.Update` is called at multiple places besides upgrade action, I've added a `--use-three-way-merge-patch-for-unstructured` global flag to control the behavior.

Yes, the name of the flag is a bit ridiculously long. I'd like some idea about how to name it better if any...

2021-08-17 17:15 UTC, bacongobbler commented
Say someone was upgrading from a version of Helm without this flag, then started using it after upgrading to Helm 3.7. Would Kubernetes be able to resolve the upgrade or would it return an error? Or worse, is the behaviour underfined when switching from a generic merge patch to a generic three-way JSON merge patch?

Conversely, if someone calls `helm --use-three-way-merge-patch-for-unstructured install mychart .` then `helm upgrade mychart .` (generic three-way JSON merge patch to generic merge patch), what happens?

I'm trying to determine if users can use these merge patch strategies interchangeably or not. Because I can imaging the scenario where someone forgets to add this flag during a `helm upgrade` and suddenly puts their Helm release into an irrecoverable state.

2021-08-22 18:05 UTC, wxdao commented
> Say someone was upgrading from a version of Helm without this flag, then started using it after upgrading to Helm 3.7. Would Kubernetes be able to resolve the upgrade or would it return an error? Or worse, is the behavior undefined when switching from a generic merge patch to a generic three-way JSON merge patch?
> 
> Conversely, if someone calls `helm --use-three-way-merge-patch-for-unstructured install mychart .` then `helm upgrade mychart .` (generic three-way JSON merge patch to generic merge patch), what happens?
> 
> I'm trying to determine if users can use these merge patch strategies interchangeably or not. Because I can imagine the scenario where someone forgets to add this flag during a `helm upgrade` and suddenly puts their Helm release into an irrecoverable state.

To summarize any behavior change if the flag is set:
- Only affects custom resources, like VirtualService, and CustomResourceDefinition resources.
- Only affects changes to those resources, i.e. mostly when running `helm upgrade` and `helm rollback`.

It's ok to interchangeably use any strategies. Because:
- There will be no difference for the stored release meta, since it's the rendered manifests that are stored. Patch strategies only affect how the live state of resources will become after an update.
- The behavior of either patch strategies is determined, and has nothing to do with what was used previously. Actually the two way merge patch will only miss out some changes and never do more. See below for the only possible difference of these two patch strategies:

```
# original / last applied
a: 1

# target / to update to
a: 1

# live state
a: 2

# result live state
a: 2 # if it's two way
a: 1 # if it's three way
```

Sorry for the late reply.

2021-09-13 20:14 UTC, zonggen commented
Could you provide unit tests for this feature? would love to keep the review cycles going :)

2022-05-11 11:49 UTC, chris-str-cst approved these changes

2025-09-27 00:22 UTC, closed without merging