Make Chart's IsRoot available to templates
helm/helm pull request #9993
Opened 2021-08-02 19:41 UTC by Ka0o0

**What this PR does / why we need it**:
This PR closes #9991 as it adds the information if the currently processed (templated) Chart is the root or not. This allows to have different behavior in case a Chart is installed on its own or included as part of another Chart. 

Templates can check this flag like so:

```
IsRoot: {{ .Chart.IsRoot }}
```

**Special notes for your reviewer**:
This is my first PR to Helm so please let me know if I'm missing something

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-08-19 02:34 UTC, technosophos requested changes
I went back and forth on whether we should add this as metadata, and I think the answer is yes, this is the best place to put this.

So all this is missing is a test. Probably, you can just add a few lines in a test like this one:

https://github.com/helm/helm/blob/main/pkg/engine/engine_test.go#L318

2021-08-23 18:08 UTC, Ka0o0 commented
Hi @technosophos ,
I've added a test case to cover both cases - IsRoot false and true.
Let me know what you think.

2021-08-24 18:05 UTC, technosophos approved these changes

2021-08-25 13:48 UTC, mattfarina approved these changes

2021-08-25 14:14 UTC, merged